main/default/objects/UW_Analysis__c/UW_Analysis__c.object-meta.xml
<CustomObject>
    <label>UW Analysis</label>
    <nameField>
        <displayFormat>UWA-{0000}</displayFormat>
        <label>UW Analysis</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UW Analysis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/UW_Analysis__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <label>Criteria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Territory</fullName>
            </value>
            <value>
                <fullName>D&amp;C Turnover Split</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Design &amp; Construct</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Insurance Brokers</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Property Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/UW_Analysis__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>UW Analysis</relationshipLabel>
    <relationshipName>UW_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/UW_Analysis__c/fields/UW_Analysis_Name__c.field-meta.xml
<CustomField>
    <fullName>UW_Analysis_Name__c</fullName>
    <label>UW Analysis Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/classes/UWAnalysisQueryUtil.cls
/**************************************************************************************************
 * Class Name: UWAnalysisQueryUtil
 * Author: 
 * Date: Dec 27, 2021
 * Description: Class to keep UW Analysis queries
 * Test Class : 
 **************************************************************************************************/
public with sharing class UWAnalysisQueryUtil {
    /*************************************************
    * Method Name: fetchUWAnalysisForOpps
    * Author: 
    * Date: 27th Dec 2021
    * Params: Opportunity Id
    * Return: list of UW Analysis
    * Exceptions:
    * Revision: 
    * Description: Fetch UW Analysis by opportunity
     *************************************************/
    public static List<UW_Analysis__c> fetchUWAnalysisForOpps(List<String> oppIds){
        return [SELECT Id, UW_Analysis_Name__c, Criteria__c
                FROM UW_Analysis__c 
                Where Submission__c IN:oppIds];
    }
}