main/default/objects/Claim_Data__c/Claim_Data__c.object-meta.xml
<CustomObject>
    <label>Claim Data</label>
    <nameField>
        <displayFormat>CLD-{00000}</displayFormat>
        <label>Claim Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Claim_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims Data</relationshipLabel>
    <relationshipName>Claims_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Claim_Data__c/fields/Claim_status__c.field-meta.xml
<CustomField>
    <fullName>Claim_status__c</fullName>
    <label>Claim status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Claim_Data__c/fields/Fees_Paid__c.field-meta.xml
<CustomField>
    <fullName>Fees_Paid__c</fullName>
    <label>Fees - Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Claim_Data__c/fields/Fees_Reserve__c.field-meta.xml
<CustomField>
    <fullName>Fees_Reserve__c</fullName>
    <label>Fees – Reserve</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Claim_Data__c/fields/Indemnity_Paid__c.field-meta.xml
<CustomField>
    <fullName>Indemnity_Paid__c</fullName>
    <label>Indemnity - Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Claim_Data__c/fields/Indemnity_Reserve__c.field-meta.xml
<CustomField>
    <fullName>Indemnity_Reserve__c</fullName>
    <label>Indemnity – Reserve</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Claim_Data__c/fields/Insured_name__c.field-meta.xml
<CustomField>
    <fullName>Insured_name__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; + Policy__r.Account__c ,Policy__r.Account__r.Name )</formula>
    <label>Insured name</label>
    <type>Text</type>
</CustomField>

main/default/objects/Claim_Data__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Claims Summary</relationshipLabel>
    <relationshipName>Claims_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Claim_Data__c/fields/Policy_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Effective_Date__c</fullName>
    <formula>Policy__r.Effective_Date__c</formula>
    <label>Policy Effective Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Claim_Data__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; + Policy__c , Policy__r.Policy_Number__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Number</label>
    <type>Text</type>
</CustomField>

main/default/objects/Claim_Data__c/fields/Total_Incurred__c.field-meta.xml
<CustomField>
    <fullName>Total_Incurred__c</fullName>
    <label>Total Incurred</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/classes/ClaimDetailsSectionController.cls
public with sharing class ClaimDetailsSectionController {
    

    @AuraEnabled(cacheable=true)
        public static List<Claim_Data__c> getSubmissionRelatedToAccount(String oppId) {
            system.debug('accId >> ' + oppId);

            List<Opportunity> oppRecordwithAccountId = [SELECT ID, AccountId from Opportunity WHERE Id =: oppId ];
            system.debug('oppRecordwithAccountId----'+oppRecordwithAccountId);
           // system.debug('claimslist'+ [ SELECT ID, Account__c, Name, Policy_Number__c, Insured_name__c from Claim_Data__c WHERE Account__c =: oppRecordwithAccountId[0].AccountId]);
           return [SELECT ID, Account__c, Name , Policy_Number__c, Insured_name__c , Policy__r.Policy_Number__c , 
                    Claim_status__c ,Indemnity_Paid__c , Indemnity_Reserve__c ,
                    Fees_Paid__c , Fees_Reserve__c, Policy__c ,Total_Incurred__c, Policy_Effective_Date__c
                    from Claim_Data__c WHERE Account__c =: oppRecordwithAccountId[0].AccountId] ;
        }
        
        
    
}