main/default/objects/Assignment_Matrix__c/Assignment_Matrix__c.object-meta.xml
<CustomObject>
    <label>Assignment Matrix</label>
    <nameField>
        <displayFormat>AM-{0000}</displayFormat>
        <label>Assignment Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Assignment_Matrix__c/fields/Assignment_Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Object_Type__c</fullName>
    <label>Assignment Object Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Document</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Assignment_Matrix__c/fields/Document_Template__c.field-meta.xml
<CustomField>
    <fullName>Document_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Template</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Assignment Matrices</relationshipLabel>
    <relationshipName>Assignment_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Assignment_Matrix__c/fields/Lookup_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Field_API_Name__c</fullName>
    <description>The lookup field to be used for current assignment</description>
    <label>Assignment Lookup Field API Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Document_Template__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Assignment_Matrix__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Assignment_Matrix__c/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <externalId>true</externalId>
    <label>Unique Identifier</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Assignment_Matrix_Query_Settings__mdt/Assignment_Matrix_Query_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Assignment Matrix Query Settings</label>
    <pluralLabel>Assignment Matrix Query Settings</pluralLabel>
</CustomObject>

main/default/objects/Assignment_Matrix_Query_Settings__mdt/fields/Assignment_Object__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Object__c</fullName>
    <label>Assignment Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Document</fullName>
                <default>true</default>
                <label>Document</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Assignment_Matrix_Query_Settings__mdt/fields/Is_Primary_Object__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary_Object__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Object</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Assignment_Matrix_Query_Settings__mdt/fields/Lookup_Field_API_name__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Field_API_name__c</fullName>
    <label>Lookup Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Assignment_Matrix_Query_Settings__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Assignment_Matrix_Query_Settings__mdt/fields/Object_Query__c.field-meta.xml
<CustomField>
    <fullName>Object_Query__c</fullName>
    <label>Object Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Assignment_Matrix_Query_Settings__mdt/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Professional Indemnity</fullName>
                <default>true</default>
                <label>Professional Indemnity</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Assignment_Matrix_Query_Settings__mdt/fields/Related_Field_On_Primary_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_Field_On_Primary_API_Name__c</fullName>
    <description>Related Field API name on Primary Object</description>
    <label>Related Field On Primary API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Assignment_Matrix_Rule__c/Assignment_Matrix_Rule__c.object-meta.xml
<CustomObject>
    <label>Assignment Matrix Rule</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Assignment Matrix Rules Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Matrix Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Assignment_Matrix_Rule__c/fields/Assignment_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Matrix__c</fullName>
    <label>Assignment Matrix</label>
    <referenceTo>Assignment_Matrix__c</referenceTo>
    <relationshipLabel>Assignment Matrix Rules</relationshipLabel>
    <relationshipName>Assignment_Matrix_Rules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Assignment_Matrix_Rule__c/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <label>Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Assignment_Matrix_Rule__c/fields/Includes_Group_Number__c.field-meta.xml
<CustomField>
    <fullName>Includes_Group_Number__c</fullName>
    <label>Includes Group Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Assignment_Matrix_Rule__c/fields/Is_NOT__c.field-meta.xml
<CustomField>
    <fullName>Is_NOT__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Returns inverse of rule evaluated value</description>
    <label>Is NOT</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Assignment_Matrix_Rule__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Field_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>equals</fullName>
                <default>true</default>
                <label>equals</label>
            </value>
            <value>
                <fullName>not equals</fullName>
            </value>
            <value>
                <fullName>in</fullName>
            </value>
            <value>
                <fullName>less than</fullName>
            </value>
            <value>
                <fullName>greater than</fullName>
            </value>
            <value>
                <fullName>less than equals</fullName>
            </value>
            <value>
                <fullName>greater than equals</fullName>
            </value>
            <value>
                <fullName>is null</fullName>
            </value>
            <value>
                <fullName>not null</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Assignment_Matrix_Rule__c/fields/Rule_Type__c.field-meta.xml
<CustomField>
    <fullName>Rule_Type__c</fullName>
    <inlineHelpText>For rule type Key Value Query which is used to apply rules to 2 fields in just one rule:
1. Field API Name must include 2 fields separated by semi-colon.
2. The first of these 2 fields must be of type &apos;Text&apos;.
3. The selected operator and field type applies to only second field.
4. The first field will use equals operator and the second field will use the operator selected.</inlineHelpText>
    <label>Rule Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Field Query</fullName>
            </value>
            <value>
                <fullName>Key Value Query</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <label>Document Template</label>
    <nameField>
        <displayFormat>DOC-{0000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Document_Template__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <label>Document Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/classes/AssignmentMatrixUtil.cls
/**
 * @description       : 
 * @author            : Vinayesh
 * @group             : 
 * @last modified on  : 07-26-2022
 * @last modified by  : Vinayesh
**/
public with sharing class AssignmentMatrixUtil {
    private static final String EQUALS_OPERATOR = 'equals';
    private static final String NOT_EQUALS_OPERATOR = 'not equals';
    private static final String IN_OPERATOR = 'in';
    private static final String GREATER_THAN_OPERATOR = 'greater than';
    private static final String LESS_THAN_OPERATOR = 'less than';
    private static final String GREATER_THAN_EQUALS_OPERATOR = 'greater than equals';
    private static final String LESS_THAN_EQUALS_OPERATOR = 'less than equals';
    private static final String IS_NULL_OPERATOR = 'is null';
    private static final String NOT_NULL_OPERATOR = 'not null';

    private static final String DOCUMENT_TYPE = 'Document';


    /**
    * @description : Populate default assignments.
    * @author
    * @param primaryId, assignmentObjectType, productName 
    * @return List<String>
    **/
    public static Set<String> GetAssignmentData(String primaryId, String assignmentObjectType, String productName) {
       String prodName = productName.split(' ')[0];
        //Need to look at error handling. Probably need a wrapper result class with error msg
       Map<String,List<sObject>> relatedDataMap = getDataMap(primaryId, assignmentObjectType, prodName);
       //String productName = (String)quoteRelatedDataMap.get(((Id)quoteId).getSObjectType().getDescribe().getName())[0].get('Product_Name__c');

       
       Map<String, List<Assignment_Matrix__c>> filterCriteriaParentMap = getFilterCriteriaParentMap(assignmentObjectType, productName);
       Map<String, List<Assignment_Matrix_Rule__c>> filterCriteriaRuleMap = getFilterCriteriaRuleMap(filterCriteriaParentMap.values());
       
       Set<String> filteredDefaultDataIds = filterAssignments(relatedDataMap, filterCriteriaParentMap, filterCriteriaRuleMap);

       
       System.debug(filteredDefaultDataIds);
       return filteredDefaultDataIds;
    }

    /**
     * Logic to filter default coverages for quote
     */
    private static Set<String> filterAssignments(Map<String,List<sObject>> relatedDataMap, Map<String, List<Assignment_Matrix__c>> filterCriteriaParentMap,
                                                 Map<String, List<Assignment_Matrix_Rule__c>> filterCriteriaRuleMap) {
       Set<String> dataIds = new Set<String>();
       for(String dataId : filterCriteriaParentMap.keySet()){
           dataIds.add(dataId);
       }
       
       Set<String> defaultAssignments = new Set<String>();
       for(String dataId : dataIds){  
           boolean assignmentMatchFound = false;       
           for(Assignment_Matrix__c parentRule : filterCriteriaParentMap.get(dataId)){
               Map<Integer, Boolean> groupMatch = new Map<Integer, Boolean>();
               Boolean hasNonGroupCriteria = false;
               for(Assignment_Matrix_Rule__c criteriaRule : filterCriteriaRuleMap.get(parentRule.Id)){
                   boolean ruleMatch = false;
                   if(criteriaRule.Includes_Group_Number__c == null) hasNonGroupCriteria = true;
                   List<sObject> dataObjList = relatedDataMap.get(criteriaRule.Object_API_Name__c);
                   //Object dataValue = dataObj.get(criteriaRule.Field_API_Name__c);
                    for(sObject dataObj : dataObjList){
                        if(criteriaRule.Rule_Type__c == 'Key Value Query'){
                            List<String> lstKey = criteriaRule.Field_API_Name__c.split(';');
                            List<String> lstValue = criteriaRule.Value__c.split(';');
                            if(checkMatch(dataObj, lstKey[0], lstValue[0], 'Text', EQUALS_OPERATOR)
                                && checkMatch(dataObj, lstKey[1], lstValue[1], criteriaRule.Field_Type__c, criteriaRule.Operator__c)){
                                ruleMatch = true;
                            }
                        }
                        else{
                            ruleMatch = checkMatch(dataObj, criteriaRule.Field_API_Name__c, criteriaRule.Value__c, criteriaRule.Field_Type__c, criteriaRule.Operator__c);
                        }
                    }
                   
                    if(criteriaRule.Is_NOT__c) ruleMatch = !ruleMatch; //If IsNOT checked we want to return the inverse.
                    System.debug(criteriaRule.Name);
                    System.debug(ruleMatch);
                    if(ruleMatch && criteriaRule.Includes_Group_Number__c == null){
                        assignmentMatchFound = true;
                    }
                    else if(!ruleMatch && criteriaRule.Includes_Group_Number__c == null){
                        assignmentMatchFound = false;
                        break;
                    }
                    else{
                        Integer grpNum = criteriaRule.Includes_Group_Number__c.intValue();
                        if(!groupMatch.containsKey(grpNum)){
                            groupMatch.put(grpNum, ruleMatch);
                        }
                        if(ruleMatch){
                            groupMatch.put(grpNum, true);
                        }
                    }

                //    if(ruleMatch) {
                //         assignmentMatchFound = true;
                //    }
                //    else{
                //         assignmentMatchFound = false;
                //        break;
                //    }
                   
               }
                boolean groupsMatch = true;
                if(groupMatch.size() > 0){
                    for(Boolean currMatch : groupMatch.values()){
                        if(!currMatch) groupsMatch = false;
                    }
                }
               if(assignmentMatchFound && groupsMatch) break;
               if(!hasNonGroupCriteria && groupsMatch){
                   assignmentMatchFound = true;
                   break;
               }
               else{
                   assignmentMatchFound = false;
               }
           }

           if(assignmentMatchFound) defaultAssignments.add(dataId);
       }

       return defaultAssignments;
    }
    
    /**
     * check for field match
     */
    private static boolean checkMatch(sObject dataObj, String fieldName, String checkValue, String fieldType, String operator){
        Object dataValue = dataObj.get(fieldName);
        if(dataValue == null){
            if(operator == IS_NULL_OPERATOR){
                return true;
            }
            else return false;
        }
        else{
            if(operator == NOT_NULL_OPERATOR){
                return true;
            }
        }
        boolean ruleMatch = false;
        switch on fieldType {
            when 'Text' {
                String textVal = (String)dataValue;
                    if(operator == EQUALS_OPERATOR) {
                        if(textVal == checkValue){
                            ruleMatch = true;
                        }
                    }
                    else if(operator == NOT_EQUALS_OPERATOR) {
                        if(textVal != checkValue){
                            ruleMatch = true;
                        }
                    }
                    else if(operator == IN_OPERATOR) {
                        //Need to split values and check individually. Make this change in coverages matrix also.
                        if(checkValue.containsIgnoreCase(textVal)){
                            ruleMatch = true;
                        }
                    }
            }
            when 'Number' {
                decimal numVal = Decimal.valueOf(String.valueOf(dataValue));
                decimal numCheckValue = Decimal.valueOf(checkValue);
                if(operator == EQUALS_OPERATOR) {
                    if(numval == numCheckValue){
                        ruleMatch = true;
                    }
                }
                else if(operator == NOT_EQUALS_OPERATOR) {
                    if(numval != numCheckValue){
                        ruleMatch = true;
                    }
                }
                else if(operator == LESS_THAN_OPERATOR) {
                    if(numval < numCheckValue){
                        ruleMatch = true;
                    }
                }
                else if(operator == LESS_THAN_EQUALS_OPERATOR) {
                    if(numval <= numCheckValue){
                        ruleMatch = true;
                    }
                }
                else if(operator == GREATER_THAN_OPERATOR) {
                    if(numval > numCheckValue){
                        ruleMatch = true;
                    }
                }
                else if(operator == GREATER_THAN_EQUALS_OPERATOR) {
                    if(numval >= numCheckValue){
                        ruleMatch = true;
                    }
                }
            }
            when 'Boolean' {
                boolean isChecked = (boolean)dataValue;
                if(operator == EQUALS_OPERATOR) {
                    if(isChecked && checkValue == 'true'){
                        ruleMatch = true;
                    }
                    else if(!isChecked && checkValue == 'false'){
                        ruleMatch = true;
                    }
                }
            }
         }
         return ruleMatch;
    }

    /**
     * Get all related data used in filtering result.
     */
    private static Map<String,List<sObject>> getDataMap(String primaryId, String assignmentObjectType, String productName) {
      Map<String,List<sObject>> dataMap = new Map<String,List<sObject>>();
      String likeCondition = '%' + productName + '%';
      //Need to do normal soql here as static query for metadata has issue with long text area
      List<Assignment_Matrix_Query_Settings__mdt> queryList = [select Id, DeveloperName, MasterLabel, Label, QualifiedApiName, 
                                                               Object_Query__c, Is_Primary_Object__c, Related_Field_On_Primary_API_Name__c,
                                                               Lookup_Field_Api_name__c, Assignment_Object__c, Product_Name__c, Object_API_Name__c
                                                               From Assignment_Matrix_Query_Settings__mdt
                                                               Where Assignment_Object__c =: assignmentObjectType And Product_Name__c like :likeCondition And IsActive__c = true];
      //List<Assignment_Matrix_Query_Settings__mdt> queryList = Assignment_Matrix_Query_Settings__mdt.getall().values();
      List<sObject> primaryObj;
      for(Assignment_Matrix_Query_Settings__mdt queryItem : queryList){
          if(queryItem.Is_Primary_Object__c){
              String primaryQuery = queryItem.Object_Query__c + ' Where Id' + ' =: primaryId';
              primaryObj = Database.query(primaryQuery);
              dataMap.put(queryItem.Object_API_Name__c, primaryObj);
              break;
          }
      }
      for(Assignment_Matrix_Query_Settings__mdt queryItem : queryList){
        if(!queryItem.Is_Primary_Object__c){
          String lookupField = queryItem.Lookup_Field_API_name__c;
          String relatedFieldValue = (String)primaryObj[0].get(queryItem.Related_Field_On_Primary_API_Name__c);
          String relatedQuery = '';
          if(queryItem.Object_Query__c.containsIgnoreCase(' where ')){
              relatedQuery = queryItem.Object_Query__c + ' And ' + lookupField + ' =: relatedFieldValue';
          }
          else{
              relatedQuery = queryItem.Object_Query__c + ' Where ' + lookupField + ' =: relatedFieldValue';
          }
            
          List<sObject> relatedList = Database.query(relatedQuery);
          dataMap.put(queryItem.Object_API_Name__c, relatedList);
      }
    }
      return dataMap;
    }

      /**
       * Get Assignment Object Id to parent matrix records map.
       */
      private static Map<String, List<Assignment_Matrix__c>> getFilterCriteriaParentMap(String assignmentObjectType, String productName){

        List<Assignment_Matrix__c> matrixList = [SELECT  Name, Document_Template__c, Assignment_Object_Type__c, Product__c,
                                                 Lookup_Field_API_Name__c, IsActive__c, Description__c, Unique_Identifier__c
                                                 FROM Assignment_Matrix__c
                                                 WHERE IsActive__c = true AND Product__c like: productName AND Assignment_Object_Type__c =: assignmentObjectType];
        Map<String, List<Assignment_Matrix__c>> matrixMap = new Map<String, List<Assignment_Matrix__c>>();
        for(Assignment_Matrix__c rootItem : matrixList){
            String lookupField = (String)rootItem.get(rootItem.Lookup_Field_API_Name__c);
            if(!matrixMap.containsKey(lookupField)){
                matrixMap.put(lookupField, new List<Assignment_Matrix__c>());
            }
            matrixMap.get(lookupField).add(rootItem);
        }
        return matrixMap;
      }


    /**
     * Get Parent to Child Criteria Rule records map.
     */
    private static Map<String, List<Assignment_Matrix_Rule__c>> getFilterCriteriaRuleMap(List<List<Assignment_Matrix__c>> parentList){
        List<Assignment_Matrix__c> parentMatrices = new List<Assignment_Matrix__c>();
        for(List<Assignment_Matrix__c> listItems : parentList){
            parentMatrices.addAll(listItems);
        }
        List<Assignment_Matrix_Rule__c> filterRuleList = [SELECT Name, Assignment_Matrix__c, Field_API_Name__c, Field_Type__c, IsActive__c, 
                                                          Operator__c, Object_API_Name__c, Rule_Type__c, Value__c, Includes_Group_Number__c, Is_NOT__c
                                                          FROM Assignment_Matrix_Rule__c
                                                          WHERE Assignment_Matrix__c in: parentMatrices AND IsActive__c = true order by Includes_Group_Number__c];
        Map<String, List<Assignment_Matrix_Rule__c>> filterRuleMap = new Map<String, List<Assignment_Matrix_Rule__c>>();
        for(Assignment_Matrix_Rule__c ruleItem : filterRuleList){
            if(!filterRuleMap.containsKey(ruleItem.Assignment_Matrix__c)){
                filterRuleMap.put(ruleItem.Assignment_Matrix__c, new List<Assignment_Matrix_Rule__c>());
            }
            filterRuleMap.get(ruleItem.Assignment_Matrix__c).add(ruleItem);
        }
        
        return filterRuleMap;
    }

     /**
    * @description : Populate default documents.
    * @author
    * @param primaryId, productName 
    * @return List<Document_Template__c>
    **/
    public static List<Document_Template__c> GetDocumentsData(String primaryId, String productName) {       
        Set<String> filteredDefaultDocIds = GetAssignmentData(primaryId, DOCUMENT_TYPE, productName);
        System.debug(filteredDefaultDocIds);
        List<Document_Template__c> docList = [Select Id, Document_Name__c
                                              From Document_Template__c
                                              Where Id in: filteredDefaultDocIds];
        System.debug(docList);
        return docList;
        //return filteredDefaultDocIds;
     }
}