main/default/objects/Assignment_Matrix__c/Assignment_Matrix__c.object-meta.xml
<CustomObject>
    <label>Assignment Matrix</label>
    <nameField>
        <displayFormat>AM-{0000}</displayFormat>
        <label>Assignment Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Assignment_Matrix__c/fields/Assignment_Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Object_Type__c</fullName>
    <label>Assignment Object Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Document</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Assignment_Matrix__c/fields/Document_Template__c.field-meta.xml
<CustomField>
    <fullName>Document_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Template</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Assignment Matrices</relationshipLabel>
    <relationshipName>Assignment_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Assignment_Matrix__c/fields/Lookup_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Field_API_Name__c</fullName>
    <description>The lookup field to be used for current assignment</description>
    <label>Assignment Lookup Field API Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Document_Template__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Assignment_Matrix__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Assignment_Matrix__c/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <externalId>true</externalId>
    <label>Unique Identifier</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Assignment_Matrix_Rule__c/Assignment_Matrix_Rule__c.object-meta.xml
<CustomObject>
    <label>Assignment Matrix Rule</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Assignment Matrix Rules Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Matrix Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Assignment_Matrix_Rule__c/fields/Assignment_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Matrix__c</fullName>
    <label>Assignment Matrix</label>
    <referenceTo>Assignment_Matrix__c</referenceTo>
    <relationshipLabel>Assignment Matrix Rules</relationshipLabel>
    <relationshipName>Assignment_Matrix_Rules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Assignment_Matrix_Rule__c/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <label>Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Assignment_Matrix_Rule__c/fields/Includes_Group_Number__c.field-meta.xml
<CustomField>
    <fullName>Includes_Group_Number__c</fullName>
    <label>Includes Group Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Assignment_Matrix_Rule__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Field_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>equals</fullName>
                <default>true</default>
                <label>equals</label>
            </value>
            <value>
                <fullName>not equals</fullName>
            </value>
            <value>
                <fullName>in</fullName>
            </value>
            <value>
                <fullName>less than</fullName>
            </value>
            <value>
                <fullName>greater than</fullName>
            </value>
            <value>
                <fullName>less than equals</fullName>
            </value>
            <value>
                <fullName>greater than equals</fullName>
            </value>
            <value>
                <fullName>is null</fullName>
            </value>
            <value>
                <fullName>not null</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Assignment_Matrix_Rule__c/fields/Rule_Type__c.field-meta.xml
<CustomField>
    <fullName>Rule_Type__c</fullName>
    <inlineHelpText>For rule type Key Value Query which is used to apply rules to 2 fields in just one rule:
1. Field API Name must include 2 fields separated by semi-colon.
2. The first of these 2 fields must be of type &apos;Text&apos;.
3. The selected operator and field type applies to only second field.
4. The first field will use equals operator and the second field will use the operator selected.</inlineHelpText>
    <label>Rule Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Field Query</fullName>
            </value>
            <value>
                <fullName>Key Value Query</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Broker_Account__c/Broker_Account__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Broker_Account__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Broker_Contact__r.AccountId ,  Broker_Contact__r.Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <label>Broker Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker_Contact</value>
        </filterItems>
        <infoMessage>You Must Select a Broker Contact</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Broker_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/IsPrimaryBroker__c.field-meta.xml
<CustomField>
    <fullName>IsPrimaryBroker__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary Broker?</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Broker Accounts</relationshipLabel>
    <relationshipName>Opportunity_Accounts1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker</fullName>
                <default>true</default>
                <label>Broker</label>
            </value>
            <value>
                <fullName>Sub-Producer</fullName>
            </value>
            <value>
                <fullName>Additional Interest</fullName>
                <isActive>false</isActive>
                <label>Additional Interest</label>
            </value>
            <value>
                <fullName>Insured</fullName>
                <isActive>false</isActive>
                <label>Insured</label>
            </value>
            <value>
                <fullName>Reinsured</fullName>
                <isActive>false</isActive>
                <label>Reinsured</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Document_Revision__c/Document_Revision__c.object-meta.xml
<CustomObject>
    <label>Document Revision</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Revisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Document_Revision__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Document Revisions</relationshipLabel>
    <relationshipName>Document_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Document_Revision__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <label>Policy</label>
</RecordType>

main/default/objects/Document_Revision__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <label>Document Template</label>
    <nameField>
        <displayFormat>DOC-{0000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Document_Template__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <label>Document Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Layer__c.field-meta.xml
<CustomField>
    <fullName>Layer__c</fullName>
    <label>Layer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/recordTypes/Aqueous.recordType-meta.xml
<RecordType>
    <fullName>Aqueous</fullName>
    <active>true</active>
    <label>Aqueous</label>
</RecordType>

main/default/objects/Renewal__c/Renewal__c.object-meta.xml
<CustomObject>
    <label>Renewal</label>
    <nameField>
        <displayFormat>REN-{00000}</displayFormat>
        <label>Renewal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Renewal__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker</label>
    <referenceTo>Broker_Account__c</referenceTo>
    <relationshipLabel>Renewals</relationshipLabel>
    <relationshipName>Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Renewal__c/fields/Claims_Number__c.field-meta.xml
<CustomField>
    <fullName>Claims_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Claims #</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Renewal__c/fields/Main_Profession__c.field-meta.xml
<CustomField>
    <fullName>Main_Profession__c</fullName>
    <formula>TEXT(Latest_Bound_Quote__r.Opportunity.Main_Profession__c)</formula>
    <label>Main Profession</label>
    <type>Text</type>
</CustomField>

main/default/objects/Renewal__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Renewals</relationshipLabel>
    <relationshipName>Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Renewal__c/recordTypes/Aqueous.recordType-meta.xml
<RecordType>
    <fullName>Aqueous</fullName>
    <active>true</active>
    <label>Aqueous</label>
</RecordType>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/AssignmentMatrixUtilTest.cls
/**
 * @description       : 
 * @author            : Vinayesh
 * @group             : 
 * @last modified on  : 07-25-2022
 * @last modified by  : Vinayesh
**/
@isTest
public class AssignmentMatrixUtilTest {
    @testSetup static void setup() {
        TriggerSettings__c setting = TestUtil.initialTriggerSetting();
        setting.BypassQuoteTrigger__c = false;
        update setting;
        GlobalStaticVar.byPassRenewalTrigger = true;
        
        String RecordTypeId = Schema.SObjectType.Renewal__c.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Contact con = new Contact(
            Email = 'test@j.com',
            Lastname = 'Test broker',
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId()
        );
        insert con;
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'England', '11354', 'United Kingdom');
        acc.BillingStreet = acc.ShippingStreet;
        acc.BillingCity = acc.ShippingCity;
        acc.BillingState = 'England';
        acc.BillingPostalCode = acc.ShippingPostalCode;
        acc.BillingCountry = acc.ShippingCountry;
        insert acc;
        Account accaq = TestUtil.createBusinessAccount('Bussiness Accoun Aq', 'Business', '123 Main Street', 'Anycity', 'England', '11354', 'United Kingdom');
        accaq.BillingStreet = acc.ShippingStreet;
        accaq.BillingCity = acc.ShippingCity;
        accaq.BillingState = 'England';
        accaq.BillingPostalCode = acc.ShippingPostalCode;
        accaq.BillingCountry = acc.ShippingCountry;
        insert accaq;
        
        Id aqueousRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Product2 productaq = TestUtil.createProduct('Professional Indemnity');
        productaq.RecordTypeId = aqueousRecordTypeId; 
        productaq.Innovisk_Entity_ID__c = 'Aqueous';
        insert productaq; 
        Opportunity oppaq = TestUtil.createOpportunity('Opp Test',accaq.Id, productaq.Id);
        oppaq.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        oppaq.AccountId = accaq.Id;
        oppaq.StageName = 'Qualified'; 
        oppaq.Innovisk_Entity_ID__c = 'Aqueous';                            
        oppaq.Product__c = productaq.Id;
        oppaq.Submission_Status__c = 'Quoted';
        oppaq.Transaction_Status__c = 'Active';
        oppaq.Coverage_Product_Options__c = 'Professional Indemnity';
        oppaq.Tax_Country__c = 'United Kingdom';
        oppaq.Main_Profession__c = 'Accountants';
        insert oppaq;


        Quote quote1 = TestUtil.createQuote('New quote', oppaq.Id);
        quote1.Layer__c = 'Primary';
        quote1.Coverage_Product_Options__c = 'Professional Indemnity';
        quote1.Status = 'Bound';
        insert quote1; 

        String rdPolicyId = Schema.SObjectType.Document_Revision__c.getRecordTypeInfosByName().get('Policy').getRecordTypeId(); 
        Policy__c policy = new Policy__c();
        policy.Account__c = accaq.Id; 
        policy.Expiration_Date__c = Date.today().addDays(100);
        insert policy;

        quote1.Policy__c=policy.Id;
        update quote1;  
        
        Broker_Account__c brokerAccount = new Broker_Account__c(
            Broker_Contact__c = con.Id,
            Opportunity__c = oppaq.Id,
            IsPrimaryBroker__c = true,
            Relationship_Type__c = 'Broker'
        );
        insert brokerAccount;
        
        Document_Template__c document = new Document_Template__c();
        document.Document_Name__c = 'Accountants Proposal Form & a Tax Scheme Questionnaire';
        insert document;
        
        Assignment_Matrix__c am = new Assignment_Matrix__c();
        am.Document_Template__c = document.id ;
        am.Assignment_Object_Type__c = 'Document';
		am.IsActive__c = true ;
       // am.Assignment_Object_Type__c = 'Document_Template__c' ;
        am.Unique_Identifier__c = 'DOC-0002_1';
       // am.CurrencyIsoCode = 'USD';
       	am.Product__c = 'Professional Indemnity';
        am.Lookup_Field_API_Name__c = 'Document_Template__c';
        insert am;
        
        Assignment_Matrix_Rule__c amr = new Assignment_Matrix_Rule__c();
        amr.Assignment_Matrix__c = am.Id;
        amr.Field_Type__c = 'Text';
        amr.IsActive__c = true ; 
        amr.Rule_Type__c = 'Field Query';
        amr.Field_API_Name__c = 'Main_Profession__c';
        amr.Value__c = 'Accountants';
        amr.Operator__c = 'in';
        amr.Object_API_Name__c = 'Renewal__c';
        amr.Includes_Group_Number__c = 1;
        insert amr;

        Assignment_Matrix_Rule__c amr1 = new Assignment_Matrix_Rule__c();
        amr1.Assignment_Matrix__c = am.Id;
        amr1.Field_Type__c = 'Number';
        amr1.IsActive__c = true ; 
        amr1.Rule_Type__c = 'Field Query';
        amr1.Field_API_Name__c = 'Claims_Number__c';
        amr1.Value__c = '0';
        amr1.Operator__c = 'greater than equals';
        amr1.Object_API_Name__c = 'Renewal__c';
        amr1.Includes_Group_Number__c = 1;
        insert amr1;

        Assignment_Matrix_Rule__c amr2 = new Assignment_Matrix_Rule__c();
        amr2.Assignment_Matrix__c = am.Id;
        amr2.Field_Type__c = 'Number';
        amr2.IsActive__c = true ; 
        amr2.Rule_Type__c = 'Key Value Query';
        amr2.Field_API_Name__c = 'Main_Profession__c;Claims_Number__c';
        amr2.Value__c = 'Accountants;0';
        amr2.Operator__c = 'greater than equals';
        amr2.Object_API_Name__c = 'Renewal__c';
        amr2.Includes_Group_Number__c = 1;
        insert amr2;
        
        Renewal__c rn = new Renewal__c(
        Broker__c = brokerAccount.id,
       	Documents_Required__c = document.Document_Name__c,
        recordtypeId = RecordTypeId,
        Latest_Bound_Quote__c = quote1.Id,
        Claims_Number__c = 1);
        insert rn;
    }
    // public testmethod static void  testMethod1(){
    //     String RecordTypeId = Schema.SObjectType.Renewal__c.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
    //       Renewal__c renewal = [Select Id, Broker__c From Renewal__c limit 1];
    //     //RenewalService.fetchRenewalRecords(RecordTypeId);
    //     //RenewalService.getListSectionSetting('Professional Indemnity');
    //     test.startTest();
    //     list<Renewal__c> renewalList = [Select id, Policy__c from Renewal__c where id =: renewal.Id];
    //     RenewalTriggerHandler.UpdateRenewalDocuments(renewalList);
    //     test.stopTest();
    // }

    public testmethod static void  testMethod1(){
        String RecordTypeId = Schema.SObjectType.Renewal__c.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
          Renewal__c renewal = [Select Id, Broker__c From Renewal__c limit 1];
        //RenewalService.fetchRenewalRecords(RecordTypeId);
        //RenewalService.getListSectionSetting('Professional Indemnity');
        test.startTest();
        list<Renewal__c> renewalList = [Select id, Policy__c from Renewal__c where id =: renewal.Id];
        //RenewalTriggerHandler.UpdateRenewalDocuments(renewalList);
        AssignmentMatrixUtil.GetDocumentsData(renewal.Id, 'Professional Indemnity');
        test.stopTest();
    }
}