main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <label>API Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/API_Log__c/fields/Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Name__c</fullName>
    <label>Business Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/API_Log__c/fields/Functionality__c.field-meta.xml
<CustomField>
    <fullName>Functionality__c</fullName>
    <label>Functionality</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/classes/APILogBatchTest.cls
@isTest
public class APILogBatchTest {
@isTest
static void insertAPILogTest(){
    API_Log__c apiLog = new API_Log__c();
apiLog.Name = 'Test';
apiLog.Business_Name__c = 'Leopanthera';
apiLog.Status__c = 'Success';
apilog.Functionality__c = 'Rating';
insert apilog;
Datetime yesterday = Datetime.now().addDays(-22);
Test.setCreatedDate(apilog.Id, yesterday);
test.startTest();

String myJSON = JSON.serialize(apilog);
// APILogBatch.insertAPILog(myJSON);
APILogBatchSchedulable a = new APILogBatchSchedulable();
a.execute(null);
test.stopTest();
}
//ScheduleTerritoryInactiveMemberCheck sh1 = new ScheduleTerritoryInactiveMemberCheck();//String sch = '0 0 23 * * ?'; system.schedule('Test Territory Check', sch, sh1); Test.stopTest();
}