main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <label>API Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/API_Log__c/fields/Quote_Id__c.field-meta.xml
<CustomField>
    <fullName>Quote_Id__c</fullName>
    <label>Quote Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Document_Revision__c/Document_Revision__c.object-meta.xml
<CustomObject>
    <label>Document Revision</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Revisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Document_Revision__c/fields/Quote_Id__c.field-meta.xml
<CustomField>
    <fullName>Quote_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Document Revisions</relationshipLabel>
    <relationshipName>Document_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Document_Revision__c/fields/Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type__c</fullName>
    <formula>TEXT(Quote_Id__r.Quote_Type__c)</formula>
    <label>Quote Type</label>
    <type>Text</type>
</CustomField>

main/default/objects/Document_Revision__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

main/default/objects/TriggerSettings__c/fields/BypassAccountTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassAccountTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassAccountTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassOpportunityTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassOpportunityTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassOpportunityTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassProductTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassProductTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassProductTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/GenericSyncApiTest.cls
/**
 * @description       : 
 * @author            : Maeran Shaikh
 * @group             : 
 * @last modified on  : 09-17-2021
 * @last modified by  : Maeran Shaikh
**/
@isTest
public with sharing class GenericSyncApiTest {
    @TestSetup
    public static void setupData(){
        
        TriggerSettings__c setting = TestUtil.initialTriggerSetting();
        setting.BypassOpportunityTrigger__c = false;
        setting.BypassAccountTrigger__c = true;
        setting.BypassProductTrigger__c = true;
        update setting;
        system.assert(setting != null);
        Account acc = TestUtil.createBusinessAccount('Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        insert acc;
        
        Product2 product = TestUtil.createProduct('MPL');
        
        insert product;
        
        Id pricebook2Id = Test.getStandardPricebookId();
        PricebookEntry pricebookEntryEquipment =  TestUtil.createPricebookEntry(pricebook2Id, product.Id);
        insert pricebookEntryEquipment;
        Opportunity opportunity = TestUtil.createOpportunity('Opp Test', acc.Id, product.Id);
        opportunity.StageName = 'Qualified';
        insert opportunity;
        List<Quote> quotes = new List<Quote>();
        for(Integer i=0 ; i<=100 ;i++){
            Quote q = new Quote(Name = 'Test ' + i,OpportunityId =opportunity.Id,Status = 'In Progress');
            quotes.add(q);
        }
        insert  quotes;
        
    }
    @isTest 
    static void getGenericSyncApiTest() {
        Quote quoteTest = [Select Id, Status, Quote_Type__c, Parent_Quote__c, AccountId, OpportunityId from Quote limit 1];
        
        Quote q = new Quote(Name = 'Test',OpportunityId =quoteTest.OpportunityId,Status = 'Bound');
        insert q;
        
        Contract contractTest = new Contract();
        contractTest.AccountId = quoteTest.AccountId;
        insert contractTest;
        quoteTest.Status = 'In Progress';
        quoteTest.Parent_Quote__c = q.Id;
        quoteTest.Quote_Type__c = 'Extension';
        quoteTest.ContractId = contractTest.Id;
        update quoteTest;
        
        Document_Revision__c docTest = new Document_Revision__c();
        docTest.Name = 'Test';
        docTest.Quote_Id__c = quoteTest.Id;
        insert docTest;
        
        Quote updatedQuote = [Select Id, Status, ContractId, Quote_Type__c, Parent_Quote__c from Quote where Id =: quoteTest.Id];
        updatedQuote.Status = 'Bound';
        update updatedQuote;
        
        List<Quote> items = new List<Quote>();
        items.add(updatedQuote);
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        Test.startTest();
        API_Log__c res = GenericSyncApi.getResponseFromApi('Quote_Sync', 'Sync Quote Status', updatedQuote, 'functionName');
        Test.stopTest();
        system.assert(res != null);
        system.assertEquals('Bound', updatedQuote.Status);
    }
}