main/default/objects/Rating_Modifier_Template__c/Rating_Modifier_Template__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier Template</label>
    <nameField>
        <label>Rating Modifier Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifier Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifier_Template__c/fields/Create_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Create_Criteria__c</fullName>
    <label>Create Criteria</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accountants</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Design &amp; Construct</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Insurance Brokers</fullName>
            </value>
            <value>
                <fullName>IT Consultants</fullName>
            </value>
            <value>
                <fullName>Media Professionals</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Property Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Display_Format__c.field-meta.xml
<CustomField>
    <fullName>Display_Format__c</fullName>
    <label>Display Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Factor Values Only</fullName>
            </value>
            <value>
                <fullName>Secondary Modifiers</fullName>
            </value>
            <value>
                <fullName>Primary Modifiers</fullName>
            </value>
            <value>
                <fullName>Eligibility</fullName>
            </value>
            <value>
                <fullName>Pros and Cons</fullName>
            </value>
            <value>
                <fullName>Default Only</fullName>
            </value>
            <value>
                <fullName>Primary Clearance PCC</fullName>
            </value>
            <value>
                <fullName>Clearance</fullName>
            </value>
            <value>
                <fullName>Modifier and Factor Values</fullName>
                <isActive>false</isActive>
                <label>Modifier and Factor Values</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Eligibility_Weighting_Factor__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Weighting_Factor__c</fullName>
    <label>Eligibility Weighting Factor</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Modifier_Format__c.field-meta.xml
<CustomField>
    <fullName>Modifier_Format__c</fullName>
    <label>Modifier Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Radio Button</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Text Area</fullName>
            </value>
            <value>
                <fullName>Rich Text Area</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Page_Section__c.field-meta.xml
<CustomField>
    <fullName>Page_Section__c</fullName>
    <label>Page Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Picklist_Default_Value__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Default_Value__c</fullName>
    <label>Picklist Default Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Picklist_Range__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Range__c</fullName>
    <label>Picklist Range</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Values__c</fullName>
    <label>Option Values</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Rating_Modifier_Code__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Code__c</fullName>
    <externalId>true</externalId>
    <label>Rating Modifier Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/classes/RatingModifierTemplateQueryUtil.cls
/**************************************************************************************************
 * Class Name: RatingModifierTemplateQueryUtil
 * Author: 
 * Date: Dec 27th, 2021
 * Description: Class to keep rating modifier template queries
 * Test Class : 
 **************************************************************************************************/
public with sharing class RatingModifierTemplateQueryUtil {
    /*************************************************
    * Method Name: fetchRatingModifierTemplatesByProductsForRiskCapture
    * Author: 
    * Date: 27th Dec 2021
    * Params: products
    * Return: list of rating modifier templates
    * Exceptions:
    * Revision: 
    * Description: Fetch rating modifier templates by products for Risk Capture Section
     *************************************************/
    public static List<Rating_Modifier_Template__c> fetchRatingModifierTemplatesByProductsForRiskCapture(List<String> products){
        return [SELECT Factor_Default_Value__c,Factor_Max__c,Factor_Min__c,Modifier_Format__c,Product__c,Name,Page_Section__c,
                Picklist_Default_Value__c,Picklist_Range__c,Picklist_Values__c,Sort_Order__c,Sort_Sub_Section__c,Comment__c,
                Sub_Section__c,Eligibility_Weighting_Factor__c,Rating_Modifier_Code__c,Display_Format__c,
                Profile_Name_for_Read_Only__c, Is_Required__c,Create_Criteria__c, Order_of_Page_Section__c 
                FROM Rating_Modifier_Template__c 
                WHERE Product__c IN: products
                AND Page_Section__c =: 'Risk Capture'];
    }
}