main/default/objects/Rating_Modifier_Template__c/Rating_Modifier_Template__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier Template</label>
    <nameField>
        <label>Rating Modifier Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifier Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifier_Template__c/fields/Display_Format__c.field-meta.xml
<CustomField>
    <fullName>Display_Format__c</fullName>
    <label>Display Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Factor Values Only</fullName>
            </value>
            <value>
                <fullName>Secondary Modifiers</fullName>
            </value>
            <value>
                <fullName>Primary Modifiers</fullName>
            </value>
            <value>
                <fullName>Eligibility</fullName>
            </value>
            <value>
                <fullName>Pros and Cons</fullName>
            </value>
            <value>
                <fullName>Default Only</fullName>
            </value>
            <value>
                <fullName>Primary Clearance PCC</fullName>
            </value>
            <value>
                <fullName>Clearance</fullName>
            </value>
            <value>
                <fullName>Modifier and Factor Values</fullName>
                <isActive>false</isActive>
                <label>Modifier and Factor Values</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Page_Section__c.field-meta.xml
<CustomField>
    <fullName>Page_Section__c</fullName>
    <label>Page Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Values__c</fullName>
    <label>Option Values</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Rating_Modifier_Code__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Code__c</fullName>
    <externalId>true</externalId>
    <label>Rating Modifier Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Rating_Modifiers__c/Rating_Modifiers__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier</label>
    <nameField>
        <label>Rating Modifiers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifiers__c/fields/Display_Format__c.field-meta.xml
<CustomField>
    <fullName>Display_Format__c</fullName>
    <label>Display Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Factor Values Only</fullName>
            </value>
            <value>
                <fullName>Eligibility</fullName>
            </value>
            <value>
                <fullName>Secondary Modifiers</fullName>
            </value>
            <value>
                <fullName>Primary Modifiers</fullName>
            </value>
            <value>
                <fullName>Pros and Cons</fullName>
            </value>
            <value>
                <fullName>Default Only</fullName>
            </value>
            <value>
                <fullName>Clearance</fullName>
            </value>
            <value>
                <fullName>Modifier and Factor Values</fullName>
                <isActive>false</isActive>
                <label>Modifier and Factor Values</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Format__c.field-meta.xml
<CustomField>
    <fullName>Format__c</fullName>
    <label>Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Radio Button</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Text Area</fullName>
            </value>
            <value>
                <fullName>Rich Text Area</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Rating Modifiers</relationshipLabel>
    <relationshipName>Rating_Modifiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Rating_Modifier_Code__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Code__c</fullName>
    <label>Rating Modifier Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Rating_Modifier_Value__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Value__c</fullName>
    <label>Rating Modifier Value</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/UW_Analysis__c/UW_Analysis__c.object-meta.xml
<CustomObject>
    <label>UW Analysis</label>
    <nameField>
        <displayFormat>UWA-{0000}</displayFormat>
        <label>UW Analysis</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UW Analysis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/UW_Analysis__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <label>Criteria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Territory</fullName>
            </value>
            <value>
                <fullName>D&amp;C Turnover Split</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Design &amp; Construct</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Insurance Brokers</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Property Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/UW_Analysis__c/fields/Notional_Income__c.field-meta.xml
<CustomField>
    <fullName>Notional_Income__c</fullName>
    <label>Notional Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/UW_Analysis__c/fields/Split_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Split_Percentage__c</fullName>
    <label>Split Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/UW_Analysis__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>UW Analysis</relationshipLabel>
    <relationshipName>UW_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/UW_Analysis__c/fields/UW_Analysis_Code__c.field-meta.xml
<CustomField>
    <fullName>UW_Analysis_Code__c</fullName>
    <label>UW Analysis Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/UW_Analysis__c/fields/UW_Analysis_Name__c.field-meta.xml
<CustomField>
    <fullName>UW_Analysis_Name__c</fullName>
    <label>UW Analysis Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/UW_Analysis__c/fields/UW_Analysis_Template__c.field-meta.xml
<CustomField>
    <fullName>UW_Analysis_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UW Analysis Template</label>
    <referenceTo>UW_Analysis_Template__c</referenceTo>
    <relationshipLabel>UW Analysis</relationshipLabel>
    <relationshipName>UW_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/UW_Analysis_Template__c/UW_Analysis_Template__c.object-meta.xml
<CustomObject>
    <label>UW Analysis Template</label>
    <nameField>
        <displayFormat>UWAT-{0000}</displayFormat>
        <label>UW Analysis Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UW Analysis Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/UW_Analysis_Template__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <label>Criteria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Territory</fullName>
            </value>
            <value>
                <fullName>D&amp;C Turnover Split</fullName>
            </value>
            <value>
                <fullName>Accountants</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Design &amp; Construct</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Insurance Brokers</fullName>
            </value>
            <value>
                <fullName>IT Consultants</fullName>
            </value>
            <value>
                <fullName>Media Professionals</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Property Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/UW_Analysis_Template__c/fields/Rating_Factor__c.field-meta.xml
<CustomField>
    <fullName>Rating_Factor__c</fullName>
    <label>Rating/Factor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/UW_Analysis_Template__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Warnings__c/Warnings__c.object-meta.xml
<CustomObject>
    <label>Warnings</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Warning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warnings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Warnings__c/fields/Main_Profession__c.field-meta.xml
<CustomField>
    <fullName>Main_Profession__c</fullName>
    <formula>TEXT(UW_Analysis_Template__r.Criteria__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Main Profession</label>
    <type>Text</type>
</CustomField>

main/default/objects/Warnings__c/fields/Percent_exceeded__c.field-meta.xml
<CustomField>
    <fullName>Percent_exceeded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Percent exceeded</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Warnings__c/fields/Rating_Modifier_Template__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rating Modifier Template</label>
    <referenceTo>Rating_Modifier_Template__c</referenceTo>
    <relationshipLabel>Warnings</relationshipLabel>
    <relationshipName>Warnings_RMT</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Warnings__c/fields/UW_Analysis_Template__c.field-meta.xml
<CustomField>
    <fullName>UW_Analysis_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UW Analysis Template</label>
    <referenceTo>UW_Analysis_Template__c</referenceTo>
    <relationshipLabel>Warnings</relationshipLabel>
    <relationshipName>Warnings</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Warnings__c/fields/Warning_Text__c.field-meta.xml
<CustomField>
    <fullName>Warning_Text__c</fullName>
    <label>Warning Text</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Warnings__c/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <formula>IF(ISBLANK(UW_Analysis_Template__c),&apos;-&apos;, UW_Analysis_Template__r.UW_Analysis_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Type</label>
    <type>Text</type>
</CustomField>

main/default/classes/UWAnalysisSectionControllerTest.cls
/*************************************************
* Class Name: UWAnalysisSectionController
* Author: Ashik Zahir
* Date: 
* Modified Date: 15-03-2021
* Requirement/Project Description: 
*************************************************/
@isTest
public class UWAnalysisSectionControllerTest {
    @testsetup static void testSetup(){
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
		Account acc  =TestUtil.createAccount('Test account 1', recordTypeId, '01 Tran Duy Hung','Westminster',
												'California','90000', 'United States');
        acc.Azure_ID__c = '8042ac98-ae5a-4692-9880-58d92d0eb9d9';
		insert acc;
    
        Product2 product = TestUtil.createProduct('MPL');
		insert product; 

        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.CloseDate = Date.today()+365;
        opp.StageName = 'New';
        opp.Azure_ID__c = 'f70e4c82-3378-41ce-870b-57f4df415874';
        insert opp;
        
        UW_Analysis_Template__c TempList = new UW_Analysis_Template__c();
        TempList.UW_Analysis_Name__c = 'Test';
        TempList.Criteria__c = 'Engineers';
        TempList.UW_Analysis_Code__c ='Code';
        TempList.Rating_Factor__c= 5000;
        TempList.Sort_Order__c = 100;
       
        insert TempList;
        
        UW_Analysis__c uwList = new UW_Analysis__c();
        uwList.Amount__c = 1000;
        //uwList.Name = 'Test';
        uwList.UW_Analysis_Name__c = 'UW Test';
        uwList.Criteria__c = 'Territory';
        uwList.UW_Analysis_Code__c = 'T1';
        uwList.Rating_Factor__c = 1000;
        uwList.Sort_Order__c = 10;
        uwList.Submission__c = opp.Id;
        uwList.UW_Analysis_Template__c = TempList.Id;
        uwList.Sort_Order__c = 10;
        uwList.Notional_Income__c = 1000;
        insert uwList;
        
        Rating_Modifiers__c ratingModifier1 = TestUtil.createRatingModifier( 'Annual gross fees / turnover', product.Name, opp.Id);
        ratingModifier1.Rating_Modifier_Code__c = 'MPL000025';
        ratingModifier1.Display_Format__c = 'Primary Modifiers';
        ratingModifier1.Opportunity__c = opp.Id;
        ratingModifier1.Rating_Modifier_Value__c = 'Yes';
        ratingModifier1.Page_Section__c = 'Pros and Cons';
        ratingModifier1.Format__c = 'Picklist';
        ratingModifier1.Picklist_Values__c = 'At least one very restrictive endorsement;At least one restrictive endorsement and no very restrictive endorsements;No restrictive endorsement';
        insert ratingModifier1;
        
        //uwList.Criteria__c = 'Design & Construct';
        //update uwList;
        
        /*List<String> fields = new List<String>();
        List<String> params = new List<String>();
        String condition = '';
        String objName = 'Warnings__c';
        fields.add('Id');
        fields.add('UW_Analysis_Template__c');
        fields.add('Rating_Modifier_Template__c');
        fields.add('Warning_Text__c');
        fields.add('Main_Profession__c');
        fields.add('Work_Type__c');
        fields.add('Percent_exceeded__c');
        insert fields;*/
    }
    @isTest static void getUWAnalysisTemplatesTest(){
        Test.startTest();
            Opportunity opp = [select Id,name from  Opportunity limit 1];
            UWAnalysisSectionController.getUWAnalysisTemplates(opp.Id);        
        Test.stopTest();
        system.assert(opp.Id!= null);
    }
    
    @isTest static void createUWAnalysisByTemplateTest(){
        Test.startTest();
        UW_Analysis_Template__c TempList =[Select Id, Name, UW_Analysis_Name__c, Criteria__c 
                                           FROM UW_Analysis_Template__c ];
        Opportunity opp = [select Id,name from  Opportunity limit 1];
        List<String> uwTemplateIds = new List<String>();
        uwTemplateIds.add(TempList.Id);
        UWAnalysisSectionController.createUWAnalysisByTemplate(opp.Id, uwTemplateIds);
        Test.stopTest();
        System.assert(uwTemplateIds!= null);
    }
    @isTest static void getUWAnalysisTest(){
        Test.startTest();
        UW_Analysis_Template__c TempList =[Select Id, Name, UW_Analysis_Name__c, Criteria__c 
                                           FROM UW_Analysis_Template__c ];
        Opportunity opp = [select Id,name from  Opportunity limit 1];
        opp.Main_Profession__c = 'Engineers';
        update opp;
        UWAnalysisSectionController.UWAlyProfessionWrapper uwAlyProfession = UWAnalysisSectionController.getUWAnalysis(opp.Id);
        Test.stopTest();
        system.assert(TempList.UW_Analysis_Name__c == 'Test');
        
    }
    @isTest static void saveUWAnalysisTest(){
        Test.startTest();
        Opportunity opp = [select Id,name from  Opportunity limit 1];
        UW_Analysis__c uwAnalysis = [SELECT UW_Analysis_Name__c, Criteria__c, UW_Analysis_Code__c, Rating_Factor__c,
                                     Sort_Order__c, Submission__c, UW_Analysis_Template__c, Split_Percentage__c,
                                     Amount__c, Notional_Income__c
                                     FROM UW_Analysis__c Limit 1];
        //UWAnalysisSectionController.saveUWAnalysis uwAnalusis = new UWAnalysisSectionController.saveUWAnalysis(uwAnalysis[0]);
        String uwAnalysisJson = '[{"amountClass":"a092500000BJqQNAA1_amount","criteria":"Territory","identifier":"'+uwAnalysis.Id+'","name":"United Kingdom","opportynityId":"'+opp.id+'","ratingFactor":1,"sortOrder":1,"splitClass":"a092500000BJqQNAA1_split","splitPercentage":50,"templateId":"a0R25000004w9yOEAQ","uwCode":"T0","amount":1000}]';
        UWAnalysisSectionController.saveUWAnalysis(uwAnalysisJson, opp.id);
       //System.assert(uwAnalysis!=null);
       Test.stopTest();
    }
    @isTest static void UWAnalysisWrapperTest(){
        Test.startTest();
        UW_Analysis_Template__c TempList =[Select Id, Name, UW_Analysis_Name__c, Criteria__c 
                                           FROM UW_Analysis_Template__c ];
        Opportunity opp = [select Id,name from  Opportunity limit 1];
        List<String> uwTemplateIds = new List<String>();
        uwTemplateIds.add(TempList.Id);
        UWAnalysisSectionController.createUWAnalysisByTemplate(opp.Id, uwTemplateIds);
        List<UW_Analysis__c> uwAnalysis = [SELECT UW_Analysis_Name__c, Criteria__c, UW_Analysis_Code__c, Rating_Factor__c,
                                     Sort_Order__c, Submission__c, UW_Analysis_Template__c, Split_Percentage__c,
                                     Amount__c, Notional_Income__c
                                     FROM UW_Analysis__c ];
        UWAnalysisSectionController.UWAnalysisWrapper uwAnalusis = new UWAnalysisSectionController.UWAnalysisWrapper(uwAnalysis[0]);
        Test.stopTest();
        //system.assert(uwAnalysis[0].Criteria__c  == 'Engineers');
    }
    
      @isTest static void getWarningsForRiskHealthTest(){
        Test.startTest();
        UW_Analysis_Template__c TempList =[Select Id, Name, UW_Analysis_Name__c, Criteria__c 
                                           FROM UW_Analysis_Template__c ];
        Opportunity opp = [select Id,name from  Opportunity limit 1];
        List<String> uwTemplateIds = new List<String>();
        uwTemplateIds.add(TempList.Id);
        //UWAnalysisSectionController.getWarningsForRiskHealth(opp.Id, uwTemplateIds);
        
          List<UW_Analysis__c> uwAnalysis = [SELECT UW_Analysis_Name__c, Criteria__c, UW_Analysis_Code__c, Rating_Factor__c,
                                     Sort_Order__c, Submission__c, UW_Analysis_Template__c, Split_Percentage__c,
                                     Amount__c, Notional_Income__c
                                     FROM UW_Analysis__c ];
         //uwAnalysis.Criteria__c = 'Design & Construct';
          update uwAnalysis;
        UWAnalysisSectionController.getWarningsForRiskHealth('D&O Standalone',opp.Id);        
        Test.stopTest();
        system.assert(opp.Id!= null);
    }
    
}