main/default/objects/Rating_Modifier_Template__c/Rating_Modifier_Template__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier Template</label>
    <nameField>
        <label>Rating Modifier Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifier Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifier_Template__c/fields/Rating_Modifier_Code__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Code__c</fullName>
    <externalId>true</externalId>
    <label>Rating Modifier Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Rating_Modifiers__c/Rating_Modifiers__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier</label>
    <nameField>
        <label>Rating Modifiers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifiers__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Rating Modifiers</relationshipLabel>
    <relationshipName>Rating_Modifiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Rating_Modifier_Code__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Code__c</fullName>
    <label>Rating Modifier Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Rating_Modifier_Value__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Value__c</fullName>
    <label>Rating Modifier Value</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/UW_Analysis__c/UW_Analysis__c.object-meta.xml
<CustomObject>
    <label>UW Analysis</label>
    <nameField>
        <displayFormat>UWA-{0000}</displayFormat>
        <label>UW Analysis</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UW Analysis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/UW_Analysis__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <label>Criteria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Territory</fullName>
            </value>
            <value>
                <fullName>D&amp;C Turnover Split</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Design &amp; Construct</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Insurance Brokers</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Property Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/UW_Analysis__c/fields/Notional_Income__c.field-meta.xml
<CustomField>
    <fullName>Notional_Income__c</fullName>
    <label>Notional Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/UW_Analysis__c/fields/Split_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Split_Percentage__c</fullName>
    <label>Split Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/UW_Analysis__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>UW Analysis</relationshipLabel>
    <relationshipName>UW_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/UW_Analysis__c/fields/UW_Analysis_Code__c.field-meta.xml
<CustomField>
    <fullName>UW_Analysis_Code__c</fullName>
    <label>UW Analysis Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/UW_Analysis__c/fields/UW_Analysis_Name__c.field-meta.xml
<CustomField>
    <fullName>UW_Analysis_Name__c</fullName>
    <label>UW Analysis Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/UW_Analysis__c/fields/UW_Analysis_Template__c.field-meta.xml
<CustomField>
    <fullName>UW_Analysis_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UW Analysis Template</label>
    <referenceTo>UW_Analysis_Template__c</referenceTo>
    <relationshipLabel>UW Analysis</relationshipLabel>
    <relationshipName>UW_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/UW_Analysis_Template__c/UW_Analysis_Template__c.object-meta.xml
<CustomObject>
    <label>UW Analysis Template</label>
    <nameField>
        <displayFormat>UWAT-{0000}</displayFormat>
        <label>UW Analysis Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UW Analysis Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/UW_Analysis_Template__c/fields/Base_Rates__c.field-meta.xml
<CustomField>
    <fullName>Base_Rates__c</fullName>
    <label>Base Rates</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/UW_Analysis_Template__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <label>Criteria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Territory</fullName>
            </value>
            <value>
                <fullName>D&amp;C Turnover Split</fullName>
            </value>
            <value>
                <fullName>Accountants</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Design &amp; Construct</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Insurance Brokers</fullName>
            </value>
            <value>
                <fullName>IT Consultants</fullName>
            </value>
            <value>
                <fullName>Media Professionals</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Property Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/UW_Analysis_Template__c/fields/Rating_Factor__c.field-meta.xml
<CustomField>
    <fullName>Rating_Factor__c</fullName>
    <label>Rating/Factor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/UW_Analysis_Template__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Warnings__c/Warnings__c.object-meta.xml
<CustomObject>
    <label>Warnings</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Warning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warnings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Warnings__c/fields/Main_Profession__c.field-meta.xml
<CustomField>
    <fullName>Main_Profession__c</fullName>
    <formula>TEXT(UW_Analysis_Template__r.Criteria__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Main Profession</label>
    <type>Text</type>
</CustomField>

main/default/objects/Warnings__c/fields/Percent_exceeded__c.field-meta.xml
<CustomField>
    <fullName>Percent_exceeded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Percent exceeded</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Warnings__c/fields/Rating_Modifier_Template__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rating Modifier Template</label>
    <referenceTo>Rating_Modifier_Template__c</referenceTo>
    <relationshipLabel>Warnings</relationshipLabel>
    <relationshipName>Warnings_RMT</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Warnings__c/fields/UW_Analysis_Template__c.field-meta.xml
<CustomField>
    <fullName>UW_Analysis_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UW Analysis Template</label>
    <referenceTo>UW_Analysis_Template__c</referenceTo>
    <relationshipLabel>Warnings</relationshipLabel>
    <relationshipName>Warnings</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Warnings__c/fields/Warning_Text__c.field-meta.xml
<CustomField>
    <fullName>Warning_Text__c</fullName>
    <label>Warning Text</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Warnings__c/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <formula>IF(ISBLANK(UW_Analysis_Template__c),&apos;-&apos;, UW_Analysis_Template__r.UW_Analysis_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Type</label>
    <type>Text</type>
</CustomField>

main/default/classes/UWAnalysisSectionController.cls
/*************************************************
* Class Name: UWAnalysisSectionController
* Author: Saumyak Pandey
* Date: 25-Jan-2021
* Requirement/Project Description: 
*************************************************/
public with sharing class UWAnalysisSectionController {
	@AuraEnabled
    public static List<UW_Analysis_Template__c> getUWAnalysisTemplates(String opportunityId){
		 return getTemplates(opportunityId);   
    }
    
    private static List<UW_Analysis_Template__c> getTemplates(String opportunityId){
        List<Opportunity> oppList = [Select Id, Main_Profession__c From Opportunity where Id =:opportunityId];
        String mainProfession = oppList[0].Main_Profession__c;
        List<UW_Analysis_Template__c> returnUWTempList = new List<UW_Analysis_Template__c>();
        List<UW_Analysis_Template__c> uwTempList = [Select Id, UW_Analysis_Name__c,Base_Rates__c 
                                                    From UW_Analysis_Template__c 
                                                    Where Criteria__c =:mainProfession];
        if(!uwTempList.isEmpty()) returnUWTempList = uwTempList;
        return returnUWTempList;
    }
    
    @AuraEnabled
    public static void createUWAnalysisByTemplate(String opportunityId,List<String> uwTemplateIds){
        List<UW_Analysis__c> uwAnalysisListToSave = new List<UW_Analysis__c>();
        if(String.isNotBlank(opportunityId) && !uwTemplateIds.isEmpty()){
            for(UW_Analysis_Template__c uwTemp : [SELECT Id, Name, UW_Analysis_Name__c, Criteria__c, Base_Rates__c,
                                                      UW_Analysis_Code__c, Rating_Factor__c, Sort_Order__c 
                                                      FROM UW_Analysis_Template__c 
                                                      Where Id IN: uwTemplateIds]){
                                                          UW_Analysis__c uwAnalysis = new UW_Analysis__c();
                                                          
                                                          uwAnalysis.UW_Analysis_Name__c = uwTemp.UW_Analysis_Name__c;
                                                          uwAnalysis.Base_Rates__c = uwTemp.Base_Rates__c;
                                                          uwAnalysis.Criteria__c = uwTemp.Criteria__c;
                                                          uwAnalysis.UW_Analysis_Code__c = uwTemp.UW_Analysis_Code__c;
                                                          uwAnalysis.Rating_Factor__c = uwTemp.Rating_Factor__c;
                                                          uwAnalysis.Sort_Order__c = uwTemp.Sort_Order__c;
                                                          uwAnalysis.Submission__c = opportunityId;
                                                          uwAnalysis.UW_Analysis_Template__c = uwTemp.Id;
                                                          uwAnalysisListToSave.add(uwAnalysis);
                                                      }
        }
            
        if(!uwAnalysisListToSave.isEmpty()){
            insert uwAnalysisListToSave;
        }
    }
    
    /*@AuraEnabled
    public static List<UWAnalysisWrapper> getUWAnalysis(String opportunityId){
        List<UWAnalysisWrapper> uwAnalysisList = new List<UWAnalysisWrapper>();
        for(UW_Analysis__c uwAnalysisQuery : [SELECT Id, UW_Analysis_Name__c, Criteria__c, UW_Analysis_Code__c, 
                                              Rating_Factor__c, Sort_Order__c, Split_Percentage__c, Amount__c, 
                                              Submission__c, Notional_Income__c, UW_Analysis_Template__c 
                                              FROM UW_Analysis__c 
                                              Where Submission__c =:opportunityId]){
                                                  UWAnalysisWrapper uw = new UWAnalysisWrapper(uwAnalysisQuery);
                                                  uwAnalysisList.add(uw);
                                              }
        
        return uwAnalysisList;
    }*/
    
    @AuraEnabled
    public static UWAlyProfessionWrapper getUWAnalysis(String opportunityId){
        UWAlyProfessionWrapper uwWrap = new UWAlyProfessionWrapper();
        List<UWAnalysisWrapper> uwAnalysisList = new List<UWAnalysisWrapper>();
        for(UW_Analysis__c uwAnalysisQuery : [SELECT Id, UW_Analysis_Name__c, Criteria__c, UW_Analysis_Code__c, 
                                              Rating_Factor__c, Sort_Order__c, Split_Percentage__c, Amount__c, 
                                              Submission__c, Notional_Income__c, UW_Analysis_Template__c 
                                              FROM UW_Analysis__c 
                                              Where Submission__c =:opportunityId]){
                                                  UWAnalysisWrapper uw = new UWAnalysisWrapper(uwAnalysisQuery);
                                                  uwAnalysisList.add(uw);
                                              }
        List<Opportunity> opp = [Select Id, Main_Profession__c From Opportunity Where Id =:opportunityId];
        if(!opp.isEmpty()) uwWrap.mainProfession = opp[0].Main_Profession__c;
        if(!uwAnalysisList.isEmpty()) uwWrap.uwAlyRecord = uwAnalysisList;
        
        return uwWrap;
    }
    
    @AuraEnabled 
    public static void saveUWAnalysis(String uwAnalysisJson, String opportunityId){
        System.debug('saveUWAnalysis----->');
        List<UWAnalysisWrapper> uwWrapper = (List<UWAnalysisWrapper>)System.JSON.deserialize(uwAnalysisJson, List<UWAnalysisWrapper>.class);  
      
        Map<string,UW_Analysis__c> oldUWAnalysisMap = new  Map<string,UW_Analysis__c>();
        List<UW_Analysis__c> uwListToUpdate = new List<UW_Analysis__c>();
        Boolean isChanged = false;
        
        List<UW_Analysis__c> oldUWAnalysisList = new List<UW_Analysis__c>();
          oldUWAnalysisList  = [SELECT Id,UW_Analysis_Name__c,Rating_Factor__c,UW_Analysis_Template__c,Sort_Order__c,UW_Analysis_Code__c,Split_Percentage__c,Amount__c FROM UW_Analysis__c 
                                                  WHERE Submission__c =: opportunityId];
       
        if(!oldUWAnalysisList.isEmpty()){
            for(UW_Analysis__c uw: oldUWAnalysisList){
                oldUWAnalysisMap.put(uw.Id, uw);
            }
        }

        for(UWAnalysisWrapper newUW : uwWrapper){
            if(oldUWAnalysisMap.get(newUW.identifier).Amount__c != newUW.amount || oldUWAnalysisMap.get(newUW.identifier).Split_Percentage__c != newUW.splitPercentage){
                System.debug('saveUWAnalysis-----newUW--->'+newUW.amount+'-----'+newUW.splitPercentage);
                System.debug('saveUWAnalysis-----newUW--->'+oldUWAnalysisMap.get(newUW.identifier).Amount__c+'-----'+oldUWAnalysisMap.get(newUW.identifier).Split_Percentage__c);
                isChanged = true;
            }
        }
        if(isChanged){
            for(UWAnalysisWrapper uwWrap: uwWrapper){
                UW_Analysis__c uwAly = new UW_Analysis__c();            
                uwAly.Id = uwWrap.identifier;                   
                uwAly.Rating_Factor__c = uwWrap.ratingFactor;            
                uwAly.Split_Percentage__c =	uwWrap.splitPercentage; 
                uwAly.Amount__c = uwWrap.amount;  
                uwAly.Submission__c = uwWrap.opportynityId;
                uwAly.Notional_Income__c = uwWrap.notonalIncome;
                
                uwListToUpdate.add(uwAly);
            }
        }

        if(!uwListToUpdate.isEmpty()) update uwListToUpdate;
    }
    

    //Prachi added
    @AuraEnabled
    public static List<Warnings__c> getWarningsForRiskHealth(String productName, String opportunityId ) {
         List<UW_Analysis__c> uwRecords = [SELECT Id, UW_Analysis_Name__c, Criteria__c, UW_Analysis_Code__c, 
                                              Rating_Factor__c, Sort_Order__c, Split_Percentage__c, Amount__c, 
                                              Submission__c, Notional_Income__c, UW_Analysis_Template__c 
                                              FROM UW_Analysis__c 
                                              Where Submission__c =:opportunityId];
        Set<Id> uwTempSet = new Set<Id>();
        List<Warnings__c> warningsDataList = new List<Warnings__c>();
        List<Warnings__c> warningsRMDataList = new List<Warnings__c>();
        List<Warnings__c> percentWarningsList = new List<Warnings__c>();
        Set<String> uwCodesForPercentCheck = new Set<String>{'WT61','WT64','WT65','WT70','WT71','WT82','WT84','WT73','WT85',
                                                             'WT86','WT88','WT91'};
        List<UW_Analysis__c> dncWorkTypes = new List<UW_Analysis__c>();                                                         
        Rating_Modifier_Template__c rmTempRecord;
        for(UW_Analysis__c rec : uwRecords){
           uwTempSet.add(rec.UW_Analysis_Template__c);
            if(rec.Criteria__c == 'Design & Construct' && uwCodesForPercentCheck.contains(rec.UW_Analysis_Code__c)){
                dncWorkTypes.add(rec);
            } 
        }
        Decimal sumCheck = 0;
        if(!dncWorkTypes.isEmpty()){
            for(UW_Analysis__c uw : dncWorkTypes){
            sumCheck = sumCheck + uw.Split_Percentage__c;
         } 
        }
        Rating_Modifiers__c rmRecord = [SELECT Opportunity__c, Rating_Modifier_Value__c, Name, Rating_Modifier_Code__c 
                                       FROM Rating_Modifiers__c where Name = 'Annual gross fees / turnover'
                                          AND Opportunity__c =:opportunityId];
        //Dynamic query
        List<String> fields = new List<String>();
        List<String> params = new List<String>();
        String condition = '';
        String objName = 'Warnings__c';
        fields.add('Id');
        fields.add('UW_Analysis_Template__c');
        fields.add('Rating_Modifier_Template__c');
        fields.add('Warning_Text__c');
        fields.add('Main_Profession__c');
        fields.add('Work_Type__c');
        fields.add('Percent_exceeded__c');
        
        // select condition to query rating modifier warnings
        String filterRMWarning = '';
        String rmTempId='';
        if(rmRecord!=null && (rmRecord.Rating_Modifier_Value__c==NULL || rmRecord.Rating_Modifier_Value__c=='0')){
            rmTempRecord = [SELECT Id, Rating_Modifier_Code__c
                                                            FROM Rating_Modifier_Template__c
                                                            WHERE Rating_Modifier_Code__c =:rmRecord.Rating_Modifier_Code__c];
            rmTempId = rmTempRecord.Id;
            filterRMWarning = 'Rating_Modifier_Template__c =: rmTempId';
            System.debug('filterRMWarning::'+filterRMWarning);
            params.add(filterRMWarning);
        }
        
        String filterUWWarnings = '';
        if(!uwTempSet.isEmpty()){
            filterUWWarnings = 'UW_Analysis_Template__c IN: uwTempSet';
            params.add(filterUWWarnings);
        }
        
        String filterpercentWarnings = '';
        if(sumCheck>50){
            filterpercentWarnings = 'Percent_exceeded__c = true';
            params.add(filterpercentWarnings);
        }
        
         condition = String.join(params, ' OR ');
         String query = CommonUtil.buildQuery(fields, objName, condition);
         System.debug('warning query-->'+query);
         warningsDataList = (List<Warnings__c>) Database.query(query);
         return warningsDataList;
    }
    /**** New Code For CD-145 ********/ 
    @AuraEnabled
    public static  List<Rating_Modifiers__c>  getAnnualModifier(String oppId){
        List<Rating_Modifiers__c> rmRecords = [SELECT Opportunity__c, Rating_Modifier_Value__c, Name, Rating_Modifier_Code__c 
        FROM Rating_Modifiers__c where Name = 'Annual gross fees / turnover'
           AND Opportunity__c =:oppId];
           return rmRecords;
    }
    
   
    public class UWAlyProfessionWrapper {
        @AuraEnabled public List<UWAnalysisWrapper> uwAlyRecord     {get; set;}
		@AuraEnabled public String mainProfession              {get; set;}
    }
    public class UWAnalysisWrapper {
        @AuraEnabled public String identifier        {get; set;}
		@AuraEnabled public String name              {get; set;}                     
		@AuraEnabled public String criteria          {get; set;}               
		@AuraEnabled public String uwCode            {get; set;}             
		@AuraEnabled public Decimal ratingFactor     {get; set;}
		@AuraEnabled public Decimal sortOrder        {get; set;}
		@AuraEnabled public Decimal splitPercentage  {get; set;}
		@AuraEnabled public Decimal amount           {get; set;}
		@AuraEnabled public String opportynityId     {get; set;}
		@AuraEnabled public Decimal notonalIncome    {get; set;}
		@AuraEnabled public String templateId        {get; set;} 
        @AuraEnabled public String amountClass       {get; set;} 
        @AuraEnabled public String splitClass        {get; set;} 
        
        public UWAnalysisWrapper() {}

        public UWAnalysisWrapper(UW_Analysis__c uwAly) {
            this.identifier = uwAly.Id;
			this.name = uwAly.UW_Analysis_Name__c;
			this.criteria = uwAly.Criteria__c;
			this.uwCode = uwAly.UW_Analysis_Code__c;
			this.ratingFactor = uwAly.Rating_Factor__c;
			this.sortOrder = uwAly.Sort_Order__c;
			this.splitPercentage = uwAly.Split_Percentage__c;
			this.amount = uwAly.Amount__c;
			this.opportynityId = uwAly.Submission__c;
			this.notonalIncome = uwAly.Notional_Income__c;
			this.templateId = uwAly.UW_Analysis_Template__c;
            this.amountClass = uwAly.Id+'_amount';
            this.splitClass = uwAly.Id+'_split';
        }
    }
}