main/default/objects/Rating_Modifier_Template__c/Rating_Modifier_Template__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier Template</label>
    <nameField>
        <label>Rating Modifier Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifier Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifier_Template__c/fields/Modifier_Product__c.field-meta.xml
<CustomField>
    <fullName>Modifier_Product__c</fullName>
    <label>Modifier Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>D&amp;O Standalone</fullName>
                <isActive>false</isActive>
                <label>D&amp;O Standalone</label>
            </value>
            <value>
                <fullName>Test Product 00</fullName>
                <isActive>false</isActive>
                <label>Test Product 00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Page_Section__c.field-meta.xml
<CustomField>
    <fullName>Page_Section__c</fullName>
    <label>Page Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifiers__c/Rating_Modifiers__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier</label>
    <nameField>
        <label>Rating Modifiers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifiers__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Rating Modifiers</relationshipLabel>
    <relationshipName>Rating_Modifiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Aqueous</fullName>
                <isActive>false</isActive>
                <label>Aqueous</label>
            </value>
            <value>
                <fullName>Cel1</fullName>
                <isActive>false</isActive>
                <label>Cel1</label>
            </value>
            <value>
                <fullName>D&amp;O Standalone</fullName>
                <isActive>false</isActive>
                <label>D&amp;O Standalone</label>
            </value>
            <value>
                <fullName>New Test</fullName>
                <isActive>false</isActive>
                <label>New Test</label>
            </value>
            <value>
                <fullName>Test</fullName>
                <isActive>false</isActive>
                <label>Test</label>
            </value>
            <value>
                <fullName>Test Product 00</fullName>
                <isActive>false</isActive>
                <label>Test Product 00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Sort_Sub_Section__c.field-meta.xml
<CustomField>
    <fullName>Sort_Sub_Section__c</fullName>
    <label>Sort Sub Section</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/classes/SortSubSectionCmpController.cls
public class SortSubSectionCmpController {
	@AuraEnabled
    public static List<SortSubSectionInfo> getSortSubSections(String objId){
		Map<String, SortSubSectionInfo> sortMap = new Map<String, SortSubSectionInfo>();
		// String DynamicfieldName = String.isBlank(objId) ?  'Modifier_Product__c': 'Product__c';
		String DynamicfieldName = 'Product__c';
		String DynamicObjName = String.isBlank(objId) ?  'Rating_Modifier_Template__c': 'Rating_Modifiers__c';
		String soql = 'Select Id, Sort_Sub_Section__c, Sub_Section__c, Page_Section__c, '+ DynamicfieldName + 
					' FROM ' + DynamicObjName + 
					' WHERE Sub_Section__c !=null ' +
					(String.isBlank(objId) ?  '': 'AND Opportunity__c =:objId') +
					' ORDER BY ' +
					'Page_Section__c, Sort_Sub_Section__c ASC';
		List<SObject> getList = Database.query(soql);
		System.debug(soql);
		System.debug(getList);
        for (SObject obj : getList)
		{
 			  String key = (String)obj.get(DynamicfieldName) + (String)obj.get('Page_Section__c') +	(String)obj.get('Sub_Section__c');
			  if(!sortMap.containsKey(key)){
					SortSubSectionInfo subobj = new SortSubSectionInfo();
					subobj.Id = key;
					subobj.pageSection = (String)obj.get('Page_Section__c');
					subobj.subSection = (String)obj.get('Sub_Section__c');
					subobj.sortNo = Integer.valueOf(obj.get('Sort_Sub_Section__c'));
					subobj.product = (String)obj.get(DynamicfieldName);
				
					sortMap.put(key, subobj);
			  }
        } 
        return sortMap.values();
    }

	@AuraEnabled
    public static void updateSortSubSections(List<SortSubSectionInfo> odr, String objId ){
		Map<String, Integer> sortMap = new Map<String, Integer>();
		// String DynamicfieldName = String.isBlank(objId) ?  'Modifier_Product__c': 'Product__c';
		String DynamicfieldName = 'Product__c';
		String DynamicObjName = String.isBlank(objId) ?  'Rating_Modifier_Template__c': 'Rating_Modifiers__c';
		for (SortSubSectionInfo obj : odr)
		{
			String key = obj.Id;
         	if(!sortMap.containsKey(key))	sortMap.put(key, obj.sortNo);
	    }

		String soql = 'Select Id, Sort_Sub_Section__c, Sub_Section__c, Page_Section__c, '+ DynamicfieldName +
					' FROM ' + DynamicObjName+ 
					' WHERE Sub_Section__c !=null ' +
					(String.isBlank(objId) ?  '': 'AND Opportunity__c =:objId') ;

		List<SObject> updateList = Database.query(soql);
        for (SObject obj : updateList)
		{	
			String key = (String)obj.get(DynamicfieldName) + (String)obj.get('Page_Section__c') + (String)obj.get('Sub_Section__c');
			if(sortMap.containsKey(key)) obj.put('Sort_Sub_Section__c', sortMap.get(key));
        } 

		if(!updateList.isEmpty()) update updateList;
    }

	public class SortSubSectionInfo {
		@AuraEnabled
		public String Id			{get; set;}
		@AuraEnabled
		public String product		{get; set;}
		@AuraEnabled
		public String pageSection	{get; set;}
		@AuraEnabled
		public String subSection    {get; set;}
		@AuraEnabled
		public Integer sortNo		{get; set;}
	}
	
}