main/default/objects/Rating_Modifier_Template__c/Rating_Modifier_Template__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier Template</label>
    <nameField>
        <label>Rating Modifier Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifier Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifier_Template__c/fields/Page_Section__c.field-meta.xml
<CustomField>
    <fullName>Page_Section__c</fullName>
    <label>Page Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/RatingModiferTempSectionLwcTest.cls
@isTest
public class RatingModiferTempSectionLwcTest {
@testsetup static void testSetup(){
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
		insert acc;
        
        Product2 product = TestUtil.createProduct('D&O Standalone');
		insert product; 

        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.CloseDate = Date.today();
        opp.StageName = 'Prospect';
        insert opp;
        
        Quote quote1 = TestUtil.createQuote('New quote 1', opp.Id);
        quote1.Status = 'In Progress';
        quote1.Coverage_Product_Options__c = 'D&O';
     	quote1.Refer_Type__c = 'Underwriting Referral';
        insert quote1;  
 
		Quote quote2 = Testutil.createQuote('New Quote 2', opp.Id);
        quote2.Status = 'In Progress';
        quote2.Coverage_Product_Options__c = 'D&O';
        quote2.Refer_Type__c = 'Underwriting Referral';
        insert quote2;
          	
    	Rating_Modifier_Template__c rateMod = new Rating_Modifier_Template__c();
    	rateMod.Name = 'Test';
    	//rateMod.Page_Section__c = 'Test Page Section';
    	//rateMod.Sub_Section__c=  'Test Page Sub Section';
    	rateMod.Product__c = 'MPL';
    	insert rateMod;
 	}
    @istest
    static void getPageSectionListMultiTest(){
        Test.startTest();
        List<String> modifierProductName = new List<String>{'MPL'};
        ratingModiferTempSectionLwcController.getPageSectionListMulti(modifierProductName);
        System.assert(True);
        Test.stopTest();
    }
     @istest
    static void getSubSectionListMultiTest(){
        Test.startTest();
        List<String> modifierProductName = new List<String>{'MPL'};
        ratingModiferTempSectionLwcController.getSubSectionListMulti(modifierProductName, 'Test Page Section');
        System.assert(True);
        Test.stopTest();
    }
      @istest
    static void getFieldListMultiTest(){
        Test.startTest();
        List<String> modifierProductName = new List<String>{'Test 1', 'Test 2'};
        ratingModiferTempSectionLwcController.getFieldListMulti(modifierProductName, 'Test Page Section','Test Page Sub Section');
        System.assert(True);
        Test.stopTest();
    }
}