main/default/objects/Rating_Modifier_Template__c/Rating_Modifier_Template__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier Template</label>
    <nameField>
        <label>Rating Modifier Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifier Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifier_Template__c/fields/Display_Format__c.field-meta.xml
<CustomField>
    <fullName>Display_Format__c</fullName>
    <label>Display Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Factor Values Only</fullName>
            </value>
            <value>
                <fullName>Secondary Modifiers</fullName>
            </value>
            <value>
                <fullName>Primary Modifiers</fullName>
            </value>
            <value>
                <fullName>Eligibility</fullName>
            </value>
            <value>
                <fullName>Pros and Cons</fullName>
            </value>
            <value>
                <fullName>Default Only</fullName>
            </value>
            <value>
                <fullName>Primary Clearance PCC</fullName>
            </value>
            <value>
                <fullName>Clearance</fullName>
            </value>
            <value>
                <fullName>Modifier and Factor Values</fullName>
                <isActive>false</isActive>
                <label>Modifier and Factor Values</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Page_Section__c.field-meta.xml
<CustomField>
    <fullName>Page_Section__c</fullName>
    <label>Page Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/classes/RatingModifierTemplateQueryUtilTest.cls
/**************************************************************************************************
* Class Name: RatingModifierTemplateQueryUtilTest
* Author: 
* Date: Dec 30th, 2021
* Description: 
**************************************************************************************************/

@isTest
public class RatingModifierTemplateQueryUtilTest {
    
    public static testmethod void coverRatingModifierTemplate(){
        Test.startTest();
        
        Rating_Modifier_Template__c rMT = TestUtil.createRatingModifierTemplate('Test Service Classification','D&O','Number');
        rMT.Display_Format__c = 'Clearance';
        rMT.Page_Section__c = 'Risk Capture';
        insert rMT;
        
        RatingModifierTemplateQueryUtil.fetchRatingModifierTemplatesByProductsForRiskCapture( New List<String>{'D&O'});
        
        Test.stopTest();
    }
}