main/default/objects/Additional_Interests__c/Additional_Interests__c.object-meta.xml
<CustomObject>
    <label>Additional Interest</label>
    <nameField>
        <displayFormat>Additional Interest-{0000}</displayFormat>
        <label>Additional Interests Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Additional_Interests__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <externalId>true</externalId>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/classes/AdditionalInterestTriggerHandler_CEL.cls
/**************************************************************************************************
 * Class Name: AdditionalInterestTriggerHandler_CEL
 * Author: 
 * Date: 15th Dec 2021
 * Description: Handler for Celerity
 * Test Class: AdditionalInterestTriggerTest
 **************************************************************************************************/
public with sharing class AdditionalInterestTriggerHandler_CEL extends TriggerHandler{
    private List<Additional_Interests__c> oldDataList;
    private List<Additional_Interests__c> newDataList; 
    private Map<Id, Additional_Interests__c> newDataMap;
    private Map<Id, Additional_Interests__c> oldDataMap; 
    
    public AdditionalInterestTriggerHandler_CEL(List<Additional_Interests__c> newDataList, List<Additional_Interests__c> oldDataList, Map<Id, Additional_Interests__c> newDataMap, Map<Id, Additional_Interests__c> oldDataMap){
        this.oldDataList = oldDataList;
        this.newDataList = newDataList;
        this.newDataMap = newDataMap;
        this.oldDataMap = oldDataMap;
    } 

	public override void beforeInsert()	{
        //generate external id
        CommonUtil.generateExternalID('Azure_ID__c', newDataList);

        //Check if the list of AdditionalInterest is existed, if existed add the error to prevent save it to DB
        CommonAdditionalInterestUtil.checkDuplicateAdditionalInterest(newDataList);
    }

    public override void beforeUpdate(){
        //generate external id
        CommonUtil.generateExternalID('Azure_ID__c', newDataList);
        
        // 06-19-2019 Quang Pham save old value of Account
        CommonAdditionalInterestUtil.setOldValueWhenAccountChanged(oldDataMap, newDataList);
    }

	public override void afterInsert(){

    }

	public override void afterUpdate(){

    }
    
    public override void beforeDelete() {
        //show validation when quote is 'Bound' or 'Bound Pending'
        CommonAdditionalInterestUtil.deleteValidationWhenQuoteLock(oldDataList);
    }
}