main/default/objects/Subjectivity__c/Subjectivity__c.object-meta.xml
<CustomObject>
    <label>Subjectivity</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subjectivity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subjectivity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Subjectivity__c/fields/Cleared__c.field-meta.xml
<CustomField>
    <fullName>Cleared__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cleared</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Cleared_Date__c.field-meta.xml
<CustomField>
    <fullName>Cleared_Date__c</fullName>
    <label>Cleared Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Subjectivity</relationshipLabel>
    <relationshipName>Subjectivity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity__c</fullName>
    <label>Subjectivity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/classes/CommonSubjectivityUtil.cls
/**************************************************************************************************
 * Class Name: CommonSubjectivityUtil
 * Author: 
 * Date: 
 * Description: Common methods for Subjectivity triggers
 **************************************************************************************************/
public class CommonSubjectivityUtil {

	
    /*************************************************
    * Method Name: populateClearedDate
    * Author:
    * Date: 
    * Params: (List<Subjectivity__c> newDataList, Map<Id, Subjectivity__c> oldDataMap
    * Return: 
    * Exceptions:
    * Description: sets the Cleared_Date__c to today if Cleared__c is checked
    * Revision: 
    *************************************************/
    public static void populateClearedDate(List<Subjectivity__c> newDataList, Map<Id, Subjectivity__c> oldDataMap){
       for (Subjectivity__c subRec : newDataList){
            if (subRec.Cleared__c == true)
            {
                subRec.Cleared_Date__c = Date.today();
            }
            else{
                subRec.Cleared_Date__c = null;
            }
        } 
    }


    /*************************************************
    * Method Name: updateQuoteStatusAQ
    * Author:
    * Date: 
    * Params: (List<Subjectivity__c> newDataList, Map<Id, Subjectivity__c> oldDataMap
    * Return: 
    * Exceptions:
    * Description: update quote status
    * Revision: 
    *************************************************/
    public static List<Quote> updateQuoteStatus(List<Subjectivity__c> subjectivities){
        Set<Id> quoteIds = new Set<Id>();
         List<Quote> syncQuotes = new List<Quote>();
        for(Subjectivity__c sub:subjectivities){
            quoteIds.add(sub.Quote__c);
        }

        List<Quote> updateQuote = new List<Quote>();
        String queryFields = 'Id, Status, OpportunityId, Product_Name__c';
        for(Quote quote : QuoteQueryUtil.fetchQuotesForQuoteIds( quoteIds, queryFields ) ){
            if(quote.status == 'Quoted' ){
                quote.status = 'Rated';
                updateQuote.add(quote);
            }
        }
        if(updateQuote.size()>0){
            update updateQuote;
        }
        return updateQuote;
    }
    
}