main/default/objects/Subjectivity__c/Subjectivity__c.object-meta.xml
<CustomObject>
    <label>Subjectivity</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subjectivity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subjectivity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Subjectivity__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Subjectivity</relationshipLabel>
    <relationshipName>Subjectivity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity__c</fullName>
    <label>Subjectivity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity_Status__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Status__c</fullName>
    <label>Subjectivity Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity_Template__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subjectivity Template</label>
    <referenceTo>Subjectivity_Template__c</referenceTo>
    <relationshipLabel>Subjectivity</relationshipLabel>
    <relationshipName>Subjectivity</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity_Text__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Text__c</fullName>
    <label>Subjectivity Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity_Type__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Type__c</fullName>
    <label>Subjectivity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
                <default>true</default>
                <label>General</label>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity_Template__c/Subjectivity_Template__c.object-meta.xml
<CustomObject>
    <label>Subjectivity Template</label>
    <nameField>
        <displayFormat>TEMP-{0000}</displayFormat>
        <label>Subjectivity Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subjectivity Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Subjectivity_Template__c/fields/Layer__c.field-meta.xml
<CustomField>
    <fullName>Layer__c</fullName>
    <label>Layer</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Profession_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Profession_Criteria__c</fullName>
    <label>Profession Criteria</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accountants</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Design &amp; Construct</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Insurance Brokers</fullName>
            </value>
            <value>
                <fullName>IT Consultants</fullName>
            </value>
            <value>
                <fullName>Media Professionals</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Property Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Codes</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Subjectivity_Name__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Name__c</fullName>
    <label>Subjectivity Name</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Subjectivity_Text__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Text__c</fullName>
    <label>Subjectivity Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/subjectivityControllerTest.cls
/**************************************************************************************************
* Class Name: subjectivityControllerTest
* Author: Ashik Zahir
* Created date: 15-Feb-2021
* Description: Test for subjectivityController
**************************************************************************************************/
@isTest
public class subjectivityControllerTest {
	@testSetup
    public static void setup() {
        Id brokerRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account accBroker = TestUtil.createAccount('Account_Business_Test_01', brokerRtId, '5305, Monroe Street', 'Toledo', 'Ohio','43623', 'United States');
        insert accBroker;              	
        
        // create product
        Product2 product = TestUtil.createProduct('Test Product');
        insert product;
        
        // create opportunity        
        Opportunity opp = TestUtil.createOpportunity('Test Opportunity', accBroker.Id, product.Id);
        opp.StageName = 'Qualified';
        insert opp;
        
        // By pass trigger to insert quote
        TriggerSettings__c settings = new TriggerSettings__c();
		settings.BypassQuoteTrigger__c = true;
		insert settings;
		System.assert(settings != null);
        
        Subjectivity_Template__c subjectivityTemplate = new Subjectivity_Template__c();
		subjectivityTemplate.Subjectivity_Name__c = 'Signed / Dated Proposal';
		subjectivityTemplate.Subjectivity_Text__c = 'Test';
		subjectivityTemplate.Profession_Criteria__c = 'Engineers';
		insert subjectivityTemplate;

        Subjectivity_Template__c subjectivityTemplate1 = new Subjectivity_Template__c();
		subjectivityTemplate1.Subjectivity_Name__c = 'Test1';
		subjectivityTemplate1.Subjectivity_Text__c = 'Test1';
        subjectivityTemplate1.State__c = 'OH';
		insert subjectivityTemplate1;

        Subjectivity_Template__c subjectivityTemplate2 = new Subjectivity_Template__c();
		subjectivityTemplate2.Subjectivity_Name__c = 'Test2';
		subjectivityTemplate2.Subjectivity_Text__c = 'Test2';
        subjectivityTemplate2.Layer__c = 'Primary';
		insert subjectivityTemplate2;

        Subjectivity_Template__c subjectivityTemplate3 = new Subjectivity_Template__c();
		subjectivityTemplate3.Subjectivity_Name__c = 'Test3';
		subjectivityTemplate3.Subjectivity_Text__c = 'Test3';
        subjectivityTemplate3.Layer__c = 'Excess';
		insert subjectivityTemplate3;
        
        // create Quote
        Quote q = TestUtil.createQuote('Test Quote', opp.Id);
        q.Rating_Status__c = 'Refer';
        q.Status = 'Rated';
        insert q;
        
        Quote q1 = TestUtil.createQuote('Test Quote Excess 1', opp.Id);
        q1.Layer__c = 'Excess';
        q1.Status = 'Rated';
        insert q1;

        Subjectivity__c subj = new Subjectivity__c();
        subj.Subjectivity__c = 'Testing';
        subJ.Subjectivity_Status__c = 'Open';
        subJ.Subjectivity_Type__c = 'MPL';
        subJ.RecordTypeId = Schema.SObjectType.Subjectivity__c.getRecordTypeInfosByName().get(GlobalVariables.RT_NAME_SUBJECTIVITY_CELERITY).getRecordTypeId();
        subJ.Quote__c = q.Id;
        insert subJ;
    }
    
    @isTest
    public static void testGetSubjectivityByQuoteId() {
        Quote qt = [SELECT id,Name FROM Quote LIMIT 1];
        Test.startTest();
        List<subjectivityController.ItemWrapper> result = subjectivityController.getSubjectivityByQuoteId(qt.Id);
        Test.stopTest();
        System.assertEquals('Open',result[0].subjectivityStatus);
    }
    
    @isTest
    public static void testUpdateRecords() {
        Test.startTest();
        Subjectivity__c subJ = [SELECT id,Name FROM Subjectivity__c LIMIT 1];
        String jsonStringRecord = '[{"Id":"'+subJ.Id+'","subjectivity":"Testing Sub","subjectivityStatus":"Open","subjectivityType":"MPL", "cleared":true}]';
        Boolean result = subjectivityController.updateRecords(jsonStringRecord);
        Test.stopTest();
        System.assert(jsonStringRecord != null);
    }
    
    @isTest
    public static void testGetProductName() {
        Quote qt = [SELECT id,Name FROM Quote LIMIT 1];
        Test.startTest();
        String result = subjectivityController.getProductName(qt.Id);
        Test.stopTest();
        System.assertEquals('Test Product',result);
    }
    
    @isTest
    public static void testGetSubjectivityTemplateList() {
        Quote qt = [SELECT id,Name FROM Quote LIMIT 1];
        Test.startTest();
        List<Subjectivity_Template__c> result = subjectivityController.getSubjectivityTemplateList(qt.Id);
        Test.stopTest();
        System.assert(result!= null);
       
        }

        @isTest
        public static void testGetSubjectivityTemplateListExcess() {
            Quote qt = [SELECT id,Name FROM Quote where name like '%Excess%' LIMIT 1];
            Test.startTest();
            List<Subjectivity_Template__c> result = subjectivityController.getSubjectivityTemplateList(qt.Id);
            Test.stopTest();
            System.assert(result!= null);
           
        }
    
    @isTest
    public static void testGetProfessionName() {
        Quote qt = [SELECT id,Name FROM Quote LIMIT 1];
        Test.startTest();
        String result = subjectivityController.getProfessionName(qt.Id);
        Test.stopTest();
        System.assert(qt != null );
        }
       
    @isTest
    public static void testCheckIsExcess() {
        Quote qt = [SELECT id,Name FROM Quote LIMIT 1];
        Test.startTest();
        String result = subjectivityController.checkIsExcess(qt.Id);
        Test.stopTest();
        System.assertEquals('Primary',result);
        }
    
    @isTest
    public static void testCreateSubjectivitiesBySubjTemplate() {
        Quote qt = [SELECT id,Name FROM Quote LIMIT 1];
        Subjectivity_Template__c subjectivityTemplate =  [SELECT id,Name FROM Subjectivity_Template__c LIMIT 1];
        Test.startTest();
        String result = subjectivityController.createSubjectivitiesBySubjTemplate(qt.Id, new List<string> {subjectivityTemplate.Id});
        Test.stopTest();
        System.assert(result!= null);
        }
}