main/default/objects/Subjectivity__c/Subjectivity__c.object-meta.xml
<CustomObject>
    <label>Subjectivity</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subjectivity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subjectivity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Subjectivity__c/fields/Cleared__c.field-meta.xml
<CustomField>
    <fullName>Cleared__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cleared</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Subjectivity</relationshipLabel>
    <relationshipName>Subjectivity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity__c</fullName>
    <label>Subjectivity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/classes/SubjectivityQueryUtil.cls
/**************************************************************************************************
 * Class Name: SubjectivityQueryUtil
 * Author: Jai
 * Date: Dec 16, 2021
 * Description: Class to keep Subjectivity queries
 * Test Class :  SubjectivityQueryUtilTest
 **************************************************************************************************/
public with sharing class SubjectivityQueryUtil {
    
    
    /*************************************************
    * Method Name: fetchSubjectivitiesForSubjectivityIds
    * Author: Jai
    * Date: 9 Dec 2021
    * Params: Set<id>
    * Return: list of Sujectivity
    * Exceptions:
    * Revision: 
    * Description: Fetch all Subjectivities for Ids
     *************************************************/
    public static List<Subjectivity__c> fetchSubjectivitiesForSubjectivityIds(Set<id> subjIds, String fields){
        String query = 'Select '+fields+ ' From Subjectivity__c where Id IN :subjIds';
        return (list<Subjectivity__c>)database.query(query);
    }

    /*************************************************
    * Method Name: fetchSubjectivitiesForQuote
    * Author: 
    * Date: 6th Jan 2022
    * Params: String quoteId
    * Return: list of subjectivities
    * Exceptions:
    * Revision: 
    * Description: Fetch all Subjectivities for quote
     *************************************************/
    public static List<Subjectivity__c> fetchSubjectivitiesForQuote(String quoteId){
        return  [select Id, Cleared__c from Subjectivity__c where Quote__c =:quoteId];
    }

}