main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>D_O</fullName>
                <label>D&amp;O</label>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/QuoteInitFormCmpController.cls
public with sharing class QuoteInitFormCmpController {
    @AuraEnabled 
    public static Opportunity getOpportunityInfo(String id) {
        return [SELECT Id, Name, AccountId, Product_Name__c, StageName,
                    Effective_Date__c, Expiration_Date__c, CloseDate, Policy__c //29-May-20 Hoang added Policy__c for #19275
				FROM Opportunity 
                WHERE Id =: id LIMIT 1];
    }	

    @AuraEnabled
    public static ResultResponse initialize(String id) {
        ResultResponse result = new ResultResponse();
        try {
            Opportunity obj = getOpportunityInfo(id);
            if (obj.StageName != 'Qualified' 
                && obj.StageName != 'Closed Won') {//29-May-20 Hoang added for #19275
                result.errors.add('Opportunity must be qualified before creating new quote.');
                result.isSuccess = false;

                return result;
            }
            /* Hoang comment to waiting confirm 
            if (obj.StageName == 'Closed Won') {
                List<Quote> quotes = [Select Id 
                                        From Quote 
                                        Where Quote_Type__c = 'Amendment' 
                                            And Status = 'In Progress'
                                            And OpportunityId =:id];
                if (!quotes.isEmpty()){
                    result.errors.add('Amendment Quote is already created.');
                    result.isSuccess = false;
                    return result; 
                }
            }*/

            result.isSuccess = true;
        } catch (Exception ex) {
            result.errors.add('Failed to init New Quote form.');
            result.isSuccess = false;
        }
        return result;
    }
}