main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/classes/PolicyQueryUtilTest.cls
/**************************************************************************************************
* Class Name: PolicyQueryUtilTest
* Author: RINKU SAINI
* Date: Jan 10, 2022
* Description: 
**************************************************************************************************/
@isTest
public class PolicyQueryUtilTest {
    
    public static testmethod void coverPolicyQueryUtil(){
        Test.startTest();
        
        Account accPersonal = new Account();
        accPersonal.Name = 'Test account 1';
        accPersonal.BillingStreet = '01 Tran Duy Hung';
        accPersonal.BillingCity = 'Westminster';
        accPersonal.BillingState = 'California';
        accPersonal.BillingPostalCode = '90000';
        accPersonal.BillingCountry = 'United States';
        accPersonal.IsMailingSameWithBillingAddress__c = true;
        accPersonal.Date_Started__c = Date.today().addYears(-2);
        insert accPersonal;
        
        
        // create policy  
        Policy__c policy = new Policy__c();
        policy.Account__c = accPersonal.Id; 
        policy.Expiration_Date__c = Date.today().addDays(100);           
        insert policy;
        PolicyQueryUtil.fetchPolicyById(policy.Id);
        
        Test.stopTest();
    }
}