main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Bound Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Total_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_Premium__c</fullName>
    <label>Total Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/QuoteEndorsementChangeSummary__c/QuoteEndorsementChangeSummary__c.object-meta.xml
<CustomObject>
    <label>Quote Endorsement Change Summary</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QuoteEndorsementChangeSummaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/QuoteEndorsementChangeSummary__c/fields/CoverageName__c.field-meta.xml
<CustomField>
    <fullName>CoverageName__c</fullName>
    <label>CoverageName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/QuoteEndorsementChangeSummary__c/fields/Deleted_Record_Summary__c.field-meta.xml
<CustomField>
    <fullName>Deleted_Record_Summary__c</fullName>
    <label>Deleted Record Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/QuoteEndorsementChangeSummary__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>FieldName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/QuoteEndorsementChangeSummary__c/fields/Limit_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Limit_Deductible__c</fullName>
    <label>LIMIT/DEDUCTIBLE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/QuoteEndorsementChangeSummary__c/fields/New_Record_Summary__c.field-meta.xml
<CustomField>
    <fullName>New_Record_Summary__c</fullName>
    <label>New Record Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/QuoteEndorsementChangeSummary__c/fields/NewValue__c.field-meta.xml
<CustomField>
    <fullName>NewValue__c</fullName>
    <label>NewValue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/QuoteEndorsementChangeSummary__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>ObjectName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/QuoteEndorsementChangeSummary__c/fields/OldValue__c.field-meta.xml
<CustomField>
    <fullName>OldValue__c</fullName>
    <label>OldValue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/QuoteEndorsementChangeSummary__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Add</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/QuoteEndorsementChangeSummary__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QuoteId</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>QuoteEndorsementChangeSummaries (QuoteId)</relationshipLabel>
    <relationshipName>QuoteEndorsementChangeSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/QuoteEndorsementChangeSummary__c/fields/SubCoverageName__c.field-meta.xml
<CustomField>
    <fullName>SubCoverageName__c</fullName>
    <label>SubCoverageName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/QuoteEndorsementChangeSummary__c/fields/Update_Record_Summary__c.field-meta.xml
<CustomField>
    <fullName>Update_Record_Summary__c</fullName>
    <label>Update Record Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/classes/QuoteEndorsementChangeSummaryUtil.cls
/*************************************************
* Class Name: QuoteEndorsementChangeSummaryUtil 
* Author: Giang Phan
* Date: 09/June/2020
* Revison : QuoteEndorsementChangeSummary Util
*************************************************/
public with sharing class QuoteEndorsementChangeSummaryUtil {
    
    public static Map<String,List<QuoteEndorsementChangeSummaryInfo>> getQuoteEndorsementChangeSummary(
                                                                                    List<String> quoteIds) {
        List<Quote> result = getQuoteWithQuoteEndorChangeSummaryList(quoteIds);
		System.debug(' # # # ' + result);
        if(!result.isEmpty()) {
            return getMapQECSFilterSection(result[0].QuoteEndorsementChangeSummaries__r);
        }
        return null;
    }

    public static List<Quote> getQuoteWithQuoteEndorChangeSummaryList(List<String> quoteIds) {

        List<Quote> result = [SELECT Id,Policy__r.Policy_Number__c,Policy__r.Azure_ID__c,Policy__r.Policy_Status__c,
                                            Status,Policy__c,Policy__r.Expiration_Date__c,//Document_ID__c,
                                            Policy__r.Effective_Date__c,Policy__r.Total_Premium__c,
                                            OpportunityId,Opportunity.AccountId,Opportunity.Account.Name,
                                            Opportunity.Account.Azure_ID__c,Opportunity.Product__c,
                                            Opportunity.Product__r.Name,Opportunity.Product__r.Azure_ID__c,
                                            Quote_Type__c,Total_Premium__c,
                                            (SELECT Id,QuoteId__c,CoverageName__c,Deleted_Record_Summary__c,
                                                    FieldName__c,Name,New_Record_Summary__c,NewValue__c,
                                                    ObjectName__c,OldValue__c,Operation__c,SubCoverageName__c,
                                                    Update_Record_Summary__c,Limit_Deductible__c
                                            FROM QuoteEndorsementChangeSummaries__r)
                                    FROM Quote WHERE Id IN :quoteIds];
        return result;

    }


    public static Map<String,List<QuoteEndorsementChangeSummaryInfo>> 
                                    getMapQECSFilterSection(List<QuoteEndorsementChangeSummary__c> returnedList) {
        
        Map<String,List<QuoteEndorsementChangeSummaryInfo>> mapQuoteEndorsementChangeSummary = 
                                                        new Map<String,List<QuoteEndorsementChangeSummaryInfo>>();
        
        QuoteEndorsementChangeSummaryInfo quoteEndorsementChangeSummaryDetailsInfo = null;
        for(QuoteEndorsementChangeSummary__c obj : returnedList) {
            if(String.isBlank(obj.ObjectName__c)) continue;

            String sectionName = obj.ObjectName__c;
            quoteEndorsementChangeSummaryDetailsInfo = createQuoteEndorsementChangeSummaryInfo(obj);
            if(mapQuoteEndorsementChangeSummary.get(sectionName) != null) {
                mapQuoteEndorsementChangeSummary.get(sectionName).add(quoteEndorsementChangeSummaryDetailsInfo);
            } else {

                List<QuoteEndorsementChangeSummaryInfo> newListTemp = 
                                            new List<QuoteEndorsementChangeSummaryInfo>();
                newListTemp.add(quoteEndorsementChangeSummaryDetailsInfo);
                mapQuoteEndorsementChangeSummary.put(sectionName, newListTemp);
            }
        }
        return mapQuoteEndorsementChangeSummary;
    }


    public static QuoteEndorsementChangeSummaryInfo createQuoteEndorsementChangeSummaryInfo(QuoteEndorsementChangeSummary__c obj) {
        
        QuoteEndorsementChangeSummaryInfo returnedObj = new QuoteEndorsementChangeSummaryInfo();
        returnedObj.coverageName = obj.CoverageName__c;
        returnedObj.deletedRecordSummary = obj.Deleted_Record_Summary__c;
        returnedObj.fieldName = obj.FieldName__c;
        returnedObj.newRecordSummary = obj.New_Record_Summary__c;
        returnedObj.newValue = obj.NewValue__c;
        returnedObj.objectName = obj.ObjectName__c;
        returnedObj.oldValue = obj.OldValue__c;
        returnedObj.operation = obj.Operation__c;
        returnedObj.subCoverageName = obj.SubCoverageName__c;
        returnedObj.updateRecordSummary = obj.Update_Record_Summary__c;
        returnedObj.limitDeductibleName = obj.Limit_Deductible__c;
        return returnedObj;

    }

    public class QuoteEndorsementChangeSummaryInfo {

        public String coverageName          {get; set;}
        public String deletedRecordSummary  {get; set;}
        public String fieldName             {get; set;}
        //public String name                  {get; set;}
        public String newRecordSummary      {get; set;}
        public String newValue              {get; set;}
        public String objectName            {get; set;}
        public String oldValue              {get; set;}
        public String operation             {get; set;}
        public String subCoverageName       {get; set;}
        public String limitDeductibleName   {get; set;}
        public String updateRecordSummary   {get; set;}

        
    }   
}