main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Initial_Premium__c.field-meta.xml
<CustomField>
    <fullName>Initial_Premium__c</fullName>
    <label>Initial Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Policy__c/fields/Total_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_Premium__c</fullName>
    <label>Total Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/classes/CommonPolicyUtil.cls
/**************************************************************************************************
 * Class Name: CommonPolicyUtil
 * Author: 
 * Date: 
 * Description: Class to keep Policy related  common methods
 **************************************************************************************************/
public class CommonPolicyUtil {

    /*************************************************
    * Method Name: setInitialPremiumValue
    * Author:
    * Date: 
    * Params: list<Policy__c>
    * Return: 
    * Exceptions:
    * Description: To set initial premium value
    * Revision: 
     *************************************************/
    //can be machived with flow
    public static void setInitialPremiumValue(List<Policy__c> newDataList) {
		for(Policy__c policy : newDataList) {
			if(policy.Total_Premium__c != null && policy.Initial_Premium__c == null) {
				policy.Initial_Premium__c = policy.Total_Premium__c;
			}
		}
	}

}