main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Initial_Premium__c.field-meta.xml
<CustomField>
    <fullName>Initial_Premium__c</fullName>
    <label>Initial Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Policy__c/fields/Layer__c.field-meta.xml
<CustomField>
    <fullName>Layer__c</fullName>
    <label>Layer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Parent_Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Parent_Policy_Number__c</fullName>
    <description>Will be used to store Parent policy no from where it is cloned from in case of Renewal</description>
    <label>Parent Policy Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>D_O</fullName>
                <label>D&amp;O</label>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Total_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_Premium__c</fullName>
    <label>Total Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Policy_Incremental_Setting__c/Policy_Incremental_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Policy Incremental Setting</label>
</CustomObject>

main/default/objects/Policy_Incremental_Setting__c/fields/End_Number__c.field-meta.xml
<CustomField>
    <fullName>End_Number__c</fullName>
    <label>End Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

main/default/objects/Policy_Incremental_Setting__c/fields/Policy_Format__c.field-meta.xml
<CustomField>
    <fullName>Policy_Format__c</fullName>
    <label>Policy Format</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

main/default/objects/Policy_Incremental_Setting__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Policy_Incremental_Setting__c/fields/Spacing__c.field-meta.xml
<CustomField>
    <fullName>Spacing__c</fullName>
    <label>Spacing</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

main/default/objects/Policy_Incremental_Setting__c/fields/Start_Number__c.field-meta.xml
<CustomField>
    <fullName>Start_Number__c</fullName>
    <label>Start Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

main/default/classes/PolicyTriggerHandler.cls
public with sharing class PolicyTriggerHandler extends TriggerHandler{
	private List<Policy__c> oldDataList;
	private List<Policy__c> newDataList;
	private Map<Id, Policy__c> newDataMap;
	private Map<Id, Policy__c> oldDataMap;
	
    public PolicyTriggerHandler (){  
		this.oldDataList = (List<Policy__c>) Trigger.old;
		this.newDataList = (List<Policy__c>) Trigger.new;
		this.newDataMap = (Map<Id, Policy__c>) Trigger.newMap;
		this.oldDataMap = (Map<Id, Policy__c>) Trigger.oldMap;
    }

	public override void beforeInsert()	{
		system.debug('beforeInsert');
		//CommonUtil.generateExternalID('Azure_ID__c', newDataList);
		setInitialPremiumValue(newDataList);
		//populatePolicyNumber(newDataList);
	}

    public override void beforeUpdate(){
		system.debug('brfore update');
		//CommonUtil.generateExternalID('Azure_ID__c', newDataList);
		setInitialPremiumValue(newDataList);
    }

	public override void afterInsert(){}

	public override void afterUpdate(){
         callSyncQuoteBatch(this.newDataList);
    }
    
    /*public static void populatePolicyNumber(List<Policy__c> newPolicies) {
        system.debug('newPolicies' +newPolicies);
	    Map<String,Policy_Incremental_Setting__c> mapProductNamePolicySetting = new Map<String,Policy_Incremental_Setting__c>();
	    Map<String,Policy_Incremental_Setting__c> mapProductNameHasCustomFieldSetting = new Map<String,Policy_Incremental_Setting__c>();
      //  List<Quote> ExcessQuote = [Select Id, Layer__c FROM Quote Where Id =: newPolicies.Quotes__r[0]];
        Set<String> policyNumbers = new Set<String>(); 
        for(Policy__c policy : [Select Policy_Number__c, Id From Policy__c ]){
			policyNumbers.add(policy.Policy_Number__c);
        }
        
		for(Policy_Incremental_Setting__c obj : [SELECT Id,Product_Name__c,Policy_Format__c,
												Start_Number__c,End_Number__c,Active__c,Suffix__c, Spacing__c
												FROM Policy_Incremental_Setting__c WHERE Product_Name__c != 'Excess']) 
		{
            System.debug('obj.Product_Name__c '+obj.Product_Name__c);
			if(!obj.Product_Name__c.contains(':')) mapProductNamePolicySetting.put(obj.Product_Name__c, obj);
			else mapProductNameHasCustomFieldSetting.put(obj.Product_Name__c,obj);
	    }
	 
	    List<Policy_Incremental_Setting__c> updateList = new List<Policy_Incremental_Setting__c>();
	    for (Policy__c newPolicy : newPolicies) {
			 // Generate policy number base on product name for current Contract
	    	if(mapProductNamePolicySetting.containsKey(newPolicy.Product_Name__c)) {
	    		Policy_Incremental_Setting__c policySetting = mapProductNamePolicySetting.get(newPolicy.Product_Name__c);
	    		if(String.isBlank(newPolicy.Policy_Number__c)){
	    			//Long Ly - Task 05/31/2019 - Check number outside the range of the Start Number and End Number.
	    			if(String.isNotBlank(policySetting.End_Number__c)) {
	    				if((Integer.valueOf(policySetting.Start_Number__c) > Integer.valueOf(policySetting.End_Number__c))) {
	    					newPolicy.addError('Policy Number Range has exceeded. Please increase the End Number'); 
	    					continue;  
	    				}
	    			}
	    			//End
					updatePolicyFieldAndSetting(updateList, policySetting, newPolicy, 'Policy_Number__c', policyNumbers);

				}else{ //Binh Dang: 14 Oct 2019 - 6775: Update Policy Number for Renewal Case
					String oldPolicyNoPattern = newPolicy.Policy_Number__c.substringBefore('__');
					String suffix = String.isBlank(policySetting.Suffix__c) ? '' : policySetting.Suffix__c; 
					String spacing =  String.isBlank(policySetting.Spacing__c) ? '' : policySetting.Spacing__c; 
					String oldSuffix = oldPolicyNoPattern.right(suffix.length());
					String oldStart = oldPolicyNoPattern.left(oldPolicyNoPattern.length()-suffix.length());

					if(oldSuffix.isNumeric()){
						String inputStr = String.valueOf(Decimal.valueOf(oldSuffix) + 1);
						oldSuffix = inputStr.leftPad(suffix.length(), '0');
					}else {
						String inputStr = String.valueOf(returnNumberStringFromString(oldSuffix, true));
						oldSuffix = oldSuffix.replace(String.valueOf(returnNumberStringFromString(oldSuffix,false)), inputStr);
					}
					
					if(String.isNotBlank(spacing) && oldStart.contains(spacing)){//already added spacing
						spacing = '';
					} 
                    
                    // Added by Maeran Shaikh on 10/6/2021 for US: 47350
                    newPolicy.Parent_Policy_Number__c = oldStart + spacing + String.valueOf(Decimal.valueOf(oldSuffix) - 1).leftPad(suffix.length(), '0');
                    //newPolicy.Parent_Policy_Number__c = String.isNotBlank(newPolicy.Policy_Number__c)?newPolicy.Policy_Number__c:'';
                    
                    
					newPolicy.Policy_Number__c = oldStart + spacing + oldSuffix;
                    System.debug('newPolicy.Policy_Number__c'+newPolicy.Policy_Number__c);
				}
	    	}
			//5 Sept 2019: Update the incremental other custom fields on current Contract
			for(String key : mapProductNameHasCustomFieldSetting.keySet()){
				List<String> customList = key.split(':');
				if(customList[0] == newPolicy.Product_Name__c) 
				{
	    			Policy_Incremental_Setting__c policySetting2 = mapProductNameHasCustomFieldSetting.get(key);
	    			if(String.isNotBlank(policySetting2.End_Number__c)) {
	    				if((Integer.valueOf(policySetting2.Start_Number__c) > Integer.valueOf(policySetting2.End_Number__c))) {
	    					newPolicy.addError( customList[1] + ' Range has exceeded. Please increase the End Number'); 
	    					continue;  
	    				}
	    			}    
					updatePolicyFieldAndSetting(updateList, policySetting2, newPolicy, customList[1], null);
	    		}
			}
		}		
		if(!updateList.isEmpty()) update updateList; // Update latest sequence number back to custom setting
        System.debug('newPolicies'+newPolicies);
	}
    */
   /* public static void updatePolicyFieldAndSetting(List<Policy_Incremental_Setting__c> updateList, 
													Policy_Incremental_Setting__c policySetting, 
													Policy__c newPolicy, String fieldName, Set<String> policyNumbers)
	{
        String suffix;
        String spacing;
        String value;
        if(newPolicy.Product_Name__c == 'Cyber Standalone' || newPolicy.Product_Name__c == 'MPL Standalone'){
            if(newPolicy.Layer__c == 'Excess'){
                policySetting = [SELECT Id,Product_Name__c,Policy_Format__c,
												Start_Number__c,End_Number__c,Active__c,Suffix__c, Spacing__c
												FROM Policy_Incremental_Setting__c WHERE Product_Name__c = 'Excess'];
            }
		//Integer start = Integer.valueOf(policySetting.Start_Number__c);
		 suffix = String.isBlank(policySetting.Suffix__c) ? '' : policySetting.Suffix__c;
		 spacing =  String.isBlank(policySetting.Spacing__c) ? '' : policySetting.Spacing__c;
		 value= ((String.format(policySetting.Policy_Format__c, 
											  new List<String>{returnNumberStringFromString(policySetting.Start_Number__c,false)})) + spacing + suffix);
		system.debug('value -- '+value);
         	    //start++;
	    policySetting.Start_Number__c = returnNumberStringFromString(policySetting.Start_Number__c,true);
	    updateList.add(policySetting);
        }*/
        
        /*if(newPolicy.Layer__c == 'Excess')
        {
            system.debug('newPolicy.Product_Name__c -'+newPolicy.Product_Name__c);
                if(newPolicy.Product_Name__c == 'Cyber Standalone' || newPolicy.Product_Name__c == 'MPL Standalone') 
                {
                  Policy_Incremental_Setting__c ExcessPolNumber = [SELECT Id,Product_Name__c,Policy_Format__c,
												Start_Number__c,End_Number__c,Active__c,Suffix__c, Spacing__c
												FROM Policy_Incremental_Setting__c WHERE Product_Name__c = 'Excess'];
                 
                   system.debug('ExcessPolNumber -'+ExcessPolNumber);
                        
                    suffix = String.isBlank(ExcessPolNumber.Suffix__c) ? '' : ExcessPolNumber.Suffix__c;
                    spacing =  String.isBlank(ExcessPolNumber.Spacing__c) ? '' : ExcessPolNumber.Spacing__c;
                    value= ((String.format(ExcessPolNumber.Policy_Format__c, 
                                           new List<String>{returnNumberStringFromString(ExcessPolNumber.Start_Number__c,false)})) + spacing + suffix);
                    system.debug('Excess value -- '+value);
                    ExcessPolNumber.Start_Number__c = returnNumberStringFromString(ExcessPolNumber.Start_Number__c,true);
                    
                    updateList.add(ExcessPolNumber);
                         
                        }
        	
        }*/
      /*  newPolicy.put(fieldName,value);

	}*/

    /*
	public static String returnNumberStringFromString(String num, Boolean increase) {
	  String n = '';
	  Integer lenght =0;
	  for (Integer i=0; i<num.length(); i++) {
		  if (num.substring(i, i+1).isNumeric()){
				  n += num.substring(i, i+1);
				  lenght +=1;
		  }
	  }
		
	  Integer newValue = increase ? Integer.valueOf(n)+1 : Integer.valueOf(n);
	  String newString = String.valueOf(newValue);
	  return newString.leftPad(lenght, '0');
  }
*/
  private void setInitialPremiumValue(List<Policy__c> newDataList) {
	for(Policy__c policy : newDataList) {
		if(policy.Total_Premium__c != null && policy.Initial_Premium__c == null) {
			policy.Initial_Premium__c = policy.Total_Premium__c;
		}
	}
  }
    public static void callSyncQuoteBatch(List<Policy__c> newDataList){
       
        List<Quote> quotes  = new List<Quote>();
        
        for(Quote q : [select Id from Quote
                      WHERE (Product_Name__c = 'MPL Standalone' OR Product_Name__c = 'Cyber Standalone') and (Policy__c IN :newDataList)
                       ]){
                           quotes.add(q);
                       }

        System.enqueueJob(new SyncQuoteQueueable(quotes));
    }   
}