main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Layer__c.field-meta.xml
<CustomField>
    <fullName>Layer__c</fullName>
    <label>Layer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Bound Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/recordNavigationCmpCtrlTest.cls
@isTest
public class recordNavigationCmpCtrlTest {

    @testSetup
    static void testSetup(){
        
        TriggerSettings__c triggerSettingsObj = new TriggerSettings__c();
        triggerSettingsObj.BypassQuoteTrigger__c = true;
        insert triggerSettingsObj;
        
        Account accountObj = TestUtil.createBusinessAccount('Test Bussiness Account', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        insert accountObj;
        
        Product2 productObj = TestUtil.createProduct('D&O Standalone');
        insert productObj; 
        
        Opportunity opportunityObj = TestUtil.createOpportunity('Test Opportunity',accountObj.Id, productObj.Id);
        opportunityObj.CloseDate = Date.today();
        opportunityObj.StageName = 'Closed Won';
        opportunityObj.Expiration_Date__c = Date.today()+60;
        insert opportunityObj;
        
        Policy__c policyObj = new Policy__c();
        policyObj.Policy_Number__c = '12345';
        policyObj.Effective_Date__c = Date.today()+5;
        policyObj.Expiration_Date__c = Date.today() + 30;
        policyObj.Policy_Status__c = 'Bound';
        insert policyObj;
        
        Quote quoteObj = TestUtil.createQuote('TestQuote', opportunityObj.Id);
        quoteObj.Status = 'In Progress';
        quoteObj.Coverage_Product_Options__c = 'D&O';
        quoteObj.Refer_Type__c = 'Underwriting Referral';
        quoteObj.Rating_Status__c = 'Refer';
        quoteObj.Last_Quote_Version__c = 'Version 1';
        quoteObj.Policy__c = policyObj.id;
        quoteObj.CloseDate__c = Date.today() + 120;
        insert quoteObj;  
        
    }
    
    @isTest
    static void runTest(){
        
        Test.startTest();
        Quote quoteObj = [Select Id, OpportunityId, layer__c from Quote where Name = 'TestQuote'];
        recordNavigationCmpCtrl.fetchDetails(quoteObj.Id);
        Test.stopTest();
    }
}