main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Bound Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Total_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_Premium__c</fullName>
    <label>Total Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/classes/EndorsementProcessLwcControllerTest.cls
@isTest
public class EndorsementProcessLwcControllerTest {
	@testSetup
    private static void setup() {
        Policy__c policy = new Policy__c();
        policy.Policy_Status__c = 'Active';
        policy.Policy_Number__c = 'POLTEST';
        policy.Effective_Date__c = Date.today().addMonths(2);
        policy.Expiration_Date__c = Date.today().addMonths(1);
        policy.Total_Premium__c = 2000;
        insert policy;
    }
    
    @isTest
    public static void testGetPolicyList() {
        List<EndorsementProcessLwcController.ItemWrapper> result = EndorsementProcessLwcController.getPolicyList('POL');
        System.assertEquals(2000, result[0].Total_Premium);
        
    }
}