main/default/objects/Account_Location__c/Account_Location__c.object-meta.xml
<CustomObject>
    <label>Account Location</label>
    <nameField>
        <displayFormat>AL-{00000000}</displayFormat>
        <label>Account Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Account_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Account_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Account Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <displayFormat>Location-{00000}</displayFormat>
        <label>Location  Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/classes/AccountLocationQueryUtil.cls
/**************************************************************************************************
 * Class Name: AccountLocationQueryUtil
 * Author: Vinay Vernekar
 * Date: 5th Dec 2021
 * Description: Query util class for account location
 **************************************************************************************************/
public with sharing class AccountLocationQueryUtil {
    /*************************************************
    * Method Name: fetchAccountLocations
    * Author: Vinay Vernekar
    * Date: 29th Nov 2021
    * Params: Set<Id> accountIds
    * Return: 
    * Exceptions:
    * Revision: 
    * Description: Fetch account locations by account ids
     *************************************************/
    public static List<Account_Location__c> fetchAccountLocations(Set<Id> accountIds){
        return [Select Id, Account__c, Location__c From Account_Location__c Where Account__c In: accountIds];
    }
}