main/default/objects/Quote_Premium__c/Quote_Premium__c.object-meta.xml
<CustomObject>
    <label>Quote Premium</label>
    <nameField>
        <displayFormat>QP-{00000000}</displayFormat>
        <label>Quote Premium Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Premiums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Quote_Premium__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Quote_Premium__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Premiums</relationshipLabel>
    <relationshipName>Quote_Premiums</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Quote_Premium__c/fields/Quote_Premium__c.field-meta.xml
<CustomField>
    <fullName>Quote_Premium__c</fullName>
    <label>Quote Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/classes/QuotePremiumQueryUtil.cls
/**************************************************************************************************
 * Class Name: QuotePremiumQueryUtil
 * Author: Vinay
 * Date: Dec 22, 2021
 * Description: Class to keep quote premium queries
 * Test Class :  QuotePremiumQueryUtilTest
 **************************************************************************************************/
public with sharing class QuotePremiumQueryUtil {
    /*************************************************
    * Method Name: fetchQuotePremiumsByProductNamesAndQuotes
    * Author: 
    * Date: 
    * Params: list of product names and quote ids
    * Return: 
    * Exceptions:
    * Description: list of quote premiums
    * Revision: 
     *************************************************/
    public static list<Quote_Premium__c> fetchQuotePremiumsByProductNamesAndQuotes(List<String> prodNames, Set<Id> quoteIds){
        return [Select Id from Quote_Premium__c where Product_Name__c in :prodNames and Quote__c in: quoteIds]; 
    }
}