main/default/objects/API_Configuration__mdt/fields/HeaderParams__c.field-meta.xml
<CustomField>
    <fullName>HeaderParams__c</fullName>
    <label>Header Params</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Opportunity/fields/LastSource__c.field-meta.xml
<CustomField>
    <fullName>LastSource__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>LastSource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/classes/SyncServiceHandler_CEL.cls
public class SyncServiceHandler_CEL {
    
     // ************For Celerity ********** //
    public static void SyncServiceCall_Cel(List<Quote> listQuote){
         API_Configuration__mdt apiSetting = CommonUtil.getAPIconfiguration('Quote_Sync');

        if(apiSetting == null) return;
        
        try{   
            for(Quote quote : listQuote){
                system.debug('QQQ-->'+quote);
                if(quote.Opportunity.LastSource__c != GlobalVariables.PROD_NAME_FOR_SHOPX &&  quote.Product_Name__c != GlobalVariables.PROD_NAME_FOR_PI){
                HttpRequest req = new HttpRequest();
                HttpResponse res = new HttpResponse();
                req = SyncServiceHandler_Common.getHttpRequest(apiSetting, quote);  
                Http h = new Http();
                res = h.send(req);
                system.debug('res-->'+res);    
                    if(!Test.isRunningTest()){
                      ApiUtil.logAPICall(req,res,'Sync Quote Status','SyncQuoteBatch', apiSetting.HeaderParams__c, 'Outbound');
                    }    
                }  
                
            }
        } 
        catch (Exception ex) {
            System.debug(ex.getMessage());
        }    
    }
     
}