main/default/objects/API_Configuration__mdt/fields/HeaderParams__c.field-meta.xml
<CustomField>
    <fullName>HeaderParams__c</fullName>
    <label>Header Params</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <label>Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Coverage__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <externalId>true</externalId>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Code__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Code__c</fullName>
    <description>User entered code which will be used across systems (radar, middleware etc)</description>
    <externalId>true</externalId>
    <label>Coverage Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coverage</fullName>
                <default>true</default>
                <label>Coverage</label>
            </value>
            <value>
                <fullName>Endorsement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/CoveragesLineItem__c/CoveragesLineItem__c.object-meta.xml
<CustomObject>
    <label>Coverages Line Item</label>
    <nameField>
        <displayFormat>CLI-{00000000}</displayFormat>
        <label>CLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverages Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CoveragesLineItem__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Coverage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Main Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coverage__c</referenceTo>
    <relationshipLabel>Coverages Line Items (Coverage)</relationshipLabel>
    <relationshipName>CoverageQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Code__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Code__c</fullName>
    <formula>Coverage__r.Coverage_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coverage Code</label>
    <type>Text</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Effective_Date__c</fullName>
    <label>Coverage Effective Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Main_Coverage</fullName>
                <label>Main Coverage</label>
            </value>
            <value>
                <fullName>Sub_Coverage</fullName>
                <label>Sub Coverage</label>
            </value>
            <value>
                <fullName>Limit</fullName>
            </value>
            <value>
                <fullName>Deductible</fullName>
            </value>
            <value>
                <fullName>Endorsement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/IsSelected__c.field-meta.xml
<CustomField>
    <fullName>IsSelected__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>The value used by the CLI of type Endorsement when added in the Quote</inlineHelpText>
    <label>IsSelected</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Coverages Line Items</relationshipLabel>
    <relationshipName>Coverages_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/recordTypes/Celerity.recordType-meta.xml
<RecordType>
    <fullName>Celerity</fullName>
    <active>true</active>
    <label>Celerity</label>
</RecordType>

main/default/objects/Master_Binder__c/Master_Binder__c.object-meta.xml
<CustomObject>
    <label>Master Binder</label>
    <nameField>
        <label>Master Binder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Binders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Master_Binder__c/fields/Layer__c.field-meta.xml
<CustomField>
    <fullName>Layer__c</fullName>
    <label>Layer</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Layer__c.field-meta.xml
<CustomField>
    <fullName>Layer__c</fullName>
    <label>Layer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Master_Binder__c.field-meta.xml
<CustomField>
    <fullName>Master_Binder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Binder</label>
    <referenceTo>Master_Binder__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>D_O</fullName>
                <label>D&amp;O</label>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Total_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_Premium__c</fullName>
    <label>Total Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Policy__c/recordTypes/Celerity.recordType-meta.xml
<RecordType>
    <fullName>Celerity</fullName>
    <active>true</active>
    <label>Celerity</label>
</RecordType>

main/default/classes/UpdateCliSelectedFieldBatch.cls
/**
 * @description       : 
 * @author            : Vinayesh
 * @group             : 
 * @last modified on  : 07-02-2022
 * @last modified by  : Vinayesh
**/
global class UpdateCliSelectedFieldBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    private Quote quoteRec;
    global UpdateCliSelectedFieldBatch() {
    }
    global UpdateCliSelectedFieldBatch(Quote newQuote) {
        quoteRec = newQuote;
    }
    public Database.QueryLocator start(Database.BatchableContext BC) {
        // String query = 'SELECT Id,Master_Binder__c,RetroDate__c,Retroactive_Date__c, Status, Azure_Id__c, Policy__c, AccountId,' +
        // 'Account.Name, QuotePremium__c, Effective_Date__c, ExpirationDate,Endorsement_Reason__c,' +
        // 'Total_Premium__c,Total_Cost_To_Client__c,Policy_Wording_Document__c, OpportunityId, Rating_Status__c, Product_Name__c,'+
        // 'Endorsement_Quote_Bound_Date__c,Quote_Type__c, Layer__c,Endorsement_Effective_Date__c ' +
        // 'FROM Quote Where Product_Name__c = \'Cyber Standalone\' ' +
        // 'And Status != \'Closed\' And Status != \'Rejected\' ' +
        // 'And Status != \'Correction\' And Status != \'Cancelled\' and Azure_Id__c = \'0a735f17-b60e-43f9-a78a-ca233f3ae97e\' order by createddate desc Limit 1'; 

        String query = 'SELECT Id,Master_Binder__c,RetroDate__c,Retroactive_Date__c, Status, Azure_Id__c, Policy__c, AccountId,' +
        'Account.Name, QuotePremium__c, Effective_Date__c, ExpirationDate,Endorsement_Reason__c,' +
        'Total_Premium__c,Total_Cost_To_Client__c,Policy_Wording_Document__c, OpportunityId, Rating_Status__c, Product_Name__c,'+
        'Endorsement_Quote_Bound_Date__c,Quote_Type__c, Layer__c,Endorsement_Effective_Date__c  ' +
        'FROM Quote Where Opportunity.RecordType.Name = \'Celerity\' And (Quote_Type__c = \'Renewal\' Or Quote_Type__c = \'Amendment\')';

        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext info, List<Quote> quoteList) {
        try{
            syncQuote(quoteRec);
        }
        catch(Exception ex){

        }
        quoteRec = null;
        try{
       
        for(Quote qt : quoteList){
            if(qt.Quote_Type__c == 'Amendment' && !qt.Product_Name__c.contains('Private')){

                List<CoveragesLineItem__c> covList = [Select Id, IsSelected__c, Coverage_Effective_Date__c, 
                                                        Coverage__r.Coverage_Type__c, Coverage__r.Id, Quote__c
                                                        From CoveragesLineItem__c where Quote__c =: qt.Id And Coverage__r.Coverage_Code__c in ('CyberDec',
                                            'AcceleratorCyberInsuredPolicy',
                                            'ServiceOfProcess',
                                            'ServiceOfProcessIL',
                                            'ServiceOfProcessPA',
                                            'PolicyTRIADisc',
                                            'CapOnLossesTRIA',
                                            'MPLDec',
                                            'MPLCoverageForm',
                                            'ExcessDec',
                                            'ExcessPolicyForm',
                                            'ExcessSignatureEndorsement',
                                            'ExcessTRIA',
                                            'ExcessSOP',
                                            'ExcessSOPIL',
                                            'ExcessSOPPA',
                                            'ExcessOFACNotice',
                                            'ExcessLossNotice',
                                            'OFAC',
                                            'LossReporting') And LastModifiedBy.Username like '%vinayesh%'];
                
                    List<CoveragesLineItem__c> dateUpdateClis = new List<CoveragesLineItem__c>();
                    for(CoveragesLineItem__c cliItem : covList){
                        cliItem.Coverage_Effective_Date__c = qt.Effective_Date__c;
                        dateUpdateClis.add(cliItem);
                    }
                    if(dateUpdateClis.size() > 0){
                        GlobalStaticVar.byPassCoverageLineItemTrigger = true;
                        GlobalStaticVar.byPassQuoteTrigger = true;
                        update dateUpdateClis;
                        GlobalStaticVar.byPassCoverageLineItemTrigger = false;
                        GlobalStaticVar.byPassQuoteTrigger = false;
                        quoteRec = quoteList[0];      
                    }
            }
                List<CoveragesLineItem__c> existCli = [Select Id, IsSelected__c, Coverage_Effective_Date__c, 
                                                       Coverage__r.Coverage_Type__c, Coverage__r.Id, Quote__c
                                                       From CoveragesLineItem__c
                                                       Where Quote__c = :qt.Id And Quote__r.Quote_Type__c = 'Renewal'];
                
                List<CoveragesLineItem__c> cliToUpdate = new List<CoveragesLineItem__c>();

                for(CoveragesLineItem__c currCLi : existCli){
                    if(currCLi.Coverage__r.Coverage_Type__c == 'Endorsement'){
                        currCLi.Coverage_Effective_Date__c = quoteList[0].Effective_Date__c;
                        cliToUpdate.add(currCLi);
                    }
                }
                //CoverageLineItemTriggerHandler_CEL.filterEndorsement(existCli);
                if(existCli.size() > 0){
                    GlobalStaticVar.byPassCoverageLineItemTrigger = true;
                    GlobalStaticVar.byPassQuoteTrigger = true;
                    update cliToUpdate;
                    GlobalStaticVar.byPassCoverageLineItemTrigger = false;
                    GlobalStaticVar.byPassQuoteTrigger = false;   
                    quoteRec = quoteList[0];
                }                     
        }
      
    }
        catch(Exception ex){
            ErrorLogsUtilityHelper.logError(ex, 'Update Renewal Date Data Fix', ex.getMessage(), quoteList[0].Id, 'Quote', 'Update', 'None');
        }
    }

    public void finish(Database.BatchableContext info) {
        syncQuote(quoteRec);
    }    

    private static void syncQuote(Quote qt){
        API_Configuration__mdt apiSetting = CommonUtil.getAPIconfiguration('Quote_Sync');
        if(qt != null){
            List<Quote> qtToUpdate = [SELECT Id, Status, Name, Rating_Status__c,Accept_Terror_Premium__c,
                                Endorsement_Quote_Bound_Date__c,
                                Quote_Type__c,Non_Prorated_Quote_Premium__c, Parent_Quote__c, Product_Name__c, Opportunity.Id
                                FROM Quote WHERE Id =: qt.Id];
            if(qtToUpdate.size() > 0){
                Quote qt1 = qtToUpdate[0];
                HttpRequest req = new HttpRequest();
                HttpResponse res = new HttpResponse();

                req = SyncQuoteBatch.getHttpRequest(apiSetting, qt1);  
                Http h = new Http();
                if(!Test.isRunningTest())
                    res = h.send(req);

                //ApiUtil.logAPICall(req,res,'Sync Quote Status','SyncQuoteBatch', apiSetting.HeaderParams__c, 'Outbound');
            }
        }
    }
    
}