main/default/objects/Additional_Insured__c/Additional_Insured__c.object-meta.xml
<CustomObject>
    <label>Additional Insured</label>
    <nameField>
        <displayFormat>Additional Insured-{0000}</displayFormat>
        <label>Additional Insured Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Insured</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Additional_Insured__c/fields/Additional_Insured_Account__c.field-meta.xml
<CustomField>
    <fullName>Additional_Insured_Account__c</fullName>
    <label>Additional Insured Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Additional Insured</relationshipLabel>
    <relationshipName>Additional_Insured</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Additional_Insured__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Additional Insured</relationshipLabel>
    <relationshipName>Additional_Insured</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <label>API Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/API_Log__c/fields/Azure_Id__c.field-meta.xml
<CustomField>
    <fullName>Azure_Id__c</fullName>
    <label>Azure Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Broker_Account__c/Broker_Account__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Broker_Account__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Broker_Contact__r.AccountId ,  Broker_Contact__r.Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <label>Broker Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker_Contact</value>
        </filterItems>
        <infoMessage>You Must Select a Broker Contact</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Broker_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Broker Accounts</relationshipLabel>
    <relationshipName>Opportunity_Accounts1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <label>Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Coverage__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <externalId>true</externalId>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Coverage__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Features</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Coverage_Limits_Deductibles__c/Coverage_Limits_Deductibles__c.object-meta.xml
<CustomObject>
    <label>Limits &amp; Deductibles</label>
    <nameField>
        <label>Option</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Limits &amp; Deductibles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Coverage_Limits_Deductibles__c/fields/Limit_Deductible_Type__c.field-meta.xml
<CustomField>
    <fullName>Limit_Deductible_Type__c</fullName>
    <label>Limit Deductible Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
            <value>
                <fullName>Endorsement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Coverage_Limits_Deductibles__c/fields/Parent_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Parent_Coverage__c</fullName>
    <label>Parent Coverage</label>
    <referenceTo>Coverage__c</referenceTo>
    <relationshipLabel>Limits &amp; Deductibles</relationshipLabel>
    <relationshipName>FeaturesProductOptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Coverage_Limits_Deductibles__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/CoveragesLineItem__c.object-meta.xml
<CustomObject>
    <label>Coverages Line Item</label>
    <nameField>
        <displayFormat>CLI-{00000000}</displayFormat>
        <label>CLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverages Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CoveragesLineItem__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Coverage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Main Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coverage__c</referenceTo>
    <relationshipLabel>Coverages Line Items (Coverage)</relationshipLabel>
    <relationshipName>CoverageQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/CoverageLineItemType__c.field-meta.xml
<CustomField>
    <fullName>CoverageLineItemType__c</fullName>
    <formula>IF(AND(ISBLANK(Sub_Coverage__c),ISBLANK(Limits_Deductibles__c)) ,Coverage__r.RecordTypeName__c,
			IF(AND(NOT(ISBLANK(Sub_Coverage__c)),ISBLANK(Limits_Deductibles__c)) ,Sub_Coverage__r.RecordTypeName__c, Limits_Deductibles__r.RecordType.Name ) )</formula>
    <label>CoverageLineItemType</label>
    <type>Text</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Limits_Deductibles__c.field-meta.xml
<CustomField>
    <fullName>Limits_Deductibles__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Limits &amp; Deductibles</label>
    <referenceTo>Coverage_Limits_Deductibles__c</referenceTo>
    <relationshipLabel>Coverages Line Items</relationshipLabel>
    <relationshipName>ProductQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Coverages Line Items</relationshipLabel>
    <relationshipName>Coverages_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/recordTypes/Aqueous.recordType-meta.xml
<RecordType>
    <fullName>Aqueous</fullName>
    <active>true</active>
    <label>Aqueous</label>
</RecordType>

main/default/objects/Quote_Option__c/Quote_Option__c.object-meta.xml
<CustomObject>
    <label>Quote Option</label>
    <nameField>
        <displayFormat>QO-{000000}</displayFormat>
        <label>Quote Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Quote_Option__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <externalId>true</externalId>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Quote_Option__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Options</relationshipLabel>
    <relationshipName>Quote_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Quote_Option__c/fields/Selected__c.field-meta.xml
<CustomField>
    <fullName>Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selected for Quote</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Referral_Reason__c/Referral_Reason__c.object-meta.xml
<CustomObject>
    <label>Referral Reason</label>
    <nameField>
        <label>Reason Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Reasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Referral_Reason__c/fields/Approval_Level_Required__c.field-meta.xml
<CustomField>
    <fullName>Approval_Level_Required__c</fullName>
    <label>Approval Level Required</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Approval_Rejected_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rejected_Date__c</fullName>
    <label>Approval/Rejected Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Approver_Level__c.field-meta.xml
<CustomField>
    <fullName>Approver_Level__c</fullName>
    <label>Approver Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Referral Reasons</relationshipLabel>
    <relationshipName>Referral_Reasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Quote_Option__c.field-meta.xml
<CustomField>
    <fullName>Quote_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Option</label>
    <referenceTo>Quote_Option__c</referenceTo>
    <relationshipLabel>Referral Reasons</relationshipLabel>
    <relationshipName>Referral_Reasons</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <length>512</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Refer</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/FinalizeQuoteControllerTest.cls
@isTest
private class FinalizeQuoteControllerTest {      
    static { 
        // create broker account        
        Id brokerRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account accBroker = TestUtil.createAccount('Account_Business_Test_01', brokerRtId, '5305, Monroe Street', 'Toledo', 'Ohio','43623', 'United States');
        insert accBroker;              	
        
        // create product
        Product2 product = TestUtil.createProduct('Test Product');
        insert product;
        
        // create opportunity        
        Opportunity opp = TestUtil.createOpportunity('Test Opportunity', accBroker.Id, product.Id);
        opp.StageName = 'Qualified';
        insert opp;
        
        TriggerSettings__c setting = new TriggerSettings__c();
        setting.BypassQuoteTrigger__c = true;
        insert setting;
        
        // create Quote
        Quote q = TestUtil.createQuote('Test Quote', opp.Id);
        q.Rating_Status__c = 'Refer';
        q.Status = 'Rated';
        q.Azure_ID__c = 'ABC';
        insert q;
        
        Quote q1 = TestUtil.createQuote('InProgress Quote', opp.Id);
        q1.Rating_Status__c = 'Clear';
        q1.Status = 'In Progress';
        insert q1;
        
        
        
        FinalizeServiceHandler_Common.ReferralReasonWrapper referralreason= new FinalizeServiceHandler_Common.ReferralReasonWrapper();
        referralreason.Name='New referral';
        referralreason.ApprovalLevelRequired='yes';
        referralreason.ApprovalStatus='Approved';
        referralreason.ApprovedBy='Test1';
        referralreason.Reason='test';
        referralreason.ApprovalRejectedDate=date.today()+120;
        referralreason.EntityPath='test';
        referralreason.ReasonType='test';
        referralreason.Status='test';
        referralreason.Id='test123';
        referralreason.ApproverLevel='2';
        
    }  
    @isTest 
    static void testMethod_X1() {   
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        Quote q = [SELECT Id FROM Quote WHERE Name='Test Quote']; 
        Quote_Option__c quoteOpt = new Quote_Option__c();
        quoteOpt.Azure_ID__c = 'Test';
        quoteOpt.Quote__c =  q.Id;
        quoteOpt.Selected__c = true;
        insert quoteOpt;
        Coverage__c cov = TestUtil.createCoverage('Test Coverage','D&O');
        insert cov;
        Coverage_Limits_Deductibles__c lded = new Coverage_Limits_Deductibles__c(Name = 'Test');
        lded.RecordTypeId = Schema.SObjectType.Coverage_Limits_Deductibles__c.getRecordTypeInfosByName().get('Deductible Option').getRecordTypeId(); 
        lded.Parent_Coverage__c = cov.Id;
        lded.Limit_Deductible_Type__c = 'Endorsement';
        insert lded;
        CoveragesLineItem__c cli = new CoveragesLineItem__c();
        cli.Quote__c = q.Id;
        //cli.CoverageLineItemType__c='Limit Option';
        cli.Limits_Deductibles__c = lded.Id;
        cli.Coverage__c = cov.Id;
        insert cli;
        Test.startTest();
        //HttpResponse res = GenericSyncApi.getResponseFromApi('Quote_Sync', 'Sync Quote Status', q, 'functionName');
        FinalizeQuoteController.syncQuoteToMiddleware(q.Id);  
        FinalizeQuoteController.checkSelectedQuoteOption(q.Id);
        FinalizeQuoteController.checkPartFixedEndorsement(q.Id);
        Test.stopTest();
        System.assertNotEquals(q.Id, null);
    }
    static testMethod void testMethod1() {   
        Test.startTest();
        Quote q = [SELECT Id FROM Quote WHERE Name='Test Quote']; 
        q.Rating_Status__c= 'Refer';
        update q;
        ResultResponse res = new ResultResponse(); 
        res = FinalizeQuoteController.finalizeQuote(q.Id);  
        FinalizeQuoteController.getReferralReasons(q.Id);
        
        List<Referral_Reason__c> refreason= new List<Referral_Reason__c>();
        Referral_Reason__c ref1=new Referral_Reason__c();
        ref1.Approval_Level_Required__c='1';
        ref1.Approval_Status__c='Approved';
        ref1.Approval_Rejected_Date__c= date.today()+365;
        ref1.Quote__c=q.id;
        refreason.add(ref1);
        Referral_Reason__c ref2=new Referral_Reason__c();
        ref2.Approval_Level_Required__c='2';
        ref2.Approval_Status__c='Rejected';
        ref2.Approval_Rejected_Date__c= date.today()+365;
        ref2.Quote__c=q.id;
        refreason.add(ref2);
        insert refreason;
        FinalizeServiceHandler_Common.getLowestApprover(refreason);  
        
        Test.stopTest();
        //System.assertNotEquals(res.data, null);
    }
    static testMethod void finaliseTest() { 
        Account acc1 = TestUtil.createBusinessAccount('Bussiness Account Test Aq', 'Business', '123 Main Street', 'Anycity', 'England', '11354', 'United Kingdom');
        
        Id aqueousRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Product2 product = TestUtil.createProduct('Professional Indemnity');
        product.RecordTypeId = aqueousRecordTypeId; 
        product.Innovisk_Entity_ID__c = 'Aqueous';
        insert product; 
        
        Opportunity opp = TestUtil.createOpportunity('Test opp', acc1.Id, product.Id);
        opp.Innovisk_Entity_ID__c = 'Aqueous';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();                            
        opp.Product__c = product.Id;
        opp.Coverage_Product_Options__c = 'Professional Indemnity';
        insert opp;
        
        Quote quot = TestUtil.createQuote('New Quote Test 2',opp.Id);
        quot.OpportunityId = opp.Id;
        quot.Rating_Status__c = 'Refer';
        quot.Status = 'Rated';
        quot.Coverage_Product_Options__c = 'Professional Indemnity';
        insert quot; 
        quot.Rating_Status__c='clear';
        update quot;
        Quote_Option__c quoteOption = new  Quote_Option__c();
        quoteOption.Quote__c=quot.Id;
        quoteOption.Selected__c=true;
        insert quoteOption;
        
        List<Referral_Reason__c> refreason= new List<Referral_Reason__c>();
        Referral_Reason__c ref1=new Referral_Reason__c();
        ref1.Approver_Level__c='1';
        ref1.Approval_Level_Required__c='1';
        ref1.Approval_Status__c='';
        ref1.Approval_Rejected_Date__c= date.today()+365;
        ref1.Quote_Option__c= quoteOption.Id;
        ref1.Quote__c=quot.id;
        ref1.Reason__c='Test';
        refreason.add(ref1);
        insert refreason;  
        
        Test.startTest();
        FinalizeQuoteController.finalizeQuote(quot.Id);  
        
        ref1.Approval_Level_Required__c='2';
        update ref1;
        FinalizeQuoteController.finalizeQuote(quot.Id);  
        
        ref1.Approval_Level_Required__c='3';
        update ref1;
        
        FinalizeQuoteController.finalizeQuote(quot.Id);  
        FinalizeQuoteController.getReferralReasons(quot.Id);
        FinalizeQuoteController.getReferralReasons('');
        FinalizeServiceHandler_Common.getLowestApprover(refreason);
        Test.stopTest();
        System.assertNotEquals(refreason, null);
    }
    
    static testMethod void finaliseTest2() { 
        Account acc1 = TestUtil.createBusinessAccount('Bussiness Account Test Aq', 'Business', '123 Main Street', 'Anycity', 'England', '11354', 'United Kingdom');
        
        Id aqueousRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Product2 product = TestUtil.createProduct('Professional Indemnity');
        product.RecordTypeId = aqueousRecordTypeId; 
        product.Innovisk_Entity_ID__c = 'Aqueous';
        insert product; 
        
        Opportunity opp = TestUtil.createOpportunity('Test opp', acc1.Id, product.Id);
        opp.Innovisk_Entity_ID__c = 'Aqueous';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();                            
        opp.Product__c = product.Id;
        opp.Coverage_Product_Options__c = 'Professional Indemnity';
        insert opp;
        
        Quote quot = TestUtil.createQuote('New Quote Test 2',opp.Id);
        quot.OpportunityId = opp.Id;
        quot.Rating_Status__c = 'Refer';
        quot.Status = 'Rated';
        quot.Coverage_Product_Options__c = 'Professional Indemnity';
        insert quot; 
        quot.Rating_Status__c='clear';
        update quot;
        Quote_Option__c quoteOption = new  Quote_Option__c();
        quoteOption.Quote__c=quot.Id;
        quoteOption.Selected__c=true;
        insert quoteOption;
        
        List<Referral_Reason__c> refreason= new List<Referral_Reason__c>();
        Referral_Reason__c ref1=new Referral_Reason__c();
        ref1.Approver_Level__c='2';
        ref1.Approval_Level_Required__c='2';
        ref1.Approval_Status__c='';
        ref1.Approval_Rejected_Date__c= date.today()+365;
        ref1.Quote_Option__c= quoteOption.Id;
        ref1.Quote__c=quot.id;
        ref1.Reason__c='Test';
        refreason.add(ref1);
        insert refreason;  
        
        Test.startTest();
        FinalizeQuoteController.finalizeQuote(quot.Id);  
        
        
        Test.stopTest();
        System.assertNotEquals(refreason, null);
    }
    
    static testMethod void finaliseTest_X3() { 
        Account acc1 = TestUtil.createBusinessAccount('Bussiness Account Test Aq', 'Business', '123 Main Street', 'Anycity', 'England', '11354', 'United Kingdom');
        
        Id aqueousRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Product2 product = TestUtil.createProduct('Professional Indemnity');
        product.RecordTypeId = aqueousRecordTypeId; 
        product.Innovisk_Entity_ID__c = 'Aqueous';
        insert product; 
        
        Opportunity opp = TestUtil.createOpportunity('Test opp', acc1.Id, product.Id);
        opp.Innovisk_Entity_ID__c = 'Aqueous';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();                            
        opp.Product__c = product.Id;
        opp.Coverage_Product_Options__c = 'Professional Indemnity';
        insert opp;
        
        Quote quot = TestUtil.createQuote('New Quote Test 2',opp.Id);
        quot.OpportunityId = opp.Id;
        quot.Rating_Status__c = 'Refer';
        quot.Status = 'Rated';
        quot.Coverage_Product_Options__c = 'Professional Indemnity';
        insert quot; 
        quot.Rating_Status__c='clear';
        update quot;
        Quote_Option__c quoteOption = new  Quote_Option__c();
        quoteOption.Quote__c=quot.Id;
        quoteOption.Selected__c=true;
        insert quoteOption;
        
        List<Referral_Reason__c> refreason= new List<Referral_Reason__c>();
        Referral_Reason__c ref1=new Referral_Reason__c();
        ref1.Approver_Level__c='3';
        ref1.Approval_Level_Required__c='3';
        ref1.Approval_Status__c='';
        ref1.Approval_Rejected_Date__c= date.today()+365;
        ref1.Quote_Option__c= quoteOption.Id;
        ref1.Quote__c=quot.id;
        //ref1.Reason__c='Test';
        refreason.add(ref1);
        insert refreason;  
        
        Test.startTest();
        FinalizeQuoteController.finalizeQuote(quot.Id);  
        
        
        Test.stopTest();
        System.assertNotEquals(refreason, null);
    }	
    
    static testMethod void finaliseTest3() { 
        Account acc1 = TestUtil.createBusinessAccount('Bussiness Account Test Aq', 'Business', '123 Main Street', 'Anycity', 'England', '11354', 'United Kingdom');
        
        Id aqueousRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Product2 product = TestUtil.createProduct('Professional Indemnity');
        product.RecordTypeId = aqueousRecordTypeId; 
        product.Innovisk_Entity_ID__c = 'Aqueous';
        insert product; 
        
        Opportunity opp = TestUtil.createOpportunity('Test opp', acc1.Id, product.Id);
        opp.Innovisk_Entity_ID__c = 'Aqueous';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();                            
        opp.Product__c = product.Id;
        opp.Coverage_Product_Options__c = 'Professional Indemnity';
        insert opp;
        
        Quote quot = TestUtil.createQuote('New Quote Test 2',opp.Id);
        quot.OpportunityId = opp.Id;
        quot.Rating_Status__c = 'Refer';
        quot.Status = 'Rated';
        quot.Coverage_Product_Options__c = 'Professional Indemnity';
        insert quot; 
        quot.Rating_Status__c='clear';
        update quot;
        Quote_Option__c quoteOption = new  Quote_Option__c();
        quoteOption.Quote__c=quot.Id;
        quoteOption.Selected__c=true;
        insert quoteOption;
        
        List<Referral_Reason__c> refreason= new List<Referral_Reason__c>();
        Referral_Reason__c ref1=new Referral_Reason__c();
        ref1.Approver_Level__c='3';
        ref1.Approval_Level_Required__c='3';
        ref1.Approval_Status__c='';
        ref1.Approval_Rejected_Date__c= date.today()+365;
        ref1.Quote_Option__c= quoteOption.Id;
        ref1.Quote__c=quot.id;
        ref1.Reason__c='Test';
        refreason.add(ref1);
        insert refreason;  
        
        Test.startTest();
        FinalizeQuoteController.finalizeQuote(quot.Id);  
        
        
        Test.stopTest();
        System.assertNotEquals(refreason, null);
    }	
    
    static testMethod void finaliseTest4() { 
        Account acc1 = TestUtil.createBusinessAccount('Bussiness Account Test Aq', 'Business', '123 Main Street', 'Anycity', 'England', '11354', 'United Kingdom');
        
        Id aqueousRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Product2 product = TestUtil.createProduct('Professional Indemnity');
        product.RecordTypeId = aqueousRecordTypeId; 
        product.Innovisk_Entity_ID__c = 'Aqueous';
        insert product; 
        
        Opportunity opp = TestUtil.createOpportunity('Test opp', acc1.Id, product.Id);
        opp.Innovisk_Entity_ID__c = 'Aqueous';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();                            
        opp.Product__c = product.Id;
        opp.Coverage_Product_Options__c = 'Professional Indemnity';
        insert opp;
        
        Quote quot = TestUtil.createQuote('New Quote Test 2',opp.Id);
        quot.OpportunityId = opp.Id;
        quot.Rating_Status__c = 'Refer';
        quot.Status = 'Rated';
        quot.Coverage_Product_Options__c = 'Professional Indemnity';
        insert quot; 
        quot.Rating_Status__c='clear';
        update quot;
        Quote_Option__c quoteOption = new  Quote_Option__c();
        quoteOption.Quote__c=quot.Id;
        quoteOption.Selected__c=true;
        insert quoteOption;
        
        List<Referral_Reason__c> refreason= new List<Referral_Reason__c>();
        Referral_Reason__c ref1=new Referral_Reason__c();
        ref1.Approver_Level__c='3';
        ref1.Approval_Level_Required__c='4';
        ref1.Approval_Status__c='';
        ref1.Approval_Rejected_Date__c= date.today()+365;
        ref1.Quote_Option__c= quoteOption.Id;
        ref1.Quote__c=quot.id;
        ref1.Reason__c='Test';
        refreason.add(ref1);
        insert refreason;  
        
        Test.startTest();
        FinalizeQuoteController.finalizeQuote(quot.Id);  
        
        
        Test.stopTest();
        System.assertNotEquals(refreason, null);
    }
    
    static testMethod void testMethod_X2() { 
        Quote q = [SELECT Rating_Status__c,Id,OpportunityId, Opportunity.AccountId FROM Quote WHERE Name='Test Quote'];
        q.Rating_Status__c = '';
        update q;
        Additional_Insured__c addIn = new Additional_Insured__c();
        addIn.Submission__c = q.OpportunityId;
        addIn.Additional_Insured_Account__c = q.Opportunity.AccountId;
        insert addIn;
        Test.startTest();
        ResultResponse res = new ResultResponse(); 
        // ProcessInstanceWorkitem instanceworkItem = [SELECT id  FROM ProcessInstanceWorkitem Limit 1];
        
        res = FinalizeQuoteController.finalizeQuote(q.Id);
        FinalizeQuoteController.quoteDetails(q.Id);
        FinalizeQuoteController.generateApprovalURL(q.Id);
        FinalizeQuoteController.handleCloseReasons(q.Id);
        FinalizeQuoteController.checkIsPrimaryBroker(q.Id);
        System.assertNotEquals(res.data, null);
        Test.stopTest();        
    } 
    
    static testMethod void testMethod2() {                 
        Quote q = [SELECT Rating_Status__c,Id FROM Quote WHERE Name='Test Quote'];
        q.Rating_Status__c = '';
        update q;
        Test.startTest();
        ResultResponse res = new ResultResponse(); 
        // ProcessInstanceWorkitem instanceworkItem = [SELECT id  FROM ProcessInstanceWorkitem Limit 1];
        
        res = FinalizeQuoteController.finalizeQuote(q.Id);
        FinalizeQuoteController.quoteDetails(q.Id);
        FinalizeQuoteController.generateApprovalURL(q.Id);
        FinalizeQuoteController.handleCloseReasons(q.Id);
        FinalizeQuoteController.checkIsPrimaryBroker(q.Id);
        System.assertNotEquals(res.data, null);
        Test.stopTest();        
    }   
    
    static testMethod void testMethod3() {                 
        Quote q = [SELECT Status,Id FROM Quote WHERE Name='Test Quote'];
        q.Status = 'Quoted';
        update q;
        ResultResponse res = new ResultResponse();    
        Test.startTest();
        res = FinalizeQuoteController.finalizeQuote(q.Id);                 
        System.assertNotEquals(res.data, null);
        Test.stopTest();        
    }   
    
    static testMethod void testMethod_X4() {      
        Id aqueousRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Product2 product = TestUtil.createProduct('Professional Indemnity');
        product.RecordTypeId = aqueousRecordTypeId; 
        product.Innovisk_Entity_ID__c = 'Aqueous';
        insert product; 
        Opportunity opp = TestUtil.createOpportunity('Test opp', null, product.Id);
        opp.Innovisk_Entity_ID__c = 'Aqueous';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();                            
        opp.Product__c = product.Id;
        opp.Coverage_Product_Options__c = 'Professional Indemnity';
        insert opp;
        Quote q = TestUtil.createQuote('New Quote Test 2',opp.Id);
        q.Rating_Status__c = 'Refer';
        q.Status = 'Rated';
        q.Coverage_Product_Options__c = 'Professional Indemnity';
        insert q;
        Account acc = new Account();
        acc.Name = 'Test';
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Broker').getRecordTypeId();
        acc.Appointed__c = false;
        insert acc;
        // Create contact
        Contact con = new Contact(
            Lastname = 'Huy broker',
            AccountId = acc.Id,
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId()
        );
        insert con;
        
        // Create broker
        Broker_Account__c broker = new Broker_Account__c(
            Broker_Contact__c = con.Id,
            Opportunity__c = q.OpportunityId,
            IsPrimaryBroker__c = true,
            Relationship_Type__c = 'Broker'
        );
        insert broker;
        ResultResponse res = new ResultResponse();  
        Test.startTest();
        res = FinalizeQuoteController.finalizeQuote(q.Id);                 
        System.assertNotEquals(res.data, null);
        Test.stopTest();
    } 
    
    static testMethod void testMethod4() {                 
        Quote q = [SELECT Rating_Status__c,Id FROM Quote WHERE Name='InProgress Quote'];
        q.Status = 'Rated';
        q.Rating_Status__c = 'Ineligible';
        update q;
        ResultResponse res = new ResultResponse();  
        Test.startTest();
        res = FinalizeQuoteController.finalizeQuote(q.Id);                 
        System.assertNotEquals(res.data, null);
        Test.stopTest();
    } 
    
    static testMethod void testMethod_X6() {    
        Id aqueousRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Product2 product = TestUtil.createProduct('Professional Indemnity');
        product.RecordTypeId = aqueousRecordTypeId; 
        product.Innovisk_Entity_ID__c = 'Aqueous';
        insert product; 
        Opportunity opp = TestUtil.createOpportunity('Test opp', null, product.Id);
        opp.Innovisk_Entity_ID__c = 'Aqueous';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();                            
        opp.Product__c = product.Id;
        opp.Source__c = 'SME';
        opp.Coverage_Product_Options__c = 'Professional Indemnity';
        insert opp;
        Quote q = TestUtil.createQuote('New Quote Test 2',opp.Id);
        q.Rating_Status__c = 'Refer';
        q.Status = 'Rated';
        q.Coverage_Product_Options__c = 'Professional Indemnity';
        insert q;
        Quote_Option__c quoteOption = new  Quote_Option__c();
        quoteOption.Quote__c=q.Id;
        quoteOption.Selected__c=true;
        insert quoteOption;
        
        List<Referral_Reason__c> refreason= new List<Referral_Reason__c>();
        Referral_Reason__c ref1=new Referral_Reason__c();
        ref1.Approver_Level__c='3';
        ref1.Approval_Level_Required__c='3';
        ref1.Approval_Status__c='';
        ref1.Approval_Rejected_Date__c= date.today()+365;
        ref1.Quote_Option__c= quoteOption.Id;
        ref1.Quote__c=q.id;
        //ref1.Reason__c='Test';
        refreason.add(ref1);
        insert refreason; 
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        ResultResponse res = new ResultResponse();    
        Test.startTest();
        res = FinalizeQuoteController.finalizeQuote(q.Id); 
        FinalizeServiceHandler_Common.IncomingFinaliseQuoteResponse ifqr = new FinalizeServiceHandler_Common.IncomingFinaliseQuoteResponse();
        ifqr.status = 'test';
        ifqr.message = 'Test';
        ifqr.data = new FinalizeServiceHandler_Common.Data();
        ifqr.data.quoteId = 'Test';
        ifqr.data.status = 'Test';
        ifqr.data.Documents = new List<FinalizeServiceHandler_Common.Documents>();
        FinalizeServiceHandler_Common.Documents ifqrDoc = new FinalizeServiceHandler_Common.Documents();
        ifqrDoc.Id = 'test';
        ifqrDoc.GeneratedDate = 'Test';
        ifqrDoc.Type = 'test';
        ifqr.data.Documents.add(ifqrDoc);
        System.assert(res != null);
        Test.stopTest();
    }
    static testMethod void testMethod_X5() {                 
        Quote q = [SELECT Rating_Status__c,Id FROM Quote WHERE Name='InProgress Quote'];
        q.Status = 'Rated'; 
        q.Rating_Status__c = 'Clear';
        update q;
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        ResultResponse res = new ResultResponse();    
        Test.startTest();
        res = FinalizeQuoteController.finalizeQuote(q.Id);                 
        System.assert(res != null);
        Test.stopTest();
    } 
    
    static testMethod void testMethod5() {                 
        Quote q = [SELECT Rating_Status__c,Id FROM Quote WHERE Name='InProgress Quote'];
        q.Status = 'Rated'; 
        q.Rating_Status__c = 'Clear';
        update q;
        ResultResponse res = new ResultResponse();    
        Test.startTest();
        res = FinalizeQuoteController.finalizeQuote(q.Id);                 
        System.assert(res != null);
        Test.stopTest();
    } 
    
    static testMethod void testException() {    
        Test.startTest();
        ResultResponse res = new ResultResponse();        
        res = FinalizeQuoteController.finalizeQuote('1');                 
        System.assertEquals(res.data, null);
        Test.stopTest();
    }
    
    static testMethod void testGetQuoteDetails() {
        Quote q = [SELECT Id FROM Quote WHERE Name='InProgress Quote'];
        q.Status = 'Rated';
        update q;
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
        app.setObjectId(q.id);
        app.setNextApproverIds(new List<Id>{userInfo.getUserId()});
        Approval.ProcessResult result = Approval.process(app);
        Test.startTest();
        Boolean isMatching = FinalizeQuoteController.getQuoteDetails(q.id);
        System.assertEquals(false,isMatching);
        Test.stopTest();
    }
    
    static testMethod void testGetQuoteDetails2() {
        Quote q = [SELECT Id FROM Quote WHERE Name='InProgress Quote'];
        q.Status = 'Rated';
        update q;
        User u = [SELECT id FROM User Where id!=:UserInfo.getUserId() AND Profile.Name='System Administrator' AND isActive=true LIMIT 1];
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
        app.setObjectId(q.id);
        app.setNextApproverIds(new List<Id>{u.Id});
        Approval.ProcessResult result = Approval.process(app);
        Test.startTest();
        Boolean isMatching = FinalizeQuoteController.getQuoteDetails(q.id);
        System.assertEquals(true,isMatching);
        Test.stopTest();
    }
    
    static testMethod void getQuoteApprovalCommentsTest(){
        FinalizeServiceHandler_AQ.CommentsWrapper cws = new FinalizeServiceHandler_AQ.CommentsWrapper(new ProcessInstanceStep(Comments='Test'));
        Quote q = [SELECT Id FROM Quote WHERE Name='InProgress Quote'];        
        Test.startTest();
        List<FinalizeServiceHandler_AQ.CommentsWrapper> wrapper = FinalizeServiceHandler_AQ.getQuoteApprovalComments(q.Id);
        Test.stopTest();
        System.assert(wrapper != null);
    }
    
    /*static testMethod void testFinalizeQuoteResult() {
Test.startTest();
Quote q = [SELECT Id FROM Quote WHERE Name='InProgress Quote'];
FinalizeQuoteController.FinalizeQuoteResult res = new FinalizeQuoteController.FinalizeQuoteResult();
res.errorMessage = 'Testing Error';
System.assertEquals('Testing Error', res.errorMessage);
res.updatedQuote = q;
System.assertEquals(q.Id, (res.updatedQuote).Id);
Test.stopTest();
}*/
    
    static testMethod void testcheckPartFixedEndorsement() { 
        Test.startTest();
        Quote q = [SELECT Status,Id FROM Quote WHERE Name='Test Quote'];
        q.Status = 'Quoted';
        update q;
        
        
        Coverage__c cov = TestUtil.createCoverage('Coverage test', 'D&O');
        cov.Coverage_Product__c = 'D&O';
        insert cov;
        Coverage_Limits_Deductibles__c ded = TestUtil.creatLimitsDeductibles('Deductible test', cov.Id);
        insert ded;
        List< CoveragesLineItem__c> lCov = new List< CoveragesLineItem__c>();
        CoveragesLineItem__c coverLi = new CoveragesLineItem__c();
        coverLi.Coverage__c  = cov.Id; 
        coverLi.Quote__c = q.Id;
        coverLi.Coverage_Premium__c  = 'Text Premium'; 
        coverLi.Min_amt__c  = 1000;
        coverLi.Max_amt__c  = 5000;
        coverLi.Deductible_Frequency__c  = 'Daily';
        coverLi.Options_Value_Percent__c  = 5;
        coverLi.Limits_Deductibles__c=ded.id;
        coverLi.Option_Value_Default__c=null;
        lCov.add(coverLi);
        insert lCov;
        
        List<Quote_Option__c> listQuoteOption= new List<Quote_Option__c>();
        Quote_Option__c qo= new Quote_Option__c();
        qo.Actual_Premium_Final__c=10000;
        qo.Actual_Premium_Annual__c=30000;
        qo.Quote__c=q.Id;
        Quote_Option__c qo1= new Quote_Option__c();
        qo1.Actual_Premium_Final__c=10000;
        qo1.Actual_Premium_Annual__c=30000;
        qo1.Quote__c=q.Id;
        listQuoteOption.add(qo);
        listQuoteOption.add(qo1);
        
        
        
        FinalizeQuoteController.checkPartFixedEndorsement(q.Id);
        FinalizeQuoteController.checkSelectedQuoteOption(q.Id);
        Test.stopTest();   
        System.assertNotEquals(lCov, null);
    }   
    
    @isTest
    static void forApprovalTest(){
        Test.startTest();
        Account acc1 = TestUtil.createBusinessAccount('Bussiness Account Test Aq', 'Business', '123 Main Street', 'Anycity', 'England', '11354', 'United Kingdom');
        
        Id aqueousRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Product2 product = TestUtil.createProduct('Professional Indemnity');
        product.RecordTypeId = aqueousRecordTypeId; 
        product.Innovisk_Entity_ID__c = 'Aqueous';
        insert product; 
        
        Opportunity opp = TestUtil.createOpportunity('Test opp', acc1.Id, product.Id);
        opp.Innovisk_Entity_ID__c = 'Aqueous';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();                            
        opp.Product__c = product.Id;
        opp.Coverage_Product_Options__c = 'Professional Indemnity';
        insert opp;
        
        Quote quote1 = TestUtil.createQuote('New Quote Test 2',opp.Id);
        quote1.OpportunityId = opp.Id;
        quote1.Rating_Status__c = 'Refer';
        quote1.Status = 'In Approval';
        quote1.Coverage_Product_Options__c = 'Professional Indemnity';
        quote1.Refer_Type__c = 'Underwriting Referral';
        insert quote1; 
        List<Referral_Reason__c> refreason= new List<Referral_Reason__c>();
        Referral_Reason__c ref1=new Referral_Reason__c();
        ref1.Approver_Level__c='3';
        ref1.Approval_Level_Required__c='1';
        //ref1.Approval_Status__c='Approved';
        ref1.Approval_Rejected_Date__c= date.today()+365;
        ref1.Quote__c=quote1.id;
        refreason.add(ref1);
        Referral_Reason__c ref2=new Referral_Reason__c();
        ref2.Approver_Level__c='0';
        ref2.Approval_Level_Required__c='2';
        //ref2.Approval_Status__c='Rejected';
        ref2.Approval_Rejected_Date__c= date.today()+365;
        ref2.Quote__c=quote1.id;
        refreason.add(ref2);
        insert refreason;  
        
        quote1.Status = 'Rated';
        update quote1;
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
        app.setObjectId(quote1.id);
        
        app.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        Approval.ProcessResult result = Approval.process(app);
        
        FinalizeQuoteController.finalizeQuote(quote1.id);
        FinalizeQuoteController.handleCloseReasons(quote1.Id);
        Test.stopTest();
        system.assertNotEquals(refreason, null);
    }
    @isTest
    static void TestvalidateSyncForQuoteBind(){
        Test.startTest();
        AsyncApexJob job = [select Status,NumberOfErrors FROM AsyncApexJob LIMIT 1];
        FinalizeQuoteController.validateSyncForQuoteBind(job.Id);
        Test.stopTest();
        system.assert(job != null);
        
    }
    
    //Mary
    @istest
    static void testMethod_Doc() {
         
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        
        Quote q = [SELECT Id, Azure_ID__c FROM Quote WHERE Name='Test Quote']; 
        Quote_Option__c quoteOpt = new Quote_Option__c();
        quoteOpt.Azure_ID__c = 'Test';
        quoteOpt.Quote__c =  q.Id;
        quoteOpt.Selected__c = true;
        insert quoteOpt;
        Coverage__c cov = TestUtil.createCoverage('Test Coverage','D&O');
        insert cov;
        Coverage_Limits_Deductibles__c lded = new Coverage_Limits_Deductibles__c(Name = 'Test');
        lded.RecordTypeId = Schema.SObjectType.Coverage_Limits_Deductibles__c.getRecordTypeInfosByName().get('Deductible Option').getRecordTypeId(); 
        lded.Parent_Coverage__c = cov.Id;
        lded.Limit_Deductible_Type__c = 'Endorsement';
        insert lded;
        CoveragesLineItem__c cli = new CoveragesLineItem__c();
        cli.Quote__c = q.Id;
        //cli.CoverageLineItemType__c='Limit Option';
        cli.Limits_Deductibles__c = lded.Id;
        cli.Coverage__c = cov.Id;
        insert cli;
        
        Test.startTest();
        //HttpResponse res = GenericSyncApi.getResponseFromApi('Quote_Sync', 'Sync Quote Status', q, 'functionName');
       // FinalizeServiceHandler_Common.generateFinalizeDocument(q.Azure_ID__c,q.Id);
        FinalizeService.finalizeAndGenerateDocAQ(q);
      /*  FinalizeServiceHandler_Common.finalizeAndGenerateDoc(q);
        FinalizeQuoteController.checkSelectedQuoteOption(q.Id);
        FinalizeQuoteController.checkPartFixedEndorsement(q.Id); */ 
        Test.stopTest();
        System.assertNotEquals(q.Id, null);
    }
    
     @istest
    static void testMethod_Doc_Cont() {
         
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        
        Quote q = [SELECT Id, Azure_ID__c FROM Quote WHERE Name='Test Quote']; 
        Quote_Option__c quoteOpt = new Quote_Option__c();
        quoteOpt.Azure_ID__c = 'Test';
        quoteOpt.Quote__c =  q.Id;
        quoteOpt.Selected__c = true;
        insert quoteOpt;
        Coverage__c cov = TestUtil.createCoverage('Test Coverage','D&O');
        insert cov;
        Coverage_Limits_Deductibles__c lded = new Coverage_Limits_Deductibles__c(Name = 'Test');
        lded.RecordTypeId = Schema.SObjectType.Coverage_Limits_Deductibles__c.getRecordTypeInfosByName().get('Deductible Option').getRecordTypeId(); 
        lded.Parent_Coverage__c = cov.Id;
        lded.Limit_Deductible_Type__c = 'Endorsement';
        insert lded;
        CoveragesLineItem__c cli = new CoveragesLineItem__c();
        cli.Quote__c = q.Id;
        //cli.CoverageLineItemType__c='Limit Option';
        cli.Limits_Deductibles__c = lded.Id;
        cli.Coverage__c = cov.Id;
        insert cli;
        
        Test.startTest();
        //HttpResponse res = GenericSyncApi.getResponseFromApi('Quote_Sync', 'Sync Quote Status', q, 'functionName');
       // FinalizeServiceHandler_Common.generateFinalizeDocument(q.Azure_ID__c,q.Id);
      //  FinalizeService.finalizeAndGenerateDocAQ(q);
        FinalizeServiceHandler_Common.finalizeAndGenerateDoc(q);
        FinalizeQuoteController.checkSelectedQuoteOption(q.Id);
        FinalizeQuoteController.checkPartFixedEndorsement(q.Id);
        Test.stopTest();
        System.assertNotEquals(q.Id, null);
    }
    
    
    @isTest static void finalizeAndGenerateDocAQTest(){
        test.startTest();
        API_Log__c apiLog = new API_Log__c();
        apiLog.Name = 'Test';
        apiLog.Status__c = 'OK';
        test.stopTest(); 
    }
}