main/default/objects/Additional_Insured__c/Additional_Insured__c.object-meta.xml
<CustomObject>
    <label>Additional Insured</label>
    <nameField>
        <displayFormat>Additional Insured-{0000}</displayFormat>
        <label>Additional Insured Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Insured</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Additional_Insured__c/fields/Additional_Insured_Account__c.field-meta.xml
<CustomField>
    <fullName>Additional_Insured_Account__c</fullName>
    <label>Additional Insured Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Additional Insured</relationshipLabel>
    <relationshipName>Additional_Insured</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Additional_Insured__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Additional Insured</relationshipLabel>
    <relationshipName>Additional_Insured</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/AdditionalInsuredTrigger_Test.cls
@isTest
public class AdditionalInsuredTrigger_Test {
	@isTest
    static void testmethodAccount() {
        Account acc = TestUtil.createBusinessAccount('Bussiness Accoun Aq', 'Business', '123 Main Street', 'Anycity', 'England', '11354', 'United Kingdom');
        acc.BillingStreet = acc.ShippingStreet;
        acc.BillingCity = acc.ShippingCity;
        acc.BillingState = acc.ShippingState;
        acc.BillingPostalCode = acc.ShippingPostalCode;
        acc.BillingCountry = acc.ShippingCountry;
        insert acc;
        
        Account acc1 = TestUtil.createBusinessAccount('Bussiness Accoun Aq1', 'Business', '123 Main Street', 'Anycity', 'England', '11354', 'United Kingdom');
        acc1.BillingStreet = acc.ShippingStreet;
        acc1.BillingCity = acc.ShippingCity;
        acc1.BillingState = acc.ShippingState;
        acc1.BillingPostalCode = acc.ShippingPostalCode;
        acc1.BillingCountry = acc.ShippingCountry;
        insert acc1;
        
        Product2 product = TestUtil.createProduct('D&O');
        insert product;   
        
        Opportunity opportunity = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opportunity.StageName = 'Qualified';
        opportunity.Coverage_Product_Options__c = 'D&O;MPL';
        insert opportunity;
        
        Additional_Insured__c additionalInsuredAcc = new Additional_Insured__c();
        additionalInsuredAcc.Submission__c = opportunity.Id;
        additionalInsuredAcc.Additional_Insured_Account__c = acc.Id;
        insert additionalInsuredAcc;
        
        
        
        
        
        //additionalInsuredAcc.Additional_Insured_Account__c = acc1.Id;
       // update additionalInsuredAcc;
        
       
    }
}