main/default/objects/Insurer_Layer_Limit__c/Insurer_Layer_Limit__c.object-meta.xml
<CustomObject>
    <label>Insurer Layer Limit</label>
    <nameField>
        <displayFormat>ILL-{0000}</displayFormat>
        <label>Insurer Layer Limit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurer Layer Limit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Insurer_Layer_Limit__c/fields/Insurer_Layer_Limit__c.field-meta.xml
<CustomField>
    <fullName>Insurer_Layer_Limit__c</fullName>
    <label>Insurer Layer Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Insurer_Layer_Limit__c/fields/Layer__c.field-meta.xml
<CustomField>
    <fullName>Layer__c</fullName>
    <label>Layer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Insurer_Layer_Limit__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Insurer Layer Limit</relationshipLabel>
    <relationshipName>Insurer_Layer_Limit</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Subjectivity_Template__c/Subjectivity_Template__c.object-meta.xml
<CustomObject>
    <label>Subjectivity Template</label>
    <nameField>
        <displayFormat>TEMP-{0000}</displayFormat>
        <label>Subjectivity Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subjectivity Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Subjectivity_Template__c/fields/Layer__c.field-meta.xml
<CustomField>
    <fullName>Layer__c</fullName>
    <label>Layer</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Profession_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Profession_Criteria__c</fullName>
    <label>Profession Criteria</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accountants</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Design &amp; Construct</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Insurance Brokers</fullName>
            </value>
            <value>
                <fullName>IT Consultants</fullName>
            </value>
            <value>
                <fullName>Media Professionals</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Property Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Subjectivity_Name__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Name__c</fullName>
    <label>Subjectivity Name</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Subjectivity_Text__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Text__c</fullName>
    <label>Subjectivity Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/classes/InsurerLayerLimitControllerTest.cls
@isTest
public class InsurerLayerLimitControllerTest {
	@testSetup 
    static void createData(){
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        insert acc;
        
        Product2 product = TestUtil.createProduct('AQ');
        insert product;   
        
        Opportunity opportunity = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opportunity.StageName = 'Qualified';
        opportunity.Coverage_Product_Options__c = 'D&O;MPL';
        insert opportunity;
        
        Subjectivity_Template__c subjectivityTemplate = new Subjectivity_Template__c();
        subjectivityTemplate.Subjectivity_Name__c = 'Signed / Dated Proposal';
        subjectivityTemplate.Subjectivity_Text__c = 'Test';
        subjectivityTemplate.Profession_Criteria__c = 'Engineers';
        insert subjectivityTemplate;
        
        Quote quote = TestUtil.createQuote('New Quote Test',opportunity.Id);
        quote.Coverage_Product_Options__c ='D&O;MPL';   
        insert quote;
        
        quote.Status = 'Quoted';
        update quote;
    }
    
    @isTest
    static void fetchInsurerLimitTest(){
        Test.startTest();
        List<Quote> quotes = [Select Id from Quote];
        decimal totalUnderlyingLayer = InsurerLayerLimitController.fetchInsurerLimit(quotes[0].Id);
        Test.stopTest(); 
        System.assertEquals(0, totalUnderlyingLayer);
    }
    
    @isTest
    static void getInsurerLayerTest(){
        Test.startTest();
        List<Quote> quotes = [Select Id from Quote];
        List<Insurer_Layer_Limit__c> insurerList= InsurerLayerLimitController.getInsurerLayer(quotes[0].Id);
        Test.stopTest();    
        System.assert(insurerList != null);
    }
    
    @isTest
    static void saveAndDeleteInsurerLayerTest(){
        Test.startTest();
        List<Quote> quotes = [Select Id from Quote];
        List<Insurer_Layer_Limit__c> insurerList = new List<Insurer_Layer_Limit__c>();
        Insurer_Layer_Limit__c insurerLayerLimit = new Insurer_Layer_Limit__c();
            insurerLayerLimit.Quote__c = quotes[0].Id;
            insurerLayerLimit.Layer__c = 'Test';
            insurerLayerLimit.CurrencyIsoCode = 'GBP';
        insurerList.add(insurerLayerLimit);
        InsurerLayerLimitController.saveInsurerLayer(insurerList);
        InsurerLayerLimitController.saveInsurerLayer(insurerList);
        InsurerLayerLimitController.deleteInsurer(insurerList[0].Id);
        Test.stopTest(); 
        System.assert(insurerList != null);
    }
}