main/default/objects/UW_Analysis_Template__c/UW_Analysis_Template__c.object-meta.xml
<CustomObject>
    <label>UW Analysis Template</label>
    <nameField>
        <displayFormat>UWAT-{0000}</displayFormat>
        <label>UW Analysis Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UW Analysis Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/UW_Analysis_Template__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <label>Criteria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Territory</fullName>
            </value>
            <value>
                <fullName>D&amp;C Turnover Split</fullName>
            </value>
            <value>
                <fullName>Accountants</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Design &amp; Construct</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Insurance Brokers</fullName>
            </value>
            <value>
                <fullName>IT Consultants</fullName>
            </value>
            <value>
                <fullName>Media Professionals</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Property Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/UW_Analysis_Template__c/fields/Default_Split_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Default_Split_Percentage__c</fullName>
    <label>Default Split Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/UW_Analysis_Template__c/fields/Rating_Factor__c.field-meta.xml
<CustomField>
    <fullName>Rating_Factor__c</fullName>
    <label>Rating/Factor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/UW_Analysis_Template__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/classes/UWAnalysisTemplateQueryUtil.cls
/**************************************************************************************************
 * Class Name: UWAnalysisTemplateQueryUtil
 * Author: 
 * Date: Dec 27, 2021
 * Description: Class to keep UW Analysis Template queries
 * Test Class : 
 **************************************************************************************************/
public with sharing class UWAnalysisTemplateQueryUtil {
    /*************************************************
    * Method Name: fetchUWAnalysisTemplatesByCriteria
    * Author: 
    * Date: 27th Dec 2021
    * Params: Criterias
    * Return: list of UW Analysis Templates
    * Exceptions:
    * Revision: 
    * Description: Fetch UW Anlalysis Templates by Criteria
     *************************************************/
    public static List<UW_Analysis_Template__c> fetchUWAnalysisTemplatesByCriteria(List<String> oppMainProfessions){
        return [SELECT Id, Name, UW_Analysis_Name__c, Criteria__c, 
                UW_Analysis_Code__c,Default_Split_Percentage__c, Rating_Factor__c, Sort_Order__c 
                FROM UW_Analysis_Template__c 
                Where Criteria__c IN: oppMainProfessions
                ORDER BY Sort_Order__c ASC];
    }
}