main/default/objects/Account_Commission_Template__c/Account_Commission_Template__c.object-meta.xml
<CustomObject>
    <label>Account Commission Template</label>
    <nameField>
        <displayFormat>ACT-{0000}</displayFormat>
        <label>Account Commission Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Commission Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Account_Commission_Template__c/fields/Cyber_Default__c.field-meta.xml
<CustomField>
    <fullName>Cyber_Default__c</fullName>
    <label>Cyber Default</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Account_Commission_Template__c/fields/Wholesaler__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <label>Wholesaler Broker Account</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Account_Product__c/Account_Product__c.object-meta.xml
<CustomObject>
    <label>Account Product</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Account_Product__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Project</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Account_Product__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/AccountCommissionQueryUtilTest.cls
/**************************************************************************************************
* Class Name: AccountCommissionQueryUtilTest
* Author: JUHI 
* Date: 
* Description: Class to keep account commission test queries
**************************************************************************************************/
@isTest
public class AccountCommissionQueryUtilTest {
    
    public static testmethod void coverAccountCommissionQueryUtil(){
        Test.startTest();
        
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account chanAcc  =TestUtil.createAccount('Test Channel Account', recordTypeId, '01 Tran Duy Hung','Westminster',
                                                 'California','90000', 'United States');
        chanAcc.Azure_ID__c = '407a8180-7cf0-4c74-99d0-4c194723916e';
        insert chanAcc;
        
        Product2 product = TestUtil.createProduct('D&O Standalone');
        insert product; 
        
         
        Account_Product__c accProd1 = new Account_Product__c();
        accProd1.Account_Id__c = chanAcc.Id;
        accProd1.Product_Id__c = product.id;
        insert accProd1;
        
        Account_Commission_Template__c ac = new Account_Commission_Template__c();
        ac.Wholesaler__c = 'Test Channel Account';
        ac.Cyber_Default__c = 20;
        insert ac;
        
        AccountCommissionQueryUtil.fetchAccountCommissionByAccounts();
        Test.stopTest();
    }
}