main/default/objects/Account_Commission_Template__c/Account_Commission_Template__c.object-meta.xml
<CustomObject>
    <label>Account Commission Template</label>
    <nameField>
        <displayFormat>ACT-{0000}</displayFormat>
        <label>Account Commission Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Commission Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Account_Commission_Template__c/fields/Cyber_Default__c.field-meta.xml
<CustomField>
    <fullName>Cyber_Default__c</fullName>
    <label>Cyber Default</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Account_Commission_Template__c/fields/Wholesaler__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <label>Wholesaler Broker Account</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Account_Product__c/Account_Product__c.object-meta.xml
<CustomObject>
    <label>Account Product</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Account_Product__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Project</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Account_Product__c/fields/Commission_percentage__c.field-meta.xml
<CustomField>
    <fullName>Commission_percentage__c</fullName>
    <label>Commission %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Account_Product__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <label>Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Coverage__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <externalId>true</externalId>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Code__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Code__c</fullName>
    <description>User entered code which will be used across systems (radar, middleware etc)</description>
    <externalId>true</externalId>
    <label>Coverage Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Coverage_Limits_Deductibles__c/Coverage_Limits_Deductibles__c.object-meta.xml
<CustomObject>
    <label>Limits &amp; Deductibles</label>
    <nameField>
        <label>Option</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Limits &amp; Deductibles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Coverage_Limits_Deductibles__c/fields/LmtDedCode__c.field-meta.xml
<CustomField>
    <fullName>LmtDedCode__c</fullName>
    <label>LmtDedCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/CoveragesLineItem__c.object-meta.xml
<CustomObject>
    <label>Coverages Line Item</label>
    <nameField>
        <displayFormat>CLI-{00000000}</displayFormat>
        <label>CLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverages Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CoveragesLineItem__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Coverage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Main Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coverage__c</referenceTo>
    <relationshipLabel>Coverages Line Items (Coverage)</relationshipLabel>
    <relationshipName>CoverageQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Code__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Code__c</fullName>
    <formula>Coverage__r.Coverage_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coverage Code</label>
    <type>Text</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Premium__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Premium__c</fullName>
    <label>Coverage Premium</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Deductible_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Frequency__c</fullName>
    <label>Deductible Frequency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/IsSelected__c.field-meta.xml
<CustomField>
    <fullName>IsSelected__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>The value used by the CLI of type Endorsement when added in the Quote</inlineHelpText>
    <label>IsSelected</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Limits_Deductibles__c.field-meta.xml
<CustomField>
    <fullName>Limits_Deductibles__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Limits &amp; Deductibles</label>
    <referenceTo>Coverage_Limits_Deductibles__c</referenceTo>
    <relationshipLabel>Coverages Line Items</relationshipLabel>
    <relationshipName>ProductQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Max_amt__c.field-meta.xml
<CustomField>
    <fullName>Max_amt__c</fullName>
    <label>Max ($)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Min_amt__c.field-meta.xml
<CustomField>
    <fullName>Min_amt__c</fullName>
    <label>Min ($)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Options_Value_Percent__c.field-meta.xml
<CustomField>
    <fullName>Options_Value_Percent__c</fullName>
    <label>Option Percentage (%)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Coverages Line Items</relationshipLabel>
    <relationshipName>Coverages_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Subjectivity__c/Subjectivity__c.object-meta.xml
<CustomObject>
    <label>Subjectivity</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subjectivity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subjectivity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Subjectivity__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Subjectivity</relationshipLabel>
    <relationshipName>Subjectivity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity__c</fullName>
    <label>Subjectivity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity_Status__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Status__c</fullName>
    <label>Subjectivity Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity_Type__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Type__c</fullName>
    <label>Subjectivity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
                <default>true</default>
                <label>General</label>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassOpportunityTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassOpportunityTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassOpportunityTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/REST_Invsk_CoveragesQuote_V2Test.cls
/**************************************************************************************************
* Class Name: REST_Invsk_CoveragesQuote_V2Test
* Author: Ashik Zahir
* Created date: 03 Feb-2021
* Description: Coverage Quote Test Class
**************************************************************************************************/
@isTest
public class REST_Invsk_CoveragesQuote_V2Test {
    
    @testsetup static void testSetup(){
        Test.startTest();
        GlobalStaticVar.byPassAccountProductTrigger = true;
       	TriggerSettings__c setting = TestUtil.initialTriggerSetting();
        setting.BypassOpportunityTrigger__c = true;
        setting.BypassQuoteTrigger__c = true;
        update setting;
        
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
		
        Account acc  = TestUtil.createAccount('Test account 1', recordTypeId, '01 Tran Duy Hung','Westminster',
												'California','90000', 'United States');
        acc.Azure_ID__c = '8042ac98-ae5a-4692-9880-58d92d0eb9d9';
		insert acc;
        
        Product2 product = TestUtil.createProduct('D&O Standalone');
		insert product;
        
        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.CloseDate = Date.today()+365;
        opp.StageName = 'New';
        opp.Azure_ID__c = 'f70e4c82-3378-41ce-870b-57f4df415874';
        insert opp;
        
        //Setip Account Commision Table
	    Account_Commission_Template__c ac = new Account_Commission_Template__c();
        ac.Wholesaler__c = 'New_J_Account_123';
        ac.Cyber_Default__c = 20;
        insert ac;
               
         //Account Product for AccountID
        Account_Product__c accProd1 = new Account_Product__c();
        accProd1.Account_Id__c = acc.Id;
        accProd1.Product_Id__c = product.id;
        insert accProd1; 
        
        
       /* Product2 product2 = TestUtil.createProduct('Cyber Standalone');
		insert product2; 

        Account_Product__c accProd3 = new Account_Product__c();
        accProd3.Account_Id__c = acc.Id;
        accProd3.Product_Id__c = product2.id;
        accProd3.Commission_percentage__c = ac.Cyber_Default__c;
        insert accProd3; */
        
        //Channel Account
	    Account chanAcc  =TestUtil.createAccount('Test Channel Account', recordTypeId, '01 Tran Duy Hung','Westminster',
												'California','90000', 'United States');
        chanAcc.Azure_ID__c = '407a8180-7cf0-4c74-99d0-4c194723916e';
		insert chanAcc;
        
        
		Account_Product__c accProd2 = new Account_Product__c();
        accProd2.Account_Id__c = chanAcc.Id;
        accProd2.Product_Id__c = product.id;
        insert accProd2;

        Id recordTypeBrokerAgency = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Broker').getRecordTypeId();
        
        Account accBroker = TestUtil.createBusinessAccount('Broker Account Test', 'Broker_Account', '625, South Mill Road', 'Anycity', 'New York', '67074', 'United States');
		accBroker.RecordTypeId = recordTypeBrokerAgency;
		
        insert accBroker;

		Contact contactBroker = TestUtil.createContact(accBroker.Id, 'Broker_Contact', 'New broker contact');
		insert  contactBroker;       
        
        Quote quote1 = TestUtil.createQuote('New quote 1', opp.Id);
        quote1.Status = 'In Progress';
        quote1.Coverage_Product_Options__c = 'D&O';
        quote1.Quote_Type__c = 'New Business';
     	quote1.Refer_Type__c = 'Underwriting Referral';
        quote1.Azure_ID__c = 'Testing-Quote';
        insert quote1; 
       
        //Data for get Request
        Quote quote2 = TestUtil.createQuote('New quote 2', opp.Id);
        quote2.Status = 'In Progress';
        quote2.Coverage_Product_Options__c = 'D&O';
        quote2.Quote_Type__c = 'New Business';
     	quote2.Refer_Type__c = 'Underwriting Referral';
        quote2.Azure_ID__c = 'Test2-Quote';
        quote2.Parent_Quote__c= quote1.Id;
        insert quote2;

		Coverage__c cov1 = TestUtil.createCoverage('Coverage test', 'MPL');
		insert cov1;
        Coverage__c cov2 = TestUtil.createCoverage('Coverage test2', 'MPL');
		insert cov2;

        Quote quote = TestUtil.createQuote('New Quote Test',opp.Id);
		quote.Coverage_Product_Options__c ='D&O;MPL';
        quote.Parent_Quote__c = quote1.Id;
		insert quote;
        
        quote.Status = 'Rated';
        update quote;
        
        //create limit deductables
		Coverage_Limits_Deductibles__c ded = TestUtil.creatLimitsDeductibles('Deductible test', cov1.Id);
        insert ded;
        
         // Coverages Line Item
        CoveragesLineItem__c coverLi = new CoveragesLineItem__c();
        coverLi.Coverage__c  = cov1.Id; 
        coverLi.Quote__c = quote.Id;
        coverLi.Limits_Deductibles__c = ded.Id;
        coverLi.Coverage_Premium__c  = 'Text Premium'; 
        coverLi.Min_amt__c  = 1000;
        coverLi.Max_amt__c  = 5000;
        coverLi.Deductible_Frequency__c  = 'Daily';
        coverLi.Options_Value_Percent__c  = 5;
        coverLi.isSelected__c = true;
        insert coverLi;
        
        CoveragesLineItem__c coverLi2 = new CoveragesLineItem__c();
        coverLi2.Coverage__c  = cov2.Id; 
        coverLi2.Quote__c = quote.Id;
        //coverLi.Limits_Deductibles__c = NULL;
        coverLi2.Coverage_Premium__c  = 'Text Premium'; 
        coverLi2.Min_amt__c  = 1000;
        coverLi2.Max_amt__c  = 5000;
        coverLi2.Deductible_Frequency__c  = 'Daily';
        coverLi2.Options_Value_Percent__c  = 5;
        coverLi2.isSelected__c = true;
        insert coverLi2;
      
        ded.LmtDedCode__c = coverLi.Limits_Deductibles__c;
        update ded;
        
        cov1.Coverage_Code__c = coverLi.Coverage__c;
        update cov1;
        
        cov2.Coverage_Code__c = coverLi2.Coverage__c;
        update cov2;
        
        
         
        /*Subjectivity__c subj = new Subjectivity__c();
        subj.Subjectivity__c = 'Testing';
        subJ.Subjectivity_Status__c = 'Open';
        subJ.Subjectivity_Type__c = 'MPL';
        subJ.Quote__c = quote1.Id;
        insert subJ;*/
        Test.stopTest();
    }
    
    @isTest
    public static void testgetQuotesFromId() {
        Test.startTest();
        List<Quote> quoteList = REST_Invsk_CoveragesQuote_V2.getQuotesFromId('Testing-Quote'); 
        Test.stopTest();
        System.assertEquals(true, quoteList != null);
    }
    
    @isTest
    public static void testgetQuoteCLIs() {
        Test.startTest();
        List<CoveragesLineItem__c> CLIList = REST_Invsk_CoveragesQuote_V2.getQuoteCLIs('Testing-Quote'); 
        Test.stopTest();
        System.assertEquals(true, CLIList != null);
    }
    
    @isTest
    static void postMethodTest1(){
        Test.startTest();
        REST_Invsk_CoveragesQuote_V2.IncomingRequest incomingRequest = new REST_Invsk_CoveragesQuote_V2.IncomingRequest();
        
        //Quote
        Quote quote = [SELECT Id, Parent_Quote__c FROM Quote WHERE Azure_Id__c='Test2-Quote' LIMIT 1];
        system.debug('parentQuote--'+quote.Parent_Quote__c);
        List<Quote> quoteAzureId = [SELECT Azure_Id__c FROM Quote WHERE Id = :quote.Id LIMIT 1];
        incomingRequest.quote = quote;
        
        //UWReason
        List<REST_Invsk_CoveragesQuote_V2.UWReason> uwReason = new List<REST_Invsk_CoveragesQuote_V2.UWReason>();
        REST_Invsk_CoveragesQuote_V2.UWReason reason = new REST_Invsk_CoveragesQuote_V2.UWReason();
        reason.OverallUWCodes = '';
        reason.UWReason = '';
        uwReason.add(reason);
        incomingRequest.reasons= uwReason;
        
        //CLI
        List<CoveragesLineItem__c> coverageLineItem = [ SELECT Quote__c,Coverage__c,Limits_Deductibles__c,Coverage_Premium__c,
                                                       Min_amt__c,Max_amt__c,Deductible_Frequency__c,Options_Value_Percent__c,isSelected__c
                                                       FROM CoveragesLineItem__c limit 2];
        incomingRequest.coverageLineItem = coverageLineItem;
        

        system.debug('incomingRequest--'+incomingRequest);

        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_CoveragesQuote_v2/';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(incomingRequest));
      	
        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;

        REST_Invsk_CoveragesQuote_V2.doPost();
        System.assert(incomingRequest != null);
        Test.stopTest();
    }
        
 
    @isTest
    static void postMethodTest2(){
        Test.startTest();
        
        REST_Invsk_CoveragesQuote_V2.IncomingRequest incomingRequest = new REST_Invsk_CoveragesQuote_V2.IncomingRequest();
        
        //Quote
        Quote quote = [SELECT Id, Parent_Quote__c,Azure_Id__c FROM Quote WHERE Azure_Id__c='Testing-Quote' LIMIT 1];
        delete quote;
        incomingRequest.quote = quote;
        
        //UWReason
        List<REST_Invsk_CoveragesQuote_V2.UWReason> uwReason = new List<REST_Invsk_CoveragesQuote_V2.UWReason>();
        REST_Invsk_CoveragesQuote_V2.UWReason reason = new REST_Invsk_CoveragesQuote_V2.UWReason();
        reason.OverallUWCodes = 'Test';
        reason.UWReason = 'Test';
        uwReason.add(reason);
        incomingRequest.reasons= uwReason;
        
        //CLI
        List<CoveragesLineItem__c> coverageLineItem = [ SELECT Quote__c,Coverage__c,Limits_Deductibles__c,Coverage_Premium__c,
                                                       Min_amt__c,Max_amt__c,Deductible_Frequency__c,Options_Value_Percent__c
                                                       FROM CoveragesLineItem__c];
        incomingRequest.coverageLineItem = coverageLineItem;

        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_CoveragesQuote_v2/';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(incomingRequest));
      	
        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;

        REST_Invsk_CoveragesQuote_V2.doPost();
        System.assert(incomingRequest != null);
        Test.stopTest();
    }
        
    @isTest
    static void postMethodTest4(){
        Test.startTest();
        
        REST_Invsk_CoveragesQuote_V2.IncomingRequest incomingRequest = new REST_Invsk_CoveragesQuote_V2.IncomingRequest();
        
        //Quote
        Quote quote = [SELECT Id, Parent_Quote__c FROM Quote WHERE Azure_Id__c='Test2-Quote' LIMIT 1];
        system.debug('parentQuote--'+quote.Parent_Quote__c);
        incomingRequest.quote = quote;
        
        //UWReason
        List<REST_Invsk_CoveragesQuote_V2.UWReason> uwReason = new List<REST_Invsk_CoveragesQuote_V2.UWReason>();
        REST_Invsk_CoveragesQuote_V2.UWReason reason = new REST_Invsk_CoveragesQuote_V2.UWReason();
        reason.OverallUWCodes = '';
        reason.UWReason = '';
        uwReason.add(reason);
        incomingRequest.reasons= uwReason;
        
         //Create coverage
		List<Coverage__c> lCov = new List<Coverage__c>();
		Coverage__c cov = TestUtil.createCoverage('Coverage test', 'D&O');
        cov.Coverage_Product__c = 'D&O';
		lCov.add(cov);
		Coverage__c cov1 = TestUtil.createCoverage('Coverage test', 'MPL');
		lCov.add(cov1);
		insert lCov;
        
        CoveragesLineItem__c coverLi = new CoveragesLineItem__c();
        coverLi.Coverage__c  = cov.Id; 
        coverLi.Quote__c = quote.Id;
        coverLi.Coverage_Premium__c  = 'Text Premium'; 
        coverLi.Min_amt__c  = 1000;
        coverLi.Max_amt__c  = 5000;
        coverLi.Deductible_Frequency__c  = 'Daily';
        coverLi.Options_Value_Percent__c  = 5;
        insert coverLi;
        
        cov.Coverage_Code__c = coverLi.Coverage__c;
        update cov;
        
        Rest_Invsk_CoveragesQuote_V2.generateCoverageLineItems(lCov,quote);
        test.stopTest();
    }
     @isTest
    static void postMethodTest5(){
        Test.startTest();
        
        REST_Invsk_CoveragesQuote_V2.IncomingRequest incomingRequest = new REST_Invsk_CoveragesQuote_V2.IncomingRequest();
        
        //Quote
        Quote quote = [SELECT Id, Parent_Quote__c,Quote_Type__c,Effective_Date__c,Endorsement_Effective_Date__c FROM Quote WHERE Azure_Id__c='Test2-Quote' LIMIT 1];
        incomingRequest.quote = quote;
        quote.Quote_Type__c='New Business';
        quote.Effective_Date__c=Date.today()+15;
        update quote;
        quote.Quote_Type__c='Amendment';
        quote.Endorsement_Effective_Date__c=Date.today()+20;
        update quote;
        
        Coverage_Limits_Deductibles__c covlid =[select id from Coverage_Limits_Deductibles__c limit 1];
        
        //UWReason
        List<REST_Invsk_CoveragesQuote_V2.UWReason> uwReason = new List<REST_Invsk_CoveragesQuote_V2.UWReason>();
        REST_Invsk_CoveragesQuote_V2.UWReason reason = new REST_Invsk_CoveragesQuote_V2.UWReason();
        reason.OverallUWCodes = '';
        reason.UWReason = '';
        uwReason.add(reason);
        incomingRequest.reasons= uwReason;
        
         //Create coverage
		
		Coverage__c cov = TestUtil.createCoverage('Coverage test', 'D&O');
        cov.Coverage_Product__c = 'D&O';
		insert cov;
	
        
        CoveragesLineItem__c coverLi = new CoveragesLineItem__c();
        coverLi.Coverage__c  = cov.Id; 
        coverLi.Quote__c = quote.Id;
        coverLi.Coverage_Premium__c  = 'Text Premium'; 
        coverLi.Min_amt__c  = 1000;
        coverLi.Max_amt__c  = 5000;
        coverLi.Deductible_Frequency__c  = 'Daily';
        coverLi.Options_Value_Percent__c  = 5;
        insert coverLi;
        
        cov.Coverage_Code__c = coverLi.Coverage__c;
        update cov;
        
        Rest_Invsk_CoveragesQuote_V2.GenerateCLIByCoverage(cov,quote);
        Test.stopTest();
    }
}