main/default/objects/Account_Commission_Template__c/Account_Commission_Template__c.object-meta.xml
<CustomObject>
    <label>Account Commission Template</label>
    <nameField>
        <displayFormat>ACT-{0000}</displayFormat>
        <label>Account Commission Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Commission Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Account_Commission_Template__c/fields/Cyber_Default__c.field-meta.xml
<CustomField>
    <fullName>Cyber_Default__c</fullName>
    <label>Cyber Default</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Account_Commission_Template__c/fields/Wholesaler__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <label>Wholesaler Broker Account</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/classes/AccountCommissionQueryUtil.cls
/**************************************************************************************************
 * Class Name: AccountCommissionQueryUtil
 * Author: Juhi
 * Date: Jul 20,2022
 * Description: Class to keep account commissiom template queries
 * Test Class : AccountCommissionQueryUtilTest
 **************************************************************************************************/
public without sharing class AccountCommissionQueryUtil {
    
      public static List<Account_Commission_Template__c> fetchAccountCommissionByAccounts(){
        return [Select id,Wholesaler__c, Cyber_Default__c from Account_Commission_Template__c];
    }

}