main/default/objects/Account_Loss_Detail__c/Account_Loss_Detail__c.object-meta.xml
<CustomObject>
    <label>Account Loss Detail</label>
    <nameField>
        <displayFormat>ALD-{000}</displayFormat>
        <label>Account Loss Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Loss Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Account_Loss_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Loss Details</relationshipLabel>
    <relationshipName>Account_Loss_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Account_Loss_Detail__c/fields/Number_of_Losses__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Losses__c</fullName>
    <label>Number of Losses</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Additional_Insured__c/Additional_Insured__c.object-meta.xml
<CustomObject>
    <label>Additional Insured</label>
    <nameField>
        <displayFormat>Additional Insured-{0000}</displayFormat>
        <label>Additional Insured Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Insured</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Additional_Insured__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Additional Insured</relationshipLabel>
    <relationshipName>Additional_Insured</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/Broker_Account__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Broker_Account__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Broker_Contact__r.AccountId ,  Broker_Contact__r.Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker</fullName>
                <default>true</default>
                <label>Broker</label>
            </value>
            <value>
                <fullName>Sub-Producer</fullName>
            </value>
            <value>
                <fullName>Additional Interest</fullName>
                <isActive>false</isActive>
                <label>Additional Interest</label>
            </value>
            <value>
                <fullName>Insured</fullName>
                <isActive>false</isActive>
                <label>Insured</label>
            </value>
            <value>
                <fullName>Reinsured</fullName>
                <isActive>false</isActive>
                <label>Reinsured</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Quote_Process__c/Quote_Process__c.object-meta.xml
<CustomObject>
    <label>Underwriter Workbench</label>
    <nameField>
        <label>Quote Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Underwriter Workbench</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Quote_Process__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quote_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Quote_Process__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insured Info</fullName>
                <default>true</default>
                <label>Insured Info</label>
            </value>
            <value>
                <fullName>Submission Console</fullName>
            </value>
            <value>
                <fullName>Underwriting Console</fullName>
            </value>
            <value>
                <fullName>Submission Info</fullName>
            </value>
            <value>
                <fullName>Underwritting Analysis</fullName>
                <label>Underwriting Analysis</label>
            </value>
            <value>
                <fullName>Compare &amp; Rate Quotes</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Quote Console</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
                <isActive>false</isActive>
                <label>Closed Lost</label>
            </value>
            <value>
                <fullName>Closed Won</fullName>
                <isActive>false</isActive>
                <label>Closed Won</label>
            </value>
            <value>
                <fullName>Pre-Screening</fullName>
                <isActive>false</isActive>
                <label>Pre-Screening</label>
            </value>
            <value>
                <fullName>Quote Version Console</fullName>
                <isActive>false</isActive>
                <label>Quote Version Console</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Quote_Process__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submission</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Underwriter Workbench</relationshipLabel>
    <relationshipName>Quote_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/SectionSetting__c/SectionSetting__c.object-meta.xml
<CustomObject>
    <description>Contains info to configure components that use sections</description>
    <label>Section Setting</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/SectionSetting__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Format__c.field-meta.xml
<CustomField>
    <fullName>Format__c</fullName>
    <label>Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Long Text</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Hyperlink</fullName>
            </value>
            <value>
                <fullName>MultiSelectPicklist</fullName>
            </value>
            <value>
                <fullName>Range</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Main_Section__c.field-meta.xml
<CustomField>
    <fullName>Main_Section__c</fullName>
    <label>Main Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>PCC</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
            <value>
                <fullName>Aqueous</fullName>
                <isActive>false</isActive>
                <label>Aqueous</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Profile_Name_for_Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Profile_Name_for_Read_Only__c</fullName>
    <label>Profile Name for Read Only</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Celerity Senior Underwriter</fullName>
            </value>
            <value>
                <fullName>Celerity Junior Underwriter</fullName>
            </value>
            <value>
                <fullName>Aqueous Underwriter</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Field_API__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_API__c</fullName>
    <label>Source Field API</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_Label__c</fullName>
    <label>Source Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Broker_Account__c</fullName>
                <label>Broker Account</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Policy_c</fullName>
                <label>Policy</label>
            </value>
            <value>
                <fullName>Rating_Modifier_Factor__c</fullName>
            </value>
            <value>
                <fullName>CoveragesLineItem__c</fullName>
            </value>
            <value>
                <fullName>Coverage_Limits_Deductibles__c</fullName>
            </value>
            <value>
                <fullName>Quote_Option__c</fullName>
            </value>
            <value>
                <fullName>Renewal__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Sub_Section__c.field-meta.xml
<CustomField>
    <fullName>Sub_Section__c</fullName>
    <label>Sub Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/Submission_Loss_Detail__c.object-meta.xml
<CustomObject>
    <label>Submission Loss Detail</label>
    <nameField>
        <displayFormat>LD-{000}</displayFormat>
        <label>Submission Loss Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Loss Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Submission_Loss_Detail__c/fields/Account_Loss_Detail__c.field-meta.xml
<CustomField>
    <fullName>Account_Loss_Detail__c</fullName>
    <label>Account Loss Detail</label>
    <referenceTo>Account_Loss_Detail__c</referenceTo>
    <relationshipLabel>Submission Loss Details</relationshipLabel>
    <relationshipName>Submission_Loss_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/fields/Loss_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loss_Amount__c</fullName>
    <label>Loss Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modifier_Product</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Submission Loss Details</relationshipLabel>
    <relationshipName>Submission_Loss_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/SubmissionInfoLwcControllerTest.cls
@isTest
public class SubmissionInfoLwcControllerTest {
	@testSetup
    public static void setup() {
             
        Id brokerRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account accBroker = TestUtil.createAccount('Account_Business_Test_01', brokerRtId, '5305, Monroe Street', 'Toledo', 'Ohio','43623', 'United States');
        insert accBroker;              	
        
        // create product
        Product2 product = TestUtil.createProduct('MPL Standalone');
		insert product;
        
		// create opportunity        
        Opportunity opp = TestUtil.createOpportunity('Test Opportunity', accBroker.Id, product.Id);
        opp.StageName = 'Qualified';
        insert opp;
        
        Account_Loss_Detail__c accountLoss = new Account_Loss_Detail__c();
        accountLoss.Account__c = accBroker.Id;
        accountLoss.Product__c = 'Cyber';
        accountLoss.Loss_Amount__c = 123;
        accountLoss.Status__c = 'Open';
        accountLoss.Year__c = '2020';
        accountLoss.Number_of_Losses__c = 23;
        insert accountLoss;
        
        Submission_Loss_Detail__c subLoss = new Submission_Loss_Detail__c();
        subLoss.Loss_Amount__c = 200;
        subLoss.Number_of_Losses__c = 2;
        subLoss.Product__c = 'MPL';
        subLoss.Status__c = 'Open';
        subLoss.Year__c = '2020';
        subLoss.Submission__c = opp.Id;
        subLoss.Account_Loss_Detail__c = accountLoss.Id;
        insert subLoss;
        
        Quote_Process__c qp = new Quote_Process__c();
        qp.Account__c = accBroker.Id;
        qp.Submission__c = opp.Id;
        insert qp;
        
        List<SectionSetting__c> secSettingLst = new List<SectionSetting__c>();
        
        SectionSetting__c secSetting = new SectionSetting__c();
        secSetting.Component__c = 'Submission Info';
        secSetting.Main_Section__c = 'Broker Account';
        secSetting.Source_Object__c = 'Broker_Account__c';
        secSetting.Order__c = 4;
        secSetting.Source_Field_Label__c = 'Relationship Type';
        secSetting.Source_Field_API__c = 'Relationship_Type__c';
        secSetting.Format__c = 'Picklist';
        secSetting.Product__c = 'MPL';
        secSetting.Profile_Name_for_Read_Only__c='Celerity Senior Underwriter';
        secSettingLst.add(secSetting);
        
        SectionSetting__c secSetting1 = new SectionSetting__c();
        secSetting1.Component__c = 'Submission Info';
        secSetting1.Main_Section__c = 'Submission Info';
        //secSetting1.Source_Object__c = 'Broker_Account__c';
        secSetting1.Order__c = 3;
        secSetting1.Source_Field_Label__c = 'Relationship Type';
        secSetting1.Source_Field_API__c = 'Relationship_Type__c';
        secSetting1.Format__c = 'Picklist';
        secSetting1.Product__c = 'MPL';
        secSetting1.Profile_Name_for_Read_Only__c='All';
        secSettingLst.add(secSetting1);
        
        SectionSetting__c secSetting2 = new SectionSetting__c();
        secSetting2.Component__c = 'Submission Info';
        secSetting2.Main_Section__c = 'Submission Info';
        secSetting2.Sub_Section__c = 'Account Info';
        secSetting2.Source_Object__c = 'Broker_Account__c';
        secSetting2.Order__c = 1;
        secSetting2.Source_Field_Label__c = 'Name';
        secSetting2.Source_Field_API__c = 'Name';
        secSetting2.Format__c = 'Text';
        secSetting2.Product__c = 'MPL';
        secSetting2.Profile_Name_for_Read_Only__c='All';
        secSettingLst.add(secSetting2);
        insert secSettingLst;
        
        SubmissionInfoLwcController.SubmissionAdditionalInsuredWrapper sub = new SubmissionInfoLwcController.SubmissionAdditionalInsuredWrapper();
        sub.Id = 'subId';
        sub.accId = 'subaccId';
        sub.name = 'subName';
        sub.linkAdditionalDetailAccountAddress = 'subAdress';
        sub.submissionId = 'subId';
        sub.linkSubmissionAdditionalDetailName='subDetail';
        sub.linkSubmissionAdditionalDetailOppName = 'subopName';
        sub.linkAdditionalDetailAccountName = 'SubAcc';
        
        SubmissionInfoLwcController.WrapperField wrapField = new SubmissionInfoLwcController.WrapperField();
        wrapField.value = 'Value';
        wrapField.isDependencyPicklist = true;
        
        SubmissionInfoLwcController.Section secWrapper = new  SubmissionInfoLwcController.Section();
        secWrapper.id = 'secWrapperId';
        secWrapper.subSectionTitle = 'secWrapperSub Title';
    }
    
    @isTest
    public static void testGetSubmissionId() {
       Quote_Process__c qp = [SELECT id,Submission__c FROM Quote_Process__c LIMIT 1];
        test.startTest();
       ResultResponse response = SubmissionInfoLwcController.getSubmissionId(String.valueOf(qp.Id));
        test.stopTest();
       System.assert(response!=null);
    }
    
    @isTest
    public static void testGetListBrokerInfo() {
        Opportunity opp = [SELECT id FROM Opportunity LIMIT 1];
        SubmissionInfoLwcController.getListBrokerInfo(opp.Id);
       	SectionSetting__c secSetting = [SELECT id,Name,Main_Section__c FROM SectionSetting__c LIMIT 1];
        secSetting.Main_Section__c = 'Submission Info';
        update secSetting;
        test.startTest();
        SubmissionInfoLwcController.getListBrokerInfo(opp.Id);
        SubmissionInfoLwcController.checkProfileIsAdmin();
         SubmissionInfoLwcController.getAccountDetails();
        test.stopTest();
        system.assertEquals( secSetting.Main_Section__c, 'Submission Info');
    }
    
   /* @isTest
    public static void testGetProductName() {
       	Quote_Process__c qp = [SELECT id,Submission__c FROM Quote_Process__c LIMIT 1];
        String productName = SubmissionInfoLwcController.getProductName(String.valueOf(qp.Id));
        System.assertEquals('Standalone',productName);
        Opportunity opp = [SELECT id,Name FROM Opportunity LIMIT 1];
        String productNameOpp = SubmissionInfoLwcController.getProductName(String.valueOf(opp.Id));
        System.assertEquals('Standalone',productNameOpp);
    }*/
    
    @isTest
    public static void testGetListSectionSetting() {
        Quote_Process__c qp = [SELECT id,Submission__c FROM Quote_Process__c LIMIT 1];
        SectionSetting__c secSet = [SELECT id,Name,Main_Section__c FROM SectionSetting__c
                                    WHERE Main_Section__c ='Broker Account' LIMIT 1];
        secSet.Main_Section__c = 'Submission Info';
        update secSet;
        SubmissionInfoLwcController.getListSectionSetting(String.valueOf(qp.Id));
        test.startTest();
        Opportunity opp = [select id from  Opportunity limit 1 ];
         SubmissionInfoLwcController.getListSectionSetting(String.valueOf(opp.Id));
        test.stopTest();
        system.assert(opp.id!=null);
    
    }
    
    @isTest
    public static void testGetOpp() {
        Opportunity opp = [SELECT id,Name FROM Opportunity LIMIT 1];
        List<String> srtLst = new List<String>{'Name'};
        String result = JSON.serialize(srtLst);
        test.startTest();
        SubmissionInfoLwcController.getOpp(opp.Id,result);
        test.stopTest();
        system.assert(result!=null,true);
    }
    
    @isTest
    public static void testGetSubmissionLossDetailBySubmission() {
        Opportunity opp = [SELECT id,Name FROM Opportunity LIMIT 1];
        test.startTest();
        SubmissionInfoLwcController.getSubmissionLossDetailBySubmission(opp.Id);
        test.stopTest();
        system.assert(opp.Id!=null);
    }
    
    @isTest
    public static void testGetStageNameSubmission() {
        Account acc = [SELECT id,Name FROM Account LIMIT 1];
        Opportunity opp = [SELECT id,Name FROM Opportunity LIMIT 1];
        Quote quote = TestUtil.createQuote('New Quote Test',opp.Id);
        quote.Coverage_Product_Options__c ='D&O;MPL';
        quote.Layer__c = 'Excess';
        quote.Status='Bound';
        quote.Quote_Type__c = 'Full Amendment';
        //insert quote;
         List<Quote> qp = new  List<Quote>();
        qp.add(quote);
        insert qp;
        quote.Status='Bound';
        update quote;
        
        Additional_Insured__c additionalInsuredAcc = new Additional_Insured__c();
        //additionalInsuredAcc.Name = 'additionalInsuredAccName';
        additionalInsuredAcc.Submission__c = opp.Id;
        additionalInsuredAcc.Additional_Insured_Account__c = acc.Id;
        insert additionalInsuredAcc;
        
        test.startTest();
        SubmissionInfoLwcController.getStageNameSubmission(opp.Id);
        SubmissionInfoLwcController.checkRelatedBoundQuotesPresent(opp.Id);
        SubmissionInfoLwcController.getSubmissionAdditionalInsuredDetails(opp.Id);
        SubmissionInfoLwcController.updateAllQuoteStatusAndCloseReason(opp.Id);
        SubmissionInfoLwcController.unDeclineUpdateSubmission(opp.Id);
        test.stopTest();
        system.assert(quote.Status=='Bound');
    }
}