main/default/objects/Account_Loss_Detail__c/Account_Loss_Detail__c.object-meta.xml
<CustomObject>
    <label>Account Loss Detail</label>
    <nameField>
        <displayFormat>ALD-{000}</displayFormat>
        <label>Account Loss Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Loss Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Account_Loss_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Loss Details</relationshipLabel>
    <relationshipName>Account_Loss_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Account_Loss_Detail__c/fields/Number_of_Losses__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Losses__c</fullName>
    <label>Number of Losses</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <label>Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Coverage__c/fields/Coverage_or_Sub__c.field-meta.xml
<CustomField>
    <fullName>Coverage_or_Sub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Coverage</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Coverage</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Coverage__c</referenceTo>
    <relationshipLabel>Coverage/Subs</relationshipLabel>
    <relationshipName>CoveragesSubs</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Coverage__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Features</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Coverage_Limits_Deductibles__c/Coverage_Limits_Deductibles__c.object-meta.xml
<CustomObject>
    <label>Limits &amp; Deductibles</label>
    <nameField>
        <label>Option</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Limits &amp; Deductibles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Coverage_Limits_Deductibles__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/CoveragesLineItem__c.object-meta.xml
<CustomObject>
    <label>Coverages Line Item</label>
    <nameField>
        <displayFormat>CLI-{00000000}</displayFormat>
        <label>CLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverages Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CoveragesLineItem__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Coverage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Main Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coverage__c</referenceTo>
    <relationshipLabel>Coverages Line Items (Coverage)</relationshipLabel>
    <relationshipName>CoverageQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Coverages Line Items</relationshipLabel>
    <relationshipName>Coverages_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <formula>INCLUDES(Coverage__r.Additional_Requirements__c, &apos;Rating Required&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rating</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Sub_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Coverage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Coverage</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selection must be a Sub Coverage Type</errorMessage>
        <filterItems>
            <field>Coverage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Coverage</value>
        </filterItems>
        <filterItems>
            <field>Coverage__c.Coverage_or_Sub__c</field>
            <operation>equals</operation>
            <valueField>$Source.Coverage__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coverage__c</referenceTo>
    <relationshipLabel>Sub Coverages Line Items</relationshipLabel>
    <relationshipName>SubCoveragesLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Rating_Modifier_Factor__c/Rating_Modifier_Factor__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier Factor</label>
    <nameField>
        <displayFormat>RMF-{0000}</displayFormat>
        <label>Rating Modifier Factor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rating Modifier Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifier_Factor__c/fields/Factor_Value__c.field-meta.xml
<CustomField>
    <fullName>Factor_Value__c</fullName>
    <label>Factor Value</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Rating_Modifier_Factor__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Rating Modifier Factors</relationshipLabel>
    <relationshipName>Rating_Modifier_Factors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifier_Factor__c/fields/Rating_Modifier__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier__c</fullName>
    <label>Rating Modifier</label>
    <referenceTo>Rating_Modifiers__c</referenceTo>
    <relationshipLabel>Rating Modifier Factors</relationshipLabel>
    <relationshipName>Rating_Modifier_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/Rating_Modifiers__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier</label>
    <nameField>
        <label>Rating Modifiers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifiers__c/fields/Factor_Default_Value__c.field-meta.xml
<CustomField>
    <fullName>Factor_Default_Value__c</fullName>
    <label>Factor Default Value</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Factor_Max__c.field-meta.xml
<CustomField>
    <fullName>Factor_Max__c</fullName>
    <label>Factor Max</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Factor_Min__c.field-meta.xml
<CustomField>
    <fullName>Factor_Min__c</fullName>
    <label>Factor Min</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Aqueous</fullName>
                <isActive>false</isActive>
                <label>Aqueous</label>
            </value>
            <value>
                <fullName>Cel1</fullName>
                <isActive>false</isActive>
                <label>Cel1</label>
            </value>
            <value>
                <fullName>D&amp;O Standalone</fullName>
                <isActive>false</isActive>
                <label>D&amp;O Standalone</label>
            </value>
            <value>
                <fullName>New Test</fullName>
                <isActive>false</isActive>
                <label>New Test</label>
            </value>
            <value>
                <fullName>Test</fullName>
                <isActive>false</isActive>
                <label>Test</label>
            </value>
            <value>
                <fullName>Test Product 00</fullName>
                <isActive>false</isActive>
                <label>Test Product 00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/Submission_Loss_Detail__c.object-meta.xml
<CustomObject>
    <label>Submission Loss Detail</label>
    <nameField>
        <displayFormat>LD-{000}</displayFormat>
        <label>Submission Loss Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Loss Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Submission_Loss_Detail__c/fields/Account_Loss_Detail__c.field-meta.xml
<CustomField>
    <fullName>Account_Loss_Detail__c</fullName>
    <label>Account Loss Detail</label>
    <referenceTo>Account_Loss_Detail__c</referenceTo>
    <relationshipLabel>Submission Loss Details</relationshipLabel>
    <relationshipName>Submission_Loss_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/fields/Loss_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loss_Amount__c</fullName>
    <label>Loss Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modifier_Product</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Submission Loss Details</relationshipLabel>
    <relationshipName>Submission_Loss_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassCoverageLineItemTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassCoverageLineItemTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassCoverageLineItemTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/RatingRequestTest.cls
@isTest
public class RatingRequestTest {
 	@testsetup static void testSetup(){
        TriggerSettings__c ts = new TriggerSettings__c();
        ts.BypassCoverageLineItemTrigger__c = true;
        ts.BypassQuoteTrigger__c = true;
        insert ts;
        Account acc = TestUtil.createBusinessAccount('Business Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
		insert acc;
        
        Product2 product = TestUtil.createProduct('D&O Standalone');
		insert product; 

        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.CloseDate = Date.today();
        opp.StageName = 'Closed Won';
    	opp.Expiration_Date__c = Date.today()+60;
        insert opp;
        
        Quote quote1 = TestUtil.createQuote('New quote 1', opp.Id);
        quote1.Status = 'In Progress';
        quote1.Coverage_Product_Options__c = 'D&O';
     	quote1.Refer_Type__c = 'Underwriting Referral';
    	quote1.Tax = 222000;
        insert quote1;  

		Quote quote2 = Testutil.createQuote('New Quote 2', opp.Id);
        quote2.Status = 'Bound';
        quote2.Coverage_Product_Options__c = 'D&O';
        quote2.Refer_Type__c = 'Underwriting Referral';
    	quote2.Tax = 2122000;
        insert quote2;
        
        
        Quote childQuote = TestUtil.createQuote('New child quote', opp.Id);
        childQuote.Status = 'In Progress';
        childQuote.Quote_Type__c = 'Amendment';
        childQuote.Coverage_Product_Options__c = 'D&O';
        childQuote.Refer_Type__c = 'Underwriting Referral';
        childQuote.Tax = 222000;
        childQuote.Parent_Quote__c = quote1.Id;
        insert childQuote; 
        

        
        Coverage__c cov = TestUtil.createCoverage('Test Coverage 1', 'D&O');
        cov.Rating__c = True;
        insert cov;
        
        Coverage__c cov2 = TestUtil.createCoverage('Test Coverage 1', 'D&O');
        cov2.RecordTypeId = Schema.SObjectType.Coverage__c.getRecordTypeInfosByName().get('Sub Coverage').getRecordTypeId();
        cov2.Coverage_or_Sub__c = cov.Id;
        insert cov2;
        
        Coverage_Limits_Deductibles__c covLd = TestUtil.creatLimitsDeductibles('Test Ld', cov.id);
        insert covLd;
        
        CoveragesLineItem__c covLineItem = TestUtil.createCoverageLineItem(quote1.Id, covLd.id, cov.Id, 'Picklist');
        covLineItem.Sub_Coverage__c = cov2.Id;
		//covLineItem.Rating__c = True;
        insert covLineItem;
        
        Rating_Modifiers__c rateMod = TestUtil.createRatingModifier('Test Rate Modifier 1', 'MPL', opp.Id);
        insert rateMod;
        
        Rating_Modifier_Factor__c rateFactor = new Rating_Modifier_Factor__c();
        rateFactor.Rating_Modifier__c = rateMod.Id;
        rateFactor.Quote__c = quote1.Id;
        rateFactor.Factor_Default_Value__c=82.866;
        rateFactor.Factor_Value__c=76.324;
        rateFactor.Factor_Max__c=3.588;
        rateFactor.Factor_Min__c=43.539;
        insert rateFactor;
        
        Account_Loss_Detail__c accountLoss = new Account_Loss_Detail__c();
        accountLoss.Account__c = acc.Id;
        accountLoss.Product__c = 'Cyber';
        accountLoss.Loss_Amount__c = 123;
        accountLoss.Status__c = 'Open';
        accountLoss.Year__c = '2020';
        accountLoss.Number_of_Losses__c = 23;
        insert accountLoss;
        
        Submission_Loss_Detail__c subLoss = new Submission_Loss_Detail__c();
        subLoss.Submission__c = opp.Id;
    	subLoss.Loss_Amount__c = 22200;
        subLoss.Status__c = 'Open';
        subLoss.Year__c ='2019';
        subLoss.Number_of_Losses__c=2;
        subLoss.Account_Loss_Detail__c = accountLoss.Id;
        insert subLoss;
    }
    
    @isTest
    static void getRatingRequestTest(){
        Test.startTest();
        Quote q = [Select Id from Quote Limit 1];
		Opportunity opp = [Select Id from Opportunity Limit 1];
        
       RatingRequest result = new RatingRequest();
        result = RatingRequest.getRatingRequest(q.id, opp.id);       
        Test.stopTest();
        system.assert(result != null);
    }
    
    @isTest
    static void getRatingRequestTest2(){
        Test.startTest();
         Account acc = TestUtil.createBusinessAccount('Business Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
		insert acc;
        
        Product2 product = TestUtil.createProduct('D&O Standalone');
		insert product; 

        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.CloseDate = Date.today();
        opp.StageName = 'Closed Won';
    	opp.Expiration_Date__c = Date.today()+60;
        insert opp;
        
        Quote quote1 = TestUtil.createQuote('New quote 1', opp.Id);
        quote1.Status = 'In Progress';
        quote1.Coverage_Product_Options__c = 'D&O';
     	quote1.Refer_Type__c = 'Underwriting Referral';
    	quote1.Tax = 222000;
        insert quote1;  

		Quote quote2 = Testutil.createQuote('New Quote 2', opp.Id);
        quote2.Status = 'Bound';
        quote2.Coverage_Product_Options__c = 'D&O';
        quote2.Refer_Type__c = 'Underwriting Referral';
    	quote2.Tax = 2122000;
        insert quote2;
        
        Coverage__c cov = TestUtil.createCoverage('Test Coverage 1', 'D&O');
        cov.Rating__c = True;
        insert cov;
        
        Coverage__c cov2 = TestUtil.createCoverage('Test Coverage 1', 'D&O');
        cov2.RecordTypeId = Schema.SObjectType.Coverage__c.getRecordTypeInfosByName().get('Sub Coverage').getRecordTypeId();
        cov2.Coverage_or_Sub__c = cov.Id;
        insert cov2;
        
        Coverage_Limits_Deductibles__c covLd = TestUtil.creatLimitsDeductibles('Test Ld', cov.id);
        covLd.RecordTypeId =Schema.SObjectType.Coverage_Limits_Deductibles__c.getRecordTypeInfosByName().get('Limit Option').getRecordTypeId();
        insert covLd;
        
        CoveragesLineItem__c covLineItem = TestUtil.createCoverageLineItem(quote1.Id, covLd.id, cov.Id, 'Picklist');
        covLineItem.Sub_Coverage__c = cov2.Id;
		//covLineItem.Rating__c = True;
        insert covLineItem;
        
        Rating_Modifiers__c rateMod = TestUtil.createRatingModifier('Test Rate Modifier 1', 'MPL', opp.Id);
        insert rateMod;
        
        Rating_Modifier_Factor__c rateFactor = new Rating_Modifier_Factor__c();
        rateFactor.Rating_Modifier__c = rateMod.Id;
        rateFactor.Quote__c = quote1.Id;
        rateFactor.Factor_Default_Value__c=82.866;
        rateFactor.Factor_Value__c=76.324;
        rateFactor.Factor_Max__c=3.588;
        rateFactor.Factor_Min__c=43.539;
        insert rateFactor;
        
        Account_Loss_Detail__c accountLoss = new Account_Loss_Detail__c();
        accountLoss.Account__c = acc.Id;
        accountLoss.Product__c = 'Cyber';
        accountLoss.Loss_Amount__c = 123;
        accountLoss.Status__c = 'Open';
        accountLoss.Year__c = '2020';
        accountLoss.Number_of_Losses__c = 23;
        insert accountLoss;
        
        Submission_Loss_Detail__c subLoss = new Submission_Loss_Detail__c();
        subLoss.Submission__c = opp.Id;
    	subLoss.Loss_Amount__c = 22200;
        subLoss.Status__c = 'Open';
        subLoss.Year__c ='2019';
        subLoss.Number_of_Losses__c=2;
        subLoss.Account_Loss_Detail__c = accountLoss.Id;
        insert subLoss;
        
        RatingRequest.PriorLimitItem ps = new RatingRequest.PriorLimitItem(covLineItem);
        RatingRequest.PriorCoverageItem pci = new RatingRequest.PriorCoverageItem(covLineItem);
        RatingRequest.CoverageItem ci = new RatingRequest.CoverageItem(covLineItem);
        RatingRequest.CoverageItem ci1 = new RatingRequest.CoverageItem();
        RatingRequest.SubCoverageItem sci = new RatingRequest.SubCoverageItem(covLineItem);
        RatingRequest.SubCoverageItem sci1 = new RatingRequest.SubCoverageItem();
        RatingRequest.LimitItem li = new RatingRequest.LimitItem(covLineItem);
        RatingRequest.LimitItem li1 = new RatingRequest.LimitItem();
        RatingRequest.DeductibleItem di = new RatingRequest.DeductibleItem(covLineItem);
        RatingRequest.DeductibleItem di1 = new RatingRequest.DeductibleItem();
        
        
        
        //RatingRequest.generateLimitDeductible(new List<CoveragesLineItem__c>{covLineItem});
        
        
        RatingRequest result = new RatingRequest();
        result = RatingRequest.getRatingRequest(quote1.id, opp.id);        
        Test.stopTest();
        system.assert(result != null);
    }
    
    @isTest
    static void getRatingRequestTestforException(){
        Test.startTest();
        Quote q = [Select Id from Quote Limit 1];
		Opportunity opp = [Select Id from Opportunity Limit 1];
       
        try{
           RatingRequest.getRatingRequest('111', '22');
        }
        catch(Exception ex){
            System.assert(ex.getMessage()!=null);
        }
        
        Test.stopTest();
    }
    
    @isTest
    static void testgetRatingRequest(){
        Quote childQuote = [Select Id from Quote where Name = 'New child quote' Limit 1];
        Opportunity opp = [Select Id from Opportunity Limit 1];        
        Test.startTest();
        RatingRequest result = RatingRequest.getRatingRequest(childQuote.Id, opp.Id);
     	RatingRequest.QuoteWrapper resultQuote = new RatingRequest.QuoteWrapper();
        resultQuote = result.quote;        
        Test.stopTest();
        system.assertEquals('New child quote', resultQuote.quoteName);
    }
    
    @isTest
    static void testgetBoundQuote(){
        Quote childQuote = [Select Id from Quote where Name = 'New child quote' Limit 1];
        Opportunity opp = [Select Id from Opportunity Limit 1];
        Test.startTest();
        Quote quote = RatingRequest.getBoundQuote(childQuote.Id);       
        Test.stopTest();
        system.assertEquals(childQuote.Id, quote.Id);
    }
    
    @isTest
    static void testgetPriorCoverageLineItem2(){
        Quote childQuote = [Select Id from Quote where Name = 'New child quote' Limit 1];
        Opportunity opp = [Select Id from Opportunity Limit 1];
        Test.startTest();
        List<CoveragesLineItem__c> covList = RatingRequest.getPriorCoverageLineItem2(childQuote.Id);                
        Test.stopTest();
        system.assertEquals('Test Coverage 1', covList[0].Coverage__r.Name);
    }
    


   
}