main/default/objects/Account_Loss_Detail__c/Account_Loss_Detail__c.object-meta.xml
<CustomObject>
    <label>Account Loss Detail</label>
    <nameField>
        <displayFormat>ALD-{000}</displayFormat>
        <label>Account Loss Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Loss Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Account_Loss_Detail__c/fields/Number_of_Losses__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Losses__c</fullName>
    <label>Number of Losses</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/Submission_Loss_Detail__c.object-meta.xml
<CustomObject>
    <label>Submission Loss Detail</label>
    <nameField>
        <displayFormat>LD-{000}</displayFormat>
        <label>Submission Loss Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Loss Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Submission_Loss_Detail__c/fields/Account_Loss_Detail__c.field-meta.xml
<CustomField>
    <fullName>Account_Loss_Detail__c</fullName>
    <label>Account Loss Detail</label>
    <referenceTo>Account_Loss_Detail__c</referenceTo>
    <relationshipLabel>Submission Loss Details</relationshipLabel>
    <relationshipName>Submission_Loss_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/fields/Loss_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loss_Amount__c</fullName>
    <label>Loss Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modifier_Product</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Submission Loss Details</relationshipLabel>
    <relationshipName>Submission_Loss_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/SubmissionLossDetailQueryUtil.cls
/**************************************************************************************************
 * Class Name: SubmissionLossDetailQueryUtil
 * Author: 
 * Date: 
 * Description: Utility class to hold all queries related to Submission Loss Detail
 * Test Class : 
 **************************************************************************************************/
public with sharing class SubmissionLossDetailQueryUtil {
    /*************************************************
    * Method Name: fetchByAccountLossAndOppStage
    * Author: Vinay Vernekar
    * Date: 13th Dec 2021
    * Params: Set<id> accountLossDetailIds, String stageName
    * Return: list of submission loss details
    * Exceptions:
    * Revision: 
    * Description: Fetch all submission loss detail records
     *************************************************/
    public static List<Submission_Loss_Detail__c> fetchByAccountLossAndOppStage(Set<id> accountLossDetailIds, String stageName){
        return [SELECT Id, Loss_Amount__c, Number_of_Losses__c,
                Product__c, Status__c, Year__c, Submission__c, Account_Loss_Detail__c,
                Account_Loss_Detail__r.Loss_Amount__c, Account_Loss_Detail__r.Number_of_Losses__c,
                Account_Loss_Detail__r.Product__c, Account_Loss_Detail__r.Status__c,
                Account_Loss_Detail__r.Year__c, Submission__r.StageName
            FROM Submission_Loss_Detail__c
            WHERE Account_Loss_Detail__c IN: accountLossDetailIds
            AND Submission__r.StageName =:stageName];
    }
}