main/default/objects/Account_Loss_Detail__c/Account_Loss_Detail__c.object-meta.xml
<CustomObject>
    <label>Account Loss Detail</label>
    <nameField>
        <displayFormat>ALD-{000}</displayFormat>
        <label>Account Loss Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Loss Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Account_Loss_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Loss Details</relationshipLabel>
    <relationshipName>Account_Loss_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Account_Loss_Detail__c/fields/Number_of_Losses__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Losses__c</fullName>
    <label>Number of Losses</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/recordTypes/Aqueous.recordType-meta.xml
<RecordType>
    <fullName>Aqueous</fullName>
    <active>true</active>
    <label>Aqueous</label>
</RecordType>

main/default/objects/Policy__c/recordTypes/Celerity.recordType-meta.xml
<RecordType>
    <fullName>Celerity</fullName>
    <active>true</active>
    <label>Celerity</label>
</RecordType>

main/default/objects/Quote_Process__c/Quote_Process__c.object-meta.xml
<CustomObject>
    <label>Underwriter Workbench</label>
    <nameField>
        <label>Quote Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Underwriter Workbench</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Quote_Process__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quote_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Quote_Process__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insured Info</fullName>
                <default>true</default>
                <label>Insured Info</label>
            </value>
            <value>
                <fullName>Submission Console</fullName>
            </value>
            <value>
                <fullName>Underwriting Console</fullName>
            </value>
            <value>
                <fullName>Submission Info</fullName>
            </value>
            <value>
                <fullName>Underwritting Analysis</fullName>
                <label>Underwriting Analysis</label>
            </value>
            <value>
                <fullName>Compare &amp; Rate Quotes</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Quote Console</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
                <isActive>false</isActive>
                <label>Closed Lost</label>
            </value>
            <value>
                <fullName>Closed Won</fullName>
                <isActive>false</isActive>
                <label>Closed Won</label>
            </value>
            <value>
                <fullName>Pre-Screening</fullName>
                <isActive>false</isActive>
                <label>Pre-Screening</label>
            </value>
            <value>
                <fullName>Quote Version Console</fullName>
                <isActive>false</isActive>
                <label>Quote Version Console</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Quote_Process__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submission</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Underwriter Workbench</relationshipLabel>
    <relationshipName>Quote_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/SectionSetting__c/SectionSetting__c.object-meta.xml
<CustomObject>
    <description>Contains info to configure components that use sections</description>
    <label>Section Setting</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/SectionSetting__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/DisplayType__c.field-meta.xml
<CustomField>
    <fullName>DisplayType__c</fullName>
    <label>Display Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Collapsed</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Format__c.field-meta.xml
<CustomField>
    <fullName>Format__c</fullName>
    <label>Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Long Text</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Hyperlink</fullName>
            </value>
            <value>
                <fullName>MultiSelectPicklist</fullName>
            </value>
            <value>
                <fullName>Range</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Main_Section__c.field-meta.xml
<CustomField>
    <fullName>Main_Section__c</fullName>
    <label>Main Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>PCC</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
            <value>
                <fullName>Aqueous</fullName>
                <isActive>false</isActive>
                <label>Aqueous</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Profile_Name_for_Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Profile_Name_for_Read_Only__c</fullName>
    <label>Profile Name for Read Only</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Celerity Senior Underwriter</fullName>
            </value>
            <value>
                <fullName>Celerity Junior Underwriter</fullName>
            </value>
            <value>
                <fullName>Aqueous Underwriter</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Field_API__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_API__c</fullName>
    <label>Source Field API</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_Label__c</fullName>
    <label>Source Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Broker_Account__c</fullName>
                <label>Broker Account</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Policy_c</fullName>
                <label>Policy</label>
            </value>
            <value>
                <fullName>Rating_Modifier_Factor__c</fullName>
            </value>
            <value>
                <fullName>CoveragesLineItem__c</fullName>
            </value>
            <value>
                <fullName>Coverage_Limits_Deductibles__c</fullName>
            </value>
            <value>
                <fullName>Quote_Option__c</fullName>
            </value>
            <value>
                <fullName>Renewal__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Sub_Section__c.field-meta.xml
<CustomField>
    <fullName>Sub_Section__c</fullName>
    <label>Sub Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassAccountTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassAccountTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassAccountTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassContactTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassContactTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassContactTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/InsureAccountControllerTest.cls
@isTest
public class InsureAccountControllerTest {
	@testSetup
    public static void setup() {
        TriggerSettings__c setting = new TriggerSettings__c();
        setting.BypassContactTrigger__c = true;
        setting.BypassAccountTrigger__c = true;
        insert setting;
        Id brokerRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account accBroker = TestUtil.createAccount('Account_Business_Test_01', brokerRtId, '5305, Monroe Street', 'Toledo', 'Ohio','43623', 'United States');
        insert accBroker;
        
        // Create contact
		Contact con = new Contact(
			Lastname = 'Test broker',
			RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId()
		);
		insert con;
        
        // create product
        Product2 product = TestUtil.createProduct('MPL Standalone');
		insert product;
        
		// create opportunity        
        Opportunity opp = TestUtil.createOpportunity('Test Opportunity', accBroker.Id, product.Id);
        opp.StageName = 'Qualified';
        insert opp;
        
        Quote_Process__c qp = new Quote_Process__c();
        qp.Account__c = accBroker.Id;
        qp.Submission__c = opp.Id;
        insert qp;
        
        Account_Loss_Detail__c accLossDet = new Account_Loss_Detail__c();
        accLossDet.Loss_Amount__c = 1000;
        accLossDet.Account__c = accBroker.Id;
        accLossDet.Number_of_Losses__c = 2;
        accLossDet.Product__c = 'MPL';
        accLossDet.Status__c = 'Open';
        insert accLossDet;
    }
   /* 
    @isTest
    public static void testGetListSectionSetting() {
         SectionSetting__c secSetting = new SectionSetting__c();
        secSetting.Component__c = 'Account Info';
        secSetting.Main_Section__c = 'Broker Account';
        secSetting.Source_Object__c = 'Account';
        secSetting.Order__c = 4;
        secSetting.Source_Field_Label__c = 'Relationship Type';
        //secSetting.Source_Field_API__c = 'Relationship_Type__c';
        secSetting.Format__c = 'Picklist';
        secSetting.Product__c = 'MPL';
        secSetting.Active__c = true;
        secSetting.Record_Type__c = 'Celerity';
        insert secSetting;
        
        Quote_Process__c qp = [SELECT id FROM Quote_Process__c LIMIT 1];
        InsureAccountController.getListSectionSetting(qp.Id);
        
        Opportunity opp = [SELECT id FROM Opportunity LIMIT 1];
        InsureAccountController.getListSectionSetting(opp.Id);
        
        Account acc = [SELECT id FROM Account LIMIT 1];
        InsureAccountController.getListSectionSetting(acc.Id);
    } 
    
    @isTest
    public static void testGetListSectionSetting2() {
        SectionSetting__c secSetting = new SectionSetting__c();
        secSetting.Component__c = 'Account Info';
        secSetting.Main_Section__c = 'Contact Info';
        secSetting.Sub_Section__c = 'Account Info';
        secSetting.Source_Object__c = 'Account';
        secSetting.Order__c = 2;
        secSetting.Source_Field_Label__c = 'Account Name';
        //secSetting.Source_Field_API__c = 'Id';
        secSetting.Format__c = 'Lookup';
        secSetting.Product__c = 'MPL';
        secSetting.Active__c = true;
        secSetting.Record_Type__c = 'Celerity';
        insert secSetting;
        
        Quote_Process__c qp = [SELECT id FROM Quote_Process__c LIMIT 1];
        InsureAccountController.getListSectionSetting(qp.Id);
        
    }
    
     @isTest
    public static void testGetListSectionSetting3() {
        SectionSetting__c secSetting = new SectionSetting__c();
        secSetting.Component__c = 'Account Info';
        secSetting.Main_Section__c = 'Contact Info';
        secSetting.Sub_Section__c = 'Account Info';
        secSetting.Source_Object__c = 'Account';
        secSetting.Order__c = 2;
        secSetting.Source_Field_Label__c = 'Account Name';
        secSetting.Source_Field_API__c = 'Id';
        secSetting.Format__c = 'Lookup';
        secSetting.Product__c = 'MPL';
        secSetting.Active__c = true;
        secSetting.Record_Type__c = 'Celerity';
        insert secSetting;
        
        Quote_Process__c qp = [SELECT id FROM Quote_Process__c LIMIT 1];
        InsureAccountController.getListSectionSetting(qp.Id);
        
    } */
    
    @isTest
    public static void testGetListSectionSetting4() {
        SectionSetting__c secSetting = new SectionSetting__c();
        secSetting.Component__c = 'Account Info';
        secSetting.Main_Section__c = 'Contact Info';
        secSetting.Source_Object__c = 'Account';
        secSetting.Order__c = 4;
        secSetting.Source_Field_Label__c = 'Relationship Type';
        //secSetting.Source_Field_API__c = 'Relationship_Type__c';
        secSetting.Format__c = 'Picklist';
        secSetting.Product__c = 'MPL';
        secSetting.Active__c = true;
        secSetting.Record_Type__c = 'Celerity';
        secSetting.DisplayType__c = 'Open';
        insert secSetting;
        
        SectionSetting__c secSetting2 = new SectionSetting__c();
        secSetting2.Component__c = 'Account Info';
        secSetting2.Main_Section__c = 'Contact Info';
        secSetting2.Sub_Section__c = 'Account Info';
        secSetting2.Source_Object__c = 'Account';
        secSetting2.Order__c = 3;
        secSetting2.Source_Field_Label__c = 'Account Name';
        //secSetting.Source_Field_API__c = 'Id';
        secSetting2.Format__c = 'Number';
        secSetting2.Product__c = 'MPL';
        secSetting2.Active__c = true;
        secSetting2.Record_Type__c = 'Celerity';
        secSetting2.DisplayType__c = 'Component';
        insert secSetting2;
        
        SectionSetting__c secSetting1 = new SectionSetting__c();
        secSetting1.Component__c = 'Account Info';
        secSetting1.Main_Section__c = 'Contact Info';
        //secSetting.Sub_Section__c = 'Account Info';
        secSetting1.Source_Object__c = 'Account';
        secSetting1.Order__c = 2;
        secSetting1.Source_Field_Label__c = 'Account Name';
        secSetting1.Source_Field_API__c = 'Id';
        secSetting1.Format__c = 'Lookup';
        secSetting1.Product__c = 'MPL';
        secSetting1.Active__c = true;
        secSetting1.Record_Type__c = 'Celerity';
        secSetting1.Profile_Name_for_Read_Only__c = 'All';
        secSetting1.DisplayType__c = 'Component';
        insert secSetting1;
        
         SectionSetting__c secSetting3 = new SectionSetting__c();
        secSetting3.Component__c = 'Account Info';
        secSetting3.Main_Section__c = 'Contact Info';
        secSetting3.Sub_Section__c = 'Account Info';
        secSetting3.Source_Object__c = 'Account';
        secSetting3.Order__c = 1;
        secSetting3.Source_Field_Label__c = 'Account Name';
        secSetting3.Source_Field_API__c = 'Id';
        secSetting3.Format__c = 'Text';
        secSetting3.Product__c = 'MPL';
        secSetting3.Active__c = true;
        secSetting3.Record_Type__c = 'Celerity';
        secSetting3.DisplayType__c = 'Component';
        insert secSetting3;
        
        Quote_Process__c qp = [SELECT id FROM Quote_Process__c LIMIT 1];
        InsureAccountController.getListSectionSetting(qp.Id);
        
        Opportunity opp = [SELECT id FROM Opportunity LIMIT 1];
        InsureAccountController.getListSectionSetting(opp.Id);
    }
    
    @isTest
    public static void testGetPicklistValues() {
        InsureAccountController.getPicklistValues('Policy__c','Cancellation_Reason__c','','');
    }
    
    @isTest
    public static void testGetRecordInfos() {
         
        
        Quote_Process__c qp = [SELECT id FROM Quote_Process__c LIMIT 1];
        InsureAccountController.getRecordInfos(qp.Id);
        
        Opportunity opp = [SELECT id FROM Opportunity LIMIT 1];
        InsureAccountController.getRecordInfos(opp.Id);
        
    }
    
    @isTest
    public static void testGetAccountInfos() {
       	SectionSetting__c secSetting = new SectionSetting__c();
        secSetting.Component__c = 'Account Info';
        secSetting.Main_Section__c = 'Contact Info';
        secSetting.Source_Object__c = 'Account';
        secSetting.Order__c = 4;
        secSetting.Source_Field_Label__c = 'Name';
        secSetting.Source_Field_API__c = 'Name';
        secSetting.Format__c = 'Text';
        secSetting.Product__c = 'MPL';
        secSetting.Active__c = true;
        secSetting.Record_Type__c = 'Celerity';
        insert secSetting;
        
        Account acc = [SELECT id FROM Account LIMIT 1];
        InsureAccountController.getAccountInfos(acc.Id); 
    }
    
    @isTest
    public static void testGetRecordTypeInfo() {
        InsureAccountController.getRecordTypeInfo('Broker','Contact');
    }
    
    @isTest
    public static void testGetAccountLossDetailByAccount() {
        Account acc = [SELECT id FROM Account LIMIT 1];
        InsureAccountController.getAccountLossDetailByAccount(acc.Id);
    }
    
    @isTest
    public static void testGetObjectRecordTypeId() {
        InsureAccountController.getObjectRecordTypeId('Contact','Broker');
    }
    
    @isTest
    public static void testGetListSectionSettingNeg() {
        SectionSetting__c secSetting1 = new SectionSetting__c();
        secSetting1.Component__c = 'Account Info';
        secSetting1.Main_Section__c = 'Contact Info';
        //secSetting.Sub_Section__c = 'Account Info';
        secSetting1.Source_Object__c = 'Account';
        secSetting1.Order__c = 2;
        secSetting1.Source_Field_Label__c = 'Account Name';
        secSetting1.Source_Field_API__c = 'Id';
        secSetting1.Format__c = 'Lookup';
        secSetting1.Product__c = 'MPL';
        secSetting1.Active__c = true;
        secSetting1.Record_Type__c = 'Celerity';
        secSetting1.Profile_Name_for_Read_Only__c = 'Celerity Senior Underwriter';
        insert secSetting1;
        
        Quote_Process__c qp = [SELECT id FROM Quote_Process__c LIMIT 1];
        InsureAccountController.getListSectionSetting(qp.Id);
    }
    
    @isTest
    public static void testWrapperUsed() {
        Account acc = [SELECT id FROM Account LIMIT 1];
        InsureAccountController.SelectOptionWrapper optionWrap = new InsureAccountController.SelectOptionWrapper();
        InsureAccountController.AccountLossDetailWrapper accLstWrap = new InsureAccountController.AccountLossDetailWrapper();
        InsureAccountController.Section sec = new InsureAccountController.Section();
        sec.order = 12;
        sec.compareTo(sec);
        
        InsureAccountController.SubSectionChild secChild = new InsureAccountController.SubSectionChild();
        secChild.order = 1;
        secChild.compareTo(secChild);
        InsureAccountController.updateQuoteInProgress('Test');
        InsureAccountController.SectionWrapper secWrap = new InsureAccountController.SectionWrapper(acc.Id,new List<InsureAccountController.Section>{sec});
    }
    @isTest
    static void testgetRecordInfos2(){        
       	SectionSetting__c secSetting = new SectionSetting__c();
        secSetting.Component__c = 'Account Info';
        secSetting.Main_Section__c = 'Contact Info';
        secSetting.Source_Object__c = 'Contact';
        secSetting.Order__c = 4;
        secSetting.Source_Field_Label__c = 'Name';
        secSetting.Source_Field_API__c = 'Name';
        secSetting.Format__c = 'Text';
        secSetting.Product__c = 'MPL';
        secSetting.Active__c = true;
        secSetting.Record_Type__c = 'Celerity';
        insert secSetting;
        Test.startTest();
        Contact con = [Select Id from Contact Limit 1];
        Contact result = InsureAccountController.getRecordInfos(String.valueOf(con.Id));
        System.assert(result!=null);  
        Test.stopTest();
    }
    @isTest
    static void checkQuotedQuoteTest(){
        Test.startTest();
        Id accId = [Select id From Account Limit 1].Id;
        Quote_Process__c qouProc = [Select id from Quote_Process__c Limit 1];
        ResultResponse result = InsureAccountController.checkQuotedQuote(accId, qouProc.Id);
        InsureAccountController.getProductName(qouProc.Id);
        System.assert(result!=null);
        Test.stopTest();
    }
    @isTest
    static void TestAqueous(){
        Test.startTest();
       
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'England', '11354', 'United Kingdom');
        acc.BillingStreet = acc.ShippingStreet;
        acc.BillingCity = acc.ShippingCity;
        acc.BillingState = acc.ShippingState;
        acc.BillingPostalCode = acc.ShippingPostalCode;
        acc.BillingCountry = acc.ShippingCountry;
        insert acc;
        
        Id aqueousRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Product2 prod = TestUtil.createProduct('Professional Indemnity');
        prod.RecordTypeId = aqueousRecordTypeId;
        prod.Innovisk_Entity_ID__c = 'Aqueous';
		insert prod;
        
        
        Opportunity oppaq = TestUtil.createOpportunity('Opportunity',acc.Id, prod.Id);
        oppaq.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        oppaq.Innovisk_Entity_ID__c = 'Aqueous';        
        oppaq.Coverage_Product_Options__c = 'Professional Indemnity';
        oppaq.StageName = 'Qualified';
        insert oppaq;
        
        Quote quoteaq = Testutil.createQuote('New Quote 2', oppaq.Id);
        quoteaq.Status = 'Quoted';
        quoteaq.Refer_Type__c = 'Underwriting Referral';
        quoteaq.Coverage_Product_Options__c = 'Professional Indemnity';
        insert quoteaq; 
        quoteaq.Layer__c='Excess';
        update quoteaq;
        
       
        
        //Opportunity oppaq = [Select Id,StageName from Opportunity where Name='Aqueous Test' Limit 1];
        InsureAccountController.updateQuoteStatusForAQ(oppaq.Id);
        Test.stopTest();
        
    }
 
    
}