main/default/objects/Account_Loss_Detail__c/Account_Loss_Detail__c.object-meta.xml
<CustomObject>
    <label>Account Loss Detail</label>
    <nameField>
        <displayFormat>ALD-{000}</displayFormat>
        <label>Account Loss Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Loss Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Account_Loss_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Loss Details</relationshipLabel>
    <relationshipName>Account_Loss_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Account_Loss_Detail__c/fields/Number_of_Losses__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Losses__c</fullName>
    <label>Number of Losses</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/Submission_Loss_Detail__c.object-meta.xml
<CustomObject>
    <label>Submission Loss Detail</label>
    <nameField>
        <displayFormat>LD-{000}</displayFormat>
        <label>Submission Loss Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Loss Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Submission_Loss_Detail__c/fields/Account_Loss_Detail__c.field-meta.xml
<CustomField>
    <fullName>Account_Loss_Detail__c</fullName>
    <label>Account Loss Detail</label>
    <referenceTo>Account_Loss_Detail__c</referenceTo>
    <relationshipLabel>Submission Loss Details</relationshipLabel>
    <relationshipName>Submission_Loss_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/fields/Loss_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loss_Amount__c</fullName>
    <label>Loss Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modifier_Product</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Submission_Loss_Detail__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Submission Loss Details</relationshipLabel>
    <relationshipName>Submission_Loss_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/CommonAccountLossDetailUtil.cls
/**************************************************************************************************
 * Class Name: CommonAccountLossDetailUtil
 * Author: 
 * Date: 
 * Description: Utility class to hold all methods related to Account Loss Detail methods
 * Test Class : 
 **************************************************************************************************/
public with sharing class CommonAccountLossDetailUtil {
    /*************************************************
    * Method Name: createSubmissionLossDetails
    * Author: Hang Lam
    * Date: 07/09/2020
    * Params: newDataMap - Map AccountLossDetail
    * Return: 
    * Description: 28736 - create SubmissionLossDetail when Account Loss Details were created and Quote Process already had Submission 
    * Can be converted to a flow : Yes
    **********************************************/
    public static void createSubmissionLossDetails(Map<Id, Account_Loss_Detail__c> newDataMap){
        Set<Id> accountIds = new Set<Id>();
        List<Submission_Loss_Detail__c> listSubmissionLoss = new List<Submission_Loss_Detail__c>();
        for(Account_Loss_Detail__c accLossDetail : newDataMap.values()){
            if(String.isNotBlank(accLossDetail.Account__c))
                accountIds.add(accLossDetail.Account__c);
        }
        List<Opportunity> listOpps = OpportunityQueryUtil.fetchOpportunitiesByAccountAndStage(accountIds, 'Qualified');
        Map<String, List<Opportunity>> accOppMap = new Map<String, List<Opportunity>>();
        if(!listOpps.isEmpty()){
            for(Opportunity opp : listOpps){
                if(accOppMap.containsKey(opp.AccountId)){
                    accOppMap.get(opp.AccountId).add(opp);
                }else{
                    accOppMap.put(opp.AccountId, new List<Opportunity>{opp});
                }
            }
        }
        
        for(Account_Loss_Detail__c accLoss : newDataMap.values()){
            if(accOppMap.get(accLoss.Account__c) != null){
                for(Opportunity opp : accOppMap.get(accLoss.Account__c)) {
                    if(opp.AccountId == accLoss.Account__c) {
                        Submission_Loss_Detail__c subLoss = new Submission_Loss_Detail__c();
                        subLoss.Loss_Amount__c = accLoss.Loss_Amount__c;
                        subLoss.Number_of_Losses__c = accLoss.Number_of_Losses__c;
                        subLoss.Product__c = accLoss.Product__c;
                        subLoss.Status__c = accLoss.Status__c;
                        subLoss.Year__c	 = accLoss.Year__c;
                        subLoss.Submission__c = opp.Id;
                        subLoss.Account_Loss_Detail__c = accLoss.Id;
                        listSubmissionLoss.add(subLoss);
                    }
                } 
            }
        }
        if(!listSubmissionLoss.isEmpty())
            insert listSubmissionLoss;
        
    }

    /*************************************************
    * Method Name: updateSubmissionLossDetails
    * Author: Hang Lam
    * Date: 07/09/2020
    * Params: newDataMap - Map AccountLossDetail
    * Return: 
    * Description: 28736 - update SubmissionLossDetail when Account Loss Details were created and Quote Process already had Submission 
    * Can be converted to a flow : Yes
    **********************************************/
    public static void updateSubmissionLossDetails(Map<Id, Account_Loss_Detail__c> newDataMap){
        List<Submission_Loss_Detail__c> listSubmissionLoss = SubmissionLossDetailQueryUtil.fetchByAccountLossAndOppStage(newDataMap.keySet(), 'Qualified');
        if(!listSubmissionLoss.isEmpty()){
            for(Submission_Loss_Detail__c subLossDetail : listSubmissionLoss){
                subLossDetail.Loss_Amount__c = subLossDetail.Account_Loss_Detail__r.Loss_Amount__c;
                subLossDetail.Number_of_Losses__c = subLossDetail.Account_Loss_Detail__r.Number_of_Losses__c;
                subLossDetail.Product__c = subLossDetail.Account_Loss_Detail__r.Product__c;
                subLossDetail.Status__c = subLossDetail.Account_Loss_Detail__r.Status__c;
                subLossDetail.Year__c = subLossDetail.Account_Loss_Detail__r.Year__c;
            }
        }
        update listSubmissionLoss;
    }
}