main/default/objects/Quote_Process__c/Quote_Process__c.object-meta.xml
<CustomObject>
    <label>Underwriter Workbench</label>
    <nameField>
        <label>Quote Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Underwriter Workbench</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Quote_Process__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quote_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Quote_Process__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insured Info</fullName>
                <default>true</default>
                <label>Insured Info</label>
            </value>
            <value>
                <fullName>Submission Console</fullName>
            </value>
            <value>
                <fullName>Underwriting Console</fullName>
            </value>
            <value>
                <fullName>Submission Info</fullName>
            </value>
            <value>
                <fullName>Underwritting Analysis</fullName>
                <label>Underwriting Analysis</label>
            </value>
            <value>
                <fullName>Compare &amp; Rate Quotes</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Quote Console</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
                <isActive>false</isActive>
                <label>Closed Lost</label>
            </value>
            <value>
                <fullName>Closed Won</fullName>
                <isActive>false</isActive>
                <label>Closed Won</label>
            </value>
            <value>
                <fullName>Pre-Screening</fullName>
                <isActive>false</isActive>
                <label>Pre-Screening</label>
            </value>
            <value>
                <fullName>Quote Version Console</fullName>
                <isActive>false</isActive>
                <label>Quote Version Console</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Quote_Process__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submission</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Underwriter Workbench</relationshipLabel>
    <relationshipName>Quote_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/CreateQuoteProcess.cls
/**
 * @description       : 
 * @author            : Vinayesh
 * @group             : 
 * @last modified on  : 08-24-2021
 * @last modified by  : Maeran Shaikh
 * Modifications Log 
 * Ver   Date         Author     Modification
 * 1.0   07-20-2021   Vinayesh   Initial Version
**/
public without sharing class CreateQuoteProcess {
    
    public static String insertQuote(String recordTypeName,String productName){
        try{
            List<Quote_Process__c> quoteProcess = [SELECT Id, Status__c,Record_Type__c,Product__c 
                                                   FROM Quote_Process__c WHERE Account__c = NULL AND Submission__c = NULL LIMIT 1];
            delete quoteProcess;
            
            Quote_Process__c obj =  new Quote_Process__c();
            obj.Record_Type__c = recordTypeName;
            obj.Product__c = productName;
            //Added by Vinayesh- Submission Console
            if(productName == 'Private Company Combo'){
                obj.Status__c = 'Submission Console';
            }
            insert obj;
            return obj.Id;
        }
        catch(Exception ex){
            system.debug('Excep: '+ex.getMessage());
            return null;
        }
    }
    
    /**
    * @description Inserted to accomodate Opp for Quote process
    * @author Maeran Shaikh | 08-24-2021 
    * @param recordTypeName 
    * @param productName 
    * @param oppId 
    * @return String 
    **/
    public static String insertQuoteForPCC(String recordTypeName,String productName, String oppId){
        try{
            List<Quote_Process__c> quoteProcess = [SELECT Id, Status__c,Record_Type__c,Product__c 
                                                   FROM Quote_Process__c WHERE Account__c = NULL AND Submission__c = NULL LIMIT 1];
            delete quoteProcess;
            
            Quote_Process__c obj =  new Quote_Process__c();
            obj.Record_Type__c = recordTypeName;
            obj.Product__c = productName;
            obj.Submission__c = oppId;
            //Added by Vinayesh- Submission Console
            if(productName == 'Private Company Combo'){
                obj.Status__c = 'Submission Console';
            }
            insert obj;
            return obj.Id;
        }
        catch(Exception ex){
            system.debug('Excep: '+ex.getMessage());
            return null;
        }
    }
}