main/default/objects/Quote_Process__c/Quote_Process__c.object-meta.xml
<CustomObject>
    <label>Underwriter Workbench</label>
    <nameField>
        <label>Quote Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Underwriter Workbench</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Quote_Process__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submission</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Underwriter Workbench</relationshipLabel>
    <relationshipName>Quote_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/QuoteProcessQueryUtil.cls
/**************************************************************************************************
 * Class Name: QuoteProcessQueryUtil
 * Author: Vinayesh
 * Date: Dec 27, 2021
 * Description: Class to keep Quote Process(UW workbench) queries
 * Test Class : 
 **************************************************************************************************/

public with sharing class QuoteProcessQueryUtil {
    
    /*************************************************
    * Method Name: fetchQPForSubmissions
    * Author: 
    * Date: 
    * Params: set<Id> oppIds
    * Return: 
    * Exceptions:
    * Description: Get QP records by Submission.
    * Revision: 
     *************************************************/
    public static List<Quote_Process__c> fetchQPForSubmissions (set<Id> oppIds){
        return [SELECT Id, Name, Submission__c FROM Quote_Process__c WHERE Submission__c IN :oppIds];
    }
}