main/default/objects/Quote_Process__c/Quote_Process__c.object-meta.xml
<CustomObject>
    <label>Underwriter Workbench</label>
    <nameField>
        <label>Quote Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Underwriter Workbench</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Quote_Process__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quote_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Quote_Process__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submission</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Underwriter Workbench</relationshipLabel>
    <relationshipName>Quote_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/Rating_Modifiers__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier</label>
    <nameField>
        <label>Rating Modifiers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifiers__c/fields/Rating_Modifier_Code__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Code__c</fullName>
    <label>Rating Modifier Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/UW_Analysis__c/UW_Analysis__c.object-meta.xml
<CustomObject>
    <label>UW Analysis</label>
    <nameField>
        <displayFormat>UWA-{0000}</displayFormat>
        <label>UW Analysis</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UW Analysis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/UW_Analysis__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <label>Criteria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Territory</fullName>
            </value>
            <value>
                <fullName>D&amp;C Turnover Split</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Design &amp; Construct</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Insurance Brokers</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Property Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/UW_Analysis__c/fields/Notional_Income__c.field-meta.xml
<CustomField>
    <fullName>Notional_Income__c</fullName>
    <label>Notional Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/UW_Analysis__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>UW Analysis</relationshipLabel>
    <relationshipName>UW_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/UW_Analysis__c/fields/UW_Analysis_Code__c.field-meta.xml
<CustomField>
    <fullName>UW_Analysis_Code__c</fullName>
    <label>UW Analysis Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/UW_Analysis__c/fields/UW_Analysis_Name__c.field-meta.xml
<CustomField>
    <fullName>UW_Analysis_Name__c</fullName>
    <label>UW Analysis Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/UW_Analysis__c/fields/UW_Analysis_Template__c.field-meta.xml
<CustomField>
    <fullName>UW_Analysis_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UW Analysis Template</label>
    <referenceTo>UW_Analysis_Template__c</referenceTo>
    <relationshipLabel>UW Analysis</relationshipLabel>
    <relationshipName>UW_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/UW_Analysis_Template__c/UW_Analysis_Template__c.object-meta.xml
<CustomObject>
    <label>UW Analysis Template</label>
    <nameField>
        <displayFormat>UWAT-{0000}</displayFormat>
        <label>UW Analysis Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UW Analysis Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/UW_Analysis_Template__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <label>Criteria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Territory</fullName>
            </value>
            <value>
                <fullName>D&amp;C Turnover Split</fullName>
            </value>
            <value>
                <fullName>Accountants</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Design &amp; Construct</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Insurance Brokers</fullName>
            </value>
            <value>
                <fullName>IT Consultants</fullName>
            </value>
            <value>
                <fullName>Media Professionals</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Property Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/UW_Analysis_Template__c/fields/Rating_Factor__c.field-meta.xml
<CustomField>
    <fullName>Rating_Factor__c</fullName>
    <label>Rating/Factor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/UW_Analysis_Template__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/classes/CloneOpportunityControllerTest.cls
@isTest
public class CloneOpportunityControllerTest {
    @testSetup static void setup() {
        TriggerSettings__c setting = TestUtil.initialTriggerSetting();
        setting.BypassQuoteTrigger__c = false;
        update setting;
 
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'England', '11354', 'United Kingdom');
        acc.BillingStreet = acc.ShippingStreet;
        acc.BillingCity = acc.ShippingCity;
        acc.BillingState = acc.ShippingState;
        acc.BillingPostalCode = acc.ShippingPostalCode;
        acc.BillingCountry = acc.ShippingCountry;
        insert acc;
        
        Id aqueousRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Product2 prod = TestUtil.createProduct('Professional Indemnity');
        prod.RecordTypeId = aqueousRecordTypeId;
        prod.Innovisk_Entity_ID__c = 'Aqueous';
        insert prod;
        
        
        Opportunity oppaq = TestUtil.createOpportunity('Aqueous Test',acc.Id, prod.Id);
        oppaq.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        oppaq.Innovisk_Entity_ID__c = 'Aqueous';        
        oppaq.Coverage_Product_Options__c = 'Professional Indemnity';
        oppaq.StageName = 'Qualified';
        insert oppaq;
        
        Rating_Modifiers__c rateMod = TestUtil.createRatingModifier('Cyber Intel Average Score', 'Cyber', oppaq.Id);
        rateMod.Rating_Modifier_Code__c='MPL000012';
        insert rateMod;
        
        Quote quoteaq = Testutil.createQuote('New Quote 2', oppaq.Id);
        quoteaq.Rating_Status__c = 'Clear';
        quoteaq.Status = 'Quoted';       
        insert quoteaq;
        quoteaq.Layer__c='Excess';
        update quoteaq;
        
        Quote_Process__c qp = new Quote_Process__c();
        qp.Account__c = acc.Id;
        qp.Submission__c = oppaq.Id;
        insert qp;
        UW_Analysis_Template__c TempList = new UW_Analysis_Template__c();
        TempList.UW_Analysis_Name__c = 'Test';
        TempList.Criteria__c = 'Engineers';
        TempList.UW_Analysis_Code__c ='Code';
        TempList.Rating_Factor__c= 5000;
        TempList.Sort_Order__c = 100;
        insert TempList;
        
        List<UW_Analysis__c> uw = new List<UW_Analysis__c>();
        
        UW_Analysis__c uwList = new UW_Analysis__c();
        uwList.Amount__c = 1000;
        uwList.UW_Analysis_Name__c = 'UW Test';
        uwList.Criteria__c = 'Territory';
        uwList.UW_Analysis_Code__c = 'T1';
        uwList.Rating_Factor__c = 1000;
        uwList.Sort_Order__c = 10;
        uwList.Submission__c = oppaq.Id;
        uwList.UW_Analysis_Template__c = TempList.Id;
        uwList.Sort_Order__c = 10;
        uwList.Notional_Income__c = 1000;
        insert uwList;
        
    }
    @isTest
    static void   cloneOpportunityTest(){
        Opportunity opp = [Select id,StageName,Received_Date__c,CloseDate from Opportunity limit 1];
        Test.startTest();
        CloneOpportunityController.cloneOpportunity(opp.id);
        
        CloneOpportunityController.cloneOpportunity(null);
        
        date dt = date.today();
        opp.Received_Date__c=dt.addDays(-450);
        opp.CloseDate=dt.addDays(-400);
        update opp;
        CloneOpportunityController.cloneOpportunity(opp.Id);
        Test.stopTest();
        system.assert( opp.StageName == 'Qualified');
    }
}