main/default/objects/Eligibility_Status__c/Eligibility_Status__c.object-meta.xml
<CustomObject>
    <label>Eligibility Status</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Eligibility Status #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligibility Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Eligibility_Status__c/fields/Eligibility_Status__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Status__c</fullName>
    <label>Eligibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Proceed</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution</fullName>
            </value>
            <value>
                <fullName>No Information</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution (consider restrictive terms, including but limited to matching/increasing retention to the largest paid loss)</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution (sub limit only)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (Unless fewer than 50 employees)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (unless Highly Compensated Separate Retention Endorsement is added)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (unless D&amp;O revenue threshold is met)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (seasonal, low wage,retail industries, etc.)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (Unless less than 100 employees)</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution and consider adding a Family Exclusion</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution and consider Major Shareholder Exclusion</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution with sub-limit</fullName>
            </value>
            <value>
                <fullName>qualified or not all locations are audited</fullName>
            </value>
            <value>
                <fullName>Prohibited Class</fullName>
            </value>
            <value>
                <fullName>Munich Referral</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard</fullName>
            </value>
            <value>
                <fullName>Stop!Decline!</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Eligibility_Status__c/fields/Rating_Modifier_Template__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Template__c</fullName>
    <label>Rating Modifier Template</label>
    <referenceTo>Rating_Modifier_Template__c</referenceTo>
    <relationshipLabel>Eligibility Statuses</relationshipLabel>
    <relationshipName>Eligibility_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Product_Option_Line_Item__c/Product_Option_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Product Option Line Item</label>
    <nameField>
        <displayFormat>POLI-{0000}</displayFormat>
        <label>Product  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Option Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Product_Option_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Option Line Items</relationshipLabel>
    <relationshipName>Product_Option_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Product_Option_Line_Item__c/fields/Clearance_Date__c.field-meta.xml
<CustomField>
    <fullName>Clearance_Date__c</fullName>
    <label>Clearance Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Product_Option_Line_Item__c/fields/Clearance_Status__c.field-meta.xml
<CustomField>
    <fullName>Clearance_Status__c</fullName>
    <label>Clearance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Closed Market</fullName>
            </value>
            <value>
                <fullName>Clearance Not Applicable</fullName>
            </value>
            <value>
                <fullName>Service failed</fullName>
            </value>
            <value>
                <fullName>Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Product_Option_Line_Item__c/fields/Is_Selected__c.field-meta.xml
<CustomField>
    <fullName>Is_Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selected</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Product_Option_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Option Line Items</relationshipLabel>
    <relationshipName>Product_Option_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Product_Option_Line_Item__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Product Option Line Items</relationshipLabel>
    <relationshipName>Product_Option_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/Rating_Modifier_Template__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier Template</label>
    <nameField>
        <label>Rating Modifier Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifier Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifier_Template__c/fields/Display_Format__c.field-meta.xml
<CustomField>
    <fullName>Display_Format__c</fullName>
    <label>Display Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Factor Values Only</fullName>
            </value>
            <value>
                <fullName>Secondary Modifiers</fullName>
            </value>
            <value>
                <fullName>Primary Modifiers</fullName>
            </value>
            <value>
                <fullName>Eligibility</fullName>
            </value>
            <value>
                <fullName>Pros and Cons</fullName>
            </value>
            <value>
                <fullName>Default Only</fullName>
            </value>
            <value>
                <fullName>Primary Clearance PCC</fullName>
            </value>
            <value>
                <fullName>Clearance</fullName>
            </value>
            <value>
                <fullName>Modifier and Factor Values</fullName>
                <isActive>false</isActive>
                <label>Modifier and Factor Values</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Values__c</fullName>
    <label>Option Values</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassAccountTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassAccountTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassAccountTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassOpportunityTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassOpportunityTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassOpportunityTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassProductTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassProductTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassProductTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/ClearanceAccordianControllerTest.cls
/**
* @description       : 
* @author            : Vinayesh
* @group             : 
* @last modified on  : 08-17-2021
* @last modified by  : Vinayesh
**/
@isTest
public with sharing class ClearanceAccordianControllerTest {
    public static Product2 product;
    public static Product2 product1;
    public static Product2 product2;
    public static Product2 product3;
    public static Product2 product4;
    public static Account acc;
    public static Opportunity opp;
    public static List<Rating_Modifier_Template__c> lRMT;
    
    static {
        TriggerSettings__c setting = TestUtil.initialTriggerSetting();
        setting.BypassOpportunityTrigger__c = false;
        setting.BypassAccountTrigger__c = true;
        setting.BypassProductTrigger__c = true;
        update setting;
        
        acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        insert acc;
        
        product = TestUtil.createProduct('Private Company Combo');
        insert product;
        
        product1 = TestUtil.createProduct('D&O');
        product1.Parent_Product__c = product.Id;
        product1.IsComboProduct__c = true;
        insert product1;
        
        product2 = TestUtil.createProduct('EPL');
        product2.Parent_Product__c = product.Id;
        product2.IsComboProduct__c = true;
        insert product2;
        
        product3 = TestUtil.createProduct('Crime');
        product3.Parent_Product__c = product.Id;
        product3.IsComboProduct__c = true;
        insert product3;
        
        product4 = TestUtil.createProduct('Fiduciary');
        product4.Parent_Product__c = product.Id;
        product4.IsComboProduct__c = true;
        insert product4;
        
        lRMT = new List<Rating_Modifier_Template__c>();
        Rating_Modifier_Template__c rMT1 = TestUtil.createRatingModifierTemplate('Test Service Classification','D&O','Number');
        rMT1.Display_Format__c = 'Clearance';
        lRMT.add(rMT1);
        Rating_Modifier_Template__c rMT2 = TestUtil.createRatingModifierTemplate('New input integer','D&O','Percentage');
        rMT2.Display_Format__c = 'Clearance';
        lRMT.add(rMT2);
        Rating_Modifier_Template__c rMT3 = TestUtil.createRatingModifierTemplate('New input integer','D&O','Radio Button');
        rMT3.Display_Format__c = 'Clearance';
        lRMT.add(rMT3);
        lRMT = new List<Rating_Modifier_Template__c>();
        Rating_Modifier_Template__c rMT7 = TestUtil.createRatingModifierTemplate('Test Service Classification','D&O','Text');
        rMT7.Display_Format__c = 'Clearance';
        lRMT.add(rMT7);
        Rating_Modifier_Template__c rMT8 = TestUtil.createRatingModifierTemplate('New input integer','D&O','Picklist');
        rMT8.Display_Format__c = 'Clearance';
        lRMT.add(rMT8);
        
        Rating_Modifier_Template__c rMT9 = TestUtil.createRatingModifierTemplate('New input integer','D&O','Date');
        rMT9.Display_Format__c = 'Clearance';
        lRMT.add(rMT9);
        Rating_Modifier_Template__c rMT4 = TestUtil.createRatingModifierTemplate('New input integer','EPL','Integer');
        rMT4.Display_Format__c = 'Clearance';
        lRMT.add(rMT4);
        Rating_Modifier_Template__c rMT5 = TestUtil.createRatingModifierTemplate('Nature of Industry','Crime','Number');
        rMT5.Display_Format__c = 'Clearance';
        lRMT.add(rMT5);
        Rating_Modifier_Template__c rMT6 = TestUtil.createRatingModifierTemplate('Annual Revenues','Fiduciary','Number');
        rMT6.Display_Format__c = 'Clearance';
        lRMT.add(rMT6);
        
        Rating_Modifier_Template__c rMT10 = TestUtil.createRatingModifierTemplate('New input integer','D&O','Picklist');
        rMT10.Display_Format__c = 'Primary Modifiers';
        rMT10.Picklist_Values__c = 'Test 1;Test 2;Test 3;Test 4';
        lRMT.add(rMT10);
        
        Rating_Modifier_Template__c rMT11 = TestUtil.createRatingModifierTemplate('Notes','D&O','Number');
        rMT11.Display_Format__c = 'Clearance';
        lRMT.add(rMT11);
        
        Rating_Modifier_Template__c rMT12 = TestUtil.createRatingModifierTemplate('Notes','D&O','Currency');
        rMT12.Display_Format__c = 'Clearance';
        lRMT.add(rMT12);
        
        Rating_Modifier_Template__c rMT13 = TestUtil.createRatingModifierTemplate('Notes','D&O','Percentage');
        rMT13.Display_Format__c = 'Clearance';
        lRMT.add(rMT13);
        
        Rating_Modifier_Template__c rMT14 = TestUtil.createRatingModifierTemplate('Notes','D&O','Integer');
        rMT14.Display_Format__c = 'Clearance';
        lRMT.add(rMT14);
        
        Rating_Modifier_Template__c rMT15 = TestUtil.createRatingModifierTemplate('Notes','D&O','Radio Button');
        rMT15.Display_Format__c = 'Clearance';
        rMT15.Picklist_Values__c = 'Test 1;Test 2;Test 3;Test 4';
        lRMT.add(rMT15);
        
        Rating_Modifier_Template__c rMT16 = TestUtil.createRatingModifierTemplate('Notes','D&O','Text Area');
        rMT16.Display_Format__c = 'Clearance';
        rMT16.Sub_Section__c = 'TEST';
        lRMT.add(rMT16);
        
        insert lRMT;
        
        
        opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.Total_Revenues__c = 100;
        insert opp;
    }
    
    
    @isTest static void testGetData() {
        
        Product_Option_Line_Item__c newRec = new Product_Option_Line_Item__c();
        newRec.Product__c = product1.Id;
        newRec.Submission__c = opp.Id;
        newRec.Account__c = acc.Id;
        newRec.Clearance_Status__c = 'Cleared';
        newRec.Is_Selected__c = true;
        newRec.Clearance_Date__c = Datetime.now();
        insert newRec;
        
        ClearanceAccordianController.ClearanceWrapper objWrapper = ClearanceAccordianController.getRatingModifiersrecords(opp.Id);
        System.assertEquals(1, objWrapper.productWrapperList.size()); 
        
    }
    
    @isTest static void testAddData() {
        
        Product_Option_Line_Item__c newRec = new Product_Option_Line_Item__c();
        newRec.Product__c = product1.Id;
        newRec.Submission__c = opp.Id;
        newRec.Account__c = acc.Id;
        newRec.Clearance_Status__c = 'Cleared';
        newRec.Is_Selected__c = true;
        newRec.Clearance_Date__c = Datetime.now();
        insert newRec;
        
        ClearanceAccordianController.addRatingModifier(opp.Id);
        ClearanceAccordianController.ClearanceWrapper objWrapper = ClearanceAccordianController.getRatingModifiersrecords(opp.Id);
        //objWrapper.eligibilityStatusWrapper = new Map<String,List<Eligibility_Status__c>>();
        String clearanceWrapperJson = Json.serialize(objWrapper.productWrapperList);
        test.startTest();
        
        ClearanceAccordianController.saveClearanceData(clearanceWrapperJson, opp.Id);
        
        test.stopTest();
        
        System.assertEquals(1, objWrapper.productWrapperList.size());
    }
    
    // Added by RINKU SAINI 20 jan 2022
    public testmethod static void coverClearanceAccordian(){
        Test.startTest();
        
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        insert acc;
        
        Product2 product = TestUtil.createProduct('MPL');
        insert product;
        
        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.Total_Revenues__c = 100;
        insert opp;
        
        Product_Option_Line_Item__c newRec = new Product_Option_Line_Item__c();
        newRec.Product__c = product.Id;
        newRec.Submission__c = opp.Id;
        newRec.Account__c = acc.Id;
        newRec.Clearance_Status__c = 'Cleared';
        newRec.Is_Selected__c = true;
        newRec.Clearance_Date__c = Datetime.now();
        insert newRec;
        
        Rating_Modifier_Template__c rMT1 = New Rating_Modifier_Template__c();
        rMT1.Name = 'Test Service Classification';
        rMT1.Display_Format__c = 'Primary Modifiers';
        rMT1.Product__c = 'MPL';
        insert rMT1;
        
        ClearanceAccordianController.addRatingModifier(opp.Id);
        
        Test.stopTest();
    }
}