main/default/objects/Eligibility_Status__c/Eligibility_Status__c.object-meta.xml
<CustomObject>
    <label>Eligibility Status</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Eligibility Status #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligibility Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Eligibility_Status__c/fields/Eligibility_Status__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Status__c</fullName>
    <label>Eligibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Proceed</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution</fullName>
            </value>
            <value>
                <fullName>No Information</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution (consider restrictive terms, including but limited to matching/increasing retention to the largest paid loss)</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution (sub limit only)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (Unless fewer than 50 employees)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (unless Highly Compensated Separate Retention Endorsement is added)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (unless D&amp;O revenue threshold is met)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (seasonal, low wage,retail industries, etc.)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (Unless less than 100 employees)</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution and consider adding a Family Exclusion</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution and consider Major Shareholder Exclusion</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution with sub-limit</fullName>
            </value>
            <value>
                <fullName>qualified or not all locations are audited</fullName>
            </value>
            <value>
                <fullName>Prohibited Class</fullName>
            </value>
            <value>
                <fullName>Munich Referral</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard</fullName>
            </value>
            <value>
                <fullName>Stop!Decline!</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Eligibility_Status__c/fields/Modifier_Product__c.field-meta.xml
<CustomField>
    <fullName>Modifier_Product__c</fullName>
    <label>Modifier Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modifier_Product</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Eligibility_Status__c/fields/Rating_Modifier_Template__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Template__c</fullName>
    <label>Rating Modifier Template</label>
    <referenceTo>Rating_Modifier_Template__c</referenceTo>
    <relationshipLabel>Eligibility Statuses</relationshipLabel>
    <relationshipName>Eligibility_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Eligibility_Status__c/fields/Rating_Modifier_Value__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Value__c</fullName>
    <label>Rating Modifier Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/Rating_Modifier_Template__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier Template</label>
    <nameField>
        <label>Rating Modifier Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifier Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifier_Template__c/fields/Modifier_Product__c.field-meta.xml
<CustomField>
    <fullName>Modifier_Product__c</fullName>
    <label>Modifier Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>D&amp;O Standalone</fullName>
                <isActive>false</isActive>
                <label>D&amp;O Standalone</label>
            </value>
            <value>
                <fullName>Test Product 00</fullName>
                <isActive>false</isActive>
                <label>Test Product 00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/EligibilityStatusQueryUtilTest.cls
/**************************************************************************************************
* Class Name: EligibilityStatusQueryUtilTest
* Author: RINKU SAINI 
* Date: 30th Dec 2021
* Description: 
**************************************************************************************************/
@isTest
public class EligibilityStatusQueryUtilTest {
    
    public static testmethod void coverfetchELStatusForServiceClassification(){
        Test.startTest();
        
        Rating_Modifier_Template__c ratingModifiersTemp = TestUtil.createRatingModifierTemplate('Service Classification', 'MPL' , 'Integer');
        insert ratingModifiersTemp;
        
        //Create Eligibility Status
        Eligibility_Status__c es = new Eligibility_Status__c();
        es.Rating_Modifier_Template__c = ratingModifiersTemp.Id;
        es.Rating_Modifier_Value__c = 'Yes';
        es.Eligibility_Status__c = 'Proceed';
        es.Modifier_Product__c = 'MPL';
        insert es;
        
        EligibilityStatusQueryUtil.fetchELStatusForServiceClassification();
        
        Test.stopTest();
    }
}