main/default/objects/Eligibility_Status__c/Eligibility_Status__c.object-meta.xml
<CustomObject>
    <label>Eligibility Status</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Eligibility Status #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligibility Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Eligibility_Status__c/fields/Eligibility_Status__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Status__c</fullName>
    <label>Eligibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Proceed</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution</fullName>
            </value>
            <value>
                <fullName>No Information</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution (consider restrictive terms, including but limited to matching/increasing retention to the largest paid loss)</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution (sub limit only)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (Unless fewer than 50 employees)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (unless Highly Compensated Separate Retention Endorsement is added)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (unless D&amp;O revenue threshold is met)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (seasonal, low wage,retail industries, etc.)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (Unless less than 100 employees)</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution and consider adding a Family Exclusion</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution and consider Major Shareholder Exclusion</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution with sub-limit</fullName>
            </value>
            <value>
                <fullName>qualified or not all locations are audited</fullName>
            </value>
            <value>
                <fullName>Prohibited Class</fullName>
            </value>
            <value>
                <fullName>Munich Referral</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard</fullName>
            </value>
            <value>
                <fullName>Stop!Decline!</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Eligibility_Status__c/fields/Modifier_Product__c.field-meta.xml
<CustomField>
    <fullName>Modifier_Product__c</fullName>
    <label>Modifier Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modifier_Product</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Eligibility_Status__c/fields/Rating_Modifier_Name__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Name__c</fullName>
    <formula>Rating_Modifier_Template__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rating Modifier Name</label>
    <type>Text</type>
</CustomField>

main/default/objects/Eligibility_Status__c/fields/Rating_Modifier_Value__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Value__c</fullName>
    <label>Rating Modifier Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/classes/EligibilityStatusQueryUtil.cls
/**************************************************************************************************
 * Class Name: EligibilityStatusQueryUtil
 * Author: 
 * Date: 27th Dec 2021
 * Description: Query util class for Account Loss Object.
 **************************************************************************************************/
public with sharing class EligibilityStatusQueryUtil{
    /*************************************************
   * Method Name: fetchELStatusForServiceClassification
   * Author:  
   * Date: 27 Dec 2021
   * Params: 
   * Return: list of Eligibility Status
   * Exceptions:
   * Revision: 
   * Description: Get Eligibility Status for 'Service Classification' Ratings Modifiers.
    *************************************************/
   public static List<Eligibility_Status__c> fetchELStatusForServiceClassification(){
       return [SELECT Id,Eligibility_Status__c,Rating_Modifier_Value__c,Modifier_Product__c 
               FROM Eligibility_Status__c WHERE Rating_Modifier_Name__c = 'Service Classification'];
   }
}