main/default/objects/Payment_Data__c/Payment_Data__c.object-meta.xml
<CustomObject>
    <label>Payment Summary</label>
    <nameField>
        <displayFormat>PD-{00000}</displayFormat>
        <label>Payment Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Payment_Data__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Payment_Data__c/fields/Due_from_Broker__c.field-meta.xml
<CustomField>
    <fullName>Due_from_Broker__c</fullName>
    <label>Due from Broker</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Payment_Data__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <label>Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Payment_Data__c/fields/IPT__c.field-meta.xml
<CustomField>
    <fullName>IPT__c</fullName>
    <label>IPT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Payment_Data__c/fields/Paid_Status__c.field-meta.xml
<CustomField>
    <fullName>Paid_Status__c</fullName>
    <label>Paid Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Not Paid</fullName>
            </value>
            <value>
                <fullName>No Payment Required</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Payment_Data__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Payments Summary</relationshipLabel>
    <relationshipName>Payments_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Payment_Data__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Payment_Data__c/fields/Producing_Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Producing_Brokerage__c</fullName>
    <label>Producing Brokerage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Payment_Data__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Payments Data</relationshipLabel>
    <relationshipName>Payments_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Payment_Data__c/fields/Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type__c</fullName>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Reinstatement</fullName>
            </value>
            <value>
                <fullName>Midterm Cancellation</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Full Amendment</fullName>
            </value>
            <value>
                <fullName>Coverage Amendment</fullName>
            </value>
            <value>
                <fullName>Insured Account Update</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation (Ab - Initio)</fullName>
            </value>
            <value>
                <fullName>Correction</fullName>
            </value>
            <value>
                <fullName>Coverage Cancel and Replace</fullName>
            </value>
            <value>
                <fullName>Policy Duration Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Payment_Data__c/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <label>Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/classes/PaymentDataTriggerHandler.cls
public class PaymentDataTriggerHandler extends TriggerHandler{

    private List<Payment_Data__c> oldDataList;
    private List<Payment_Data__c> newDataList;
    private Map<Id, Payment_Data__c> newDataMap;
    private Map<Id, Payment_Data__c> oldDataMap;
    
    public PaymentDataTriggerHandler() {
        this.oldDataList = (List<Payment_Data__c>) Trigger.old;
        this.oldDataMap = (Map<Id, Payment_Data__c>) Trigger.oldMap;
        
        this.newDataList = (List<Payment_Data__c>) Trigger.new;
        this.newDataMap = (Map<Id, Payment_Data__c>) Trigger.newMap;
    }

    public override void beforeInsert(){}

    public override void beforeUpdate(){
        updateLastModifiedDate(oldDataList ,newDataList );
    }

    public override void afterInsert(){}

    public override void afterUpdate(){
        
    }

    public static void updateLastModifiedDate(List<Payment_Data__c> oldDataList , List<Payment_Data__c> newDataList )
    {
            List<Payment_Data__c> listPayment = new List<Payment_Data__c>();
            List<Payment_Data__c> listPaymentToUpdate = new List<Payment_Data__c>();
            Datetime now = Datetime.now();
            Integer offset = UserInfo.getTimezone().getOffset(now);
            Datetime local = now.addSeconds(offset/1000);
           for(Payment_Data__c newPaymentData : newDataList) 
           {
            for(Payment_Data__c oldPaymentData : oldDataList){
                    if(newPaymentData.CurrencyIsoCode != oldPaymentData.CurrencyIsoCode || 
                        newPaymentData.OwnerId != oldPaymentData.OwnerId ||
                        newPaymentData.Quote_Type__c != oldPaymentData.Quote_Type__c ||
                        newPaymentData.Reference_Number__c != oldPaymentData.Reference_Number__c ||
                        newPaymentData.Premium__c != oldPaymentData.Premium__c ||
                        newPaymentData.IPT__c != oldPaymentData.IPT__c ||
                        newPaymentData.Fee__c != oldPaymentData.Fee__c ||
                        newPaymentData.Producing_Brokerage__c != oldPaymentData.Producing_Brokerage__c ||
                        newPaymentData.Due_from_Broker__c != oldPaymentData.Due_from_Broker__c ||
                        newPaymentData.Amount_Paid__c != oldPaymentData.Amount_Paid__c ||
                        newPaymentData.Paid_Status__c != oldPaymentData.Paid_Status__c ||
                        newPaymentData.Due_Date__c != oldPaymentData.Due_Date__c ||
                        newPaymentData.Policy__c != oldPaymentData.Policy__c ||
                        newPaymentData.Quote__c != oldPaymentData.Quote__c ){
                            //newPaymentData.Last_Modified_Date__c = Date.Today().format();
                            newPaymentData.Last_Modified_Date__c = System.now();
                            listPaymentToUpdate.add(newPaymentData);
                            system.debug('Date.Today();-------'+Date.Today());
                           
                        }
            }
                        system.debug('listPaymentToUpdate-------'+listPaymentToUpdate);
                        system.debug('Date.Today();-------'+Date.Today());
                        system.debug('newPaymentData.Last_Modified_Date__c-----'+newPaymentData.Last_Modified_Date__c);
                        system.debug('newPaymentData.Fee__c-----'+newPaymentData.Fee__c);
           }

         //  if(listPaymentToUpdate.size() > 0 ) update listPaymentToUpdate;
    }
    
}