main/default/objects/Quote_Option__c/Quote_Option__c.object-meta.xml
<CustomObject>
    <label>Quote Option</label>
    <nameField>
        <displayFormat>QO-{000000}</displayFormat>
        <label>Quote Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Quote_Option__c/fields/Option_Type__c.field-meta.xml
<CustomField>
    <fullName>Option_Type__c</fullName>
    <label>Option Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Limit</fullName>
            </value>
            <value>
                <fullName>Free Form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Quote_Option__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Options</relationshipLabel>
    <relationshipName>Quote_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Quote_Option__c/fields/Selected__c.field-meta.xml
<CustomField>
    <fullName>Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selected for Quote</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Referral_Reason__c/Referral_Reason__c.object-meta.xml
<CustomObject>
    <label>Referral Reason</label>
    <nameField>
        <label>Reason Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Reasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Referral_Reason__c/fields/Approval_Level_Required__c.field-meta.xml
<CustomField>
    <fullName>Approval_Level_Required__c</fullName>
    <label>Approval Level Required</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Approval_Rejected_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rejected_Date__c</fullName>
    <label>Approval/Rejected Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Approved_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approved By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Referral_Reasons</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Approver_Level__c.field-meta.xml
<CustomField>
    <fullName>Approver_Level__c</fullName>
    <label>Approver Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Entity_Path__c.field-meta.xml
<CustomField>
    <fullName>Entity_Path__c</fullName>
    <label>Entity Path</label>
    <length>512</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Option_Id__c.field-meta.xml
<CustomField>
    <fullName>Option_Id__c</fullName>
    <label>Option Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Option_Limit__c.field-meta.xml
<CustomField>
    <fullName>Option_Limit__c</fullName>
    <formula>Quote_Option__r.Limit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Option Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Option_Type__c.field-meta.xml
<CustomField>
    <fullName>Option_Type__c</fullName>
    <formula>TEXT(Quote_Option__r.Option_Type__c)</formula>
    <label>Option Type</label>
    <type>Text</type>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Referral Reasons</relationshipLabel>
    <relationshipName>Referral_Reasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Quote_Option__c.field-meta.xml
<CustomField>
    <fullName>Quote_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Option</label>
    <referenceTo>Quote_Option__c</referenceTo>
    <relationshipLabel>Referral Reasons</relationshipLabel>
    <relationshipName>Referral_Reasons</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <length>512</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Reason_Type__c.field-meta.xml
<CustomField>
    <fullName>Reason_Type__c</fullName>
    <label>Reason Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refer</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Referral_Reason__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Refer</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/ReferralReasonQueryUtil.cls
/**************************************************************************************************
 * Class Name: ReferralReasonQueryUtil
 * Author: 
 * Date: Jan 3, 2021
 * Description: Class to keep Referral Reason queries
 * Test Class : ReferralReasonQueryUtilTest
 **************************************************************************************************/
public with sharing class ReferralReasonQueryUtil {
    /*************************************************
    * Method Name: fetchRefReasonsByQuoteId
    * Author: 
    * Date: 22 Dec 2021
    * Params: Id quoteId
    * Return: List<Referral_Reason__c> 
    * Exceptions:
    * Revision: 
    * Description: Fetch Referral Reasons
     *************************************************/
    public static List<Referral_Reason__c> fetchRefReasonsByQuoteId(Id quoteId){
        return [SELECT Id,Name,Approval_Level_Required__c,Approval_Status__c,
                Approval_Rejected_Date__c,Approver_Level__c,Approved_By__c,Option_Id__c,
                Entity_Path__c,Reason__c,Reason_Type__c,Status__c,Approved_By__r.Name,
                Quote_Option__c,Quote_Option__r.Selected__c,Option_Type__c,Option_Limit__c 
                From Referral_Reason__c                                                               
                Where Quote__c=:quoteId];
    }

}