main/default/objects/Product_Option_Line_Item__c/Product_Option_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Product Option Line Item</label>
    <nameField>
        <displayFormat>POLI-{0000}</displayFormat>
        <label>Product  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Option Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Product_Option_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Option Line Items</relationshipLabel>
    <relationshipName>Product_Option_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Product_Option_Line_Item__c/fields/Clearance_Status__c.field-meta.xml
<CustomField>
    <fullName>Clearance_Status__c</fullName>
    <label>Clearance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Closed Market</fullName>
            </value>
            <value>
                <fullName>Clearance Not Applicable</fullName>
            </value>
            <value>
                <fullName>Service failed</fullName>
            </value>
            <value>
                <fullName>Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Product_Option_Line_Item__c/fields/Is_Selected__c.field-meta.xml
<CustomField>
    <fullName>Is_Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selected</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Product_Option_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Option Line Items</relationshipLabel>
    <relationshipName>Product_Option_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Product_Option_Line_Item__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Product Option Line Items</relationshipLabel>
    <relationshipName>Product_Option_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Quote_Process__c/Quote_Process__c.object-meta.xml
<CustomObject>
    <label>Underwriter Workbench</label>
    <nameField>
        <label>Quote Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Underwriter Workbench</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Quote_Process__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quote_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Quote_Process__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insured Info</fullName>
                <default>true</default>
                <label>Insured Info</label>
            </value>
            <value>
                <fullName>Submission Console</fullName>
            </value>
            <value>
                <fullName>Underwriting Console</fullName>
            </value>
            <value>
                <fullName>Submission Info</fullName>
            </value>
            <value>
                <fullName>Underwritting Analysis</fullName>
                <label>Underwriting Analysis</label>
            </value>
            <value>
                <fullName>Compare &amp; Rate Quotes</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Quote Console</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
                <isActive>false</isActive>
                <label>Closed Lost</label>
            </value>
            <value>
                <fullName>Closed Won</fullName>
                <isActive>false</isActive>
                <label>Closed Won</label>
            </value>
            <value>
                <fullName>Pre-Screening</fullName>
                <isActive>false</isActive>
                <label>Pre-Screening</label>
            </value>
            <value>
                <fullName>Quote Version Console</fullName>
                <isActive>false</isActive>
                <label>Quote Version Console</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Quote_Process__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submission</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Underwriter Workbench</relationshipLabel>
    <relationshipName>Quote_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/Rating_Modifier_Template__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier Template</label>
    <nameField>
        <label>Rating Modifier Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifier Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifier_Template__c/fields/Display_Format__c.field-meta.xml
<CustomField>
    <fullName>Display_Format__c</fullName>
    <label>Display Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Factor Values Only</fullName>
            </value>
            <value>
                <fullName>Secondary Modifiers</fullName>
            </value>
            <value>
                <fullName>Primary Modifiers</fullName>
            </value>
            <value>
                <fullName>Eligibility</fullName>
            </value>
            <value>
                <fullName>Pros and Cons</fullName>
            </value>
            <value>
                <fullName>Default Only</fullName>
            </value>
            <value>
                <fullName>Primary Clearance PCC</fullName>
            </value>
            <value>
                <fullName>Clearance</fullName>
            </value>
            <value>
                <fullName>Modifier and Factor Values</fullName>
                <isActive>false</isActive>
                <label>Modifier and Factor Values</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Page_Section__c.field-meta.xml
<CustomField>
    <fullName>Page_Section__c</fullName>
    <label>Page Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Rating_Modifier_Code__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Code__c</fullName>
    <externalId>true</externalId>
    <label>Rating Modifier Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/classes/QuoteProcessControllerTest.cls
/**
 * @description       : 
 * @author            : Vinayesh
 * @group             : 
 * @last modified on  : 02-21-2022
 * @last modified by  : Vinayesh
**/
@isTest
public class QuoteProcessControllerTest {
    @testSetup static void setup(){
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        insert acc;
        
        Product2 product = TestUtil.createProduct('D&O Standalone');
        insert product; 
        
        Product2 product5 = TestUtil.createProduct('Private Company Combo');
        insert product5;
        
        Product2 product1 = TestUtil.createProduct('D&O');
        product1.Parent_Product__c = product.Id;
        product1.IsComboProduct__c = true;
        insert product1;

        Product2 product2 = TestUtil.createProduct('EPL');
        product2.Parent_Product__c = product.Id;
        product2.IsComboProduct__c = true;
        insert product2;

        Product2 product3 = TestUtil.createProduct('Crime');
        product3.Parent_Product__c = product.Id;
        product3.IsComboProduct__c = true;
        insert product3;

        Product2 product4 = TestUtil.createProduct('Fiduciary');
        product4.Parent_Product__c = product.Id;
        product4.IsComboProduct__c = true;
        insert product4;
        
        List<Rating_Modifier_Template__c> lRMT = new List<Rating_Modifier_Template__c>();
        Rating_Modifier_Template__c rMT1 = TestUtil.createRatingModifierTemplate('Test Service Classification','D&O','Number');
        rMT1.Display_Format__c = 'Clearance';
        rMT1.Rating_Modifier_Code__c = 'PSDO00000121212';
        rMT1.Page_Section__c = 'Test';
        lRMT.add(rMT1);
        Rating_Modifier_Template__c rMT2 = TestUtil.createRatingModifierTemplate('New input integer','D&O','Integer');
        rMT2.Display_Format__c = 'Clearance';
        rMT2.Rating_Modifier_Code__c = 'PSFID000005989890';
        rMT2.Page_Section__c = 'Test';
        lRMT.add(rMT2);
        Rating_Modifier_Template__c rMT3 = TestUtil.createRatingModifierTemplate('New input integer','D&O','Integer');
        rMT3.Display_Format__c = 'Clearance';
        rMT3.Rating_Modifier_Code__c = 'PSEPL000005232421';
        rMT3.Page_Section__c = 'Test';
        lRMT.add(rMT3);
        Rating_Modifier_Template__c rMT4 = TestUtil.createRatingModifierTemplate('New input integer','EPL','Integer');
        rMT4.Display_Format__c = 'Clearance';
        rMT4.Page_Section__c = 'Test';
        lRMT.add(rMT4);
        // Rating_Modifier_Template__c rMT5 = TestUtil.createRatingModifierTemplate(Label.NATURE_OF_INDUSTRY_OR_SECTOR,'Crime','Number');
        // rMT5.Display_Format__c = 'Clearance';
        // lRMT.add(rMT5);
        Rating_Modifier_Template__c rMT6 = TestUtil.createRatingModifierTemplate(Label.ANNUAL_REVENUES,'Fiduciary','Number');
        rMT6.Display_Format__c = 'Clearance';
        rMT6.Page_Section__c = 'Test';
        Rating_Modifier_Template__c rMT7 = TestUtil.createRatingModifierTemplate('Test D&O','D&O','Number');
        rMT7.Display_Format__c = 'Clearance';
        rMT7.Rating_Modifier_Code__c = 'PSEPL000005232422';
        rMT7.Page_Section__c = 'Test';
        lRMT.add(rMT7);
        
        insert lRMT;



        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.CloseDate = Date.today();
        opp.StageName = 'Prospect';
        insert opp;

        Product_Option_Line_Item__c newRec = new Product_Option_Line_Item__c();
        newRec.Product__c = product1.Id;
        newRec.Submission__c = opp.Id;
        newRec.Account__c = acc.Id;
        newRec.Clearance_Status__c = 'Cleared';
        newRec.Is_Selected__c = true;
        insert newRec;
        
        Quote quote1 = TestUtil.createQuote('New quote 1', opp.Id);
        quote1.Status = 'In Progress';
        quote1.Coverage_Product_Options__c = 'D&O';
        quote1.Refer_Type__c = 'Underwriting Referral';
        insert quote1;  
        
        Quote_Process__c quoteProc = new Quote_Process__c();
        quoteProc.Name = 'Test Process';
        quoteProc.Account__c = acc.Id;
        quoteProc.Submission__c = opp.Id;
        quoteProc.Status__c = 'Insured Info';
        insert quoteProc;
    }
    

    @isTest
    static void getRecordInfosFromQuoteProcessTest(){
        Test.startTest();
        QuoteProcessController.getSingleQuoteProcess();
        Quote_Process__c q = [Select Id,Name from Quote_Process__c where Name ='Test Process' Limit 1];
        QuoteProcessController.getRecordInfos(q.Id);
        system.assertEquals('Test Process', q.Name);
        Test.stopTest();
    }
    @isTest
    static void getRecordInfosFromOpportunityTest(){
        Test.startTest();
        Opportunity opp = [Select Id,StageName
                           from Opportunity where StageName = 'Prospect' Limit 1];
        QuoteProcessController.getRecordInfos(opp.Id);
        system.assertEquals('Prospect', opp.StageName);
        Test.stopTest();
    }
    @isTest
    static void createSubmissionTest(){
        Test.startTest();
        Account acc = [Select Id from Account Limit 1];
        Quote_Process__c q = [Select Id,Name from Quote_Process__c where Name ='Test Process' Limit 1];
        QuoteProcessController.createSubmission(q.Id, acc.Id );
        system.assertEquals('Test Process', q.Name);
        Test.stopTest();
    }
    @isTEst 
    static void checkExistQuoteStatusBoundOrBoundPendingTest(){
        Opportunity  opp = [Select Name from Opportunity Limit 1];
        
        Test.startTest();
        Boolean bool = QuoteProcessController.checkExistQuoteStatusBoundOrBoundPending(opp.Id);
    	test.stopTest();
        system.assertEquals(true, bool);
    }

    @isTEst 
    static void checkRatingModifiersValidityForOppTest(){
        Opportunity  opp = [Select Name from Opportunity Limit 1];
        
        Test.startTest();
        Boolean bool = QuoteProcessController.checkRatingModifiersValidityForOpp(opp.Id);
    	test.stopTest();
        system.assertEquals(false, bool);
    }

    @isTEst 
    static void updateAllQuoteToInProgressTest(){
        Opportunity  opp = [Select Name from Opportunity Limit 1];
        Quote quo =  [SELECT Id, Name, Status, Rating_Status__c, Last_Quote_Version__c
											FROM Quote
											WHERE OpportunityId =:opp.Id Limit 1];
        quo.Status ='Rated';
        update quo;
        
        Test.startTest();
        QuoteProcessController.updateAllQuoteToInProgress(opp.Id);
        system.assertEquals('Rated', quo.Status);
    	test.stopTest();
        
    }

     @isTest
    static void ItemWrapperTest2(){
        Test.startTest();
        QuoteProcessController.ItemWrapper Iw = new QuoteProcessController.ItemWrapper();
        Iw.Name='Name';
        system.assert(Iw!=null);
        Test.stopTest();
    }
}