main/default/objects/Product_Option_Line_Item__c/Product_Option_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Product Option Line Item</label>
    <nameField>
        <displayFormat>POLI-{0000}</displayFormat>
        <label>Product  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Option Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Product_Option_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Option Line Items</relationshipLabel>
    <relationshipName>Product_Option_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Product_Option_Line_Item__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Product Option Line Items</relationshipLabel>
    <relationshipName>Product_Option_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/ProductOptionLineItemQueryUtil.cls
/**************************************************************************************************
 * Class Name: ProductOptionLineItemQueryUtil
 * Author: Vinay
 * Date: Dec 22nd, 2021
 * Description: Class to keep product option line item queries
 * Test Class : ProductOptionLineItemQueryUtilTest
 **************************************************************************************************/
public with sharing class ProductOptionLineItemQueryUtil {
    /*************************************************
    * Method Name: fetchPOLIByProdsAndOpps
    * Author: Vinay Vernekar
    * Date: 22nd Dec 2021
    * Params: opportunity ids and product ids
    * Return: list of product option line items
    * Exceptions:
    * Revision: 
    * Description: Fetch product option line items by opportunity ids and product ids
     *************************************************/
    public static List<Product_Option_Line_Item__c> fetchPOLIByProdsAndOpps(Set<Id> opportunityIds, Set<Id> productIds){
        return [Select Submission__c, Product__c, Product__r.Name From Product_Option_Line_Item__c Where Submission__c In :opportunityIds And Product__c In :productIds];
    }

    /*************************************************
    * Method Name: fetchPOLIByOpps
    * Author: Jai
    * Date: Jan 11 2022
    * Params: opportunity ids and fields to query
    * Return: list of product option line items
    * Exceptions:
    * Revision: 
    * Description: Fetch product option line items by opportunity ids and product ids
     *************************************************/
    public static List<Product_Option_Line_Item__c> fetchPOLIByOpps(Set<String> opportunityIds, String fields ){
        String queryStr = 'Select '+fields+' From Product_Option_Line_Item__c where Submission__c IN :opportunityIds';
        return (List<Product_Option_Line_Item__c>) database.query(queryStr);
    }

}