main/default/objects/Agency_License__c/Agency_License__c.object-meta.xml
<CustomObject>
    <label>Agency License</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Agency License Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agency Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Agency_License__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agency Licenses</relationshipLabel>
    <relationshipName>Agency_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Agency_License__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <label>License Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Agency_License__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Surplus Lines</fullName>
            </value>
            <value>
                <fullName>Admitted Lines</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Agency_License__c/fields/NIPR_License_Status__c.field-meta.xml
<CustomField>
    <fullName>NIPR_License_Status__c</fullName>
    <label>NIPR License Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Agency_License__c/fields/NPN__c.field-meta.xml
<CustomField>
    <fullName>NPN__c</fullName>
    <label>NPN (National producer number)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Broker_Account__c/Broker_Account__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Broker_Account__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Broker_Contact__r.AccountId ,  Broker_Contact__r.Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <label>Broker Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker_Contact</value>
        </filterItems>
        <infoMessage>You Must Select a Broker Contact</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Broker_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/IsPrimaryBroker__c.field-meta.xml
<CustomField>
    <fullName>IsPrimaryBroker__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary Broker?</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Broker Accounts</relationshipLabel>
    <relationshipName>Opportunity_Accounts1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_License__c/Broker_License__c.object-meta.xml
<CustomObject>
    <label>Broker License</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Broker License Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Broker_License__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker_Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Broker Licenses</relationshipLabel>
    <relationshipName>Broker_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Broker_License__c/fields/License_State__c.field-meta.xml
<CustomField>
    <fullName>License_State__c</fullName>
    <label>License State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Codes</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Broker_License__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Surplus Lines</fullName>
            </value>
            <value>
                <fullName>Limited Lines</fullName>
            </value>
            <value>
                <fullName>Admitted Lines</fullName>
            </value>
            <value>
                <fullName>Admitted</fullName>
                <isActive>false</isActive>
                <label>Admitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Broker_License__c/fields/NPN__c.field-meta.xml
<CustomField>
    <fullName>NPN__c</fullName>
    <description>This is returned from the NIPR api call</description>
    <label>NPN (National producer number)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Binding_License_Number__c.field-meta.xml
<CustomField>
    <fullName>Binding_License_Number__c</fullName>
    <label>Binding License Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Policy__c/fields/Binding_License_Owner__c.field-meta.xml
<CustomField>
    <fullName>Binding_License_Owner__c</fullName>
    <label>Binding License Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Producer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Binding_License_Owner_Address__c.field-meta.xml
<CustomField>
    <fullName>Binding_License_Owner_Address__c</fullName>
    <label>Binding License Owner Address</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Policy__c/fields/Binding_License_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Binding_License_Owner_Name__c</fullName>
    <label>Binding License Owner Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Policy__c/fields/Is_Signature_Pack_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Is_Signature_Pack_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Signature Pack Uploaded</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Policy__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>D_O</fullName>
                <label>D&amp;O</label>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/UpdateLicenseInfoOnPolicy.cls
/**************************************************************************************************
 * Class Name: UpdateLicenseInfoOnPolicy
 * Author: Jai Singh
 * Date: 22-12-2021 
 * Description: Update broker details.
 **************************************************************************************************/
public with sharing class UpdateLicenseInfoOnPolicy {
    public UpdateLicenseInfoOnPolicy() {

    }

    /*************************************************
    * Method Name: getBrokerDetail
    * Author: Jai Singh
    * Date: 22-12-2021
    * Params: 
    * Return: 
    * Exceptions:
    * Description: Returning Data of Policy,Opportunity,Quote,Broker Account, Agency License and Broker License USing Wrapper Class.
    * Revision: 
     *************************************************/
    @AuraEnabled
    public static LicenseInfoWrapper getBrokerDetail(String recId ) {
        LicenseInfoWrapper liwObj = new LicenseInfoWrapper();
        system.debug(recId);
        Id recordId = recId;
        Id opportunityId = null;

        if( recordId.getSObjectType() == Schema.Quote.SObjectType ){
            Set<Id> qIdSet = new set<Id> {recId};
            list<Quote> qList = QuoteQueryUtil.fetchQuotesForQuoteIds(qIdSet, 'OpportunityId, Product_Name__c' );
            if( !qList.isEmpty()  ){
                liwObj.q = qList[0];
                opportunityId = qList[0].OpportunityId;
            }
        }else if( recordId.getSObjectType() == Schema.Policy__c.SObjectType ){
            Policy__c p = [Select Id, Product_Name__c,(Select Id from Submissions__r limit 1) from Policy__c where Id = :recordId ];
            liwObj.p = p;
            if( p.Submissions__r.size() > 0 ){
                opportunityId = p.Submissions__r[0].Id;
            }
        }
        if( opportunityId != null  ){
            
            list<Opportunity> oppList = [Select Id, AccountId, Account.BillingState, Account.BillingStateCode,RecordType.Name,
                                        ( Select Id, Broker_Contact__c, Broker_Contact__r.AccountId from Opportunity_Accounts1__r where IsPrimaryBroker__c = true )
                                        FROM Opportunity 
                                        WHERE
                                        Id = :opportunityId
                                        ];
            if( !oppList.isEmpty() && oppList[0].Opportunity_Accounts1__r.size() > 0 ){
                liwObj.opp = oppList[0];
                liwObj.ba = oppList[0].Opportunity_Accounts1__r[0];
                if( oppList[0].Opportunity_Accounts1__r[0].Broker_Contact__r.AccountId != null ){
                    list<Agency_License__c> alList = [ Select Id, Agency__c,Agency__r.Name, License_Number__c, License_State__c, License_Type__c, NIPR_License_Status__c, RecordType.Name, NPN__c,
                                                        Agency__r.BillingStreet, Agency__r.BillingCity, Agency__r.BillingState, Agency__r.BillingPostalCode
                                                        FROM Agency_License__c
                                                        where Agency__c =: oppList[0].Opportunity_Accounts1__r[0].Broker_Contact__r.AccountId AND
                                                        License_State__c = :oppList[0].Account.BillingStateCode
                                                    ];
                    liwObj.alList = alList;
                }
                list<Broker_License__c> blList = [ Select Id, Broker__c,Broker__r.Name, License_Number__c, License_State__c, License_Type__c, RecordType.Name, NPN__c, 
                                                Broker__r.Account.Name, Broker__r.Account.BillingStreet, Broker__r.Account.BillingCity, Broker__r.Account.BillingState, Broker__r.Account.BillingPostalCode
                                                FROM Broker_License__c
                                                where Broker__c =: oppList[0].Opportunity_Accounts1__r[0].Broker_Contact__c AND
                                                License_State__c = :oppList[0].Account.BillingStateCode
                                                ];
                liwObj.blList = blList;
                 
            }
        }
        system.debug(liwObj);
        return liwObj;

    }

    /*************************************************
    * Method Name: updatePolicyBLInfo
    * Author: Jai Singh
    * Date: 
    * Params: 
    * Return: 
    * Exceptions:
    * Description: Update Policy.
    * Revision: 
     *************************************************/
    @AuraEnabled
    public static void updatePolicyBLInfo(Id policyId, String blInfo){
        system.debug(blInfo);
        if(String.isNotBlank(blInfo)){
        BindingLicenseInfo blObj = (BindingLicenseInfo)JSON.deserialize(blInfo, BindingLicenseInfo.class );
        
        TriggerHandler.bypass('PolicyTriggerBaseHandler');       
        
        update new Policy__c(
            Id = policyId,
            Binding_License_Number__c = blObj.bindingLicenseNumber,
            Binding_License_Owner__c = blObj.bindingLicenseOwner,
            Binding_License_Owner_Address__c = blObj.bindingLicenseOwnerAddress ,
            Binding_License_Owner_Name__c = blObj.bindingLicenseOwnerName
            //Is_Signature_Pack_Uploaded__c = blObj.IsSignaturePackUploaded
        );   
        TriggerHandler.clearBypass('PolicyTriggerBaseHandler');
        }
    }

   public class LicenseInfoWrapper{
        @AuraEnabled
        public Opportunity opp;
        @AuraEnabled
        public Quote q;
        @AuraEnabled
        public Policy__c p;
        @AuraEnabled
        public Broker_Account__c ba;
        @AuraEnabled
        public list<Agency_License__c> alList ;
        @AuraEnabled
        public list<Broker_License__c> blList;

    }

    public class BindingLicenseInfo{
        @AuraEnabled
        public string bindingLicenseOwner;
        @AuraEnabled
        public string bindingLicenseOwnerName;                
        @AuraEnabled
        public string bindingLicenseNumber;
        @AuraEnabled
        public string bindingLicenseOwnerAddress;
        @AuraEnabled
        public Boolean IsSignaturePackUploaded;
        @AuraEnabled
        public string productName;
        @AuraEnabled
        public string oppRecordType;


    }
}