main/default/objects/Agency_License__c/Agency_License__c.object-meta.xml
<CustomObject>
    <label>Agency License</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Agency License Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agency Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Agency_License__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agency Licenses</relationshipLabel>
    <relationshipName>Agency_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Agency_License__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Surplus Lines</fullName>
            </value>
            <value>
                <fullName>Admitted Lines</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Agency_License__c/fields/MRe_Appointment_Status__c.field-meta.xml
<CustomField>
    <fullName>MRe_Appointment_Status__c</fullName>
    <label>MRe Appointment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Appointed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Agency_License__c/recordTypes/MRe_Appointment.recordType-meta.xml
<RecordType>
    <fullName>MRe_Appointment</fullName>
    <active>true</active>
    <label>MRe Appointment</label>
</RecordType>

main/default/classes/AgencyLicenseQueryUtil.cls
/**************************************************************************************************
 * Class Name: AgencyLicenseQueryUtil
 * Author: 
 * Date: Jan 3, 2021
 * Description: Class to keep Agency License queries
 * Test Class : AgencyLicenseQueryUtilTest
 **************************************************************************************************/
public with sharing class AgencyLicenseQueryUtil {
    
    /*************************************************
    * Method Name: fetchLicenseByAgencyId
    * Author: 
    * Date: 22 Dec 2021
    * Params: Id agencyId, String insuredState
    * Return: Contact
    * Exceptions:
    * Revision: 
    * Description: Fetch agency License
     *************************************************/
    public static List<Agency_License__c> fetchLicenseByAgencyId(Id agencyId, String insuredState){
        return [SELECT Id
                FROM Agency_License__c 
                WHERE Agency__c =: agencyId 
                AND License_Type__c = 'Admitted Lines' 
                AND RecordType.DeveloperName = 'MRe_Appointment'
                AND License_State__c=:insuredState
                AND MRe_Appointment_Status__c = 'Appointed'
                LIMIT 1];
    }

}