main/default/objects/Factor_Summary__c/Factor_Summary__c.object-meta.xml
<CustomObject>
    <label>Factor Summary</label>
    <nameField>
        <displayFormat>FS-{00000}</displayFormat>
        <label>Factor Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factor Summarys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Factor_Summary__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Factor Summarys</relationshipLabel>
    <relationshipName>Factor_Summary_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Factor_Summary__c/fields/Quote_Option__c.field-meta.xml
<CustomField>
    <fullName>Quote_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Option</label>
    <referenceTo>Quote_Option__c</referenceTo>
    <relationshipLabel>Factor_Summarys</relationshipLabel>
    <relationshipName>Factor_Summary_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Bound Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Quote_Option__c/Quote_Option__c.object-meta.xml
<CustomObject>
    <label>Quote Option</label>
    <nameField>
        <displayFormat>QO-{000000}</displayFormat>
        <label>Quote Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Quote_Option__c/fields/Bound__c.field-meta.xml
<CustomField>
    <fullName>Bound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selected for Bound</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Quote_Option__c/fields/Netted_Down_Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Netted_Down_Commission_Amount__c</fullName>
    <label>Netted Down Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Quote_Option__c/fields/Netted_Down_Commission_Percent__c.field-meta.xml
<CustomField>
    <fullName>Netted_Down_Commission_Percent__c</fullName>
    <label>Netted Down Commission Percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Quote_Option__c/fields/Netted_Down_MGA_Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Netted_Down_MGA_Commission_Amount__c</fullName>
    <label>Netted Down MGA Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Quote_Option__c/fields/Netted_Down_MGA_Commission_Percent__c.field-meta.xml
<CustomField>
    <fullName>Netted_Down_MGA_Commission_Percent__c</fullName>
    <label>Netted Down MGA Commission Percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Quote_Option__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Options</relationshipLabel>
    <relationshipName>Quote_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Quote_Option__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Quote_Option__c/fields/Rate_Change__c.field-meta.xml
<CustomField>
    <fullName>Rate_Change__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate Change</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Quote_Option__c/fields/Tax_Percent__c.field-meta.xml
<CustomField>
    <fullName>Tax_Percent__c</fullName>
    <label>Tax Percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/QuoteOptionTriggerHandlerTest.cls
@isTest
public class QuoteOptionTriggerHandlerTest {
    
    @testSetup
    public static void testSetup(){
        
        TriggerSettings__c triggerSettingsObj = new TriggerSettings__c();
        triggerSettingsObj.BypassQuoteTrigger__c = true;
        insert triggerSettingsObj;
        
        Account accountObj = TestUtil.createBusinessAccount('Test Bussiness Account', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        insert accountObj;
        
        Product2 productObj = TestUtil.createProduct('D&O Standalone');
        insert productObj; 
        
        Opportunity opportunityObj = TestUtil.createOpportunity('Test Opportunity',accountObj.Id, productObj.Id);
        opportunityObj.CloseDate = Date.today();
        opportunityObj.StageName = 'Closed Won';
        opportunityObj.Expiration_Date__c = Date.today()+60;
        insert opportunityObj;
        
        Policy__c policyObj = new Policy__c();
        policyObj.Policy_Number__c = '12345';
        policyObj.Effective_Date__c = Date.today()+5;
        policyObj.Expiration_Date__c = Date.today() + 30;
        policyObj.Policy_Status__c = 'Bound';
        insert policyObj;
        
        Quote quoteObj = TestUtil.createQuote('TestQuote', opportunityObj.Id);
        quoteObj.Status = 'In Progress';
        quoteObj.Coverage_Product_Options__c = 'D&O';
        quoteObj.Refer_Type__c = 'Underwriting Referral';
        quoteObj.Rating_Status__c = 'Refer';
        quoteObj.Last_Quote_Version__c = 'Version 1';
        quoteObj.Policy__c = policyObj.id;
        quoteObj.CloseDate__c = Date.today() + 120;
        insert quoteObj;
        
        List<Quote_Option__c> lstQuoteOptions = new List<Quote_Option__c>();
        Quote_Option__c objQO1 = new Quote_Option__c();
        objQO1.Quote__c = quoteObj.Id;
        objQO1.Bound__c = true;
        objQO1.Tax_Percent__c = 10;
        lstQuoteOptions.add(objQO1);
        Quote_Option__c objQO2 = new Quote_Option__c();
        objQO2.Quote__c = quoteObj.Id;
        objQO2.Bound__c = false;
        objQO2.Netted_Down_Commission_Percent__c = 20;
        objQO2.Tax_Percent__c = 20;
        lstQuoteOptions.add(objQO2);        
        Quote_Option__c objQO3 = new Quote_Option__c();
        objQO3.Quote__c = quoteObj.Id;
        objQO3.Bound__c = false;
        objQO3.Tax_Percent__c = 30;
        lstQuoteOptions.add(objQO3);
        insert lstQuoteOptions;       
                
    }
    
    @isTest
    public static void runTest(){
        
        Quote_Option__c objQO1 = [SELECT Id, Bound__c FROM Quote_Option__c WHERE Tax_Percent__c = 10];
        System.assertEquals(true, objQO1.Bound__c);
        Quote_Option__c objQO2 = [SELECT Id, Bound__c, Netted_Down_Commission_Percent__c FROM Quote_Option__c WHERE Tax_Percent__c = 20];
        System.assertEquals(false, objQO2.Bound__c);
        
        Quote quoteObj = [Select Id,Status From Quote Where Name = 'TestQuote'];
        
        Test.startTest();
        objQO2.Bound__c = true;
        objQO2.Netted_Down_Commission_Percent__c = 30;
        update objQO2; 
        quoteObj.Status = 'Bound';
        Update quoteObj;
        Test.stopTest();
        
        Quote_Option__c objQO3 = [SELECT Id,Quote__c, Bound__c,Rate__c,Rate_Change__c,Netted_Down_Commission_Amount__c,Netted_Down_Commission_Percent__c,Netted_Down_MGA_Commission_Percent__c,Netted_Down_MGA_Commission_Amount__c FROM Quote_Option__c WHERE Tax_Percent__c = 10];
        
        
        Factor_Summary__c factSumm2 = new Factor_Summary__c();
        factSumm2.Code__c = 'Netted Down Premium Broker Commission Sum';
        factSumm2.Quote__c = objQO3.Quote__c;
        factSumm2.Quote_Option__c = objQO3.Id;
        insert factSumm2;
        
        Factor_Summary__c factSumm1 = new Factor_Summary__c();
        factSumm1.Code__c = 'Netted Down Premium MGA Commission Percent';
        factSumm1.Quote__c = objQO3.Quote__c;
        factSumm1.Quote_Option__c = objQO3.Id;
        insert factSumm1;
        
        Factor_Summary__c factSumm3 = new Factor_Summary__c();
        factSumm3.Code__c = 'Netted Down Premium MGA Commission Sum';
        factSumm3.Quote__c = objQO3.Quote__c;
        factSumm3.Quote_Option__c = objQO3.Id;
        insert factSumm3;
        
        Factor_Summary__c factSumm4 = new Factor_Summary__c();
        factSumm4.Code__c = 'Rate';
        factSumm4.Quote__c = objQO3.Quote__c;
        factSumm4.Quote_Option__c = objQO3.Id;
        insert factSumm4;
        
        Factor_Summary__c factSumm5 = new Factor_Summary__c();
        factSumm5.Code__c = 'Rate Change';
        factSumm5.Quote__c = objQO3.Quote__c;
        factSumm5.Quote_Option__c = objQO3.Id;
        insert factSumm5;
        
        System.assertEquals(false, objQO3.Bound__c);           
        Quote_Option__c objQO4 = [SELECT Id, Bound__c, Quote__c, Netted_Down_Commission_Percent__c FROM Quote_Option__c WHERE Tax_Percent__c = 20];
        Factor_Summary__c factSumm = new Factor_Summary__c();
        factSumm.Code__c = 'Netted Down Premium Broker Commission Percent';
        factSumm.Quote__c = objQO4.Quote__c;
        factSumm.Quote_Option__c = objQO4.Id;
        insert factSumm;
        System.assertEquals(true, objQO4.Bound__c);
        Map<String,Quote_Option__c> quotOption = new Map<String,Quote_Option__c>();
        quotOption.put(objQO4.id,objQO4);
        quotOption.put(objQO2.id,objQO2);
        quotOption.put(objQO3.id,objQO3);
        QuoteOptionTriggerHandler.populateFactorSummary(quotOption);
    }

}