main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <label>Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Coverage__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <externalId>true</externalId>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Coverage_Limits_Deductibles__c/Coverage_Limits_Deductibles__c.object-meta.xml
<CustomObject>
    <label>Limits &amp; Deductibles</label>
    <nameField>
        <label>Option</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Limits &amp; Deductibles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CoveragesLineItem__c/CoveragesLineItem__c.object-meta.xml
<CustomObject>
    <label>Coverages Line Item</label>
    <nameField>
        <displayFormat>CLI-{00000000}</displayFormat>
        <label>CLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverages Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CoveragesLineItem__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Coverage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Main Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coverage__c</referenceTo>
    <relationshipLabel>Coverages Line Items (Coverage)</relationshipLabel>
    <relationshipName>CoverageQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Coverages Line Items</relationshipLabel>
    <relationshipName>Coverages_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Factor_Summary__c/Factor_Summary__c.object-meta.xml
<CustomObject>
    <label>Factor Summary</label>
    <nameField>
        <displayFormat>FS-{00000}</displayFormat>
        <label>Factor Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factor Summarys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Factor_Summary__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Factor Summarys</relationshipLabel>
    <relationshipName>Factor_Summary_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Factor_Summary__c/fields/Quote_Option__c.field-meta.xml
<CustomField>
    <fullName>Quote_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Option</label>
    <referenceTo>Quote_Option__c</referenceTo>
    <relationshipLabel>Factor_Summarys</relationshipLabel>
    <relationshipName>Factor_Summary_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Quote_Option__c/Quote_Option__c.object-meta.xml
<CustomObject>
    <label>Quote Option</label>
    <nameField>
        <displayFormat>QO-{000000}</displayFormat>
        <label>Quote Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Quote_Option__c/fields/Actual_Premium__c.field-meta.xml
<CustomField>
    <fullName>Actual_Premium__c</fullName>
    <label>Actual Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Quote_Option__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <externalId>true</externalId>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Quote_Option__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Options</relationshipLabel>
    <relationshipName>Quote_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifier_Factor__c/Rating_Modifier_Factor__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier Factor</label>
    <nameField>
        <displayFormat>RMF-{0000}</displayFormat>
        <label>Rating Modifier Factor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rating Modifier Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifier_Factor__c/fields/Factor_Value__c.field-meta.xml
<CustomField>
    <fullName>Factor_Value__c</fullName>
    <label>Factor Value</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Rating_Modifier_Factor__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Rating Modifier Factors</relationshipLabel>
    <relationshipName>Rating_Modifier_Factors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifier_Factor__c/fields/Rating_Modifier__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier__c</fullName>
    <label>Rating Modifier</label>
    <referenceTo>Rating_Modifiers__c</referenceTo>
    <relationshipLabel>Rating Modifier Factors</relationshipLabel>
    <relationshipName>Rating_Modifier_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/Rating_Modifiers__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier</label>
    <nameField>
        <label>Rating Modifiers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifiers__c/fields/Factor_Default_Value__c.field-meta.xml
<CustomField>
    <fullName>Factor_Default_Value__c</fullName>
    <label>Factor Default Value</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Factor_Max__c.field-meta.xml
<CustomField>
    <fullName>Factor_Max__c</fullName>
    <label>Factor Max</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Factor_Min__c.field-meta.xml
<CustomField>
    <fullName>Factor_Min__c</fullName>
    <label>Factor Min</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Rating_Modifier_Code__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Code__c</fullName>
    <label>Rating Modifier Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Subjectivity_Template__c/Subjectivity_Template__c.object-meta.xml
<CustomObject>
    <label>Subjectivity Template</label>
    <nameField>
        <displayFormat>TEMP-{0000}</displayFormat>
        <label>Subjectivity Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subjectivity Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Subjectivity_Template__c/fields/Profession_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Profession_Criteria__c</fullName>
    <label>Profession Criteria</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accountants</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Design &amp; Construct</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Insurance Brokers</fullName>
            </value>
            <value>
                <fullName>IT Consultants</fullName>
            </value>
            <value>
                <fullName>Media Professionals</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Property Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Subjectivity_Name__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Name__c</fullName>
    <label>Subjectivity Name</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Subjectivity_Text__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Text__c</fullName>
    <label>Subjectivity Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/classes/CreateFactorSummaryTest.cls
/**************************************************************************************************
* Class Name: CreateFactorSummary
* Author: Namana K G
* Created date: 05-May-2021
* Description: CreateFactorSummaryTest Class
**************************************************************************************************/
@isTest
public class CreateFactorSummaryTest {
    @testSetup
    public static void setupData() {
        Product2 product = TestUtil.createProduct('D&O');
        insert product;
        
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        insert acc;
        
        Opportunity opportunity = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opportunity.StageName = 'Qualified';
        insert opportunity;
        
        Subjectivity_Template__c  subjectivityTemplate = new Subjectivity_Template__c();
        subjectivityTemplate.Subjectivity_Name__c = 'Signed / Dated Proposal';
        subjectivityTemplate.Subjectivity_Text__c  = 'Test';
        subjectivityTemplate.Profession_Criteria__c = 'Engineers';
        insert subjectivityTemplate;
        
        Quote quote = TestUtil.createQuote('Quote Test',opportunity.Id);
        quote.Azure_ID__c = 'Test Az 1';
        upsert quote;
        
        Quote ratedQuote = TestUtil.createQuote('Rated Quote Test',opportunity.Id);
        //ratedQuote.Status = 'Rated';
        ratedQuote.Status = 'IN PROGRESS';
        ratedQuote.Azure_ID__c = 'Test Az 2';
        insert ratedQuote;
        
        Coverage__c cov = Testutil.createCoverage('Coverage 1', 'D&O');
        insert cov;
        
        Coverage_Limits_Deductibles__c covLD = TestUtil.creatLimitsDeductibles('test LD', cov.id);
        insert covLD;
        
        CoveragesLineItem__c covLineItem = testUtil.createCoverageLineItem(ratedQuote.id, covLD.id, cov.Id, 'Picklist');
        covLineItem.Azure_ID__c = '61b1c13d-24a5-4181-8ccc-d3929c1b4edd';
        covLineItem.Coverage_Product__c = 'D&O';
        insert covLineItem;
        
        Rating_Modifiers__c rateMod = TestUtil.createRatingModifier('Test Rat Modifier', 'MPL', opportunity.id);
        rateMod.Azure_ID__c = 'Test ID Azure';
        rateMod.Rating_Modifier_Code__c = 'Cyber000156';
        insert rateMod;
        
        Rating_Modifier_Factor__c rm = new Rating_Modifier_Factor__c();
        rm.Factor_Default_Value__c = 123;
        rm.Factor_Max__c = 300;
        rm.Factor_Min__c = 100;
        rm.Factor_Value__c = 120;
        rm.Rating_Modifier__c = rateMod.Id;
        rm.Quote__c = quote.Id;    
        insert rm; 
        
        Factor_Summary__c fac = new Factor_Summary__c();
        fac.Code__c = '1';
        fac.Quote__c = quote.Id;
        insert fac;
        
        
    }  
    
    @isTest
    public static void createNewFactorSummaryTest () {
        Quote quote = [SELECT Id FROM Quote limit 1];
        List<Factor_Summary__c> fsList = new List<Factor_Summary__c>();
        List<Factor_Summary__c> fsListQC = new List<Factor_Summary__c>();
        Map<String, List<Factor_Summary__c>> mapOfOptionIdVsListOfFactorSummary = new Map<String, List<Factor_Summary__c>>();
        
        Quote_Option__c quoteOption = new Quote_Option__c();
        quoteOption.Actual_Premium__c = 181;
        quoteOption.Quote__c = quote.Id;
        insert quoteOption;
            
        Factor_Summary__c fac = new Factor_Summary__c();
        fac.Code__c = 'Rate';
        fac.Quote__c = quote.Id;
        fsList.add(fac);
        
        Factor_Summary__c facQC = new Factor_Summary__c();
        facQC.Code__c = 'Rate';
        facQC.Quote__c = quote.Id;
        fsListQC.add(facQC);
        mapOfOptionIdVsListOfFactorSummary.put(quoteOption.Id, fsListQC);
        
        test.startTest();
        CreateFactorSummary.createNewFactorSummary(fsList, quote.Id); 
        CreateFactorSummary.createNewFactorSummaryQC(mapOfOptionIdVsListOfFactorSummary);  
        CreateFactorSummary.createNewFactorSummary(fsList, ''); 
        test.stopTest();
        system.assert(fsList != null);
        
    }
}