main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <label>Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Coverage__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coverage</fullName>
                <default>true</default>
                <label>Coverage</label>
            </value>
            <value>
                <fullName>Endorsement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Coverage__c/fields/Form_Number__c.field-meta.xml
<CustomField>
    <fullName>Form_Number__c</fullName>
    <label>Form Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/classes/CoverageQueryUtilTest.cls
/**************************************************************************************************
 * Class Name: CoverageQueryUtilTest
 * Author: Vinay V
 * Date: Dec 28th, 2021
 * Description: Test class for CoverageQueryUtil
 **************************************************************************************************/
@isTest
public with sharing class CoverageQueryUtilTest {
    @testsetup
	static void testSetup(){
		Coverage__c cov1 = new Coverage__c(Name = 'Coverage Name', Form_Number__c = 'ACMP 27 03 08 04', Coverage_Product__c = 'MPL', Coverage_Type__c = 'Endorsement');
		insert cov1;
    }

    static testmethod void test_fetchCoveragesByProducts(){
        Test.startTest();
        List<Coverage__c> coverages = CoverageQueryUtil.fetchCoveragesByProducts(new list<String>{'MPL'});
        // added by Rinku Saini 3rd Jan 2022
        CoverageQueryUtil.fetchCoveragesByProductName(new list<String>{'MPL'});
        system.assert(coverages.size() > 0);
        Test.stopTest();
    }
}