main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <label>Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Coverage__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <externalId>true</externalId>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Code__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Code__c</fullName>
    <description>User entered code which will be used across systems (radar, middleware etc)</description>
    <externalId>true</externalId>
    <label>Coverage Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coverage</fullName>
                <default>true</default>
                <label>Coverage</label>
            </value>
            <value>
                <fullName>Endorsement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/CoveragesLineItem__c/CoveragesLineItem__c.object-meta.xml
<CustomObject>
    <label>Coverages Line Item</label>
    <nameField>
        <displayFormat>CLI-{00000000}</displayFormat>
        <label>CLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverages Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CoveragesLineItem__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Coverage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Main Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coverage__c</referenceTo>
    <relationshipLabel>Coverages Line Items (Coverage)</relationshipLabel>
    <relationshipName>CoverageQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Code__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Code__c</fullName>
    <formula>Coverage__r.Coverage_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coverage Code</label>
    <type>Text</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Premium__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Premium__c</fullName>
    <label>Coverage Premium</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Main_Coverage</fullName>
                <label>Main Coverage</label>
            </value>
            <value>
                <fullName>Sub_Coverage</fullName>
                <label>Sub Coverage</label>
            </value>
            <value>
                <fullName>Limit</fullName>
            </value>
            <value>
                <fullName>Deductible</fullName>
            </value>
            <value>
                <fullName>Endorsement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/IsSelected__c.field-meta.xml
<CustomField>
    <fullName>IsSelected__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>The value used by the CLI of type Endorsement when added in the Quote</inlineHelpText>
    <label>IsSelected</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Option_Value_Default__c.field-meta.xml
<CustomField>
    <fullName>Option_Value_Default__c</fullName>
    <label>Option Value Default</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Coverages Line Items</relationshipLabel>
    <relationshipName>Coverages_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Technical_Premium__c.field-meta.xml
<CustomField>
    <fullName>Technical_Premium__c</fullName>
    <label>Technical Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/recordTypes/Celerity.recordType-meta.xml
<RecordType>
    <fullName>Celerity</fullName>
    <active>true</active>
    <label>Celerity</label>
</RecordType>

main/default/classes/CoverageLineItemTriggerHandler_CEL.cls
/**************************************************************************************************
 * Class Name: CoverageLineItemTriggerHandler_CEL
 * Author: 
 * Date: 
 * Description: Class to keep Celerity related  common methods
 * Test Class : CoverageLineItemTriggerTest
 **************************************************************************************************/
public class CoverageLineItemTriggerHandler_CEL extends TriggerHandler {


    private List<CoveragesLineItem__c> oldDataList;
    private List<CoveragesLineItem__c> newDataList; 
    private Map<Id, CoveragesLineItem__c> newDataMap;
    private Map<Id, CoveragesLineItem__c> oldDataMap; 

    Map<Id, Quote> updateQuoteMap = new Map<Id, Quote>();
    
    public CoverageLineItemTriggerHandler_CEL(List<CoveragesLineItem__c> newDataList, List<CoveragesLineItem__c> oldDataList, 
                                         Map<Id, CoveragesLineItem__c> newDataMap, Map<Id, CoveragesLineItem__c> oldDataMap){
                                             this.oldDataList = oldDataList;
                                             this.newDataList = newDataList;
                                             this.newDataMap = newDataMap;
                                             this.oldDataMap = oldDataMap;
                                         } 

	public override void beforeInsert()	{
        //filterEndorsement(newDataList);
        // Generate Azure Id before insert of CLI
		CommonUtil.generateExternalID('Azure_ID__c', newDataList);
	}

    public override void beforeUpdate(){
        
        //filterEndorsement(newDataList);
        // Generate Azure Id before update of CLI
		CommonUtil.generateExternalID('Azure_ID__c', newDataList);
    }

	
	public override void afterInsert(){
        filterEndorsement(newDataList);
        //update Quote ExcessLimit
        map<Id,Quote> updateExcessLimitMap = CommonCoverageLineItemUtil.updateExcessLimit(this.newDataMap);
        updateQuoteMap.putAll(updateExcessLimitMap);

        //update quote Technical Premium
        map<Id,Quote> updateTechPremiumMap = updateCelTechnicalPremium(this.newDataList);
        updateQuoteMap.putAll(updateTechPremiumMap);

        //update quote status
        map<Id,Quote> updateStatusMap = CommonCoverageLineItemUtil.updateQuoteStatus(this.newDataList,null);
        updateQuoteMap.putAll(updateStatusMap);

        if(updateQuoteMap.Values().size() > 0){
            update updateQuoteMap.Values();
        } 
    }

	
	public override void afterUpdate(){
        filterEndorsement(newDataList);
        //update quote status
        map<Id,Quote> updateStatusMap = CommonCoverageLineItemUtil.updateQuoteStatus(this.newDataList,this.oldDataMap);
        updateQuoteMap.putAll(updateStatusMap);

        //update Quote ExcessLimit
        map<Id,Quote> updateExcessLimitMap = CommonCoverageLineItemUtil.updateExcessLimit(this.newDataMap);
        updateQuoteMap.putAll(updateExcessLimitMap);

        //update quote Technical Premium
        map<Id,Quote> updateTechPremiumMap = updateCelTechnicalPremium(this.newDataList);
        updateQuoteMap.putAll(updateTechPremiumMap);

        if(updateQuoteMap.Values().size() > 0){
            update updateQuoteMap.Values();
        }

        //update CLI Option_Value_Default__c
        CommonCoverageLineItemUtil.handleUpdateSyncLimitDeductible(this.oldDataMap, this.newDataMap);
    }

    
    public override void afterdelete(){
        //update quote status
        map<Id,Quote> updateStatusMap = CommonCoverageLineItemUtil.updateQuoteStatus(oldDataList,null);

        /* should it updated, trigger handler does not have DML?*/
        
     }


     /*************************************************
    * Method Name: updateCelTechnicalPremium
    * Author: 
    * Date: 
    * Params: Map<Id, CoveragesLineItem__c>
    * Return: 
    * Exceptions:
    * Description: update Technical premium Term
    * Revision: 
     *************************************************/
    public static Map<Id, Quote> updateCelTechnicalPremium(List<CoveragesLineItem__c > newDataList) {
        Set<ID> quoteIds = new Set<ID>();
        Set<ID> existQuoteId = new Set<ID>();
        List<Quote> updateQuote = new List<Quote>();
        Map<Id, Quote> updateQuoteMap = new Map<Id, Quote>();
        List<CoveragesLineItem__c> CLIList = CoverageLineItemQueryUtil.fetchCLIsForTechnicalPremium(newDataList);
        if(CLIList.size()>0){
           for (CoveragesLineItem__c cli : CLIList){
               quoteIds.add(cli.Quote__c);
           } 
           String queryFields = 'Id,Celerity_Excess_Limit__c,Underlying_Excess_Limit__c, Celerity_Technical_Premium__c, Status, Product_Name__c';
           Map<Id,Quote> mapQuote = new Map<Id,Quote>( QuoteQueryUtil.fetchQuotesForQuoteIds(quoteIds, queryFields) );

           //can be removed
           for(Quote qt : mapQuote.values()){
               if(updateQuoteMap.containsKey(qt.Id)){
                   existQuoteId.add(qt.Id);
               }
               else{
                   updateQuoteMap.put(qt.Id, qt);
               }
           }

           for(Id existingId : existQuoteId){
               mapQuote.put(existingId, updateQuoteMap.get(existingId));
           }
           //can be removed

           for (CoveragesLineItem__c cli: CLIList) {
               if(String.isNotBlank(cli.Coverage_Premium__c) && ((cli.Quote__r.Layer__c != 'Excess' && Trigger.isInsert) || Trigger.isUpdate)){ //check added by Vinay to bypass for Excess layer
                if(cli.Coverage_Product__c =='MPL' || cli.Coverage_Product__c =='Cyber' || cli.Coverage_Product__c =='Private Company Combo' ){
                    mapQuote.get(cli.Quote__c).Celerity_Technical_Premium__c = cli.Technical_Premium__c;
                    }
               }
           }
       }
       return updateQuoteMap;
   }
    
  //Filtering Endorsement coverages as per US:56883
    public static void filterEndorsement(List<CoveragesLineItem__c> clis){
        List<EndorsementTabLwcController.Endorsement> selEndorsementCovs =  EndorsementTabLwcController.getSelectedEndorsement(clis[0].Quote__c);
        String selClis = '';
        List<CoveragesLineItem__c> clisForRating = new List<CoveragesLineItem__c>();
        for(EndorsementTabLwcController.Endorsement endtCli : selEndorsementCovs){
            selClis += endtCli.id +  ' ' + ';';
        }

        List<CoveragesLineItem__c> existCli = [Select Id, IsSelected__c, Coverage__r.Coverage_Type__c, Coverage__r.Id,
                                                Coverage__r.Coverage_Code__c,Quote__c
                                                From CoveragesLineItem__c
                                                Where Quote__c = :clis[0].Quote__c];

        
        List<CoveragesLineItem__c> tempCli = new List<CoveragesLineItem__c>();
        // List<String> covToUpdateSelected = new List<String>();
        // List<String> covToUpdateNotSelected = new List<String>();
        for(CoveragesLineItem__c c1 : existCli){
            if(c1.Coverage__r.Coverage_Type__c == null) continue;
            CoveragesLineItem__c updateCli = new CoveragesLineItem__c();
            updateCli.Id = c1.Id;
            if(c1.Coverage__r.Coverage_Type__c.contains('Endorsement')){
                if(!selClis.contains(c1.Coverage__r.Id)){
                    updateCli.IsSelected__c = false;
                }
                else{
                    system.debug('vinay selected cov ' + c1.Coverage__r.Coverage_Code__c);
                    updateCli.IsSelected__c = true;
                }
                tempCli.add(updateCli);
            }
        }

        // List<CoveragesLineItem__c> cliToUpdate = new List<CoveragesLineItem__c>();
        // for(CoveragesLineItem__c c1 : tempCli){
        //     boolean cliInTrigger = false;
        //     for(CoveragesLineItem__c c2 : clis){
        //         if(c1.Id == c2.Id){
        //             c2.IsSelected__c = c1.IsSelected__c;
        //             cliInTrigger = true;
        //         }
        //     }
        //     if(!cliInTrigger) cliToUpdate.add(c1);
        // }

        GlobalStaticVar.byPassCoverageLineItemTrigger = true;
        GlobalStaticVar.byPassQuoteTrigger = true;
        update tempCli;
        GlobalStaticVar.byPassCoverageLineItemTrigger = false;
        GlobalStaticVar.byPassQuoteTrigger = false;
    }
}