main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <label>Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Coverage__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassCoverageTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassCoverageTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassCoverageTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/CoverageTriggerTest.cls
@isTest
public class CoverageTriggerTest {
	
    @isTest
    public static void testCoverage() {
        TriggerSettings__c setting = TestUtil.initialTriggerSetting();
        System.assertEquals(true,setting.BypassCoverageTrigger__c);
        setting.BypassCoverageTrigger__c = false;
		update setting;
        
        //Create coverage
		Coverage__c cov1 = TestUtil.createCoverage('Coverage test', 'MPL');
		insert cov1;
        
        cov1.Coverage_Product__c = 'Cyber';
        update cov1;
    }
}