main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <label>Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Coverage__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Coverage__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Features</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/CoveragesLineItem__c.object-meta.xml
<CustomObject>
    <label>Coverages Line Item</label>
    <nameField>
        <displayFormat>CLI-{00000000}</displayFormat>
        <label>CLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverages Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CoveragesLineItem__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Coverage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Main Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coverage__c</referenceTo>
    <relationshipLabel>Coverages Line Items (Coverage)</relationshipLabel>
    <relationshipName>CoverageQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Eligibility_Status__c/Eligibility_Status__c.object-meta.xml
<CustomObject>
    <label>Eligibility Status</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Eligibility Status #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligibility Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Eligibility_Status__c/fields/Eligibility_Status__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Status__c</fullName>
    <label>Eligibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Proceed</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution</fullName>
            </value>
            <value>
                <fullName>No Information</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution (consider restrictive terms, including but limited to matching/increasing retention to the largest paid loss)</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution (sub limit only)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (Unless fewer than 50 employees)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (unless Highly Compensated Separate Retention Endorsement is added)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (unless D&amp;O revenue threshold is met)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (seasonal, low wage,retail industries, etc.)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (Unless less than 100 employees)</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution and consider adding a Family Exclusion</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution and consider Major Shareholder Exclusion</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution with sub-limit</fullName>
            </value>
            <value>
                <fullName>qualified or not all locations are audited</fullName>
            </value>
            <value>
                <fullName>Prohibited Class</fullName>
            </value>
            <value>
                <fullName>Munich Referral</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard</fullName>
            </value>
            <value>
                <fullName>Stop!Decline!</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Eligibility_Status__c/fields/Modifier_Product__c.field-meta.xml
<CustomField>
    <fullName>Modifier_Product__c</fullName>
    <label>Modifier Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modifier_Product</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Eligibility_Status__c/fields/Rating_Modifier_Template__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Template__c</fullName>
    <label>Rating Modifier Template</label>
    <referenceTo>Rating_Modifier_Template__c</referenceTo>
    <relationshipLabel>Eligibility Statuses</relationshipLabel>
    <relationshipName>Eligibility_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/Rating_Modifier_Template__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier Template</label>
    <nameField>
        <label>Rating Modifier Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifier Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifier_Template__c/fields/Modifier_Product__c.field-meta.xml
<CustomField>
    <fullName>Modifier_Product__c</fullName>
    <label>Modifier Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>D&amp;O Standalone</fullName>
                <isActive>false</isActive>
                <label>D&amp;O Standalone</label>
            </value>
            <value>
                <fullName>Test Product 00</fullName>
                <isActive>false</isActive>
                <label>Test Product 00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifier_Template__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifiers__c/Rating_Modifiers__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier</label>
    <nameField>
        <label>Rating Modifiers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifiers__c/fields/Eligibility_Status__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Status__c</fullName>
    <label>Eligibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Proceed</fullName>
                <color>#33CC00</color>
                <label>Proceed</label>
            </value>
            <value>
                <fullName>Proceed with Caution</fullName>
                <color>#F3D904</color>
                <label>Proceed with Caution</label>
            </value>
            <value>
                <fullName>Stop!Decline!</fullName>
                <color>#FF0000</color>
                <label>Stop!Decline!</label>
            </value>
            <value>
                <fullName>No Information</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution (consider restrictive terms, including but limited to matching/increasing retention to the largest paid loss)</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution (sub limit only)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (Unless fewer than 50 employees)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (unless Highly Compensated Separate Retention Endorsement is added)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (unless D&amp;O revenue threshold is met)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (seasonal, low wage,retail industries, etc.)</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard (Unless less than 100 employees)</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution and consider adding a Family Exclusion</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution and consider Major Shareholder Exclusion</fullName>
            </value>
            <value>
                <fullName>Proceed with Caution with sub-limit</fullName>
            </value>
            <value>
                <fullName>qualified or not all locations are audited</fullName>
            </value>
            <value>
                <fullName>Prohibited Class</fullName>
            </value>
            <value>
                <fullName>Munich Referral</fullName>
            </value>
            <value>
                <fullName>STOP! Higher Hazard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Aqueous</fullName>
                <isActive>false</isActive>
                <label>Aqueous</label>
            </value>
            <value>
                <fullName>Cel1</fullName>
                <isActive>false</isActive>
                <label>Cel1</label>
            </value>
            <value>
                <fullName>D&amp;O Standalone</fullName>
                <isActive>false</isActive>
                <label>D&amp;O Standalone</label>
            </value>
            <value>
                <fullName>New Test</fullName>
                <isActive>false</isActive>
                <label>New Test</label>
            </value>
            <value>
                <fullName>Test</fullName>
                <isActive>false</isActive>
                <label>Test</label>
            </value>
            <value>
                <fullName>Test Product 00</fullName>
                <isActive>false</isActive>
                <label>Test Product 00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/ProductTriggerHandler_AQ.cls
/**************************************************************************************************
 * Class Name: ProductTriggerHandler_AQ
 * Author: 
 * Date: 
 * Description: Class to keep AQ related  common methods
 * Test Class : ProductTriggerHandlerTest
 **************************************************************************************************/
public with sharing class ProductTriggerHandler_AQ extends TriggerHandler {


    private List<Product2> oldDataList;
    private List<Product2> newDataList; 
    private Map<Id, Product2> newDataMap;
    private Map<Id, Product2> oldDataMap; 

    public ProductTriggerHandler_AQ(  List<Product2> newDataList, 
                                                List<Product2> oldDataList, 
                                                Map<Id, Product2> newDataMap, 
                                                Map<Id, Product2> oldDataMap){
        this.oldDataList = oldDataList;
        this.newDataList = newDataList;
        this.newDataMap = newDataMap;
        this.oldDataMap = oldDataMap;
    } 

    public override void afterInsert(){
        //add product name to object's picklist field 
        CommonProductUtil.addProductNameToObject('Rating_Modifier_Template__c.Modifier_Product__c',newDataList);
        CommonProductUtil.addProductNameToObject('Rating_Modifiers__c.Product__c',newDataList);
        CommonProductUtil.addProductNameToObject('Coverage__c.Coverage_Product__c',newDataList);
        CommonProductUtil.addProductNameToObject('CoveragesLineItem__c.Coverage_Product__c',newDataList);
        CommonProductUtil.addProductNameToObject('Endorsement_Line_Item__c.Coverage_Product__c',newDataList);
        CommonProductUtil.addProductNameToObject('Eligibility_Status__c.Modifier_Product__c',newDataList);
       
    }

    public override void afterUpdate() {
        //update product name in object's picklist field 
        CommonProductUtil.updateProductNameFromObject('Modifier_Product',oldDataMap, newDataMap);
    }

    public override void afterDelete() {
        //remove product name from object's picklist field 
        CommonProductUtil.removeProductNameFromObject('Rating_Modifier_Template__c.Modifier_Product__c',oldDataList);
        CommonProductUtil.removeProductNameFromObject('Rating_Modifiers__c.Product__c',oldDataList);
        CommonProductUtil.removeProductNameFromObject('Coverage__c.Coverage_Product__c', oldDataList);
        CommonProductUtil.removeProductNameFromObject('CoveragesLineItem__c.Coverage_Product__c', oldDataList);
        CommonProductUtil.removeProductNameFromObject('Endorsement_Line_Item__c.Coverage_Product__c', oldDataList);
        CommonProductUtil.removeProductNameFromObject('Eligibility_Status__c.Modifier_Product__c', oldDataList);
    }
}