main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <label>Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Coverage__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Coverage__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Features</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Coverage_Limits_Deductibles__c/Coverage_Limits_Deductibles__c.object-meta.xml
<CustomObject>
    <label>Limits &amp; Deductibles</label>
    <nameField>
        <label>Option</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Limits &amp; Deductibles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Coverage_Limits_Deductibles__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Free_Form_Endorsements__c/Free_Form_Endorsements__c.object-meta.xml
<CustomObject>
    <label>Free Form Endorsement</label>
    <nameField>
        <displayFormat>FF-{000}</displayFormat>
        <label>Free Form Endorsements ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Free Form Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Free_Form_Endorsements__c/fields/Endorsement_Name__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Name__c</fullName>
    <label>Endorsement Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Free_Form_Endorsements__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Free Form Endorsements</relationshipLabel>
    <relationshipName>Free_Form_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/FreeFormEndorsementTriggerHandlerTest.cls
/**************************************************************************************************
* Class Name: FreeFormEndorsementTriggerHandler
* Author: Ashik Zahir
* Created date: 06-April-2021
* Description: TriggerHandlerTest for Free_Form_Endorsements__c Object
**************************************************************************************************/
@isTest
public class FreeFormEndorsementTriggerHandlerTest {
@testSetup 
    static void createData(){
        Account acc = TestUtil.createBusinessAccount('Bussiness Accoun Aq', 'Business', '123 Main Street', 'Anycity', 'England', '11354', 'United Kingdom');
        acc.BillingStreet = acc.ShippingStreet;
        acc.BillingCity = acc.ShippingCity;
        acc.BillingState = acc.ShippingState;
        acc.BillingPostalCode = acc.ShippingPostalCode;
        acc.BillingCountry = acc.ShippingCountry;
        insert acc;
        
        Id aqueousRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Product2 product = TestUtil.createProduct('Professional Indemnity');
        product.RecordTypeId = aqueousRecordTypeId; 
        product.Innovisk_Entity_ID__c = 'Aqueous';
        insert product;   
        
        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.StageName = 'Qualified'; 
        opp.Innovisk_Entity_ID__c = 'Aqueous';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();                            
        opp.Product__c = product.Id;
        opp.Coverage_Product_Options__c = 'Professional Indemnity';
        insert opp;
        
        //Create coverage
        List<Coverage__c> lCov = new List<Coverage__c>();
        Coverage__c cov = TestUtil.createCoverage('Coverage test', 'D&O');
        cov.Coverage_Product__c = 'D&O';
        lCov.add(cov);
        Coverage__c cov1 = TestUtil.createCoverage('Coverage test', 'MPL');
        lCov.add(cov1);
        insert lCov;
        
        //create limit deductables
        Coverage_Limits_Deductibles__c ded = TestUtil.creatLimitsDeductibles('Deductible test', cov.Id);
        insert ded;
        
        // By pass trigger to insert quote
        TriggerSettings__c settings = new TriggerSettings__c();
        settings.BypassQuoteTrigger__c = true;
        insert settings;
        System.assert(settings != null);
        
        //Quote
        Quote quote = TestUtil.createQuote('New Quote Test',opp.Id);
        quote.Coverage_Product_Options__c ='Professional Indemnity'; 
        quote.Status = 'In Progress';
        quote.OpportunityId = opp.Id;
        insert quote;
        
        //quote.Endorsement_Type__c='New Business';
        update quote;
        
    }
    
    @isTest
    static void testFreeformEndorsement(){
        Test.startTest();
        Id quoteId = [Select Id from Quote Limit 1].Id;
        system.debug('quoteId '+quoteId);
        Free_Form_Endorsements__c free = new Free_Form_Endorsements__c();
        free.Quote__c = quoteId;
        insert free;
        
        free.Endorsement_Name__c = 'Free_Form_Endorsements';
        update free;
        
        System.assertEquals(1, [Select id from Free_Form_Endorsements__c Where Quote__c = :quoteId].size());
        
        //delete free;  
        Test.stopTest();
    }
}