main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <label>Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Coverage__c/fields/Additional_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Additional_Requirements__c</fullName>
    <label>Additional Requirements</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rating Required</fullName>
            </value>
            <value>
                <fullName>Load by Default</fullName>
            </value>
            <value>
                <fullName>Schedule</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Part-Fixed</fullName>
            </value>
            <value>
                <fullName>Exclude from NB and Renewal view</fullName>
            </value>
            <value>
                <fullName>Load without limit</fullName>
            </value>
            <value>
                <fullName>Do not show on Endorsement widget</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Coverage__c/fields/Apply_to_Quote__c.field-meta.xml
<CustomField>
    <fullName>Apply_to_Quote__c</fullName>
    <label>Apply to Quote</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Code__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Code__c</fullName>
    <description>User entered code which will be used across systems (radar, middleware etc)</description>
    <externalId>true</externalId>
    <label>Coverage Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_or_Sub__c.field-meta.xml
<CustomField>
    <fullName>Coverage_or_Sub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Coverage</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Coverage</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Coverage__c</referenceTo>
    <relationshipLabel>Coverage/Subs</relationshipLabel>
    <relationshipName>CoveragesSubs</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Product_Combo__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product_Combo__c</fullName>
    <label>Coverage Product Combo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Coverage_Product__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_to_replace__c.field-meta.xml
<CustomField>
    <fullName>Coverage_to_replace__c</fullName>
    <label>Coverage to replace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coverage</fullName>
                <default>true</default>
                <label>Coverage</label>
            </value>
            <value>
                <fullName>Endorsement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Coverage__c/fields/Default_Notes__c.field-meta.xml
<CustomField>
    <fullName>Default_Notes__c</fullName>
    <label>Default Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Coverage__c/fields/Form_Number__c.field-meta.xml
<CustomField>
    <fullName>Form_Number__c</fullName>
    <label>Form Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Coverage__c/fields/Optional_Coverage_Name__c.field-meta.xml
<CustomField>
    <fullName>Optional_Coverage_Name__c</fullName>
    <label>Optional Coverage Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Coverage__c/fields/Page_Section__c.field-meta.xml
<CustomField>
    <fullName>Page_Section__c</fullName>
    <label>Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Coverage_Limits_Deductibles__c/Coverage_Limits_Deductibles__c.object-meta.xml
<CustomObject>
    <label>Limits &amp; Deductibles</label>
    <nameField>
        <label>Option</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Limits &amp; Deductibles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Coverage_Limits_Deductibles__c/fields/Default_Value__c.field-meta.xml
<CustomField>
    <fullName>Default_Value__c</fullName>
    <label>Default Value</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Coverage_Limits_Deductibles__c/fields/Endorsement_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Data_Type__c</fullName>
    <label>Endorsement Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Range</fullName>
            </value>
            <value>
                <fullName>Fixed value</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Coverage_Limits_Deductibles__c/fields/Parent_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Parent_Coverage__c</fullName>
    <label>Parent Coverage</label>
    <referenceTo>Coverage__c</referenceTo>
    <relationshipLabel>Limits &amp; Deductibles</relationshipLabel>
    <relationshipName>FeaturesProductOptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/CoverageQueryUtil.cls
/**************************************************************************************************
 * Class Name: CoverageQueryUtil
 * Author: Vinay
 * Date: Dec 23, 2021
 * Description: Class to keep coverage queries
 * Test Class : CoverageQueryUtil
 **************************************************************************************************/
public with sharing class CoverageQueryUtil {
    /*************************************************
    * Method Name: fetchCoveragesByProducts
    * Author: Vinay
    * Date: 23 Dec 2021
    * Params: List<String>
    * Return: list<Coverage__c>
    * Exceptions:
    * Revision: 
    * Description: Fetch coverages by product names
     *************************************************/
    public static List<Coverage__c> fetchCoveragesByProducts(List<String> productnames){
       return [SELECT Id, Name, Coverage_Product__c, Form_Number__c FROM Coverage__c WHERE Coverage_Type__c = 'Endorsement' AND Coverage_Product__c IN:productnames AND Form_Number__c != NULL];
    }
    
     /*************************************************
    * Method Name: fetchCoveragesByProductName
    * Author: RINKU SAINI
    * Date: 3rd Jan 2022
    * Params: List<String>
    * Return: list<Coverage__c>
    * Exceptions:
    * Revision: 
    * Description: Fetch coverages by product names
     *************************************************/
    public static List<Coverage__c> fetchCoveragesByProductName(List<String> products){
        return  [Select Id,Name,Coverage_Product__c,Coverage_Product_Combo__c,RecordType.Name,Coverage_or_Sub__c, State__c, Coverage_to_replace__c,
                 Default_Notes__c, Coverage_Code__c, Coverage_Type__c,Page_Section__c,Form_Number__c,Apply_to_Quote__c, Optional_Coverage_Name__c, Optional_Factor_Label__c,
                 (Select Id,RecordTypeId,RecordType.Name,Page_Section__c,Endorsement_Data_Type__c,Option_Picklist__c,Default_Value__c From FeaturesProductOptions__r)
                 From Coverage__c 
                 Where ((Coverage_Type__c = 'Endorsement' AND (Additional_Requirements__c INCLUDES ('Load by Default') or Additional_Requirements__c INCLUDES ('Load without limit')) )
                        OR Coverage_Type__c != 'Endorsement') 
                 AND Coverage_Product__c In : products];
    }

     /*************************************************
    * Method Name: fetchCoveragesByProduct
    * Author: 
    * Date: 31st Jan 2022
    * Params: List<String>
    * Return: list<Coverage__c>
    * Exceptions:
    * Revision: 
    * Description: Fetch coverages by product names
     *************************************************/
    public static List<Coverage__c> fetchAllCoveragesByProductName(List<String> products){
        return  [Select Id,Name,Coverage_Product__c,Coverage_Product_Combo__c,RecordType.Name,Coverage_or_Sub__c, State__c, Coverage_to_replace__c,
                 Default_Notes__c, Coverage_Type__c,Page_Section__c,Form_Number__c,Apply_to_Quote__c, Optional_Coverage_Name__c,Optional_Factor_Label__c,
                 (Select Id,RecordTypeId,RecordType.Name,Page_Section__c,Endorsement_Data_Type__c,Option_Picklist__c,Default_Value__c From FeaturesProductOptions__r)
                 From Coverage__c 
                 Where Coverage_Product__c In : products];
    }
}