main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <label>Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Coverage__c/fields/Coverage_Code__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Code__c</fullName>
    <description>User entered code which will be used across systems (radar, middleware etc)</description>
    <externalId>true</externalId>
    <label>Coverage Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Product_Combo__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product_Combo__c</fullName>
    <label>Coverage Product Combo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Coverage_Product__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Coverage__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Features</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Coverage_Limits_Deductibles__c/Coverage_Limits_Deductibles__c.object-meta.xml
<CustomObject>
    <label>Limits &amp; Deductibles</label>
    <nameField>
        <label>Option</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Limits &amp; Deductibles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Coverage_Limits_Deductibles__c/fields/LmtDedCode__c.field-meta.xml
<CustomField>
    <fullName>LmtDedCode__c</fullName>
    <label>LmtDedCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Coverage_Limits_Deductibles__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Coverage_Limits_Deductibles__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>TEXT( Parent_Coverage__r.Coverage_Product__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/CoveragesLineItem__c.object-meta.xml
<CustomObject>
    <label>Coverages Line Item</label>
    <nameField>
        <displayFormat>CLI-{00000000}</displayFormat>
        <label>CLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverages Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CoveragesLineItem__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Coverage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Main Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coverage__c</referenceTo>
    <relationshipLabel>Coverages Line Items (Coverage)</relationshipLabel>
    <relationshipName>CoverageQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Code__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Code__c</fullName>
    <formula>Coverage__r.Coverage_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coverage Code</label>
    <type>Text</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Premium__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Premium__c</fullName>
    <label>Coverage Premium</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Product_Combo__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product_Combo__c</fullName>
    <label>Coverage Product Combo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/CoverageLineItemType__c.field-meta.xml
<CustomField>
    <fullName>CoverageLineItemType__c</fullName>
    <formula>IF(AND(ISBLANK(Sub_Coverage__c),ISBLANK(Limits_Deductibles__c)) ,Coverage__r.RecordTypeName__c,
			IF(AND(NOT(ISBLANK(Sub_Coverage__c)),ISBLANK(Limits_Deductibles__c)) ,Sub_Coverage__r.RecordTypeName__c, Limits_Deductibles__r.RecordType.Name ) )</formula>
    <label>CoverageLineItemType</label>
    <type>Text</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Option_Value_Default__c.field-meta.xml
<CustomField>
    <fullName>Option_Value_Default__c</fullName>
    <label>Option Value Default</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Override_Premium__c.field-meta.xml
<CustomField>
    <fullName>Override_Premium__c</fullName>
    <label>Override Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Coverages Line Items</relationshipLabel>
    <relationshipName>Coverages_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/Pre_Rate_Calculator_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Pre Rate Calculator Setting</label>
    <pluralLabel>Pre Rate Calculator Settings</pluralLabel>
</CustomObject>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/Base_Rate_Table__c.field-meta.xml
<CustomField>
    <fullName>Base_Rate_Table__c</fullName>
    <label>Base Rate Table</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/CLI_Type_Deductible_Option__c.field-meta.xml
<CustomField>
    <fullName>CLI_Type_Deductible_Option__c</fullName>
    <label>CLI Type Deductible Option</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/CLI_Type_Limit_Option__c.field-meta.xml
<CustomField>
    <fullName>CLI_Type_Limit_Option__c</fullName>
    <label>CLI Type Limit Option</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/CLI_Type_Main_Option__c.field-meta.xml
<CustomField>
    <fullName>CLI_Type_Main_Option__c</fullName>
    <label>CLI Type Main Option</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/County_Table_Name__c.field-meta.xml
<CustomField>
    <fullName>County_Table_Name__c</fullName>
    <label>County Table Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/Coverage_Code__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Code__c</fullName>
    <label>Coverage Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/Exec_Coverage_Code__c.field-meta.xml
<CustomField>
    <fullName>Exec_Coverage_Code__c</fullName>
    <label>Exec Coverage Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/ExecLmtDedCode__c.field-meta.xml
<CustomField>
    <fullName>ExecLmtDedCode__c</fullName>
    <label>ExecLmtDedCode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/Industry_Modifier_Code__c.field-meta.xml
<CustomField>
    <fullName>Industry_Modifier_Code__c</fullName>
    <label>Industry Modifier Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/LimitILF_Table_Name__c.field-meta.xml
<CustomField>
    <fullName>LimitILF_Table_Name__c</fullName>
    <label>LimitILF Table Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/LmtDedCode__c.field-meta.xml
<CustomField>
    <fullName>LmtDedCode__c</fullName>
    <label>LmtDedCode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/LmtDedRetentionCode__c.field-meta.xml
<CustomField>
    <fullName>LmtDedRetentionCode__c</fullName>
    <label>LmtDedRetentionCode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/Policy_Retention_Table_Name__c.field-meta.xml
<CustomField>
    <fullName>Policy_Retention_Table_Name__c</fullName>
    <label>Policy Retention Table Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>ProductName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Pre_Rate_Calculator_Setting__mdt/fields/SnT_Modifier_Code__c.field-meta.xml
<CustomField>
    <fullName>SnT_Modifier_Code__c</fullName>
    <label>SnT Modifier Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

main/default/objects/Product_Option_Line_Item__c/Product_Option_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Product Option Line Item</label>
    <nameField>
        <displayFormat>POLI-{0000}</displayFormat>
        <label>Product  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Option Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Product_Option_Line_Item__c/fields/Clearance_Status__c.field-meta.xml
<CustomField>
    <fullName>Clearance_Status__c</fullName>
    <label>Clearance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Closed Market</fullName>
            </value>
            <value>
                <fullName>Clearance Not Applicable</fullName>
            </value>
            <value>
                <fullName>Service failed</fullName>
            </value>
            <value>
                <fullName>Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Product_Option_Line_Item__c/fields/Is_Selected__c.field-meta.xml
<CustomField>
    <fullName>Is_Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selected</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Product_Option_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Option Line Items</relationshipLabel>
    <relationshipName>Product_Option_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Product_Option_Line_Item__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Product Option Line Items</relationshipLabel>
    <relationshipName>Product_Option_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifier_Factor__c/Rating_Modifier_Factor__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier Factor</label>
    <nameField>
        <displayFormat>RMF-{0000}</displayFormat>
        <label>Rating Modifier Factor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rating Modifier Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifier_Factor__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Rating Modifier Factors</relationshipLabel>
    <relationshipName>Rating_Modifier_Factors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/QuoteCoverageTableController.cls
/**
 * @description       : 
 * @author            : 
 * @group             : 
 * @last modified on  : 01-24-2022
 * @last modified by  : Vinayesh
**/
public with sharing class QuoteCoverageTableController {
    public QuoteCoverageTableController() {

    }

    @AuraEnabled
    public static RelatedListWrapper fetchCoverageDetails(String quoteId){

        RelatedListWrapper objWrap = new RelatedListWrapper();

        Quote objQuote = [Select Id,Quote_Type__c, Status,Product_Name__c, OpportunityId, QuotePremium__c, Prior_Discount_Quote_Premium__c, Shared_Aggregate_Limit__c, Combined_Max_Agg_Limit_of_Liability__c from Quote where Id =: quoteId];

        List<String> productNames = new List<String>();// = {'D&O','EPL','Crime','Fiduciary'};

        Decimal requiredLimit;

        for(Product_Option_Line_Item__c objPOLI : [Select Id, Product__c, Product__r.Name, Is_Selected__c from Product_Option_Line_Item__c 
                                                    where Submission__c = :objQuote.OpportunityId and Is_Selected__c = true AND Clearance_Status__c = 'Cleared']){
                                                    
            productNames.add(objPOLI.Product__r.Name);

        }

        Map<String, Pre_Rate_Calculator_Setting__mdt> mapMetadataSettings = new Map<String, Pre_Rate_Calculator_Setting__mdt>();
        Pre_Rate_Calculator_Setting__mdt metadataSettingExcess  = new Pre_Rate_Calculator_Setting__mdt();
        for(Pre_Rate_Calculator_Setting__mdt metadataSettings : [Select Id, Active__c,  County_Table_Name__c, Industry_Modifier_Code__c, LimitILF_Table_Name__c, Policy_Retention_Table_Name__c, 
                                                            ProductName__c, SnT_Modifier_Code__c, Order__c, Coverage_Code__c, CLI_Type_Deductible_Option__c, CLI_Type_Limit_Option__c, 
                                                            CLI_Type_Main_Option__c, Exec_Coverage_Code__c, ExecLmtDedCode__c, LmtDedCode__c, LmtDedRetentionCode__c, Base_Rate_Table__c 
                                                            from Pre_Rate_Calculator_Setting__mdt order By Order__c Asc]){
                                                                if(productNames.contains(metadataSettings.ProductName__c)){
                                                                    //productNames.add(metadataSettings.ProductName__c);
                                                                    mapMetadataSettings.put(metadataSettings.ProductName__c, metadataSettings);
                                                                }
                                                                if(metadataSettings.ProductName__c == 'Excess'){
                                                                    metadataSettingExcess = metadataSettings;
                                                                }
                                                            }

        List<RecordDetails> lstRecordDetails = new List<RecordDetails>();
        for(String product : productNames){

            RecordDetails objRecordDetails = new RecordDetails();
            objRecordDetails.productName = product;
            Decimal technicalPremium = 0;
            Pre_Rate_Calculator_Setting__mdt metadataSettings = mapMetadataSettings.get(product);
            for(CoveragesLineItem__c covLineItem : [Select Id, Coverage_Premium__c, Coverage_Product__c, Coverage_Product_Combo__c,
                                        CoverageLineItemType__c, Quote__c, Override_Premium__c, Option_Value_Default__c, Coverage__c, 
                                        Coverage__r.Coverage_Code__c, Coverage__r.Coverage_Product__c, 
                                        Coverage__r.Name, Limits_Deductibles__c, Limits_Deductibles__r.Name, Limits_Deductibles__r.LmtDedCode__c 
                                        from CoveragesLineItem__c where Quote__c = : quoteId]){

                                            if(covLineItem.Coverage__r.Coverage_Code__c == metadataSettings.Coverage_Code__c && covLineItem.Limits_Deductibles__r.LmtDedCode__c == metadataSettings.LmtDedCode__c && covLineItem.CoverageLineItemType__c == metadataSettings.CLI_Type_Limit_Option__c){
                                                requiredLimit = covLineItem.Option_Value_Default__c != null ? Decimal.valueOf(covLineItem.Option_Value_Default__c) : 0;// update by Jitendra on 07-Jan-2022 for MAT-80
                                                objRecordDetails.requiredLimit = requiredLimit;
                                            }
                                            if(covLineItem.Coverage__r.Coverage_Code__c == metadataSettings.Coverage_Code__c && covLineItem.Limits_Deductibles__r.LmtDedCode__c == metadataSettings.LmtDedRetentionCode__c && covLineItem.CoverageLineItemType__c == metadataSettings.CLI_Type_Deductible_Option__c){
                                                objRecordDetails.policyRetention = covLineItem.Option_Value_Default__c != null ? Decimal.valueOf(covLineItem.Option_Value_Default__c) : 0;// update by Jitendra on 07-Jan-2022 for MAT-80
                                                
                                            }
                                            if(covLineItem.Coverage_Product_Combo__c == product && covLineItem.CoverageLineItemType__c == metadataSettings.CLI_Type_Main_Option__c){
                                                technicalPremium += covLineItem.Coverage_Premium__c != null ? Decimal.valueOf(covLineItem.Coverage_Premium__c) : 0;// update by Jitendra on 07-Jan-2022 for MAT-80
                                                objRecordDetails.actualPremium += covLineItem.Override_Premium__c != null? covLineItem.Override_Premium__c : 0;
                                            }
                                            /*if(product == 'D&O'){
                                                if(covLineItem.Coverage__r.Coverage_Code__c == 'DOCoverage'&& covLineItem.CoverageLineItemType__c == 'Main Coverage'){
                                                    objRecordDetails.technicalPremium = covLineItem.Coverage_Premium__c != null ? Decimal.valueOf(covLineItem.Coverage_Premium__c) : 0;// update by Jitendra on 07-Jan-2022 for MAT-80
                                                    objRecordDetails.actualPremium = covLineItem.Override_Premium__c != null ? covLineItem.Override_Premium__c : 0;
                                                }
                                                if(covLineItem.Coverage__r.Coverage_Code__c == 'DOCoverage' && covLineItem.Limits_Deductibles__r.LmtDedCode__c == 'DOMaxAggLOL' && covLineItem.CoverageLineItemType__c == 'Limit Option'){
                                                    requiredLimit = covLineItem.Option_Value_Default__c != null ? Decimal.valueOf(covLineItem.Option_Value_Default__c) : 0;// update by Jitendra on 07-Jan-2022 for MAT-80
                                                    objRecordDetails.requiredLimit = requiredLimit;
                                                }
                                                if(covLineItem.Coverage__r.Coverage_Code__c == 'DOCoverage' && covLineItem.Limits_Deductibles__r.LmtDedCode__c == 'DORetentionAmt' && covLineItem.CoverageLineItemType__c == 'Deductible Option'){
                                                    objRecordDetails.policyRetention = covLineItem.Option_Value_Default__c != null ? Decimal.valueOf(covLineItem.Option_Value_Default__c) : 0;// update by Jitendra on 07-Jan-2022 for MAT-80
                                                }
                                            }
                                            else if(product == 'EPL'){
                                                if(covLineItem.Coverage__r.Coverage_Code__c == 'EPLCoverage'&& covLineItem.CoverageLineItemType__c == 'Main Coverage'){
                                                    objRecordDetails.technicalPremium = covLineItem.Coverage_Premium__c != null ? Decimal.valueOf(covLineItem.Coverage_Premium__c) : 0;
                                                    objRecordDetails.actualPremium = covLineItem.Override_Premium__c != null ? covLineItem.Override_Premium__c : 0;
                                                }
                                                if(covLineItem.Coverage__r.Coverage_Code__c == 'EPLCoverage' && covLineItem.Limits_Deductibles__r.LmtDedCode__c == 'EPLMaxAggLOL' && covLineItem.CoverageLineItemType__c == 'Limit Option'){
                                                    requiredLimit = covLineItem.Option_Value_Default__c != null ? Decimal.valueOf(covLineItem.Option_Value_Default__c) : 0;
                                                    objRecordDetails.requiredLimit = requiredLimit;
                                                }
                                                if(covLineItem.Coverage__r.Coverage_Code__c == 'EPLCoverage' && covLineItem.Limits_Deductibles__r.LmtDedCode__c == 'EPLRetentionAmt' && covLineItem.CoverageLineItemType__c == 'Deductible Option'){
                                                    objRecordDetails.policyRetention = covLineItem.Option_Value_Default__c !=null ? Decimal.valueOf(covLineItem.Option_Value_Default__c) : 0;
                                                }
                                            }*/

                                        }

            objRecordDetails.technicalPremium = technicalPremium;
            lstRecordDetails.add(objRecordDetails);

        }

        objWrap.listRecordDetails = lstRecordDetails;
        objWrap.objQuote = objQuote;
        return objWrap;
        
    }

    @AuraEnabled
    public static String saveQuotePremium(Quote objQuote){

        String returnMsg = '';
        if(objQuote != null){
            update objQuote;
            returnMsg = 'success';
        }

        return returnMsg;

    }

    public class RelatedListWrapper {
        @AuraEnabled
        public List <RecordDetails> listRecordDetails;
        @AuraEnabled
        public Quote objQuote;
        @AuraEnabled
        public List <String> lstSelectedProduct;
    }

    public class RecordDetails {
        @AuraEnabled
        public String productName {get;set;}
        @AuraEnabled
        public Boolean isSectionHidden {get;set;}
        @AuraEnabled
        public Boolean isOptionalCoverage {get;set;}
        @AuraEnabled
        public String backgroundColorHeader {get;set;}
        @AuraEnabled
        public Decimal overallRatingModifier {get;set;}
        @AuraEnabled
        public Decimal requiredLimit{get;set;}
        @AuraEnabled
        public Decimal executiveLimit{get;set;}
        @AuraEnabled
        public Decimal policyRetention{get;set;}
        @AuraEnabled
        public Decimal technicalPremium{get;set;}
        @AuraEnabled
        public Decimal actualPremium{get;set;}
        @AuraEnabled
        public List<SObject> listRatingModifier{get;set;}

        public RecordDetails(){
            this.productName = '';
            this.isSectionHidden = false;
            this.isOptionalCoverage = false;
            this.backgroundColorHeader = 'slds-accordion__summary slds-box header-background-grey';
            this.overallRatingModifier = 0.0;
            this.requiredLimit = 0.0;
            this.technicalPremium = 0.0;
            this.policyRetention = 0.0;
            this.actualPremium = 0.0;
            listRatingModifier = new List<Rating_Modifier_Factor__c>();
        }
    }

}