main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <label>Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Coverage__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <externalId>true</externalId>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Code__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Code__c</fullName>
    <description>User entered code which will be used across systems (radar, middleware etc)</description>
    <externalId>true</externalId>
    <label>Coverage Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Coverage__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/CoveragesLineItem__c/CoveragesLineItem__c.object-meta.xml
<CustomObject>
    <label>Coverages Line Item</label>
    <nameField>
        <displayFormat>CLI-{00000000}</displayFormat>
        <label>CLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverages Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CoveragesLineItem__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Coverage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Main Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coverage__c</referenceTo>
    <relationshipLabel>Coverages Line Items (Coverage)</relationshipLabel>
    <relationshipName>CoverageQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Code__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Code__c</fullName>
    <formula>Coverage__r.Coverage_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coverage Code</label>
    <type>Text</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Coverage_Product__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Product__c</fullName>
    <label>Coverage Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coverage_Products</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Option_Value_Default__c.field-meta.xml
<CustomField>
    <fullName>Option_Value_Default__c</fullName>
    <label>Option Value Default</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Coverages Line Items</relationshipLabel>
    <relationshipName>Coverages_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/CyberCoveragesTemp__c.object-meta.xml
<CustomObject>
    <label>Cyber Coverages Temp Data</label>
    <nameField>
        <displayFormat>Temp - {0000000}</displayFormat>
        <label>Cyber Coverages Temp Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CyberCoveragesTemp</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/CyberCoveragesTemp__c/fields/BIandExtraExpensesNP__c.field-meta.xml
<CustomField>
    <fullName>BIandExtraExpensesNP__c</fullName>
    <label>BIandExtraExpenses-NonProratedPremium</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/BIandExtraExpensesQP__c.field-meta.xml
<CustomField>
    <fullName>BIandExtraExpensesQP__c</fullName>
    <label>BIandExtraExpensesQP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/CyberCrimeNP__c.field-meta.xml
<CustomField>
    <fullName>CyberCrimeNP__c</fullName>
    <label>CyberCrimeNP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/CyberCrimeQP__c.field-meta.xml
<CustomField>
    <fullName>CyberCrimeQP__c</fullName>
    <label>CyberCrimeQP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/DataBreachLiabilityNP__c.field-meta.xml
<CustomField>
    <fullName>DataBreachLiabilityNP__c</fullName>
    <label>DataBreachLiabilityNP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/DataBreachLiabilityQP__c.field-meta.xml
<CustomField>
    <fullName>DataBreachLiabilityQP__c</fullName>
    <label>DataBreachLiabilityQP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/FundsTransferNP__c.field-meta.xml
<CustomField>
    <fullName>FundsTransferNP__c</fullName>
    <label>FundsTransferNP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/FundsTransferQP__c.field-meta.xml
<CustomField>
    <fullName>FundsTransferQP__c</fullName>
    <label>FundsTransferQP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/InsuredSystemFailureNP__c.field-meta.xml
<CustomField>
    <fullName>InsuredSystemFailureNP__c</fullName>
    <label>InsuredSystemFailureNP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/InsuredSystemFailureQP__c.field-meta.xml
<CustomField>
    <fullName>InsuredSystemFailureQP__c</fullName>
    <label>InsuredSystemFailureQP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/InvoiceManipulationNP__c.field-meta.xml
<CustomField>
    <fullName>InvoiceManipulationNP__c</fullName>
    <label>InvoiceManipulationNP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/InvoiceManipulationQP__c.field-meta.xml
<CustomField>
    <fullName>InvoiceManipulationQP__c</fullName>
    <label>InvoiceManipulationQP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/OutsourceSecurityFailureNP__c.field-meta.xml
<CustomField>
    <fullName>OutsourceSecurityFailureNP__c</fullName>
    <label>OutsourceSecurityFailureNP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/OutsourceSecurityFailureQP__c.field-meta.xml
<CustomField>
    <fullName>OutsourceSecurityFailureQP__c</fullName>
    <label>OutsourceSecurityFailureQP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/OutsourceSystemFailureNP__c.field-meta.xml
<CustomField>
    <fullName>OutsourceSystemFailureNP__c</fullName>
    <label>OutsourceSystemFailureNP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/OutsourceSystemFailureQP__c.field-meta.xml
<CustomField>
    <fullName>OutsourceSystemFailureQP__c</fullName>
    <label>OutsourceSystemFailureQP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/PCIFinesAndAssessmentNP__c.field-meta.xml
<CustomField>
    <fullName>PCIFinesAndAssessmentNP__c</fullName>
    <label>PCIFinesAndAssessmentNP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/PCIFinesAndAssessmentQP__c.field-meta.xml
<CustomField>
    <fullName>PCIFinesAndAssessmentQP__c</fullName>
    <label>PCIFinesAndAssessmentQP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>QuoteId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/ReferenceId__c.field-meta.xml
<CustomField>
    <fullName>ReferenceId__c</fullName>
    <label>ReferenceId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/RegDefenceAndPenaltiesNP__c.field-meta.xml
<CustomField>
    <fullName>RegDefenceAndPenaltiesNP__c</fullName>
    <label>RegDefenceAndPenaltiesNP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/RegDefenceAndPenaltiesQP__c.field-meta.xml
<CustomField>
    <fullName>RegDefenceAndPenaltiesQP__c</fullName>
    <label>RegDefenceAndPenaltiesQP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/SocialEngineeringNP__c.field-meta.xml
<CustomField>
    <fullName>SocialEngineeringNP__c</fullName>
    <label>SocialEngineeringNP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/SocialEngineeringQP__c.field-meta.xml
<CustomField>
    <fullName>SocialEngineeringQP__c</fullName>
    <label>SocialEngineeringQP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/TelecomFraudNP__c.field-meta.xml
<CustomField>
    <fullName>TelecomFraudNP__c</fullName>
    <label>TelecomFraudNP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/CyberCoveragesTemp__c/fields/TelecomFraudQP__c.field-meta.xml
<CustomField>
    <fullName>TelecomFraudQP__c</fullName>
    <label>TelecomFraudQP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/classes/CyberCliUpdateBatchTest.cls
/**
 * @description       : 
 * @author            : Vinayesh
 * @group             : 
 * @last modified on  : 07-01-2022
 * @last modified by  : Vinayesh
**/
@isTest
public class CyberCliUpdateBatchTest {	
    @testSetup
    public static void testSetup() {
        
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        insert acc;
        
        Product2 product = TestUtil.createProduct('Cyber Standalone');
        product.IsActive = true;
        insert product; 
        
        List<Coverage__c> insertCoverageList1 = New List<Coverage__c>();

        Coverage__c cov9 = TestUtil.createCoverage('DataBreachLiability', 'Cyber');
        cov9.Coverage_Code__c = 'DataBreachLiability';
        insertCoverageList1.add(cov9);

        Coverage__c cov10 = TestUtil.createCoverage('CyberCrime', 'Cyber');
        cov10.Coverage_Code__c = 'CyberCrime';
        insertCoverageList1.add(cov10);

        Coverage__c cov11 = TestUtil.createCoverage('BIandExtraExpenses', 'Cyber');
        cov11.Coverage_Code__c = 'BIandExtraExpenses';
        insertCoverageList1.add(cov11);

        insert insertCoverageList1;

        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.Name = 'Test Opportunity';
        opp.CloseDate = Date.today()+10;
        opp.StageName = 'Qualified';
        opp.Effective_Date__c = Date.today();
        opp.Expiration_Date__c = Date.today()+120;
        opp.Azure_ID__c= 'Test Id';
        opp.Probability= 0.5;
        insert opp; 

        Quote quote = TestUtil.createQuote('Quote Test',opp.Id);
        quote.Azure_ID__c = 'Test Az 1';
        insert quote;

        CyberCoveragesTemp__c covPremiumData = new CyberCoveragesTemp__c();
        covPremiumData.QuoteId__c = 'Test Az 1';
        covPremiumData.ReferenceId__c = quote.Id;
        covPremiumData.RegDefenceAndPenaltiesQP__c = 10.546;
        covPremiumData.SocialEngineeringQP__c = 10.546;
        covPremiumData.CyberCrimeNP__c = 10.546;
        covPremiumData.DataBreachLiabilityNP__c = 10.546;
        covPremiumData.FundsTransferNP__c = 10.546;
        covPremiumData.BIandExtraExpensesQP__c = 10.546;
        covPremiumData.InsuredSystemFailureNP__c = 10.546;
        covPremiumData.InvoiceManipulationNP__c = 10.546;
        covPremiumData.InvoiceManipulationQP__c = 10.546;
        covPremiumData.PCIFinesAndAssessmentNP__c = 10.546;
        covPremiumData.CyberCrimeQP__c = 10.546;
        covPremiumData.InsuredSystemFailureQP__c = 10.546;
        covPremiumData.FundsTransferQP__c = 10.546;
        covPremiumData.OutsourceSystemFailureNP__c = 10.546;
        covPremiumData.RegDefenceAndPenaltiesNP__c = 10.546;
        covPremiumData.TelecomFraudQP__c = 10.546;
        covPremiumData.OutsourceSecurityFailureQP__c = 10.546;
        covPremiumData.OutsourceSecurityFailureNP__c = 10.546;
        covPremiumData.PCIFinesAndAssessmentQP__c = 10.546;
        covPremiumData.OutsourceSystemFailureQP__c = 10.546;
        covPremiumData.SocialEngineeringNP__c = 10.546;
        covPremiumData.TelecomFraudNP__c = 10.546;
        covPremiumData.BIandExtraExpensesNP__c = 10.546;
        covPremiumData.DataBreachLiabilityQP__c = 10.546;

        insert covPremiumData;

        List<Coverage__c> insertCoverageList = New List<Coverage__c>();
        //Create coverage
        Coverage__c cov = TestUtil.createCoverage('RegDefenceAndPenalties', 'Cyber');
        cov.Coverage_Code__c = 'RegDefenceAndPenalties';
        insertCoverageList.add(cov);
        
        Coverage__c cov1 = TestUtil.createCoverage('PCIFinesAndAssessment', 'Cyber');
        cov1.Coverage_Code__c = 'PCIFinesAndAssessment';
        insertCoverageList.add(cov1);

        Coverage__c cov2 = TestUtil.createCoverage('SocialEngineering', 'Cyber');
        cov2.Coverage_Code__c = 'SocialEngineering';
        insertCoverageList.add(cov2);

        Coverage__c cov3 = TestUtil.createCoverage('FundsTransfer', 'Cyber');
        cov3.Coverage_Code__c = 'FundsTransfer';
        insertCoverageList.add(cov3);

        Coverage__c cov4 = TestUtil.createCoverage('InvoiceManipulation', 'Cyber');
        cov4.Coverage_Code__c = 'InvoiceManipulation';
        insertCoverageList.add(cov4);

        Coverage__c cov5 = TestUtil.createCoverage('TelecomFraud', 'Cyber');
        cov5.Coverage_Code__c = 'TelecomFraud';
        insertCoverageList.add(cov5);

        Coverage__c cov6 = TestUtil.createCoverage('OutsourceSecurityFailure', 'Cyber');
        cov6.Coverage_Code__c = 'OutsourceSecurityFailure';
        insertCoverageList.add(cov6);

        Coverage__c cov7 = TestUtil.createCoverage('InsuredSystemFailure', 'Cyber');
        cov7.Coverage_Code__c = 'InsuredSystemFailure';
        insertCoverageList.add(cov7);

        Coverage__c cov8 = TestUtil.createCoverage('OutsourceSystemFailure', 'Cyber');
        cov8.Coverage_Code__c = 'OutsourceSystemFailure';
        insertCoverageList.add(cov8);



        insert insertCoverageList;    
    }
    @isTest static void cyberUpdateTest() {
        Coverage__c cov8 = TestUtil.createCoverage('TestCov', 'Cyber');
        cov8.Coverage_Code__c = 'teSTJSDKNFKSD';
        insert cov8;
        Quote quote1 = [Select Id From Quote];
        GlobalStaticVar.byPassCoverageLineItemTrigger = true;
        GlobalStaticVar.byPassQuoteTrigger = true;
        CoveragesLineItem__c cli1 = new CoveragesLineItem__c();
        cli1.Quote__c = quote1.Id;
        cli1.Coverage_Product__c = cov8.Coverage_Product__c;
        cli1.Coverage__c = cov8.Id;
        cli1.Option_Value_Default__c = 'Coverage';
        insert cli1;

        Test.startTest();
        CyberCliUpdateBatch cb = new CyberCliUpdateBatch();
        Id batchId = Database.executeBatch(cb, 10);
        Test.stopTest();
        //System.assertEquals(1, [select count() from Opportunity where Renewed__c = true]);
    }

    @isTest static void cliIsSelectedUpdateTest() {
        GlobalStaticVar.byPassQuoteTrigger = true;

        Opportunity opp = [Select Id from Opportunity limit 1];
        Quote qt = [Select Id from Quote limit 1];
        qt.Quote_Type__c = 'Renewal';
        update qt;
        Quote quote = TestUtil.createQuote('Quote Test1',opp.Id);
        quote.Azure_ID__c = 'Test Az 2';
        quote.Quote_Type__c = 'Amendment';
        insert quote;

        Coverage__c cov8 = TestUtil.createCoverage('TestCov', 'Cyber');
        cov8.Coverage_Code__c = 'OFAC';
        insert cov8;
        GlobalStaticVar.byPassCoverageLineItemTrigger = true;
        GlobalStaticVar.byPassQuoteTrigger = true;
        CoveragesLineItem__c cli1 = new CoveragesLineItem__c();
        cli1.Quote__c = quote.Id;
        cli1.Coverage_Product__c = cov8.Coverage_Product__c;
        cli1.Coverage__c = cov8.Id;
        cli1.Option_Value_Default__c = 'Coverage';
        insert cli1;

        Test.startTest();
        UpdateCliSelectedFieldBatch cb = new UpdateCliSelectedFieldBatch();
        Id batchId = Database.executeBatch(cb, 5);
        Test.stopTest();
        // Test.startTest();
        // UpdateCliSelectedFieldBatch cb = new UpdateCliSelectedFieldBatch();
        // Id batchId = Database.executeBatch(cb, 5);
        // Test.stopTest();
        //System.assertEquals(1, [select count() from Opportunity where Renewed__c = true]);
    }

    @isTest static void overallRatingFactorTest() {

         
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test1', 'Business', '1231 Main Street', 'Anycity', 'New York', '11354', 'United States');
        insert acc;

        Product2 product1 = TestUtil.createProduct('Private Company Combo');
        insert product1;
        
        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product1.Id);
        opp.Name = 'Test Opportunity1';
        opp.CloseDate = Date.today()+10;
        opp.StageName = 'Qualified';
        opp.Effective_Date__c = Date.today();
        opp.Expiration_Date__c = Date.today()+120;
        opp.Azure_ID__c= 'Test Id1';
        opp.Probability= 0.5;
        insert opp;

        Quote quote = TestUtil.createQuote('Quote Test',opp.Id);
        quote.Azure_ID__c = 'Test Az 2';
        quote.Status = 'Rated';
        insert quote;

        Test.startTest();
        OverallRatingFactorUpdateBatch cb = new OverallRatingFactorUpdateBatch();
        Id batchId = Database.executeBatch(cb, 3);
        Test.stopTest();
        //System.assertEquals(1, [select count() from Opportunity where Renewed__c = true]);
    }
}