main/default/objects/Rating_Modifiers__c/Rating_Modifiers__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier</label>
    <nameField>
        <label>Rating Modifiers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifiers__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Rating Modifiers</relationshipLabel>
    <relationshipName>Rating_Modifiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Aqueous</fullName>
                <isActive>false</isActive>
                <label>Aqueous</label>
            </value>
            <value>
                <fullName>Cel1</fullName>
                <isActive>false</isActive>
                <label>Cel1</label>
            </value>
            <value>
                <fullName>D&amp;O Standalone</fullName>
                <isActive>false</isActive>
                <label>D&amp;O Standalone</label>
            </value>
            <value>
                <fullName>New Test</fullName>
                <isActive>false</isActive>
                <label>New Test</label>
            </value>
            <value>
                <fullName>Test</fullName>
                <isActive>false</isActive>
                <label>Test</label>
            </value>
            <value>
                <fullName>Test Product 00</fullName>
                <isActive>false</isActive>
                <label>Test Product 00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Rating_Modifier_Code__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Code__c</fullName>
    <label>Rating Modifier Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/classes/RatingModifierQueryUtilTest.cls
/**************************************************************************************************
 * Class Name: RatingModifierQueryUtilTest
 * Author: RINKU SAINI
 * Date: Dec 28th, 2021
 * Description: Class to keep rating modifiers queries
 **************************************************************************************************/

@isTest
public class RatingModifierQueryUtilTest {
    
    public static testmethod void coverRatingModifierQueryUtil(){
        Test.startTest();
        
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        insert acc;
        
        Product2 product = TestUtil.createProduct('MPL Standalone');
        insert product; 
        
        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.CloseDate = Date.today();
        opp.StageName = 'Prospect';
        opp.Azure_ID__c = '123';
        insert opp;
        
        
        Rating_Modifiers__c ratingModifier = new Rating_Modifiers__c(Name = 'New Rating Modifier1',Product__c='MPL',
                                                                     Rating_Modifier_Code__c='abcd', Opportunity__c = opp.Id );
        insert ratingModifier;
        
        RatingModifierQueryUtil.fetchRatingModifiersByOpportunity(opp.Id);   
        RatingModifierQueryUtil.fetchRatingModifiersByOpportunityAndProduct( New Set<Id>{opp.Id}, New List<String>{'MPL Standalone'});
        RatingModifierQueryUtil.fetchRatingModifiersByOpportunityForRiskCapture( New Set<String>{opp.Id});
        RatingModifierQueryUtil.fetchRatingModifiersByNameAndOppId( New Set<Id>{opp.Id} );
        RatingModifierQueryUtil.fetchRatingModifiersByCodeAndOppId( New Set<String>{opp.Id} );
        RatingModifierQueryUtil.fetchRatingModifiersByDisplayFormate( New List<Id>{opp.Id}, New List<String>{''});
        Test.stopTest();
    }
}