main/default/objects/Rating_Modifiers__c/Rating_Modifiers__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier</label>
    <nameField>
        <label>Rating Modifiers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifiers__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Rating Modifiers</relationshipLabel>
    <relationshipName>Rating_Modifiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Aqueous</fullName>
                <isActive>false</isActive>
                <label>Aqueous</label>
            </value>
            <value>
                <fullName>Cel1</fullName>
                <isActive>false</isActive>
                <label>Cel1</label>
            </value>
            <value>
                <fullName>D&amp;O Standalone</fullName>
                <isActive>false</isActive>
                <label>D&amp;O Standalone</label>
            </value>
            <value>
                <fullName>New Test</fullName>
                <isActive>false</isActive>
                <label>New Test</label>
            </value>
            <value>
                <fullName>Test</fullName>
                <isActive>false</isActive>
                <label>Test</label>
            </value>
            <value>
                <fullName>Test Product 00</fullName>
                <isActive>false</isActive>
                <label>Test Product 00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Rating_Modifier_Value__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Value__c</fullName>
    <label>Rating Modifier Value</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Subjectivity_Template__c/Subjectivity_Template__c.object-meta.xml
<CustomObject>
    <label>Subjectivity Template</label>
    <nameField>
        <displayFormat>TEMP-{0000}</displayFormat>
        <label>Subjectivity Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subjectivity Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Subjectivity_Template__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aqueous</fullName>
            </value>
            <value>
                <fullName>Celerity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Profession_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Profession_Criteria__c</fullName>
    <label>Profession Criteria</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accountants</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Design &amp; Construct</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Insurance Brokers</fullName>
            </value>
            <value>
                <fullName>IT Consultants</fullName>
            </value>
            <value>
                <fullName>Media Professionals</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Property Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Subjectivity_Name__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Name__c</fullName>
    <label>Subjectivity Name</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Subjectivity_Text__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Text__c</fullName>
    <label>Subjectivity Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/classes/RatingModifiersTriggerHandlerTest.cls
/**
 * @description       : 
 * @author            : Maeran Shaikh
 * @group             : 
 * @last modified on  : 12-21-2021
 * @last modified by  : Maeran Shaikh
**/
@isTest
private class RatingModifiersTriggerHandlerTest {
    
    @testSetup
    public static void setupData() {
        Product2 product = TestUtil.createProduct('Cyber');
        insert product;

        Product2 product2 = TestUtil.createProduct('Professional Indemnity');
        insert product2;

        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        insert acc;

        Opportunity opportunity = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opportunity.StageName = 'Qualified';
        insert opportunity;

        Opportunity opportunity2 = TestUtil.createOpportunity('Opp Test',acc.Id, product2.Id);
        opportunity.StageName = 'Qualified';
        insert opportunity2;
        
         Quote quote1 = TestUtil.createQuote('New quote 1', opportunity.Id);
        quote1.Status = 'Rated';
        insert quote1; 
        
        Quote quote2 = TestUtil.createQuote('New quote 1', opportunity2.Id);
        quote2.Status = 'Rated';
        insert quote2;

        /* opportunity.StageName = 'Closed Won';
         update opportunity;*/

        Rating_Modifiers__c rM = new Rating_Modifiers__c(Name = 'Test Rating Modifier', Opportunity__c = opportunity.Id,Product__c ='Cyber', Rating__c = true,Rating_Modifier_Value__c = 'Test 1');
        insert rM;

        Rating_Modifiers__c rM2 = new Rating_Modifiers__c(Name = 'Test Rating Modifier2', Opportunity__c = opportunity2.Id,Product__c = 'Professional Indemnity', Rating__c = true,Rating_Modifier_Value__c = 'Test 21');
        insert rM2;
		
        Rating_Modifiers__c rM3 = new Rating_Modifiers__c(Name = 'Test Rating Modifier3', Opportunity__c = opportunity2.Id, Rating__c = true,Rating_Modifier_Value__c = 'Test 21');
        insert rM3;

        Rating_Modifiers__c rM4 = new Rating_Modifiers__c(Name = 'Proposal Form Date', Product__c = 'Professional Indemnity', Rating_Modifier_Value__c = 'test', Opportunity__c = opportunity2.Id, Rating__c = true);
        insert rM4;

        Subjectivity_Template__c subjectivityTemplate = new Subjectivity_Template__c();
        subjectivityTemplate.Subjectivity_Name__c = 'Signed / Dated Proposal';
        subjectivityTemplate.Subjectivity_Text__c = 'Test';
        subjectivityTemplate.Profession_Criteria__c = 'Engineers';
        insert subjectivityTemplate;
    }
    
    @isTest
    static void testBeforeInsert() {
        Opportunity o = [SELECT Id FROM Opportunity LIMIT 1];
        Rating_Modifiers__c rM = new Rating_Modifiers__c(Name = 'New Rating Modifier', Opportunity__c = o.Id);
		Test.startTest();
        insert rM;
        Test.stopTest();
        System.assert(true);
    }
    
    @isTest
    static void testBeforeUpdate() {

        Rating_Modifiers__c rM = [SELECT Id,Rating__c,Rating_Modifier_Value__c FROM Rating_Modifiers__c WHERE Name = 'Test Rating Modifier'];
        rM.Rating_Modifier_Value__c = 'Testing 123';
		Test.startTest();
        update rM;
        Test.stopTest();
        System.assert(true);
    }


    @isTest
    static void testBeforeUpdateAQ() {

        Rating_Modifiers__c rM = [SELECT Id,Rating__c,Rating_Modifier_Value__c FROM Rating_Modifiers__c WHERE Name = 'Test Rating Modifier2'];
        rM.Rating_Modifier_Value__c = 'Testing 123';
		Test.startTest();
        update rM;
        Test.stopTest();
        System.assert(true);
    }
    
     @isTest
    static void testBeforeUpdateOthers() {

        Rating_Modifiers__c rM = [SELECT Id,Rating__c,Rating_Modifier_Value__c FROM Rating_Modifiers__c WHERE Name = 'Test Rating Modifier3'];
        rM.Rating_Modifier_Value__c = 'Testing 123';
		Test.startTest();
        update rM;
        Test.stopTest();
        System.assert(true);
    }

    @isTest
    static void testBeforeUpdateProposalFormDate() {

        Rating_Modifiers__c rM = [SELECT Id,Rating__c,Rating_Modifier_Value__c FROM Rating_Modifiers__c WHERE Name = 'Proposal Form Date'];
		Test.startTest();
        rm.Rating_Modifier_Value__c = null;
        update rM;
        Test.stopTest();
        System.assert(true);
    }
}