main/default/objects/Rating_Modifiers__c/Rating_Modifiers__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier</label>
    <nameField>
        <label>Rating Modifiers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifiers__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Rating Modifiers</relationshipLabel>
    <relationshipName>Rating_Modifiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Aqueous</fullName>
                <isActive>false</isActive>
                <label>Aqueous</label>
            </value>
            <value>
                <fullName>Cel1</fullName>
                <isActive>false</isActive>
                <label>Cel1</label>
            </value>
            <value>
                <fullName>D&amp;O Standalone</fullName>
                <isActive>false</isActive>
                <label>D&amp;O Standalone</label>
            </value>
            <value>
                <fullName>New Test</fullName>
                <isActive>false</isActive>
                <label>New Test</label>
            </value>
            <value>
                <fullName>Test</fullName>
                <isActive>false</isActive>
                <label>Test</label>
            </value>
            <value>
                <fullName>Test Product 00</fullName>
                <isActive>false</isActive>
                <label>Test Product 00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rating_Modifiers__c/fields/Rating_Modifier_Value__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier_Value__c</fullName>
    <label>Rating Modifier Value</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Subjectivity__c/Subjectivity__c.object-meta.xml
<CustomObject>
    <label>Subjectivity</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subjectivity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subjectivity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Subjectivity__c/fields/Cleared__c.field-meta.xml
<CustomField>
    <fullName>Cleared__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cleared</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Cleared_Date__c.field-meta.xml
<CustomField>
    <fullName>Cleared_Date__c</fullName>
    <label>Cleared Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Subjectivity</relationshipLabel>
    <relationshipName>Subjectivity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Bind</fullName>
                <default>true</default>
                <label>Pre-Bind</label>
            </value>
            <value>
                <fullName>Post-Bind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity__c</fullName>
    <label>Subjectivity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity_Template__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subjectivity Template</label>
    <referenceTo>Subjectivity_Template__c</referenceTo>
    <relationshipLabel>Subjectivity</relationshipLabel>
    <relationshipName>Subjectivity</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity_Text__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Text__c</fullName>
    <label>Subjectivity Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Subjectivity_Template__c/Subjectivity_Template__c.object-meta.xml
<CustomObject>
    <label>Subjectivity Template</label>
    <nameField>
        <displayFormat>TEMP-{0000}</displayFormat>
        <label>Subjectivity Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subjectivity Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Subjectivity_Template__c/fields/Cleared__c.field-meta.xml
<CustomField>
    <fullName>Cleared__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cleared</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Cleared_Date__c.field-meta.xml
<CustomField>
    <fullName>Cleared_Date__c</fullName>
    <label>Cleared Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aqueous</fullName>
            </value>
            <value>
                <fullName>Celerity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Profession_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Profession_Criteria__c</fullName>
    <label>Profession Criteria</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accountants</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Design &amp; Construct</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Insurance Brokers</fullName>
            </value>
            <value>
                <fullName>IT Consultants</fullName>
            </value>
            <value>
                <fullName>Media Professionals</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Property Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Bind</fullName>
            </value>
            <value>
                <fullName>Post-Bind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Subjectivity_Name__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Name__c</fullName>
    <label>Subjectivity Name</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Subjectivity_Text__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Text__c</fullName>
    <label>Subjectivity Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/classes/RatingModifiersTriggerHandler_AQ.cls
/**************************************************************************************************
 * Class Name: RatingModifiersTriggerHandler_AQ
 * Author: 
 * Date: 
 * Description: Class to keep method related to Aqueous
 * Test Class : RatingModifiersTriggerHandlerTest
 **************************************************************************************************/
public with sharing class RatingModifiersTriggerHandler_AQ extends TriggerHandler{
    private List<Rating_Modifiers__c> oldDataList;
    private List<Rating_Modifiers__c> newDataList; 
    private Map<Id, Rating_Modifiers__c> newDataMap;
    private Map<Id, Rating_Modifiers__c> oldDataMap; 
    
    public RatingModifiersTriggerHandler_AQ(List<Rating_Modifiers__c> newDataList, List<Rating_Modifiers__c> oldDataList, Map<Id, Rating_Modifiers__c> newDataMap, Map<Id, Rating_Modifiers__c> oldDataMap){
        this.oldDataList = oldDataList;
        this.newDataList = newDataList;
        this.newDataMap = newDataMap;
        this.oldDataMap = oldDataMap;
    } 

	public override void beforeInsert()	{
        //generate external id
        CommonUtil.generateExternalID('Azure_ID__c', newDataList);
    }

    public override void beforeUpdate(){
        //generate external id
        CommonUtil.generateExternalID('Azure_ID__c', newDataList);
    }

	public override void afterInsert(){

    }

	public override void afterUpdate(){
        //if proposal form date is empty, create a subjectivity record
        createSubjectivityIfProposalFormDateEmpty(newDataList,oldDataMap);
    }


     /*************************************************
    * Method Name: createSubjectivityIfProposalFormDateEmpty
    * Author:
    * Date: 
    * Params: List<Rating_Modifiers__c> rmRecordList
    * Return: 
    * Exceptions:
    * Description: Create subjectivities based on proposal form date
    * Revision: 
    * Can be done with flows: Yes
     *************************************************/
    public static void createSubjectivityIfProposalFormDateEmpty(List<Rating_Modifiers__c> rmRecordList,Map<Id, Rating_Modifiers__c> oldDataMap) {
        Set<Id> oppIdSet = new Set<Id>();
        List<Subjectivity__c> subjectivityListToCreate = new List<Subjectivity__c>(); 
        try{  
            for( Rating_Modifiers__c rmRecord : rmRecordList ){

                if(rmRecord.Name == 'Proposal Form Date' && rmRecord.Opportunity__c !=null && rmRecord.Rating_Modifier_Value__c == null
                  && rmRecord.Product__c == 'Professional Indemnity' && rmRecord.Rating_Modifier_Value__c != oldDataMap.get(rmRecord.Id).Rating_Modifier_Value__c){

                    oppIdSet.add(rmRecord.Opportunity__c);

                    break;
                }
            }
            System.debug('oppIdSet::'+oppIdSet);
            List<Subjectivity_Template__c> subjTemp = [SELECT Id, Name, Profession_Criteria__c, Subjectivity_Name__c, Subjectivity_Text__c 
                                                           FROM Subjectivity_Template__c 
                                                           WHERE Subjectivity_Name__c ='Signed / Dated Proposal'];
            List<Quote> quotes = [Select Id,OpportunityId, Product_Name__c from Quote WHERE OpportunityId IN :oppIdSet];

            if(!quotes.isEmpty() && subjTemp != null && subjTemp.size() > 0){
                for(Quote quote : quotes){
                    Subjectivity__c subRec = new Subjectivity__c(); 
                    subRec.Quote__c = quote.Id;
                    subRec.Subjectivity__c = subjTemp[0].Subjectivity_Name__c;
                    subRec.Subjectivity_Text__c = subjTemp[0].Subjectivity_Text__c;
                    subRec.Stage__c = 'Pre-Bind';
                    subRec.Cleared__c = false;
                    subRec.Cleared_Date__c = null;
                    subRec.Subjectivity_Template__c = subjTemp[0].Id;

                   
                    subRec.RecordTypeId = Schema.SObjectType.Subjectivity__c.getRecordTypeInfosByName().get(GlobalVariables.RT_NAME_SUBJECTIVITY_AQUEOUS).getRecordTypeId();
                    
                    subjectivityListToCreate.add(subRec);
                }
            }
            if(!subjectivityListToCreate.isEmpty()) insert subjectivityListToCreate;

            if(Test.isRunningTest())
                throw new DmlException();
    	}
        catch (Exception ex) {
            String errorMsg = 'Failed to create Subjectivity.<br/>Please contact your administator.';
            for(Rating_Modifiers__c item : (List<Rating_Modifiers__c>)Trigger.new ){
                if(!Test.isRunningTest()) item.addError(errorMsg);
            }
        }
    }
}