main/default/objects/Document_Revision__c/Document_Revision__c.object-meta.xml
<CustomObject>
    <label>Document Revision</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Revisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Document_Revision__c/fields/Document_Azure_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Azure_Id__c</fullName>
    <label>Document Azure Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

main/default/objects/Document_Revision__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Document Revisions</relationshipLabel>
    <relationshipName>Document_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Document_Revision__c/fields/Quote_Id__c.field-meta.xml
<CustomField>
    <fullName>Quote_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Document Revisions</relationshipLabel>
    <relationshipName>Document_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Document_Revision__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <label>Policy</label>
</RecordType>

main/default/objects/Document_Revision__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

main/default/objects/Payment_Detail__c/Payment_Detail__c.object-meta.xml
<CustomObject>
    <description>Payment Detail</description>
    <label>Payment Detail</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>Payment Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Payment_Detail__c/fields/Card_Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>Card_Holder_Name__c</fullName>
    <label>Card Holder Name</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

main/default/objects/Payment_Detail__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Payment Details</relationshipLabel>
    <relationshipName>Payment_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Payment_Detail__c/fields/Processor_Response_Type__c.field-meta.xml
<CustomField>
    <fullName>Processor_Response_Type__c</fullName>
    <label>Processor Response Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

main/default/objects/Payment_Detail__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <label>Transaction ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Initial_Premium__c.field-meta.xml
<CustomField>
    <fullName>Initial_Premium__c</fullName>
    <label>Initial Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Bound Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>D_O</fullName>
                <label>D&amp;O</label>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Total_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_Premium__c</fullName>
    <label>Total Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Policy__c/recordTypes/Celerity.recordType-meta.xml
<RecordType>
    <fullName>Celerity</fullName>
    <active>true</active>
    <label>Celerity</label>
</RecordType>

main/default/objects/Subjectivity__c/Subjectivity__c.object-meta.xml
<CustomObject>
    <label>Subjectivity</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subjectivity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subjectivity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Subjectivity__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Subjectivity</relationshipLabel>
    <relationshipName>Subjectivity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity__c</fullName>
    <label>Subjectivity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity_Status__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Status__c</fullName>
    <label>Subjectivity Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity__c/fields/Subjectivity_Type__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Type__c</fullName>
    <label>Subjectivity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
                <default>true</default>
                <label>General</label>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/REST_Invsk_QuoteOperation_v2_Test.cls
@isTest
public class REST_Invsk_QuoteOperation_v2_Test {
@testSetup
    public static void setup() {
       // Test.startTest();
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        insert acc;
        
        Product2 product = TestUtil.createProduct('Celerity');
        insert product; 
        
        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.CloseDate = Date.today();
        opp.StageName = 'Prospect';
        insert opp;
        
        Quote quote1 = TestUtil.createQuote('New quote 1', opp.Id);
        quote1.Status = 'Rated';
        quote1.Rating_Status__c ='Clear';
        quote1.Azure_ID__c = '854db2f3';
        quote1.Coverage_Product_Options__c = 'D&O';
        quote1.Refer_Type__c = 'Underwriting Referral';
        insert quote1;  
        
        Document_Revision__c documentRevision = new Document_Revision__c();
        documentRevision.Quote_Id__c = quote1.Id;
        documentRevision.Document_Azure_Id__c= 'Test Document';
        insert documentRevision;
        
        Subjectivity__c subj = new Subjectivity__c();
        subj.Subjectivity__c = 'Testing';
        subJ.Subjectivity_Status__c = 'Open';
        subJ.Subjectivity_Type__c = 'MPL';
        subJ.Quote__c = quote1.Id;
        subJ.RecordTypeId = Schema.SObjectType.Subjectivity__c.getRecordTypeInfosByName().get(GlobalVariables.RT_NAME_SUBJECTIVITY_CELERITY).getRecordTypeId();
        insert subJ;
        
        Policy__c policy = new Policy__c();
        policy.Account__c = acc.Id;
        policy.Product_Name__c = 'MPL';
        policy.Expiration_Date__c = Date.today().addDays(100);
        policy.Total_Premium__c = 2000;
        policy.Initial_Premium__c = null;
        insert policy;
      //  Test.stopTest();
    }
    
    @isTest
    static void testQuoteInvalidAzureId() {
       Test.startTest();
        REST_Invsk_QuoteOperation_v2.CommingRequest com = new REST_Invsk_QuoteOperation_v2.CommingRequest();
        Opportunity currentOpp = [SELECT Azure_ID__c FROM Opportunity];
        com.quoteAzureId = currentOpp.Azure_ID__c;
        com.operation = 'FinalizeQuote';
        com.status = '';

        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_QuoteOperation_v2';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(com));

        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;
        
        REST_Invsk_QuoteOperation_v2.doPost();
        Test.stopTest();
        
        System.assertEquals(400, RestContext.response.statusCode);
    }
    @isTest
    static void testQuoteFinalizeError() {
       
        REST_Invsk_QuoteOperation_v2.CommingRequest com = new REST_Invsk_QuoteOperation_v2.CommingRequest();
        Quote currentQuote = [SELECT Azure_ID__c FROM Quote];
        currentQuote.Status ='In Progress';
        update currentQuote;
        com.quoteAzureId = currentQuote.Azure_ID__c;
        com.operation = 'FinalizeQuote';

        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_QuoteOperation_v2';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(com));
        RestResponse response = new RestResponse();
        
        RestContext.request = request;
        RestContext.response = response;
        Test.startTest();
        REST_Invsk_QuoteOperation_v2.doPost();
        Test.stopTest();
        
        System.assertEquals(400, RestContext.response.statusCode);
    }

    @isTest
    static void testStatusUpdateQuoted() {
         Test.startTest();

        REST_Invsk_QuoteOperation_v2.CommingRequest com = new REST_Invsk_QuoteOperation_v2.CommingRequest();
        Quote currentQuote = [SELECT Azure_ID__c FROM Quote];
        com.quoteAzureId = currentQuote.Azure_ID__c;
        com.operation = 'StatusUpdate';
        com.status = 'Quoted';
        
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_QuoteOperation_v2';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(com));

        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;
       
        REST_Invsk_QuoteOperation_v2.doPost();
        Test.stopTest();
        
        System.assertEquals(200, RestContext.response.statusCode);
    }
    @isTest
    static void testStatusUpdateClosed() {

        REST_Invsk_QuoteOperation_v2.CommingRequest com = new REST_Invsk_QuoteOperation_v2.CommingRequest();
        Quote currentQuote = [SELECT status,Azure_ID__c FROM Quote];
        com.quoteAzureId = currentQuote.Azure_ID__c;
        com.operation = 'StatusUpdate';
        com.status = 'Closed';
        com.closedReason ='Closed';

        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_QuoteOperation_v2';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(com));

        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;
        Test.startTest();
        REST_Invsk_QuoteOperation_v2.doPost();
        Test.stopTest();
        
        System.assertEquals(currentQuote.status, 'Rated');
    }

    @isTest
    static void testAzureIDempty() {
        List<String> errors = new List<String>();
        REST_Invsk_QuoteOperation_v2.CommingRequest com = new REST_Invsk_QuoteOperation_v2.CommingRequest();
        com.quoteAzureId = '';
        com.operation = '';
        com.status = '';

        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_QuoteOperation_v2';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(com));

        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;
        Test.startTest();
        REST_Invsk_QuoteOperation_v2.doPost();
        Test.stopTest();
        
        System.assertEquals(400, RestContext.response.statusCode);
    }

    @isTest
    static void testQuoteOperationCaseStatusUpdateEmpty() {
        
        REST_Invsk_QuoteOperation_v2.CommingRequest com = new REST_Invsk_QuoteOperation_v2.CommingRequest();
        Quote currentQuote = [SELECT Azure_ID__c FROM Quote];
        com.quoteAzureId = currentQuote.Azure_ID__c; 
        com.operation = 'StatusUpdate';
        com.status = '';

        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_QuoteOperation_v2';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(com));

        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;
        Test.startTest();
        REST_Invsk_QuoteOperation_v2.doPost();
        Test.stopTest();
        
        System.assertEquals(200, RestContext.response.statusCode);
    }
    @isTest
    static void testQuoteInvalidOperation() {
        
        REST_Invsk_QuoteOperation_v2.CommingRequest com = new REST_Invsk_QuoteOperation_v2.CommingRequest();
        Quote currentQuote = [SELECT Azure_ID__c FROM Quote];
        com.quoteAzureId = currentQuote.Azure_ID__c; 
        com.operation = 'Invalid';

        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_QuoteOperation_v2';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(com));

        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;
        Test.startTest();
        REST_Invsk_QuoteOperation_v2.doPost();
        Test.stopTest();
        
        System.assertEquals(200, RestContext.response.statusCode);
    }
    @isTest
    static void testQuoteOperationChangeSummary() {
        
        List<String> errors = new List<String>();
        REST_Invsk_QuoteOperation_v2.CommingRequest com = new REST_Invsk_QuoteOperation_v2.CommingRequest();
        Quote currentQuote = [SELECT Azure_ID__c FROM Quote];
        com.quoteAzureId = currentQuote.Azure_ID__c; 
        com.operation = 'ChangeSummary';
        com.status = '';

        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_QuoteOperation_v2';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(com));

        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;
        Test.startTest();
        REST_Invsk_QuoteOperation_v2.doPost();
        Test.stopTest();
        
        System.assertEquals(200, RestContext.response.statusCode);
    }   

    @isTest 
    static void bindQuoteTest(){
       
        Policy__c policy = [Select Id FROM Policy__c];
        policy.Policy_Status__c = 'Cancelled';
        update policy;
        Quote quo =  [SELECT Id,Azure_Id__c FROM Quote Limit 1];
        quo.Status = 'Quoted';
        quo.Policy__c = policy.Id;
        update quo;
        Test.startTest();
        REST_Invsk_QuoteOperation_v2.CommingRequest comingReq = new REST_Invsk_QuoteOperation_v2.CommingRequest();
		comingReq.quoteAzureId = quo.Azure_ID__c;
        comingReq.operation = 'BindQuote';
        Payment_Detail__c paymentDetails = new Payment_Detail__c();
        paymentDetails.Transaction_ID__c = 'abcdef';
        paymentDetails.Card_Holder_Name__c = 'HolderName';
        paymentDetails.Processor_Response_Type__c = 'Test process';
        paymentDetails.Amount__c = 200;
        paymentDetails.Processor_Response_Type__c = 'Monthly'; 
        comingReq.paymentDetails = paymentDetails;

        String myJSON = JSON.serialize(comingReq);
        RestRequest request = new RestRequest();
		RestResponse res = new RestResponse();
        request.requestUri = '/services/apexrest/Invsk_QuoteOperation_v2/';
        request.httpMethod = 'POST';
		request.requestBody = Blob.valueof(myJSON);
		request.addHeader('Content-Type', 'application/json'); 
        RestContext.request = request;
		RestContext.response = res;

        REST_Invsk_QuoteOperation_v2.doPost();
        system.assertEquals('Quoted', [Select Status FROM Quote WHERE ID =: quo.Id].Status);
    	test.stopTest();
    }   
    @isTest 
    static void bindQuoteTestException(){
       
        Policy__c policy = [Select Id FROM Policy__c];
        Quote quo =  [SELECT Id,Azure_Id__c FROM Quote Limit 1];
        
        Test.startTest();
        REST_Invsk_QuoteOperation_v2.CommingRequest comingReq = new REST_Invsk_QuoteOperation_v2.CommingRequest();
		comingReq.quoteAzureId = quo.Azure_ID__c;
        comingReq.operation = 'BindQuote';
 
        String myJSON = JSON.serialize(comingReq);
        RestRequest request = new RestRequest();
		RestResponse res = new RestResponse();
        request.requestUri = '/services/apexrest/Invsk_QuoteOperation_v2/';
        request.httpMethod = 'POST';
		request.requestBody = Blob.valueof(myJSON);
		request.addHeader('Content-Type', 'application/json'); 
        RestContext.request = request;
		RestContext.response = res;

        REST_Invsk_QuoteOperation_v2.doPost();
        system.assertEquals('Rated', [Select Status FROM Quote WHERE ID =: quo.Id].Status);
    	test.stopTest();
    }   
}