main/default/objects/Document_Revision__c/Document_Revision__c.object-meta.xml
<CustomObject>
    <label>Document Revision</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Revisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Document_Revision__c/fields/Document_Azure_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Azure_Id__c</fullName>
    <label>Document Azure Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

main/default/objects/Document_Revision__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Document Revisions</relationshipLabel>
    <relationshipName>Document_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Document_Revision__c/fields/Quote_Id__c.field-meta.xml
<CustomField>
    <fullName>Quote_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Document Revisions</relationshipLabel>
    <relationshipName>Document_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Document_Revision__c/fields/Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type__c</fullName>
    <formula>TEXT(Quote_Id__r.Quote_Type__c)</formula>
    <label>Quote Type</label>
    <type>Text</type>
</CustomField>

main/default/objects/Document_Revision__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <label>Policy</label>
</RecordType>

main/default/objects/Document_Revision__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

main/default/objects/Payment_Detail__c/Payment_Detail__c.object-meta.xml
<CustomObject>
    <description>Payment Detail</description>
    <label>Payment Detail</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>Payment Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Payment_Detail__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Payment Details</relationshipLabel>
    <relationshipName>Payment_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date__c</fullName>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-Payment</fullName>
            </value>
            <value>
                <fullName>Business Closed</fullName>
            </value>
            <value>
                <fullName>Insured Request</fullName>
            </value>
            <value>
                <fullName>Sanctions/OFAC</fullName>
            </value>
            <value>
                <fullName>Merger or Acquisition</fullName>
            </value>
            <value>
                <fullName>Completion of Operation</fullName>
            </value>
            <value>
                <fullName>Underwriting Reasons</fullName>
            </value>
            <value>
                <fullName>Finance Company Request</fullName>
            </value>
            <value>
                <fullName>Product Unsuitable / Misunderstood</fullName>
            </value>
            <value>
                <fullName>Product too expensive</fullName>
            </value>
            <value>
                <fullName>Alternate Product Purchased</fullName>
            </value>
            <value>
                <fullName>Cover overlapped with pre-existing cover</fullName>
            </value>
            <value>
                <fullName>Product cancelled within cooling off period</fullName>
            </value>
            <value>
                <fullName>Product cancelled by Underwriter</fullName>
            </value>
            <value>
                <fullName>Poor service / complaint</fullName>
            </value>
            <value>
                <fullName>Cover no longer required</fullName>
            </value>
            <value>
                <fullName>Other (administrative reason)</fullName>
            </value>
            <value>
                <fullName>Not Known</fullName>
            </value>
            <value>
                <fullName>Non Payment of premium</fullName>
            </value>
            <value>
                <fullName>Cancellation ab initio</fullName>
                <isActive>false</isActive>
                <label>Cancellation ab initio</label>
            </value>
            <value>
                <fullName>Cancellation mid term</fullName>
                <isActive>false</isActive>
                <label>Cancellation mid term</label>
            </value>
            <value>
                <fullName>Cancelled due to non-payment of premium</fullName>
                <isActive>false</isActive>
                <label>Cancelled due to non-payment of premium</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Bound Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>D_O</fullName>
                <label>D&amp;O</label>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/REST_Invsk_QuoteOperation_v2.cls
/**************************************************************************************************
* Class Name: REST_Invsk_QuoteOperation_v2
* Author: Priyanka Fulwani
* Created date: 04-Nov-2020
* Description: REST web service API for Quote Operation v2
**************************************************************************************************/
@RestResource(urlMapping='/Invsk_QuoteOperation_v2/*')
global with sharing class REST_Invsk_QuoteOperation_v2 {
    @HttpPost
    global static void doPost() {
        
        OutcomingResponse outResponse = new OutcomingResponse();
        RestRequest req = RestContext.request;
        CommingRequest commingRequest = (CommingRequest) JSON.deserializeStrict(req.requestBody.toString(), CommingRequest.class);
        
        try {
            
            if (String.isBlank(commingRequest.quoteAzureId)) {
                outResponse.status = 'Failed';
                outResponse.isSuccess = false;
                outResponse.errors.add('Quote AzureId cannot be Empty');
                RestContext.response.statusCode = 400;
                RestContext.response.addHeader('Content-Type', 'application/json');
                RestContext.response.responseBody = Blob.valueOf(JSON.serialize(outResponse));
                ApiUtil.logAPICallIn(RestContext.request, RestContext.response, 'REST_Invsk_QuoteOperation_v2', 'REST_Invsk_QuoteOperation_v2.doPost');
                return;
            }
            
            List<Quote> QuoteList = [SELECT Id,Azure_Id__c,Status,Product_Name__c FROM Quote WHERE Azure_Id__c = :commingRequest.quoteAzureId];
            
            if(QuoteList.isEmpty()) {
                outResponse.status = 'Failed';
                outResponse.isSuccess = false;
                outResponse.errors.add('Invalid Quote AzureId');
                RestContext.response.statusCode = 400;
                RestContext.response.addHeader('Content-Type', 'application/json');
                RestContext.response.responseBody = Blob.valueOf(JSON.serialize(outResponse));
                ApiUtil.logAPICallIn(RestContext.request, RestContext.response, 'REST_Invsk_QuoteOperation_v2', 'REST_Invsk_QuoteOperation_v2.doPost');
                return;
            } 
            
            if (commingRequest.operation != 'FinalizeQuote'
                && commingRequest.operation != 'BindQuote'
                && commingRequest.operation != 'StatusUpdate'
                && commingRequest.operation != 'ChangeSummary') {
                    outResponse.status = 'Failed';
                    outResponse.isSuccess = false;
                    outResponse.errors.add('INVALID OPERATION');
                    RestContext.response.statusCode = 200;
                    RestContext.response.addHeader('Content-Type', 'application/json');
                    RestContext.response.responseBody = Blob.valueOf(JSON.serialize(outResponse));
                    ApiUtil.logAPICallIn(RestContext.request, RestContext.response, 'REST_Invsk_QuoteOperation_v2', 'REST_Invsk_QuoteOperation_v2.doPost');
                    return;
                }
            
            if (commingRequest.operation == 'StatusUpdate' && String.isBlank(commingRequest.status)) {
                outResponse.status = 'Failed';
                outResponse.isSuccess = false;
                outResponse.errors.add('Status value is required for operation StatusUpdate');
                RestContext.response.statusCode = 200;
                RestContext.response.addHeader('Content-Type', 'application/json');
                RestContext.response.responseBody = Blob.valueOf(JSON.serialize(outResponse));
                ApiUtil.logAPICallIn(RestContext.request, RestContext.response, 'REST_Invsk_QuoteOperation_v2', 'REST_Invsk_QuoteOperation_v2.doPost');
                return;
            }
            
            if(commingRequest.operation == 'ChangeSummary'){
                QuoteEndorsementChangeSummaryCtrl.getQuoteEndorsementChangeSummary(QuoteList[0].Id,true);
            }
            
            if(commingRequest.operation == 'FinalizeQuote'){
                
                ResultResponse result =  FinalizeQuoteController.finalizeQuote(QuoteList[0].Id);
                 outResponse.status = 'Passed';
                 outResponse.isSuccess = true;
                system.debug('result==>'+result);
                if(!result.errors.isEmpty()){
                    outResponse.status = 'Failed';
                    outResponse.isSuccess = false;
                    outResponse.errors.add(result.errors[0]);
                    RestContext.response.statusCode = 400;
                    RestContext.response.addHeader('Content-Type', 'application/json');
                    RestContext.response.responseBody = Blob.valueOf(JSON.serialize(outResponse));
                    ApiUtil.logAPICallIn(RestContext.request, RestContext.response, 'REST_Invsk_QuoteOperation_v2', 'REST_Invsk_QuoteOperation_v2.doPost');
                    return;   
                }
                
            }else if(commingRequest.operation == 'BindQuote'){
                if(QuoteList[0].Status =='Quoted' || QuoteList[0].Status =='Presented' || QuoteList[0].Status =='Bound Pending'){
                    system.debug('PN->'+QuoteList[0].Product_Name__c);
                    BindQuoteController.bindQuoteIncoming(QuoteList[0].Id, commingRequest.billingType, false);
                    if (QuoteList[0].Product_Name__c == 'Cyber Standalone' || QuoteList[0].Product_Name__c == 'MPL Standalone' ){
                       BindQuoteController.bindQuoteWithBLInfo(QuoteList[0].Id, commingRequest.billingType, false, req.requestBody.toString());
                       system.debug('Bind all license info');
                    }
                    outResponse.status = 'Passed';
                    outResponse.isSuccess = true;
                }
                else{
                    outResponse.status = 'Failed';
                    outResponse.isSuccess = false;
                    outResponse.errors.add('The Quote Status must be Quoted/Presented/Bound Pending to Bind Quote.');
                    RestContext.response.statusCode = 400;
                    RestContext.response.addHeader('Content-Type', 'application/json');
                    RestContext.response.responseBody = Blob.valueOf(JSON.serialize(outResponse));
                    ApiUtil.logAPICallIn(RestContext.request, RestContext.response, 'REST_Invsk_QuoteOperation_v2', 'REST_Invsk_QuoteOperation_v2.doPost');
                    return;   
                }
                //Fetch latest generated Policy Id -
                Quote quote = [Select Id, Policy__r.Policy_Number__c,Endorsement_Quote_Bound_Date__c, 
                               Sequence_Number__c,Policy__r.Policy_Status__c, Azure_Id__c, Policy__c, Quote_Type__c
                               FROM QUOTE WHERE Azure_Id__c =:commingRequest.quoteAzureId];
                // Added for US:52026 on 23/9/2021
                if(String.isNotBlank(commingRequest.policyBoundDate)){
                    quote.Endorsement_Quote_Bound_Date__c = Datetime.valueOf(commingRequest.policyBoundDate);
                    TriggerHandler.bypass('QuoteTriggerBaseHandler');
                    update quote;
                    TriggerHandler.clearBypass('QuoteTriggerBaseHandler');  

                }

                if(String.isNotBlank(quote.Policy__c))
                {
                    if(commingRequest.paymentDetails != null) // Check and insert Payment Detail
                    { 
                        commingRequest.paymentDetails.Policy__c = quote.Policy__c;
                        insert commingRequest.paymentDetails;
                    }
                    
                    String quoteType = quote.Quote_Type__c;                   
                    String contractStatus = quote.Policy__r.Policy_Status__c;
                    // Added for US:52026 on 23/9/2021
                    Policy__c policy = new Policy__c(Id = quote.Policy__c);
                    if(String.isNotBlank(commingRequest.policyAzureId)){
                        policy.Azure_ID__c = commingRequest.policyAzureId;
                    }
                    if(String.isNotBlank(commingRequest.policyNumber)){
                        policy.Policy_Number__c = commingRequest.policyNumber;
                    }

                    if((quoteType == 'Midterm Cancellation' || quoteType == 'Flat Cancellation') && contractStatus=='Cancelled')
                    {                        
                        
                        policy.Cancellation_Date__c =String.isNotBlank(commingRequest.CancellationDate)?Date.valueOf(commingRequest.CancellationDate):null;
                        policy.Cancellation_Reason__c = String.isNotBlank(commingRequest.CancellationReason)?commingRequest.CancellationReason:null;
                       
                    }
                    update policy;
                }
                outResponse.result.put('PolicyNumber', quote.Policy__r.Policy_Number__c);
                outResponse.result.put('Quote Type', quote.Quote_Type__c);
                outResponse.result.put('BoundDateTime', quote.Endorsement_Quote_Bound_Date__c.format('YYYY-MM-dd kk:mm:ss'));
            } 
            else if (commingRequest.operation == 'StatusUpdate') {
                
                Quote currentQuote = QuoteList[0];
                currentQuote.Status = commingRequest.status;
                if (currentQuote.Status == 'Quoted') {
                    currentQuote.Rating_Status__c = 'Clear';
                }
                if (currentQuote.Status == 'Closed') {
                    currentQuote.Closed_Reason__c = commingRequest.closedReason;
                }
                update currentQuote;
                outResponse.result.put('closedReason', commingRequest.closedReason);
            }
            
        Quote Quoteresult = [SELECT Azure_Id__c, Status,Rating_Status__c, (select Id, Document_Azure_Id__c from Document_Revisions__r) FROM Quote WHERE Azure_Id__c = :commingRequest.quoteAzureId];
        
        outResponse.result.put('quoteId', commingRequest.quoteAzureId);
        outResponse.result.put('Quote Status', Quoteresult.Status);
        if(Quoteresult.Status =='Quoted' && Quoteresult.Rating_Status__c =='Clear')
        outResponse.result.put('documentId', Quoteresult.Document_Revisions__r[0].Document_Azure_Id__c);
        
        RestContext.response.statusCode = 200;
        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.responseBody = Blob.valueOf(JSON.serialize(outResponse));
            outResponse.status = 'Success';
            outResponse.isSuccess = true;
            outResponse.errors.clear();
        } catch (Exception ex) {
            outResponse.status = 'Failed';
            outResponse.isSuccess = false;
            outResponse.errors.add(CommonUtil.getExceptionMessage(ex)); 
        } 
        ApiUtil.logAPICallIn(RestContext.request, RestContext.response, 'REST_Invsk_QuoteOperation_v2', 'REST_Invsk_QuoteOperation_v2.doPost');       
        
    }
    public class CommingRequest {
        public String quoteAzureId;
        public String operation;
        public String status;
        public String channelType;
        public String closedReason;
        public String CancellationDate; 
        public String CancellationReason;
        public Payment_Detail__c paymentDetails;
        public String billingType; 
        // Added by Maeran for US: 52026
        public String policyNumber; 
        public String policyAzureId; 
        public String policyBoundDate; 
        //Added by Juhi for US: 57225
        public String bindingLicenseNumber;
        public String bindingLicenseOwner;
        public String bindingLicenseOwnerAddress;
        public String bindingLicenseOwnerName;
        public Boolean IsSignaturePackUploaded;
    }
    
    public class OutcomingResponse {
        public String status                {get; set;}
        public List<String> errors          {get; set;}
        public Boolean isSuccess            {get; set;}
        public Map<String, Object> result   {get; set;}
        
        public OutcomingResponse() {
            this.status = null;
            this.isSuccess = false;
            this.errors = new List<String>();
            this.result = new Map<String, Object>();
        }
    }
    
}