main/default/objects/Document_Revision__c/Document_Revision__c.object-meta.xml
<CustomObject>
    <label>Document Revision</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Revisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Document_Revision__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SOA</fullName>
            </value>
            <value>
                <fullName>Binder</fullName>
            </value>
            <value>
                <fullName>PolicyForm</fullName>
                <label>Policy Form</label>
            </value>
            <value>
                <fullName>ChangeEndorsement</fullName>
                <label>Change Endorsement</label>
            </value>
            <value>
                <fullName>QuoteProposal</fullName>
                <label>Quote Proposal</label>
            </value>
            <value>
                <fullName>WorkSheet</fullName>
            </value>
            <value>
                <fullName>QuoteSchedulePrimary</fullName>
                <label>Quote Schedule Primary</label>
            </value>
            <value>
                <fullName>QuoteScheduleExcess</fullName>
                <label>Quote Schedule Excess</label>
            </value>
            <value>
                <fullName>PolicySchedulePrimary</fullName>
                <label>Policy Schedule Primary</label>
            </value>
            <value>
                <fullName>PolicyScheduleExcess</fullName>
                <label>Policy Schedule Excess</label>
            </value>
            <value>
                <fullName>QuoteSchedulePrimaryAmendment</fullName>
                <label>Quote Schedule Primary Amendment</label>
            </value>
            <value>
                <fullName>QuoteScheduleExcessAmendment</fullName>
                <label>Quote Schedule Excess Amendment</label>
            </value>
            <value>
                <fullName>ExcessPolicyAmendment</fullName>
            </value>
            <value>
                <fullName>PrimaryPolicyAmendment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Document_Revision__c/fields/Quote_Id__c.field-meta.xml
<CustomField>
    <fullName>Quote_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Document Revisions</relationshipLabel>
    <relationshipName>Document_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Document_Revision__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

main/default/classes/DocumentRevisionTriggerHandler_CEL.cls
/**************************************************************************************************
 * Class Name: DocumentRevisionTriggerHandler_CEL
 * Author: Vinay
 * Date: 24th Dec 2021
 * Description: Class to keep document revision methods
 * Test Class : 
 **************************************************************************************************/
public with sharing class DocumentRevisionTriggerHandler_CEL extends TriggerHandler{
    private List<Document_Revision__c> oldDataList;
    private List<Document_Revision__c> newDataList; 
    private Map<Id, Document_Revision__c> newDataMap;
    private Map<Id, Document_Revision__c> oldDataMap; 
    
    public DocumentRevisionTriggerHandler_CEL(List<Document_Revision__c> newDataList, List<Document_Revision__c> oldDataList, Map<Id, Document_Revision__c> newDataMap, Map<Id, Document_Revision__c> oldDataMap){
        this.oldDataList = oldDataList;
        this.newDataList = newDataList;
        this.newDataMap = newDataMap;
        this.oldDataMap = oldDataMap;
    }  

    public override void beforeInsert()	{

    }

    public override void beforeUpdate(){

    }

	public override void afterInsert(){
        callSyncQuoteBatch(this.newDataList);
    }

	public override void afterUpdate(){
        callSyncQuoteBatch(this.newDataList);
    }

    /*************************************************
    * Method Name: callSyncQuoteBatch
    * Author: 
    * Date: 
    * Params: List<Document_Revision__c>
    * Return: 
    * Description: Sync quotes when document revision type is set as "Quote Proposal"
     *************************************************/
    public static void callSyncQuoteBatch(List<Document_Revision__c> newDataList){
        Set<Id> quoteIds  = new Set<Id>();
        List<Quote> quotes  = new List<Quote>();
        
        for(Document_Revision__c doc :newDataList){
                if(String.isNotBlank(doc.Quote_Id__c))
                {
                    if(doc.Document_Type__c =='QuoteProposal')
                	{                       
                    	quoteIds.add(doc.Quote_Id__c);
                    }
                }            
        }
        for(Quote q : QuoteQueryUtil.fetchCyberMPLQuotesByQuoteIDs(quoteIds)){
            quotes.add(q);
        }

        System.enqueueJob(new SyncQuoteQueueable(quotes));
    } 
}