main/default/objects/Document_Revision__c/Document_Revision__c.object-meta.xml
<CustomObject>
    <label>Document Revision</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Revisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Document_Revision__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SOA</fullName>
            </value>
            <value>
                <fullName>Binder</fullName>
            </value>
            <value>
                <fullName>PolicyForm</fullName>
                <label>Policy Form</label>
            </value>
            <value>
                <fullName>ChangeEndorsement</fullName>
                <label>Change Endorsement</label>
            </value>
            <value>
                <fullName>QuoteProposal</fullName>
                <label>Quote Proposal</label>
            </value>
            <value>
                <fullName>WorkSheet</fullName>
            </value>
            <value>
                <fullName>QuoteSchedulePrimary</fullName>
                <label>Quote Schedule Primary</label>
            </value>
            <value>
                <fullName>QuoteScheduleExcess</fullName>
                <label>Quote Schedule Excess</label>
            </value>
            <value>
                <fullName>PolicySchedulePrimary</fullName>
                <label>Policy Schedule Primary</label>
            </value>
            <value>
                <fullName>PolicyScheduleExcess</fullName>
                <label>Policy Schedule Excess</label>
            </value>
            <value>
                <fullName>QuoteSchedulePrimaryAmendment</fullName>
                <label>Quote Schedule Primary Amendment</label>
            </value>
            <value>
                <fullName>QuoteScheduleExcessAmendment</fullName>
                <label>Quote Schedule Excess Amendment</label>
            </value>
            <value>
                <fullName>ExcessPolicyAmendment</fullName>
            </value>
            <value>
                <fullName>PrimaryPolicyAmendment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Document_Revision__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Document Revisions</relationshipLabel>
    <relationshipName>Document_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Document_Revision__c/fields/Quote_Id__c.field-meta.xml
<CustomField>
    <fullName>Quote_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Document Revisions</relationshipLabel>
    <relationshipName>Document_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Document_Revision__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <label>Policy</label>
</RecordType>

main/default/objects/Document_Revision__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Subjectivity_Template__c/Subjectivity_Template__c.object-meta.xml
<CustomObject>
    <label>Subjectivity Template</label>
    <nameField>
        <displayFormat>TEMP-{0000}</displayFormat>
        <label>Subjectivity Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subjectivity Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Subjectivity_Template__c/fields/Profession_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Profession_Criteria__c</fullName>
    <label>Profession Criteria</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accountants</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Design &amp; Construct</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Insurance Brokers</fullName>
            </value>
            <value>
                <fullName>IT Consultants</fullName>
            </value>
            <value>
                <fullName>Media Professionals</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Property Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Subjectivity_Name__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Name__c</fullName>
    <label>Subjectivity Name</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Subjectivity_Template__c/fields/Subjectivity_Text__c.field-meta.xml
<CustomField>
    <fullName>Subjectivity_Text__c</fullName>
    <label>Subjectivity Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/classes/REST_Invsk_UpdateDocumentIdTest.cls
/**
 * Class Name: REST_Invsk_UpdateDocumentIdTest 
* Author: Vinith K
* Date: 15-Feb-2021
* Requirement/Project Name: Innovisk
*/
@isTest
private class REST_Invsk_UpdateDocumentIdTest {
	public Static String azureId = ''; 
	static{
        Id brokerRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account accBroker = TestUtil.createAccount('Account_Business_Test_01', brokerRtId, '5305, Monroe Street', 'Toledo', 'Ohio','43623', 'United States');
        insert accBroker;             
        
        // create product
        Product2 product = TestUtil.createProduct('Test Product');
        insert product;
        
        // create opportunity        
        Opportunity opp = TestUtil.createOpportunity('Test Opportunity', accBroker.Id, product.Id);
        opp.StageName = 'Qualified';
        insert opp;
        
     /*   Subjectivity_Template__c subjectivityTemplate = new Subjectivity_Template__c();
        subjectivityTemplate.Subjectivity_Name__c = 'Signed / Dated Proposal';
        subjectivityTemplate.Subjectivity_Text__c = 'Test';
        subjectivityTemplate.Profession_Criteria__c = 'Engineers';
        insert subjectivityTemplate;*/
        
        // create Quote
        Quote q = TestUtil.createQuote('Test Quote', opp.Id);
        q.Rating_Status__c = 'Clear';
        q.Status = 'Bound';
        insert q;
         
         // create policy  
        Policy__c policy = new Policy__c();        
        policy.Azure_ID__c = '123456';
        policy.Account__c = accBroker.Id; 
        policy.Expiration_Date__c = Date.today().addDays(100);           
        insert policy;
		
        azureId = new GuidUtil().NewGuid();
        Quote newQuote = [Select Id, Azure_ID__c from Quote limit 1 ];
        newQuote.Azure_ID__c = azureId;
        newQuote.Policy__c = policy.Id;
        update newQuote;

    }

	@isTest
    static void testDoPostReqNull() {
        
        // Set up a test request
		RestRequest request = new RestRequest();
		request.requestUri = '/services/apexrest/Invsk_UpdateDocumentId';
		request.httpMethod = 'POST';
		request.requestBody = Blob.valueOf(JSON.serialize(null));
		RestContext.request = request;


    	RestResponse response  = new RestResponse();
		RestContext.response = response; 

		Test.startTest();
        REST_Invsk_UpdateDocumentId.doPost();
        Test.stopTest();
		System.assertEquals(200, RestContext.response.statusCode);     
    }

	@isTest
    static void testDoPost() {
        Test.startTest();
        Quote newQuote = [Select Id,Azure_Id__c From Quote Where Azure_Id__c = :azureId];
        
        Document_Revision__c tranSitD = new Document_Revision__c();
		tranSitD.Quote_Id__c = newQuote.Id;
		tranSitD.Document_Type__c = 'QuoteProposal';
		insert tranSitD;
		        
		REST_Invsk_UpdateDocumentId.ComingRequestWrapper requestWrapper = new REST_Invsk_UpdateDocumentId.ComingRequestWrapper(); 
		requestWrapper.docType = 'QuoteProposal';
		requestWrapper.quoteId = newQuote.Azure_ID__c;
		requestWrapper.docId = tranSitD.Id;
        requestWrapper.Name = requestWrapper.docType  + '.pdf';
        
        REST_Invsk_UpdateDocumentId.ComingRequestWrapper requestWrapper2 = new REST_Invsk_UpdateDocumentId.ComingRequestWrapper(); 
		requestWrapper2.docType = 'Binder';
		requestWrapper2.quoteId = newQuote.Azure_ID__c;
		requestWrapper2.docId = tranSitD.Id;
        requestWrapper2.Name = requestWrapper2.docType  + '.pdf';

		String q = '"quoteId":"'+ newQuote.Azure_ID__c + '"'; 
		String d = '"docId":"' + tranSitD.Id + '"'; 
		String p = '"docType":"QuoteProposal"';
        String n = '"Name":"QuoteProposal.pdf"';

		String reqString = '[{' + q + ',' + d + ',' + p + ', ' + n + '}]';
        
      

     // Set up a test request
		RestRequest request = new RestRequest();
		request.requestUri = '/services/apexrest/Invsk_UpdateDocumentId';
		request.httpMethod = 'POST';
		request.requestBody = Blob.valueOf(reqString);
		RestContext.request = request;

    	RestResponse response  = new RestResponse();
		RestContext.response = response; 

		
        REST_Invsk_UpdateDocumentId.doPost();
        Test.stopTest();
		System.assertEquals(200, RestContext.response.statusCode);     
    }
    @isTest
    static void testDoPost2() {
        Test.startTest();
        Quote newQuote = [Select Id,Azure_Id__c From Quote Where Azure_Id__c = :azureId];
        
        Document_Revision__c tranSitD = new Document_Revision__c();
		tranSitD.Quote_Id__c = newQuote.Id;
		tranSitD.Document_Type__c = 'QuoteProposal';
		insert tranSitD;
		        
		REST_Invsk_UpdateDocumentId.ComingRequestWrapper requestWrapper = new REST_Invsk_UpdateDocumentId.ComingRequestWrapper(); 
		requestWrapper.docType = 'QuoteProposal';
		requestWrapper.quoteId = newQuote.Azure_ID__c;
		requestWrapper.docId = tranSitD.Id;
        requestWrapper.Name = requestWrapper.docType  + '.pdf';
        
        REST_Invsk_UpdateDocumentId.ComingRequestWrapper requestWrapper2 = new REST_Invsk_UpdateDocumentId.ComingRequestWrapper(); 
		requestWrapper2.docType = 'Binder';
		requestWrapper2.quoteId = newQuote.Azure_ID__c;
		requestWrapper2.docId = tranSitD.Id;
        requestWrapper2.Name = requestWrapper2.docType  + '.pdf';

		String q = '"quoteId":"'+ newQuote.Azure_ID__c + '"'; 
		String d = '"docId":"' + tranSitD.Id + '"'; 
		String p = '"docType":"Binder"';
        String n = '"Name":"QuoteProposal.pdf"';

		String reqString = '[{' + q + ',' + d + ',' + p + ', ' + n + '}]';
        

     // Set up a test request
		RestRequest request = new RestRequest();
		request.requestUri = '/services/apexrest/Invsk_UpdateDocumentId';
		request.httpMethod = 'POST';
		request.requestBody = Blob.valueOf(reqString);
		RestContext.request = request;

    	RestResponse response  = new RestResponse();
		RestContext.response = response; 

		
        REST_Invsk_UpdateDocumentId.doPost();
        Test.stopTest();
		System.assertEquals(200, RestContext.response.statusCode);     
    }


 	@isTest
    static void testDoGetEmptyQuoteId() {

        // Set up a test request
		RestRequest request = new RestRequest();
		request.requestUri = '/services/apexrest/REST_Invsk_UpdateDocumentId';
		request.httpMethod = 'GET';
		request.addParameter('quoteId', '');

		RestResponse response  = new RestResponse();

		RestContext.request = request;
		RestContext.response = response; 

		Test.startTest();
        REST_Invsk_UpdateDocumentId.doGet();
        Test.stopTest();
		System.assertEquals(200, RestContext.response.statusCode);
    }

    @isTest
    static void testDoGetEmptyDoc() {
        
  		Quote newQuote = [Select Id,Azure_Id__c From Quote limit 1];

        REST_Invsk_UpdateDocumentId.ResponseBodyWrapper responseBodyWrapper = new REST_Invsk_UpdateDocumentId.ResponseBodyWrapper(); 
        responseBodyWrapper.docRevisionId = newQuote.Azure_ID__c;
        responseBodyWrapper.docType = '';
        responseBodyWrapper.docName = '';

        // Set up a test request
		RestRequest request = new RestRequest();
		request.requestUri = '/services/apexrest/REST_Invsk_UpdateDocumentId';
		request.httpMethod = 'GET';
		request.addParameter('quoteId', newQuote.Azure_ID__c);

		RestResponse response  = new RestResponse();

		RestContext.request = request;
		RestContext.response = response; 

		Test.startTest();
        REST_Invsk_UpdateDocumentId.doGet();
        Test.stopTest();
		System.assertEquals(200, RestContext.response.statusCode);
    }

     @isTest
    static void testDoGet() {
        
  		Quote newQuote = [Select Id,Azure_Id__c, Policy__c From Quote limit 1];

  		// Create new Transit Detail
		Document_Revision__c tranSitD = new Document_Revision__c();
		tranSitD.Quote_Id__c =  newQuote.Id;
		tranSitD.Policy__c = newQuote.Policy__c;
		insert tranSitD;

        REST_Invsk_UpdateDocumentId.ResponseBodyWrapper responseBodyWrapper = new REST_Invsk_UpdateDocumentId.ResponseBodyWrapper(); 
        responseBodyWrapper.docRevisionId = newQuote.Azure_ID__c;
        responseBodyWrapper.docType = '';
        responseBodyWrapper.docName = '';

        // Set up a test request
		RestRequest request = new RestRequest();
		request.requestUri = '/services/apexrest/Invsk_UpdateDocumentId';
		request.httpMethod = 'GET';
		request.addParameter('quoteId', newQuote.Azure_ID__c);

		RestResponse response  = new RestResponse();

		RestContext.request = request;
		RestContext.response = response; 

		Test.startTest();
        REST_Invsk_UpdateDocumentId.doGet();
        Test.stopTest();
		System.assertEquals(200, RestContext.response.statusCode);    
    }

    @isTest
    static void TestValidRequest1(){
    	REST_Invsk_UpdateDocumentId.ComingRequestWrapper commingRequest = new REST_Invsk_UpdateDocumentId.ComingRequestWrapper();
    	commingRequest.quoteId = '';
        REST_Invsk_UpdateDocumentId.OutComingResponse outComingResponse = new REST_Invsk_UpdateDocumentId.OutComingResponse();
        RestRequest req = new RestRequest();
    
    	REST_Invsk_UpdateDocumentId.validRequest(commingRequest, outComingResponse, req, 0);
    }

    @isTest
    static void TestValidRequest2(){
    	REST_Invsk_UpdateDocumentId.ComingRequestWrapper commingRequest = new REST_Invsk_UpdateDocumentId.ComingRequestWrapper();
        commingRequest.quoteId = 'string';
        commingRequest.docId = 'string';
        commingRequest.docType = '';
        
        REST_Invsk_UpdateDocumentId.OutComingResponse outComingResponse = new REST_Invsk_UpdateDocumentId.OutComingResponse();
        RestRequest req = new RestRequest();
    
    	REST_Invsk_UpdateDocumentId.validRequest(commingRequest, outComingResponse, req, 1);
    }

    @isTest
    static void TestValidRequest3(){
    	REST_Invsk_UpdateDocumentId.ComingRequestWrapper commingRequest = new REST_Invsk_UpdateDocumentId.ComingRequestWrapper();
        commingRequest.quoteId = 'string';
        commingRequest.docType = 'string';
        commingRequest.docId = '';

        REST_Invsk_UpdateDocumentId.OutComingResponse outComingResponse = new REST_Invsk_UpdateDocumentId.OutComingResponse();
        RestRequest req = new RestRequest();
    
    	REST_Invsk_UpdateDocumentId.validRequest(commingRequest, outComingResponse, req, 2);
    }

    
}