main/default/objects/Document_Revision__c/Document_Revision__c.object-meta.xml
<CustomObject>
    <label>Document Revision</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Revisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Document_Revision__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Document Revisions</relationshipLabel>
    <relationshipName>Document_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Document_Revision__c/fields/Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type__c</fullName>
    <formula>TEXT(Quote_Id__r.Quote_Type__c)</formula>
    <label>Quote Type</label>
    <type>Text</type>
</CustomField>

main/default/objects/Document_Revision__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Layer__c.field-meta.xml
<CustomField>
    <fullName>Layer__c</fullName>
    <label>Layer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Bound Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/customSingleRelListCtrlTest.cls
@isTest
public class customSingleRelListCtrlTest {
    
    @testSetup
    static void testSetup(){
        
        TriggerSettings__c triggerSettingsObj = new TriggerSettings__c();
        triggerSettingsObj.BypassQuoteTrigger__c = true;
        insert triggerSettingsObj;
        
        Account accountObj = TestUtil.createBusinessAccount('Test Bussiness Account', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        insert accountObj;
        
        Product2 productObj = TestUtil.createProduct('D&O Standalone');
        insert productObj; 
        
        Opportunity opportunityObj = TestUtil.createOpportunity('Test Opportunity',accountObj.Id, productObj.Id);
        opportunityObj.CloseDate = Date.today();
        opportunityObj.StageName = 'Closed Won';
        opportunityObj.Expiration_Date__c = Date.today()+60;
        insert opportunityObj;
        
        Policy__c policyObj = new Policy__c();
        policyObj.Policy_Number__c = '12345';
        policyObj.Effective_Date__c = Date.today()+5;
        policyObj.Expiration_Date__c = Date.today() + 30;
        policyObj.Policy_Status__c = 'Bound';
        insert policyObj;
        
        Quote quoteObj = TestUtil.createQuote('TestQuote', opportunityObj.Id);
        quoteObj.Status = 'In Progress';
        quoteObj.Coverage_Product_Options__c = 'D&O';
        quoteObj.Refer_Type__c = 'Underwriting Referral';
        quoteObj.Rating_Status__c = 'Refer';
        quoteObj.Last_Quote_Version__c = 'Version 1';
        quoteObj.Policy__c = policyObj.id;
        quoteObj.CloseDate__c = Date.today() + 120;
        quoteObj.Effective_Date__c = system.today()+60;
        quoteObj.ExpirationDate = system.today();
        quoteObj.Quote_Type__c = 'New Business';
        insert quoteObj;  
        
        Document_Revision__c documentRevisionObj = new Document_Revision__c();
        documentRevisionObj.Name = 'Test Revision';
        insert documentRevisionObj;
    }
    
    @isTest
    static void runTest(){
        
        Test.startTest();
        Quote quoteObj = [Select Id,OpportunityId from Quote where Name = 'TestQuote'];
        String fieldConfigDetails = '"label":"","apiName":"QuoteNumber","isHyperlink":"true","":"navigateToRecord":"true";;"label":"Quote Name","apiName":"Name","isHyperlink":"true","":"navigateToRecord":"true";;"label":"Status","apiName":"Status","isHyperlink":"false","":"navigateToRecord":"";;"label":"Layer","apiName":"Layer__c","isHyperlink":"false","":"navigateToRecord":""';
        String relationshipFieldName = 'OpportunityId';
        Document_Revision__c documentRevisionObj = [Select Id from Document_Revision__c where Name = 'Test Revision'];
        customSingleRelListCtrl.getDocRevisionRecord(documentRevisionObj.Id);
        customSingleRelListCtrl.fetchRecords(quoteObj.OpportunityId, 'Quote', fieldConfigDetails, relationshipFieldName, null);
        Test.stopTest();
    }
    
    @isTest
    static void runTest1(){
        
        Test.startTest();
        Quote quoteObj = [Select Id,OpportunityId from Quote where Name = 'TestQuote'];
        String fieldConfigDetails = '"label":"","apiName":"QuoteNumber","isHyperlink":"true","":"navigateToRecord":"true";;"label":"Quote Name","apiName":"Name","isHyperlink":"true","":"navigateToRecord":"true";;"label":"Status","apiName":"Status","isHyperlink":"false","":"navigateToRecord":"";;"label":"Layer","apiName":"Layer__c","isHyperlink":"false","":"navigateToRecord":""';
        String soqlAdditionalWhereCondition = ' AND Layer__c = \'Primary\'';
        String relationshipFieldName = 'OpportunityId';
        customSingleRelListCtrl.fetchRecords(quoteObj.OpportunityId, 'Quote', fieldConfigDetails, relationshipFieldName, soqlAdditionalWhereCondition);
        Test.stopTest();
        
    }
}