main/default/objects/Account_Product__c/Account_Product__c.object-meta.xml
<CustomObject>
    <label>Account Product</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Account_Product__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Project</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Account_Product__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Broker_Account__c/Broker_Account__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Broker_Account__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Broker_Contact__r.AccountId ,  Broker_Contact__r.Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <label>Broker Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker_Contact</value>
        </filterItems>
        <infoMessage>You Must Select a Broker Contact</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Broker_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/IsPrimaryBroker__c.field-meta.xml
<CustomField>
    <fullName>IsPrimaryBroker__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary Broker?</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Broker Accounts</relationshipLabel>
    <relationshipName>Opportunity_Accounts1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Document_Revision__c/Document_Revision__c.object-meta.xml
<CustomObject>
    <label>Document Revision</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Revisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Document_Revision__c/fields/Document_Azure_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Azure_Id__c</fullName>
    <label>Document Azure Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

main/default/objects/Document_Revision__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SOA</fullName>
            </value>
            <value>
                <fullName>Binder</fullName>
            </value>
            <value>
                <fullName>PolicyForm</fullName>
                <label>Policy Form</label>
            </value>
            <value>
                <fullName>ChangeEndorsement</fullName>
                <label>Change Endorsement</label>
            </value>
            <value>
                <fullName>QuoteProposal</fullName>
                <label>Quote Proposal</label>
            </value>
            <value>
                <fullName>WorkSheet</fullName>
            </value>
            <value>
                <fullName>QuoteSchedulePrimary</fullName>
                <label>Quote Schedule Primary</label>
            </value>
            <value>
                <fullName>QuoteScheduleExcess</fullName>
                <label>Quote Schedule Excess</label>
            </value>
            <value>
                <fullName>PolicySchedulePrimary</fullName>
                <label>Policy Schedule Primary</label>
            </value>
            <value>
                <fullName>PolicyScheduleExcess</fullName>
                <label>Policy Schedule Excess</label>
            </value>
            <value>
                <fullName>QuoteSchedulePrimaryAmendment</fullName>
                <label>Quote Schedule Primary Amendment</label>
            </value>
            <value>
                <fullName>QuoteScheduleExcessAmendment</fullName>
                <label>Quote Schedule Excess Amendment</label>
            </value>
            <value>
                <fullName>ExcessPolicyAmendment</fullName>
            </value>
            <value>
                <fullName>PrimaryPolicyAmendment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Document_Revision__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Document Revisions</relationshipLabel>
    <relationshipName>Document_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Document_Revision__c/fields/Quote_Id__c.field-meta.xml
<CustomField>
    <fullName>Quote_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Document Revisions</relationshipLabel>
    <relationshipName>Document_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Document_Revision__c/fields/Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type__c</fullName>
    <formula>TEXT(Quote_Id__r.Quote_Type__c)</formula>
    <label>Quote Type</label>
    <type>Text</type>
</CustomField>

main/default/objects/Document_Revision__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <label>Policy</label>
</RecordType>

main/default/objects/Document_Revision__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <displayFormat>Location-{00000}</displayFormat>
        <label>Location  Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Initial_Premium__c.field-meta.xml
<CustomField>
    <fullName>Initial_Premium__c</fullName>
    <label>Initial Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Policy__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>D_O</fullName>
                <label>D&amp;O</label>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Total_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_Premium__c</fullName>
    <label>Total Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassAccountTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassAccountTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassAccountTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassBrokerAccountTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassBrokerAccountTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassBrokerAccountTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassOpportunityTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassOpportunityTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassOpportunityTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteLineItemTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteLineItemTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteLineItemTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/REST_Invsk_PolicyTest.cls
@isTest
public with sharing class REST_Invsk_PolicyTest {

	private static Opportunity newOppt;
	private static Quote newQuote;
	//private static Equipment__c equipment;
	private static Location__c loc;
	private static Account accBusiness;
	private static Contact contactBroker;
	 @testsetup static void testSetup() {
		// Create Custom Setting
		TriggerSettings__c setting = TestUtil.initialTriggerSetting();
		setting.BypassQuoteTrigger__c = false;
		setting.BypassQuoteLineItemTrigger__c = false;
		setting.BypassOpportunityTrigger__c = false;
		setting.BypassBrokerAccountTrigger__c = false;
		//setting.BypassQuoteEquipmentTrigger__c = false;
		setting.BypassAccountTrigger__c = false;
		update setting;

		// Create Accounts
		List<Account> accountInserts = new List<Account>();
		        
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
		Account accBusiness  =TestUtil.createAccount('Test account 1', recordTypeId, '01 Tran Duy Hung','Westminster',
												'California','90000', 'United States');
         accBusiness.Azure_ID__c = '8042ac98-ae5a-4692-9880-58d92d0eb9d9';
		insert accBusiness;
        system.debug('accBusiness Id'+accBusiness.Id);
        
         Id recordTypeBrokerAgency = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Broker').getRecordTypeId();
        
        Account accBroker = TestUtil.createBusinessAccount('Broker Account Test', 'Broker_Account', '625, South Mill Road', 'Anycity', 'New York', '67074', 'United States');
		accBroker.RecordTypeId = recordTypeBrokerAgency;
		
        insert accBroker;

		Contact contactBroker = TestUtil.createContact(accBroker.Id, 'Broker_Contact', 'New broker contact');
		insert  contactBroker;   

		/*// Create Contact Broker
		Id brokerConRtId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId();
		//contactBroker = TestUtil.createContact('Contact_Broker_Test_01', brokerConRtId, accBorker.Id);
		Contact contactBroker = TestUtil.createContact(accBusiness.Id, 'Broker_Contact', 'New broker contact');
		insert contactBroker;*/

		// Create Product
		/*Id productRtId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Vindati').getRecordTypeId();
		Product2 equipmentProduct = TestUtil.createProduct('Equipment', productRtId, 'Vindati');
		equipmentProduct.Pay_Plan__c = '2 Pay Plan;4 Pay Plan;6 Pay Plan';
		insert equipmentProduct;*/
        
         Product2 product = TestUtil.createProduct('D&O Standalone');
		insert product; 

		Id pricebook2Id = Test.getStandardPricebookId();
		PricebookEntry pricebookEntryEquipment =  TestUtil.createPricebookEntry(pricebook2Id, product.Id);
		insert pricebookEntryEquipment;

		// Create Opportunity
		/*Id opptRtId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Vindati').getRecordTypeId();
		newOppt = TestUtil.createOpportunity('Opportunity Test', accBusiness.Id, 
                                        product.Id, opptRtId, product.Innovisk_Entity_ID__c);
		insert newOppt;*/
        
        Opportunity newOppt = TestUtil.createOpportunity('Opp Test',accBusiness.Id, product.Id);
        newOppt.CloseDate = Date.today()+365;
        newOppt.StageName = 'New';
        newOppt.Azure_ID__c = 'f70e4c82-3378-41ce-870b-57f4df415874';
        insert newOppt;

		// Add Broker to Opportunity
		Broker_Account__c newBroAccount = TestUtil.createBrokerAccount(contactBroker.Id, newOppt.Id);
		insert newBroAccount;

		// Qualify Opportunity
		Opportunity opptUpdate = [Select Id, StageName From Opportunity where Id=: newOppt.Id];
		opptUpdate.StageName = 'Qualified';
		update opptUpdate;

		newQuote = TestUtil.createQuote('test',newOppt.Id);
		newQuote.Status = 'Quoted';
		insert newQuote; 
         
          // create policy  
        Policy__c policy = new Policy__c();
        	policy.Account__c = accBusiness.Id;
        	policy.Product_Name__c = 'MPL';
        	policy.Expiration_Date__c = Date.today().addDays(100);
        	policy.Total_Premium__c = 2000;
        	policy.Initial_Premium__c = null;
        insert policy;



		List<Quote> lstQuote = [SELECT Id,Azure_ID__c FROM Quote WHERE Id = :newQuote.Id];
		//BindQuoteController.bindQuoteFromAPI(lstQuote[0].Azure_ID__c);

		       
        Account_Product__c accProduct = new Account_Product__c();
        accProduct.Account_Id__c = accBusiness.Id;
        accProduct.Product_Id__c = product.id;
        insert accProduct;

		List<Quote> lstQuote2 = [SELECT Id,Azure_ID__c,ContractId FROM Quote WHERE Id = :newQuote.Id];
		Document_Revision__c documentRevision  = new Document_Revision__c(
        	Name = 'QuoteProposal' + '_' + String.valueOf(Datetime.now()),
        	Document_Azure_Id__c = '1',
        	Document_Type__c = 'QuoteProposal',
        	Quote_Id__c = newQuote.Id
        	//Contract__c = lstQuote2[0].ContractId
        );
        insert documentRevision;         

       String rdPolicyId = Schema.SObjectType.Document_Revision__c.getRecordTypeInfosByName().get('Policy').getRecordTypeId(); 
       String dtNow = String.valueOf(Datetime.now());
       Document_Revision__c newDoc = new Document_Revision__c(
            Name = 'PolicyForm' + '_' + dtNow,
            Document_Azure_Id__c = '3',
            Document_Type__c = 'PolicyForm',
            RecordTypeId = rdPolicyId
            //Contract__c = lstQuote2[0].ContractId
        ); 
        insert newDoc;         
	}

   
    @isTest
    public static void testGetEquipmentValidParam() {
        
       // accBusiness = [SELECT Id,Azure_Id__c FROM Account Where Id = :accBusiness.Id];
       
        //contactBroker = [SELECT Id,Azure_Id__c FROM Contact Where Id = :contactBroker.Id];
        system.debug('accBusiness'+ accBusiness);
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_Policies/';
        request.httpMethod = 'POST';
        //request.headers.put('Channel-Key', accBusiness.Azure_Id__c);
        //request.headers.put('Broker-Key', contactBroker.Azure_Id__c);
        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;

        Test.startTest();
        REST_Invsk_Policy.getPolicies();
        Test.stopTest();
        
        System.assertEquals(200, RestContext.response.statusCode);
    }
	
    @isTest
    public static void testEmptyAccountPolicy() {
        	
        //accBusiness = [SELECT Id FROM Account Where Id = :accBusiness.Id];
        system.debug('accBusiness'+accBusiness);
        //contactBroker = [SELECT Id,Azure_Id__c FROM Contact Where Id = :contactBroker.Id];
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_Policies/';
        request.httpMethod = 'POST';
        //request.headers.put('Channel-Key', accBusiness.Azure_Id__c);
        //request.headers.put('Broker-Key', contactBroker.Azure_Id__c);

        REST_Invsk_Policy.IncomingRequest inComingRequest = new REST_Invsk_Policy.IncomingRequest();
        inComingRequest.AccountId = '';
        inComingRequest.PolicyAzureId = '';
        request.requestBody = Blob.valueOf(JSON.serialize(inComingRequest));    

        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;

        Test.startTest();
        REST_Invsk_Policy.getPolicies();
        Test.stopTest();
        
        System.assertEquals(200, RestContext.response.statusCode);
    } 
    @isTest
    public static void testEndorsementSummary1() {
        //accBusiness = [SELECT Id,Azure_Id__c FROM Account Where Id = :accBusiness.Id];
        //contactBroker = [SELECT Id,Azure_Id__c FROM Contact Where Id = :contactBroker.Id];

        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_Policies/';
        request.httpMethod = 'POST';
       // request.headers.put('Channel-Key', accBusiness.Azure_Id__c);
        //request.headers.put('Broker-Key', contactBroker.Azure_Id__c);
        request.requestBody = Blob.valueOf('{ "AccountId":"", "PolicyAzureId":"" }');

        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;      

        Test.startTest();
        REST_Invsk_Policy.getPolicies();
        Test.stopTest();
        
        System.assertEquals(200, RestContext.response.statusCode);  
    }   
	
    @isTest
    public static void testGetEquipmentBrokerInvalid() {
        
       // accBusiness = [SELECT Id FROM Account Where Id = :accBusiness.Id];
       // contactBroker = [SELECT Id,Azure_Id__c FROM Contact Where Id = :contactBroker.Id];
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_Policies/';
        request.httpMethod = 'POST';
       // request.headers.put('Channel-Key', accBusiness.Azure_Id__c);
        request.headers.put('Broker-Key', 'test-123');
        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;

        Test.startTest();
        REST_Invsk_Policy.getPolicies();
        Test.stopTest();
        
        System.assertEquals(200, RestContext.response.statusCode);
    }
     @isTest
    public static void testGetEquipmentChannelInvalid() {
        
        //accBusiness = [SELECT Id,Azure_Id__c FROM Account Where Id = :accBusiness.Id];
        //contactBroker = [SELECT Id,Azure_Id__c FROM Contact Where Id = :contactBroker.Id];
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_Policies/';
        request.httpMethod = 'POST';
        request.headers.put('Channel-Key', 'test111');
        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;

        Test.startTest();
        REST_Invsk_Policy.getPolicies();
        Test.stopTest();
        
        System.assertEquals(200, RestContext.response.statusCode);
    }

   
    @isTest
    public static void testGetEquipmentNoBroker() {
        
        //accBusiness = [SELECT Id,Azure_Id__c FROM Account Where Id = :accBusiness.Id];
        //contactBroker = [SELECT Id,Azure_Id__c FROM Contact Where Id = :contactBroker.Id];
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_Policies/';
        request.httpMethod = 'POST';
       // request.headers.put('Channel-Key', accBusiness.Azure_Id__c);
        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;

        Test.startTest();
        REST_Invsk_Policy.getPolicies();
        Test.stopTest();
        
        System.assertEquals(200, RestContext.response.statusCode);
    }
    @isTest
    public static void testGetEquipmentNoChannel() {
        
        //accBusiness = [SELECT Id,Azure_Id__c FROM Account Where Id = :accBusiness.Id];
       // system.debug('accBusiness------------------'+accBusiness);
        //contactBroker = [SELECT Id,Azure_Id__c FROM Contact Where Id = :contactBroker.Id];
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_Policies/';
        request.httpMethod = 'POST';
       // request.headers.put('Broker-Key', contactBroker.Azure_Id__c);
        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;

        Test.startTest();
        REST_Invsk_Policy.getPolicies();
        Test.stopTest();
        
        System.assertEquals(200, RestContext.response.statusCode);
    }
	
    @isTest
    public static void testCreateDocumentRevisionMap() {
        List<Document_Revision__c> doc = [SELECT Name,Document_Type__c FROM Document_Revision__c];  
        system.assert(doc != null);
    }
    
    @isTest
    public static void testsetEndorsementQuoteWrapper() {
         Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
		Account acc  =TestUtil.createAccount('Test account 1', recordTypeId, '01 Tran Duy Hung','Westminster',
												'California','90000', 'United States');
       // acc.Azure_ID__c = '8042ac98-ae5a-4692-9880-58d92d0eb9d9';
		insert acc;
    
        Product2 product = TestUtil.createProduct('D&O Standalone');
		insert product; 

        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.CloseDate = Date.today()+365;
        opp.StageName = 'New';
       // opp.Azure_ID__c = 'f70e4c82-3378-41ce-870b-57f4df415874';
        insert opp;
       
        Quote newQuote1 = TestUtil.createQuote('test',opp.Id);
        newQuote1.Status = 'Quoted';
        //newQuote1.ContractId = newContract.Id;        
        newQuote1.Quote_Type__c = 'Amendment';
        newQuote1.Status = 'Bound';  
        insert newQuote1;
        Test.startTest();
       
        REST_Invsk_Policy.EndorsementQuoteWrapper  wrap=new REST_Invsk_Policy.EndorsementQuoteWrapper();
        // wrap.Id = newQuote1.Id;
         REST_Invsk_Policy.setEndorsementQuoteWrapper(newQuote1); 
        Test.stopTest();
          
        
    }
    
     @isTest
    public static void testcreatePolicyWrap() {
         Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
		Account acc  =TestUtil.createAccount('Test account 1', recordTypeId, '01 Tran Duy Hung','Westminster',
												'California','90000', 'United States');
  insert acc;
    
        Product2 product = TestUtil.createProduct('D&O Standalone');
		insert product; 

        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.CloseDate = Date.today()+365;
        opp.StageName = 'New';
        insert opp;
       
        Quote newQuote1 = TestUtil.createQuote('test',opp.Id);
        newQuote1.Status = 'Quoted';
        newQuote1.Quote_Type__c = 'Amendment';
        newQuote1.Status = 'Bound';  
        insert newQuote1;
        Test.startTest();
        Map<Id, List<Document_Revision__c>> docRevMap = new Map<Id, List<Document_Revision__c>>();
        List<Document_Revision__c> doc = [SELECT Name,Document_Type__c,Document_Azure_Id__c,Policy__c
        	FROM Document_Revision__c];
       // REST_Invsk_Policy.getPolicies();
         REST_Invsk_Policy.createPolicyWrap(newQuote1,docRevMap); 
        Test.stopTest();
          
        
    }
     @isTest
    public static void testWrapcreateDocumentRevisionMap() {
         Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
		Account acc  =TestUtil.createAccount('Test account 1', recordTypeId, '01 Tran Duy Hung','Westminster',
												'California','90000', 'United States');
        insert acc;
        Set<Id> policyIds = new Set<Id>();
        Policy__c policy = new Policy__c();
        	policy.Account__c = acc.Id;
        	policy.Product_Name__c = 'MPL';
        	policy.Expiration_Date__c = Date.today().addDays(100);
        	policy.Total_Premium__c = 2000;
        	policy.Initial_Premium__c = null;
        insert policy;
        policyIds.add(policy.Id);
        Test.startTest();
       //REST_Invsk_Policy.getPolicies();
         REST_Invsk_Policy.createDocumentRevisionMap(policyIds); 
        Test.stopTest();
          
        
    }
       @isTest
    public static void testsample() {
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_Policies/';
        request.httpMethod = 'POST';
        request.headers.put('Channel-Key', '407a8180-7cf0-4c74-99d0-4c194723916e');
        request.headers.put('Channel-Key', '407a8180-7cf0-4c74-99d0-4c194723916e');
        request.headers.put('Broker-Key', '407a8180-7cf0-4c74-99d0-4c194723916e');
        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;
  Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account chanAcc  =TestUtil.createAccount('Test Channel Account', recordTypeId, '01 Tran Duy Hung','Westminster',
												'California','90000', 'United States');
        chanAcc.Azure_ID__c = '407a8180-7cf0-4c74-99d0-4c194723916e';
		insert chanAcc;
        Product2 prod =[Select id from Product2 where name='D&O Standalone'];
     	Opportunity opportunity1 = [SELECT Id FROM Opportunity limit 1];
		Broker_Account__c brokers = [SELECT Id, IsPrimaryBroker__c,Broker_Contact__c FROM Broker_Account__c WHERE Opportunity__c =: opportunity1.Id];
       
        contact con =[select id,LastName from contact where Lastname=:'New broker contact'];
        
        con.Azure_Id__c='407a8180-7cf0-4c74-99d0-4c194723916e';
        update con;
        Account_Product__c accProd1 = new Account_Product__c();
        accProd1.Account_Id__c = chanAcc.Id;
        accProd1.Product_Id__c = prod.id;
        insert accProd1;
        Test.startTest();
        REST_Invsk_Policy.getPolicies();
        Test.stopTest();
        
    }
      @isTest
    static void postMethodTest(){
        Test.startTest();
                
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account chanAcc  =TestUtil.createAccount('Test Channel Account', recordTypeId, '01 Tran Duy Hung','Westminster',
												'California','90000', 'United States');
        chanAcc.Azure_ID__c = '407a8180-7cf0-4c74-99d0-4c194723916e';
		insert chanAcc;
         Product2 prod =[Select id from Product2 where name='D&O Standalone'];
       Opportunity opportunity1 = [SELECT Id FROM Opportunity limit 1];
		Broker_Account__c brokers = [SELECT Id, IsPrimaryBroker__c,Broker_Contact__c FROM Broker_Account__c WHERE Opportunity__c =: opportunity1.Id];
        
      contact con =[select id,LastName from contact where Lastname=:'New broker contact'];
        
        con.Azure_Id__c='407a8180-7cf0-4c74-99d0-4c194723916e';
        update con;
        Account_Product__c accProd1 = new Account_Product__c();
        accProd1.Account_Id__c = chanAcc.Id;
        accProd1.Product_Id__c = prod.id;
        insert accProd1;
         
        Set<Id> policyIds = new Set<Id>();        
         List<Quote> quoteEndorsementList = new List<Quote>();
        Policy__c policy = new Policy__c();
        policy.Account__c = chanAcc.Id;
        policy.Product_Name__c = 'MPL';
        policy.Expiration_Date__c = Date.today().addDays(100);
        policy.Total_Premium__c = 2000;
        policy.Initial_Premium__c = null;
        policy.Azure_ID__c='407a8180-7cf0-4c74-99d0-4c194723916e';
        insert policy;
        policyIds.add(policy.Id);
        
        Quote newQuote1 = TestUtil.createQuote('test',opportunity1.Id);
        newQuote1.Status = 'Quoted';
        newQuote1.Quote_Type__c = 'Amendment';
        newQuote1.Status = 'Bound';  
        insert newQuote1;
        
        quoteEndorsementList.add(newQuote1);
        
        REST_Invsk_Policy.IncomingRequest incomingRequest = new REST_Invsk_Policy.IncomingRequest();
        incomingRequest.PolicyAzureId = [Select Id,Name,Azure_Id__c from Policy__c Limit 1].Azure_Id__c;
      //  incomingRequest.accountId = [Select Id, Name,Azure_Id__c from Account where Name = 'Test account 1'].Azure_Id__c;
        
        
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_Policies/';
        request.httpMethod = 'POST';
        request.headers.put('Channel-Key', '407a8180-7cf0-4c74-99d0-4c194723916e');
        request.headers.put('Channel-Key', '407a8180-7cf0-4c74-99d0-4c194723916e');
        request.headers.put('Broker-Key', '407a8180-7cf0-4c74-99d0-4c194723916e');
       
        request.requestBody = Blob.valueOf(JSON.serialize(incomingRequest));
        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;
        
        REST_Invsk_Policy.getPolicies();
       
        System.assertEquals(200, RestContext.response.statusCode);
        Test.stopTest();
    }
          @isTest
    static void postMethodTest1(){
        Test.startTest();
                
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account chanAcc  =TestUtil.createAccount('Test Channel Account', recordTypeId, '01 Tran Duy Hung','Westminster',
												'California','90000', 'United States');
        chanAcc.Azure_ID__c = '407a8180-7cf0-4c74-99d0-4c194723916e';
		insert chanAcc;
         Product2 prod =[Select id from Product2 where name='D&O Standalone'];
       Opportunity opportunity1 = [SELECT Id FROM Opportunity limit 1];
		Broker_Account__c brokers = [SELECT Id, IsPrimaryBroker__c,Broker_Contact__c FROM Broker_Account__c WHERE Opportunity__c =: opportunity1.Id];
        
      contact con =[select id,LastName from contact where Lastname=:'New broker contact'];
        
        con.Azure_Id__c='407a8180-7cf0-4c74-99d0-4c194723916e';
        update con;
        Account_Product__c accProd1 = new Account_Product__c();
        accProd1.Account_Id__c = chanAcc.Id;
        accProd1.Product_Id__c = prod.id;
        insert accProd1;
         
        Set<Id> policyIds = new Set<Id>();        
         List<Quote> quoteEndorsementList = new List<Quote>();
        Policy__c policy = new Policy__c();
        policy.Account__c = chanAcc.Id;
        policy.Product_Name__c = 'MPL';
        policy.Expiration_Date__c = Date.today().addDays(100);
        policy.Total_Premium__c = 2000;
        policy.Initial_Premium__c = null;
        insert policy;
        policyIds.add(policy.Id);
        
        Quote newQuote1 = TestUtil.createQuote('test',opportunity1.Id);
        newQuote1.Status = 'Quoted';
        newQuote1.Quote_Type__c = 'Amendment';
        newQuote1.Status = 'Bound';  
        newQuote1.Azure_ID__c = '407a8180-7cf0-4c74-99d0-4c194723916e';
        insert newQuote1;
        
        quoteEndorsementList.add(newQuote1);
        
        REST_Invsk_Policy.IncomingRequest incomingRequest = new REST_Invsk_Policy.IncomingRequest();
       // incomingRequest.PolicyAzureId = [Select Id,Name,Azure_Id__c from Policy__c Limit 1].Azure_Id__c;
        incomingRequest.accountId = [Select Id, Name,Azure_Id__c from Account where Name = 'Test account 1'].Azure_Id__c;
        
        
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_Policies/';
        request.httpMethod = 'POST';
        request.headers.put('Channel-Key', '407a8180-7cf0-4c74-99d0-4c194723916e');
        request.headers.put('Channel-Key', '407a8180-7cf0-4c74-99d0-4c194723916e');
        request.headers.put('Broker-Key', '407a8180-7cf0-4c74-99d0-4c194723916e');
       
        request.requestBody = Blob.valueOf(JSON.serialize(incomingRequest));
        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;
        
        REST_Invsk_Policy.getPolicies();
       
        System.assertEquals(200, RestContext.response.statusCode);
        Test.stopTest();
    }
              @isTest
    static void postMethodTest2(){
        Test.startTest();
                
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account chanAcc  =TestUtil.createAccount('Test Channel Account', recordTypeId, '01 Tran Duy Hung','Westminster',
												'California','90000', 'United States');
        chanAcc.Azure_ID__c = '407a8180-7cf0-4c74-99d0-4c194723916e';
		insert chanAcc;
         Product2 prod =[Select id from Product2 where name='D&O Standalone'];
       Opportunity opportunity1 = [SELECT Id FROM Opportunity limit 1];
		Broker_Account__c brokers = [SELECT Id, IsPrimaryBroker__c,Broker_Contact__c FROM Broker_Account__c WHERE Opportunity__c =: opportunity1.Id];
        
      contact con =[select id,LastName from contact where Lastname=:'New broker contact'];
        
        con.Azure_Id__c='407a8180-7cf0-4c74-99d0-4c194723916e';
        update con;
        Account_Product__c accProd1 = new Account_Product__c();
        accProd1.Account_Id__c = chanAcc.Id;
        accProd1.Product_Id__c = prod.id;
        insert accProd1;
         
        Set<Id> policyIds = new Set<Id>();        
         List<Quote> quoteEndorsementList = new List<Quote>();
        Policy__c policy = new Policy__c();
        policy.Account__c = chanAcc.Id;
        policy.Product_Name__c = 'MPL';
        policy.Expiration_Date__c = Date.today().addDays(100);
        policy.Total_Premium__c = 2000;
        policy.Initial_Premium__c = null;
        insert policy;
        policyIds.add(policy.Id);
        
        Quote newQuote1 = TestUtil.createQuote('test',opportunity1.Id);
        newQuote1.Status = 'Quoted';
        newQuote1.Quote_Type__c = 'Amendment';
        newQuote1.Status = 'Bound';  
        newQuote1.Policy__c = policy.Id;
        insert newQuote1;
        
        quoteEndorsementList.add(newQuote1);
        
        REST_Invsk_Policy.IncomingRequest incomingRequest = new REST_Invsk_Policy.IncomingRequest();
       // incomingRequest.PolicyAzureId = [Select Id,Name,Azure_Id__c from Policy__c Limit 1].Azure_Id__c;
      //  incomingRequest.accountId = [Select Id, Name,Azure_Id__c from Account where Name = 'Test account 1'].Azure_Id__c;
        
        
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Invsk_Policies/';
        request.httpMethod = 'POST';
        request.headers.put('Channel-Key', '407a8180-7cf0-4c74-99d0-4c194723916e');
        request.headers.put('Channel-Key', '407a8180-7cf0-4c74-99d0-4c194723916e');
        request.headers.put('Broker-Key', '407a8180-7cf0-4c74-99d0-4c194723916e');
       
        request.requestBody = Blob.valueOf(JSON.serialize(incomingRequest));
        // Set up a test request
        RestResponse response = new RestResponse();
        
        // Call the method to test
        RestContext.request = request;
        RestContext.response = response;
        
        REST_Invsk_Policy.getPolicies();
       
        System.assertEquals(200, RestContext.response.statusCode);
        Test.stopTest();
    }
}