main/default/objects/SectionSetting__c/SectionSetting__c.object-meta.xml
<CustomObject>
    <description>Contains info to configure components that use sections</description>
    <label>Section Setting</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/SectionSetting__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Main_Section__c.field-meta.xml
<CustomField>
    <fullName>Main_Section__c</fullName>
    <label>Main Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Profile_Name_for_Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Profile_Name_for_Read_Only__c</fullName>
    <label>Profile Name for Read Only</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Celerity Senior Underwriter</fullName>
            </value>
            <value>
                <fullName>Celerity Junior Underwriter</fullName>
            </value>
            <value>
                <fullName>Aqueous Underwriter</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Field_API__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_API__c</fullName>
    <label>Source Field API</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Broker_Account__c</fullName>
                <label>Broker Account</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Policy_c</fullName>
                <label>Policy</label>
            </value>
            <value>
                <fullName>Rating_Modifier_Factor__c</fullName>
            </value>
            <value>
                <fullName>CoveragesLineItem__c</fullName>
            </value>
            <value>
                <fullName>Coverage_Limits_Deductibles__c</fullName>
            </value>
            <value>
                <fullName>Quote_Option__c</fullName>
            </value>
            <value>
                <fullName>Renewal__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/SectionSettingsQueryUtil.cls
/**************************************************************************************************
 * Class Name: SectionSettingsQueryUtil
 * Author: 
 * Date: Dec 27, 2021
 * Description: Class to keep UW Analysis Template queries
 * Test Class : 
 **************************************************************************************************/
public with sharing class SectionSettingsQueryUtil {
    /*************************************************
    * Method Name: fetchCeleritySubmissionInfoSettings
    * Author: 
    * Date: 27th Dec 2021
    * Params: 
    * Return: list of Section Settings
    * Exceptions:
    * Revision: 
    * Description: Fetch Section Settings for Celerity Submission Info Component
     *************************************************/
    public static List<SectionSetting__c> fetchCeleritySubmissionInfoSettings(){
        return [SELECT Id,Source_Field_API__c FROM SectionSetting__c 
                WHERE Component__c = 'Submission Info' AND Main_Section__c != 'Broker Account'
                AND Record_Type__c = 'Celerity' And Source_Object__c = 'Opportunity'
                And Profile_Name_for_Read_Only__c =null/* ORDER BY Order__c ASC*/];
    }
}