main/default/objects/SectionSetting__c/SectionSetting__c.object-meta.xml
<CustomObject>
    <description>Contains info to configure components that use sections</description>
    <label>Section Setting</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/SectionSetting__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Format__c.field-meta.xml
<CustomField>
    <fullName>Format__c</fullName>
    <label>Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Long Text</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Hyperlink</fullName>
            </value>
            <value>
                <fullName>MultiSelectPicklist</fullName>
            </value>
            <value>
                <fullName>Range</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Main_Section__c.field-meta.xml
<CustomField>
    <fullName>Main_Section__c</fullName>
    <label>Main Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Field_API__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_API__c</fullName>
    <label>Source Field API</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_Label__c</fullName>
    <label>Source Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Broker_Account__c</fullName>
                <label>Broker Account</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Policy_c</fullName>
                <label>Policy</label>
            </value>
            <value>
                <fullName>Rating_Modifier_Factor__c</fullName>
            </value>
            <value>
                <fullName>CoveragesLineItem__c</fullName>
            </value>
            <value>
                <fullName>Coverage_Limits_Deductibles__c</fullName>
            </value>
            <value>
                <fullName>Quote_Option__c</fullName>
            </value>
            <value>
                <fullName>Renewal__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Sub_Section__c.field-meta.xml
<CustomField>
    <fullName>Sub_Section__c</fullName>
    <label>Sub Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/classes/SubmissionInfoDetailLWCCtrlTest.cls
@isTest
public class SubmissionInfoDetailLWCCtrlTest {
@testsetup static void testSetup(){
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
		insert acc;
        
        Product2 product = TestUtil.createProduct('D&O Standalone');
		insert product; 

        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.CloseDate = Date.today();
        opp.StageName = 'Closed Won';
    	opp.Expiration_Date__c = Date.today()+60;
        insert opp;
        
        Quote quote1 = TestUtil.createQuote('New quote 1', opp.Id);
        quote1.Status = 'In Progress';
        quote1.Coverage_Product_Options__c = 'D&O';
     	quote1.Refer_Type__c = 'Underwriting Referral';
        insert quote1;  

		Quote quote2 = Testutil.createQuote('New Quote 2', opp.Id);
        quote2.Status = 'Bound';
        quote2.Coverage_Product_Options__c = 'D&O';
        quote2.Refer_Type__c = 'Underwriting Referral';
        insert quote2; 
  
    	SectionSetting__c secSettings1 = new SectionSetting__c();
    	secSettings1.Component__c = 'Submission Info';
        secSettings1.Order__c = 7;
   		secSettings1.Main_Section__c = 'Submission Status';
    	secSettings1.Sub_Section__c = 'Submission Status Sub';
    	secSettings1.Source_Object__c = 'Opportunity';
   		secSettings1.Source_Field_API__c = 'Amount';
        secSettings1.Source_Field_Label__c = 'Amount';
        secSettings1.Format__c = 'Number';
		insert secSettings1;      
	}
    @isTest
    static void getListSectionSettingTest(){
        Test.startTest();
        SubmissionInfoDetailLWCCtrl.getListSectionSetting();
        System.assert(True);
        Test.stopTest();
    }
    @isTest
    static void getListSectionSettingTest2(){
        Test.startTest();
        SectionSetting__c secSetting = [Select Id, Source_Object__c, Sub_Section__c from SectionSetting__c];
        secSetting.Source_Object__c = '';
        secSetting.Sub_Section__c = '';
        try{
           update secSetting;
        SubmissionInfoDetailLWCCtrl.getListSectionSetting();   
        }
        catch(Exception ex){
            System.debug(ex.getMessage());
        }      
        System.assert(True);
        Test.stopTest();
    }
     @isTest
    static void getListSectionSettingTest3(){
        Test.startTest();
        SectionSetting__c secSetting = [Select Id, Source_Object__c, Sub_Section__c, Main_Section__c from SectionSetting__c];        
        secSetting.Main_Section__c = '';
        secSetting.Sub_Section__c = '';
        try{
           update secSetting;
        SubmissionInfoDetailLWCCtrl.getListSectionSetting();   
        }
        catch(Exception ex){
            System.debug(ex.getMessage());
        }      
        System.assert(True);
        Test.stopTest();
    }
    
    @isTest
    static void getOppTest(){
        Test.startTest();
        Opportunity opp = [Select Id from Opportunity Limit 1];
        Map<String, Object> getOpp = SubmissionInfoDetailLWCCtrl.getOpp(opp.id, '["Name"]');
        System.assert(getOpp!=null);
        Test.stopTest();
    }
}