main/default/objects/SectionSetting__c/SectionSetting__c.object-meta.xml
<CustomObject>
    <description>Contains info to configure components that use sections</description>
    <label>Section Setting</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/SectionSetting__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <label>Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/DisplayType__c.field-meta.xml
<CustomField>
    <fullName>DisplayType__c</fullName>
    <label>Display Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Collapsed</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Format__c.field-meta.xml
<CustomField>
    <fullName>Format__c</fullName>
    <label>Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Long Text</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Hyperlink</fullName>
            </value>
            <value>
                <fullName>MultiSelectPicklist</fullName>
            </value>
            <value>
                <fullName>Range</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Group_Field_Key__c.field-meta.xml
<CustomField>
    <fullName>Group_Field_Key__c</fullName>
    <formula>Record_Type__c +  Component__c +  Main_Section__c +  Sub_Section__c</formula>
    <label>Group Field Key</label>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Lookup_To__c.field-meta.xml
<CustomField>
    <fullName>Lookup_To__c</fullName>
    <label>Lookup To</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Main_Section__c.field-meta.xml
<CustomField>
    <fullName>Main_Section__c</fullName>
    <label>Main Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>PCC</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
            <value>
                <fullName>Aqueous</fullName>
                <isActive>false</isActive>
                <label>Aqueous</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Field_API__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_API__c</fullName>
    <label>Source Field API</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_Label__c</fullName>
    <label>Source Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Broker_Account__c</fullName>
                <label>Broker Account</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Policy_c</fullName>
                <label>Policy</label>
            </value>
            <value>
                <fullName>Rating_Modifier_Factor__c</fullName>
            </value>
            <value>
                <fullName>CoveragesLineItem__c</fullName>
            </value>
            <value>
                <fullName>Coverage_Limits_Deductibles__c</fullName>
            </value>
            <value>
                <fullName>Quote_Option__c</fullName>
            </value>
            <value>
                <fullName>Renewal__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Sub_Section__c.field-meta.xml
<CustomField>
    <fullName>Sub_Section__c</fullName>
    <label>Sub Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Type_Of_Section__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Section__c</fullName>
    <formula>IF(ISBLANK(Sub_Section__c), IF(ISBLANK(Source_Field_API__c), &apos;MainSection&apos;, &apos;Field&apos;), IF(!ISBLANK(Source_Field_API__c), &apos;Field&apos;, &apos;SubSection&apos;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type Of Section</label>
    <type>Text</type>
</CustomField>

main/default/classes/sectionSettingLwcController.cls
public with sharing class sectionSettingLwcController {
	static final String CHARACTER = ',';
	@AuraEnabled
    public static List<OptionWrapper> getComponentList(String recordTypeName) 
	{
	    Set<String> componentsSet = new Set<String>();
		List<OptionWrapper> componentList = new List<OptionWrapper>();
		for(SectionSetting__c obj : [SELECT Component__c FROM SectionSetting__c WHERE Record_Type__c=:recordTypeName AND Component__c!=null ]) 
		{
		    componentsSet.add(obj.Component__c);     
        } 
		
		for(String com :componentsSet){
			componentList.add(new OptionWrapper(com, com));
		}

		return componentList;
	}

	@AuraEnabled
	public static List<OptionWrapper> getProductList(String recordTypeName){
		Set<String> productSet = new Set<String>();
		List<OptionWrapper> productList = new List<OptionWrapper>();
		
		for(SectionSetting__c obj : [SELECT Product__c FROM SectionSetting__c
									 WHERE Record_Type__c = :recordTypeName AND Product__c!=null ]) 
		{
		    productSet.add(obj.Product__c);     
		}
		
		for(String prod :productSet){
			productList.add(new OptionWrapper(prod, prod));
		}
		system.debug('getProductList '+ productList);
		return productList;
	}

	@AuraEnabled
    public static List<OptionWrapper> getSectionList(String conditionGroup) 
	{
		List<String> lstStr = conditionGroup.split(CHARACTER);
		List<OptionWrapper> sectionList = new List<OptionWrapper>();
		if(lstStr.size()==2) //MainSection query
			for(SectionSetting__c obj : [SELECT Id, Main_Section__c	FROM SectionSetting__c WHERE Record_Type__c=:lstStr[0] 
										AND Component__c=:lstStr[1] AND Type_Of_Section__c='MainSection' //AND Active__c=true
										Order by Order__c]) 
			{
				  sectionList.add(new OptionWrapper(obj.Main_Section__c, obj.Id));    //label,value
			} 
		
		if(lstStr.size()==3) //SubSection query
		{
			sectionList.add(new OptionWrapper('', '')); 
			for(SectionSetting__c obj : [SELECT Id, Sub_Section__c FROM SectionSetting__c WHERE Record_Type__c=:lstStr[0] 
									AND Component__c=:lstStr[1] AND Main_Section__c=:lstStr[2] AND Type_Of_Section__c='SubSection' //AND Active__c=true
									Order by Order__c]) 
			{
				  sectionList.add(new OptionWrapper(obj.Sub_Section__c, obj.Id));    //label,value
			} 
		}
       return sectionList;
	}
	
    @AuraEnabled
    public static List<OptionWrapper> getMainSectionList(String recordTypeName, String componentName)
	{
		List<OptionWrapper> componentList = new List<OptionWrapper>();
		for(SectionSetting__c obj : [SELECT Id, Main_Section__c
				FROM SectionSetting__c WHERE Record_Type__c=:recordTypeName AND Component__c=:componentName 
				AND Type_Of_Section__c='MainSection' //AND Active__c=true
				Order by Order__c]) 
		{
              componentList.add(new OptionWrapper(obj.Main_Section__c, obj.Id));    //label,value
        } 
       return componentList;
	}
	
	@AuraEnabled
	public static List<OptionWrapper> getSubSectionList(String recordTypeName, String componentName,String mainSectionName)
	{
      	List<OptionWrapper> componentList = new List<OptionWrapper>();
		componentList.add(new OptionWrapper('', '')); 
		for(SectionSetting__c obj : [SELECT Id, Sub_Section__c, Main_Section__c 
				FROM SectionSetting__c WHERE Record_Type__c=:recordTypeName AND Component__c=:componentName AND Main_Section__c=:mainSectionName
				AND Type_Of_Section__c='SubSection' //AND Active__c=true
				Order by Order__c]) 
		{
              componentList.add(new OptionWrapper(obj.Sub_Section__c, obj.Id));    //mainSection, label,value
        } 

       return componentList;
	}

	@AuraEnabled
	public static List<SectionSetting__c> getFieldList(String groupdId) //input is Mainsection Id or SubSectionId
	{
        return [SELECT Id,Name,Record_Type__c, Product__c,Component__c,Main_Section__c,Sub_Section__c,Source_Field_API__c,
				Source_Field_Label__c, Source_Object__c,Format__c,DisplayType__c, Order__c,Active__c,Criteria__c,Lookup_To__c
				FROM SectionSetting__c WHERE Type_Of_Section__c='Field' AND Group_Field_Key__c=:groupdId //AND Active__c=true 
				Order by Order__c];
	}

	@AuraEnabled
	public static String updateSectionRelatedData(String oldValue, String newValue) //input is Mainsection Id or SubSectionId
	{
		//if newValue ='' --> delete event
		//if newValue !='' --> new or edit event
		String returnStr ='MainSection';
		system.debug('@@@ oldValue:'+ oldValue);
		system.debug('@@@ newValue:'+ newValue);
		List<SectionSetting__c> sectionList = new List<SectionSetting__c>();
		List<String> oldStrList = new List<String> ();
		List<String> newStrList = new List<String> ();
		if(oldValue.contains(CHARACTER)) oldStrList = oldValue.split(CHARACTER);
		if(newValue.contains(CHARACTER)) newStrList = newValue.split(CHARACTER);

		system.debug('@@@ updateSectionRelatedData:');
		system.debug('@@@ oldStrList:'+ oldStrList);
		system.debug('@@@ newStrList:'+ newStrList);
		//check Main or Sub Section base on newValue
		//....
		Boolean isMainSection = false;

		if(String.isBlank(newValue))//Delete case
		{
			if(oldStrList.size()==4) //--> delete Sub Section
			{
				sectionList = [SELECT Id FROM SectionSetting__c WHERE Record_Type__c=:oldStrList[0] 
							AND Component__c=:oldStrList[1] AND Main_Section__c=:oldStrList[2] AND Sub_Section__c=:oldStrList[3]];

			}else//delete Main Section
			{
				sectionList = [SELECT Id FROM SectionSetting__c WHERE Record_Type__c=:oldStrList[0] 
										AND Component__c=:oldStrList[1] AND Main_Section__c=:oldStrList[2] ];
				isMainSection = true;
			}
			
			if(!sectionList.isEmpty()) delete sectionList;
			
			returnStr = isMainSection ? 'deleted Main Section' : 'deleted Sub Section';

		}else //Edit or New case
		{
			if(String.isBlank(oldValue)) // New Section logic
				 returnStr = (newStrList.size()==4) ? 'added SubSection' : 'added MainSection';
			else//Edit Section logic
			{	
				system.debug('@@@ Edit Section logic:');
				system.debug('@@@ oldStrList size:' + oldStrList.size());
				if(oldStrList.size()==4) //--> edit Sub Section Name
				{
					system.debug('@@@ Edit Sub Section logic:');
					sectionList = [SELECT Id, Sub_Section__c FROM SectionSetting__c WHERE Record_Type__c=:oldStrList[0] 
								AND Component__c=:oldStrList[1] AND Main_Section__c=:oldStrList[2] AND Sub_Section__c=:oldStrList[3]];
					for(SectionSetting__c obj : sectionList) 
					{
						obj.Sub_Section__c =newValue; 
					} 
					returnStr ='edited SubSection';
				}else//edit Main Section name
				{
					system.debug('@@@ Edit Main Section logic:');
					sectionList = [SELECT Id, Main_Section__c FROM SectionSetting__c WHERE Record_Type__c=:oldStrList[0] 
											AND Component__c=:oldStrList[1] AND Main_Section__c=:oldStrList[2] ];
					for(SectionSetting__c obj : sectionList) 
					{
						obj.Main_Section__c =newValue; 
					} 
					returnStr ='edited MainSection';
				}
				if(!sectionList.isEmpty()) update sectionList;
			}
		}

		return returnStr;
	}

	@AuraEnabled
	public static String updateComponentRelatedData(String rt, String componentName, String mode) //input is Mainsection Id or SubSectionId
	{
		String result ='';
		
		List<String> lst = new List<String>();
		//system.debug('@@@ lst:' + lst.size());
		if(mode=='Edit'){
			if(componentName.contains(CHARACTER)) // Edit case
			{
				lst = componentName.split(CHARACTER);
				String oldValue = lst[0];
				String newvalue = lst[1];
				//Update all Main Section, Subsection, Fields of Component
				//Separate old value and new value by special character -
				List<SectionSetting__c> componentsList = [SELECT Component__c FROM SectionSetting__c WHERE Record_Type__c=:rt AND Component__c=:oldValue ];
				for(SectionSetting__c obj : componentsList) 
				{
					obj.Component__c =newvalue; 
				} 
				update componentsList;
				result ='Updated success';
			}else//Create new Component Mode
			{
				//Create new Main Section 
				SectionSetting__c newobj = new 	SectionSetting__c();
				newobj.Record_Type__c = rt;
				newobj.Component__c = componentName;
				newobj.Main_Section__c = 'Main Section - ' + componentName;
				newobj.Order__c = 1;
				newobj.Active__c = true;
				insert newobj;
				result ='Inserted success';
			}
		}
		if(String.isNotBlank(componentName) && mode == 'Delete')
		{
			List<SectionSetting__c> componentsList = [SELECT Component__c FROM SectionSetting__c WHERE Record_Type__c=:rt AND Component__c=:componentName ];
			delete componentsList;
			result ='Deleted success';
		}
		
		return result;
	}

	public class OptionWrapper {
        @AuraEnabled
        public String label {get; set;}
        @AuraEnabled
        public String value {get; set;}

        public OptionWrapper(String label, String value) {
            this.label = label;
            this.value = value;
        }
	}
	

}