main/default/objects/CoveragesLineItem__c/CoveragesLineItem__c.object-meta.xml
<CustomObject>
    <label>Coverages Line Item</label>
    <nameField>
        <displayFormat>CLI-{00000000}</displayFormat>
        <label>CLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverages Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CoveragesLineItem__c/fields/Option_Value_Default__c.field-meta.xml
<CustomField>
    <fullName>Option_Value_Default__c</fullName>
    <label>Option Value Default</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Coverages Line Items</relationshipLabel>
    <relationshipName>Coverages_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Quote_Version__c/Quote_Version__c.object-meta.xml
<CustomObject>
    <label>Quote Version</label>
    <nameField>
        <label>Quote Version</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Quote_Version__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Versions</relationshipLabel>
    <relationshipName>Quote_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Quote_Version_Item__c/Quote_Version_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Version Item</label>
    <nameField>
        <displayFormat>QV-{0000}</displayFormat>
        <label>Quote Version Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Version Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Quote_Version_Item__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add</fullName>
                <default>true</default>
                <label>Add</label>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Quote_Version_Item__c/fields/Quote_Version__c.field-meta.xml
<CustomField>
    <fullName>Quote_Version__c</fullName>
    <label>Quote Version</label>
    <referenceTo>Quote_Version__c</referenceTo>
    <relationshipLabel>Quote Version Items</relationshipLabel>
    <relationshipName>Quote_Version_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Quote_Version_Item__c/fields/Source_Field_API__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_API__c</fullName>
    <label>Source Field API</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

main/default/objects/Quote_Version_Item__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

main/default/classes/QuoteVersionControllerTest.cls
@isTest
public class QuoteVersionControllerTest {
	@testsetup static void testSetup(){
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
		insert acc;
        
        Product2 product = TestUtil.createProduct('D&O Standalone');
		insert product; 

        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.CloseDate = Date.today();
        opp.StageName = 'Closed Won';
    	opp.Expiration_Date__c = Date.today()+60;
        insert opp;
        
        
        Opportunity opp2 = TestUtil.createOpportunity('Opp Test2',acc.Id, product.Id);
        opp2.CloseDate = Date.today();
        opp2.StageName = 'Closed Won';
    	opp2.Expiration_Date__c = Date.today()+60;
        insert opp2;
            
        Quote quote1 = TestUtil.createQuote('New quote 1', opp.Id);
        quote1.Status = 'In Progress';
        quote1.Coverage_Product_Options__c = 'D&O';
     	quote1.Refer_Type__c = 'Underwriting Referral';
        insert quote1;  

		Quote quote2 = Testutil.createQuote('New Quote 2', opp.Id);
        quote2.Status = 'Bound Pending';
        quote2.Coverage_Product_Options__c = 'D&O';
        quote2.Refer_Type__c = 'Underwriting Referral';
        insert quote2;  
        
        Quote_Version__c quoteVersion = new Quote_Version__c();
        quoteVersion.Name = 'Test Version1';
        quoteVersion.Quote__c = quote1.Id;
        insert quoteVersion;
        
        Quote_Version_Item__c quoteVersItem = new Quote_Version_Item__c();
        quoteVersItem.Quote_Version__c = quoteVersion.Id;
        quoteVersItem.Source_Field_API__c = 'Option_Value_Default__c';
        quoteVersItem.Source_Object__c = 'CoveragesLineItem__c';
        quoteVersItem.Operation__c = 'Add';
        insert quoteVersItem;
	}
    @istest
    static void getListQuoteVersionsTest(){
        Test.startTest();
        Quote q = [Select Id from Quote limit 1];
        QuoteVersionController.getListQuoteVersions(q.id);
        System.assert(True);
        Test.stopTest();
    }
    
    @isTest
    static void checkExistVersionTest(){
        Test.startTest();
     	Quote q = [Select Id from Quote limit 1];
        List<Quote_Version_Item__c> quoteItemVersion = [Select Id, Source_Object__c, Source_Field_API__c, Value__c from Quote_Version_Item__c];
        Boolean result = QuoteVersionController.checkExistVersion(quoteItemVersion, q.Id);
       	new QuoteVersionController.QuoteVersionItemWrapper('Test','Test','Test','Test','Test','Test');
        System.assert(result!=null);
        Test.stopTest();
    }
}