main/default/objects/CoveragesLineItem__c/CoveragesLineItem__c.object-meta.xml
<CustomObject>
    <label>Coverages Line Item</label>
    <nameField>
        <displayFormat>CLI-{00000000}</displayFormat>
        <label>CLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverages Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CoveragesLineItem__c/fields/Option_Value_Default__c.field-meta.xml
<CustomField>
    <fullName>Option_Value_Default__c</fullName>
    <label>Option Value Default</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/CoveragesLineItem__c/recordTypes/Celerity.recordType-meta.xml
<RecordType>
    <fullName>Celerity</fullName>
    <active>true</active>
    <label>Celerity</label>
</RecordType>

main/default/classes/CoverageLineItemTriggerHandler_AQ.cls
/**************************************************************************************************
 * Class Name: CoverageLineItemTriggerHandler_AQ
 * Author: 
 * Date: 
 * Description: Class to keep Celerity related  common methods
 * Test Class : CoverageLineItemTriggerTest
 **************************************************************************************************/
public class CoverageLineItemTriggerHandler_AQ extends TriggerHandler {

    private List<CoveragesLineItem__c> oldDataList;
    private List<CoveragesLineItem__c> newDataList; 
    private Map<Id, CoveragesLineItem__c> newDataMap;
    private Map<Id, CoveragesLineItem__c> oldDataMap; 

    Map<Id, Quote> updateQuoteMap = new Map<Id, Quote>();
    
    public CoverageLineItemTriggerHandler_AQ(List<CoveragesLineItem__c> newDataList, List<CoveragesLineItem__c> oldDataList, 
                                         Map<Id, CoveragesLineItem__c> newDataMap, Map<Id, CoveragesLineItem__c> oldDataMap){
                                             this.oldDataList = oldDataList;
                                             this.newDataList = newDataList;
                                             this.newDataMap = newDataMap;
                                             this.oldDataMap = oldDataMap;
                                         } 

	public override void beforeInsert()	{
        // Generate Azure Id before insert of CLI
		CommonUtil.generateExternalID('Azure_ID__c', newDataList);
	}

    public override void beforeUpdate(){
        // Generate Azure Id before update of CLI
		CommonUtil.generateExternalID('Azure_ID__c', newDataList);
    }

	
	public override void afterInsert(){
        //update Quote ExcessLimit
        map<Id,Quote> updateExcessLimitMap = CommonCoverageLineItemUtil.updateExcessLimit(this.newDataMap);
        updateQuoteMap.putAll(updateExcessLimitMap);


        //update quote status
        map<Id,Quote> updateStatusMap = CommonCoverageLineItemUtil.updateQuoteStatus(this.newDataList,null);
        updateQuoteMap.putAll(updateStatusMap);

        if(updateQuoteMap.Values().size() > 0){
            update updateQuoteMap.Values(); 
        } 
    }

	
	public override void afterUpdate(){
        //update quote status
        map<Id,Quote> updateStatusMap = CommonCoverageLineItemUtil.updateQuoteStatus(this.newDataList,this.oldDataMap);
        updateQuoteMap.putAll(updateStatusMap);

        //update Quote ExcessLimit
        map<Id,Quote> updateExcessLimitMap = CommonCoverageLineItemUtil.updateExcessLimit(this.newDataMap);
        updateQuoteMap.putAll(updateExcessLimitMap);


        if(updateQuoteMap.Values().size() > 0){
            update updateQuoteMap.Values();
        }
        
        //update CLI Option_Value_Default__c
        CommonCoverageLineItemUtil.handleUpdateSyncLimitDeductible(this.oldDataMap, this.newDataMap);
    }

    
    public override void afterdelete(){
        //update quote status
        map<Id,Quote> updateStatusMap = CommonCoverageLineItemUtil.updateQuoteStatus(oldDataList,null);

        /* should it updated?
        
        */
    }
}