main/default/objects/Broker_License__c/Broker_License__c.object-meta.xml
<CustomObject>
    <label>Broker License</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Broker License Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Broker_License__c/fields/License_State__c.field-meta.xml
<CustomField>
    <fullName>License_State__c</fullName>
    <label>License State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Codes</valueSetName>
    </valueSet>
</CustomField>

main/default/classes/CommonBrokerLicenseUtil.cls
/**************************************************************************************************
 * Class Name: CommonBrokerLicenseUtil
 * Author: 
 * Date: 
 * Description: 
 **************************************************************************************************/
public with sharing class CommonBrokerLicenseUtil {
    //7760: Change NIPR run from Contact to Broker License (Binh Dang: 1 Nov 2019)
	public static void updateNIPRFlafByCallOut(List<Broker_License__c> newDataList,Map<Id, Broker_License__c> oldDataMap) {
        List<Id> listBrokerLCId = new List<Id>();
        if(oldDataMap == null) { //Insert case
            for(Broker_License__c license :newDataList) {
                if(String.isNotBlank(license.License_Number__c) && String.isNotBlank(license.License_State__c)) 
                    listBrokerLCId.add(license.Id);
            }
        }else{
            for(Broker_License__c license : newDataList) { //Update Case
                String oldLicenseNumber = oldDataMap.get(license.Id).License_Number__c;
                String newLicenseNumber = license.License_Number__c;

                String oldLicenseState = oldDataMap.get(license.Id).License_State__c;
                String newLicenseState = license.License_State__c;

                if(	(String.isNotBlank(newLicenseNumber) && newLicenseNumber != oldLicenseNumber)
                    ||  (String.isNotBlank(newLicenseState) && newLicenseState != oldLicenseState)
                    ) 
                    listBrokerLCId.add(license.Id);
            }
        }
        if(!listBrokerLCId.isEmpty()){
            Invsk_Callout.getNIPRCallOut(listBrokerLCId);
            /*NIPRLisenceBatch b = new NIPRLisenceBatch();
            database.executebatch(b,1);*/
        } 
    }
}