main/default/objects/Broker_License__c/Broker_License__c.object-meta.xml
<CustomObject>
    <label>Broker License</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Broker License Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Broker_License__c/fields/License_State__c.field-meta.xml
<CustomField>
    <fullName>License_State__c</fullName>
    <label>License State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Codes</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Broker_License__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Surplus Lines</fullName>
            </value>
            <value>
                <fullName>Limited Lines</fullName>
            </value>
            <value>
                <fullName>Admitted Lines</fullName>
            </value>
            <value>
                <fullName>Admitted</fullName>
                <isActive>false</isActive>
                <label>Admitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Broker_License__c/fields/NIPR_License_flag__c.field-meta.xml
<CustomField>
    <fullName>NIPR_License_flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NIPR License flag</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Broker_License__c/fields/NPN__c.field-meta.xml
<CustomField>
    <fullName>NPN__c</fullName>
    <description>This is returned from the NIPR api call</description>
    <label>NPN (National producer number)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/classes/NIPRLisenceBatch.cls
/**************************************************************************************************
 * Class Name: NIPRLisenceBatch
 * Author: Giang PHAN
 * Date: 14-Nov-2019
 * Description: Batch Program to Callouts LicenseNumber.
 **************************************************************************************************/
global class NIPRLisenceBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String strQuery = 'SELECT Id, License_Number__c, License_State__c,License_Type__c, NPN__c FROM Broker_License__c';
        return Database.getQueryLocator(strQuery);
    }

    global void execute(Database.BatchableContext BC, list<Broker_License__c> listBrokerLCId) {
        Invsk_Callout.NIPRResponse resNIPR = new Invsk_Callout.NIPRResponse();
        API_Configuration__mdt apiSetting = CommonUtil.getAPIconfiguration('NIPR_API');
        if(apiSetting == null) return ;

        List<Broker_License__c> updatedBrokerLicenses = new List<Broker_License__c>();

        for(Broker_License__c brokerLC : listBrokerLCId){

            if(String.isNotBlank(brokerLC.License_Number__c) && String.isNotBlank(brokerLC.License_State__c)){
                Map<String, Invsk_Callout.LicenseLookup> mapsLicenselookup = new Map<String, Invsk_Callout.LicenseLookup>();
                mapsLicenselookup.put('licenseLookup', new Invsk_Callout.LicenseLookup(brokerLC.License_Number__c,brokerLC.License_State__c)); 
                
                Http httpVar = new Http();  
                HttpRequest req = Invsk_Callout.getHttpRequest(apiSetting);
                HttpResponse res = new HttpResponse();
                
                //Send Resquest Callouts
                req.setBody(JSON.serialize(mapsLicenselookup));                            
                res = httpVar.send(req);
                
                //Response Callouts 
                Map<String, Object> resultMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
                    
                if(resultMap.containsKey('isValidBrokerLicense') && (Boolean)resultMap.get('isValidBrokerLicense')){
                    String numberNPN = (String)resultMap.get('npn');                          
                    if(String.isNotBlank(numberNPN)) {
                        brokerLC.NPN__c = numberNPN;
                        brokerLC.NIPR_License_flag__c = true;
                        updatedBrokerLicenses.add(brokerLC); 
                        }
                    }                       
                }
                //Update Broker License NPN
                if(!updatedBrokerLicenses.isEmpty()) upsert updatedBrokerLicenses;
            }
    }

    global void finish(Database.BatchableContext BC) {
        
    }
}