main/default/objects/Broker_License__c/Broker_License__c.object-meta.xml
<CustomObject>
    <label>Broker License</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Broker License Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Broker_License__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker_Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Broker Licenses</relationshipLabel>
    <relationshipName>Broker_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Broker_License__c/fields/License_State__c.field-meta.xml
<CustomField>
    <fullName>License_State__c</fullName>
    <label>License State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Codes</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Broker_License__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Surplus Lines</fullName>
            </value>
            <value>
                <fullName>Limited Lines</fullName>
            </value>
            <value>
                <fullName>Admitted Lines</fullName>
            </value>
            <value>
                <fullName>Admitted</fullName>
                <isActive>false</isActive>
                <label>Admitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Broker_License__c/fields/NPN__c.field-meta.xml
<CustomField>
    <fullName>NPN__c</fullName>
    <description>This is returned from the NIPR api call</description>
    <label>NPN (National producer number)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/classes/BrokerLicenseQueryUtil.cls
/**************************************************************************************************
 * Class Name: BrokerLicenseQueryUtil
 * Author: 
 * Date: Jan 4th, 2022
 * Description: Class to keep Broker license queries
 * Test Class : BrokerLicenseQueryUtilTest
 **************************************************************************************************/
public with sharing class BrokerLicenseQueryUtil {
    /*************************************************
    * Method Name: fetchLicencesForBroker
    * Author: 
    * Date: 6th Jan 2022
    * Params: String brkContactId
    * Return: list of broker licenses
    * Exceptions:
    * Revision: 
    * Description: Fetch all broker licenses
     *************************************************/
    public static List<Broker_License__c> fetchLicencesForBroker(String brkContactId){
        return [SELECT Id,License_Number__c, License_State__c,License_Type__c, NPN__c 
                FROM Broker_License__c 
                WHERE Broker__c =:brkContactId];
    }
}