main/default/objects/Sanction_Status__c/Sanction_Status__c.object-meta.xml
<CustomObject>
    <label>Sanction Status</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Sanction Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sanction Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Sanction_Status__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sanction Statuses</relationshipLabel>
    <relationshipName>Sanction_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Sanction_Status__c/fields/Review_Requested__c.field-meta.xml
<CustomField>
    <fullName>Review_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Review Requested</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Sanction_Status__c/fields/Sanction_Status__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Status__c</fullName>
    <label>Sanction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Potential Match</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Sanction_Status__c/recordTypes/Aqueous.recordType-meta.xml
<RecordType>
    <fullName>Aqueous</fullName>
    <active>true</active>
    <label>Aqueous</label>
</RecordType>

main/default/objects/Sanction_Status__c/recordTypes/Celerity.recordType-meta.xml
<RecordType>
    <fullName>Celerity</fullName>
    <active>true</active>
    <label>Celerity</label>
</RecordType>

main/default/classes/SanctionStatusTrigger_Test.cls
@isTest
public class SanctionStatusTrigger_Test {

    @isTest
     static void testmethod1() {
         Account acc = TestUtil.createBusinessAccount('Bussiness Accoun Aq', 'Business', '123 Main Street', 'Anycity', 'England', '11354', 'United Kingdom');
         acc.BillingStreet = acc.ShippingStreet;
         acc.BillingCity = acc.ShippingCity;
         acc.BillingState = acc.ShippingState;
         acc.BillingPostalCode = acc.ShippingPostalCode;
         acc.BillingCountry = acc.ShippingCountry;
         insert acc;
         
         Account acc1 = TestUtil.createBusinessAccount('Bussiness Accoun Aq', 'Business', '123 Main Street', 'Anycity', 'England', '11354', 'United Kingdom');
         acc1.BillingStreet = acc.ShippingStreet;
         acc1.BillingCity = acc.ShippingCity;
         acc1.BillingState = acc.ShippingState;
         acc1.BillingPostalCode = acc.ShippingPostalCode;
         acc1.BillingCountry = acc.ShippingCountry;
         insert acc1;
         
         
         Sanction_Status__c sancstatus = new Sanction_Status__c();
         sancstatus.Account__c = acc.Id; 
         sancstatus.Review_Requested__c = true;
         sancstatus.Sanction_Status__c = 'Potential Match';
         sancstatus.RecordTypeId = Schema.SObjectType.Sanction_Status__c.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
         
         insert sancstatus;
         
         Sanction_Status__c sancstatus1 = new Sanction_Status__c();
         sancstatus1.Account__c = acc.Id; 
         sancstatus1.Review_Requested__c = true;
         sancstatus1.RecordTypeId = Schema.SObjectType.Sanction_Status__c.getRecordTypeInfosByName().get('Celerity').getRecordTypeId();
         
         upsert sancstatus1;
         
         sancstatus1.Review_Requested__c = false;
         update sancstatus1;

         //sancstatus.Account__c = acc1.Id;
         sancstatus.Sanction_Status__c = 'Failed';
       	 update sancstatus;
     }
         
}