main/default/objects/Sanction_Status__c/Sanction_Status__c.object-meta.xml
<CustomObject>
    <label>Sanction Status</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Sanction Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sanction Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Sanction_Status__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sanction Statuses</relationshipLabel>
    <relationshipName>Sanction_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Sanction_Status__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Sanction_Status__c/fields/Decline_Reason__c.field-meta.xml
<CustomField>
    <fullName>Decline_Reason__c</fullName>
    <label>Decline Reason</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Sanction_Status__c/fields/Review_Note__c.field-meta.xml
<CustomField>
    <fullName>Review_Note__c</fullName>
    <label>Review Note</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Sanction_Status__c/fields/Review_Requested__c.field-meta.xml
<CustomField>
    <fullName>Review_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Review Requested</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Sanction_Status__c/fields/Review_Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Review_Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review Requested By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sanction_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Sanction_Status__c/fields/Reviewed_By__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sanction_Statuses1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Sanction_Status__c/fields/Reviewed_On__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_On__c</fullName>
    <label>Reviewed On</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Sanction_Status__c/fields/Sanction_Date__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Date__c</fullName>
    <label>Sanction Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Sanction_Status__c/fields/Sanction_Status__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Status__c</fullName>
    <label>Sanction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Potential Match</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Sanction_Status__c/fields/SearchId__c.field-meta.xml
<CustomField>
    <fullName>SearchId__c</fullName>
    <label>SearchId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/classes/SanctionStatusTriggerHandler_CEL.cls
public class SanctionStatusTriggerHandler_CEL extends TriggerHandler{
    private List<Sanction_Status__c> oldDataList;
    private List<Sanction_Status__c> newDataList; 
    private Map<Id, Sanction_Status__c> newDataMap;
    private Map<Id, Sanction_Status__c> oldDataMap;
    
    public SanctionStatusTriggerHandler_CEL(List<Sanction_Status__c> newDataList, List<Sanction_Status__c> oldDataList, 
                                         Map<Id, Sanction_Status__c> newDataMap, Map<Id, Sanction_Status__c> oldDataMap){
                                             this.oldDataList = oldDataList;
                                             this.newDataList = newDataList;
                                             this.newDataMap = newDataMap;
                                             this.oldDataMap = oldDataMap;
                                         }  

    public SanctionStatusTriggerHandler_CEL() {

    }

    public override void beforeInsert(){
        setFieldOnInsert(newDataList);
    }

    public override void beforeUpdate(){}

    public override void afterInsert(){
        setSanctionStatusonAccountonInsert(newDataList);
    }

    public override void afterUpdate(){
        setSanctionStatusonAccountonUpdate(newDataList,oldDataMap);
    }

    public static void setSanctionStatusonAccountonInsert(List<Sanction_Status__c> newDataList){

        List<Account> listAccounttoUpdate = new List<Account>();
        for(Sanction_Status__c objSanctionStatus : newDataList){
            Account acc = new Account();
            acc.Id = objSanctionStatus.Account__c;
            acc.CEL_Sanction_Status__c = objSanctionStatus.Sanction_Status__c;
            acc.Sanction_Date__c = objSanctionStatus.Sanction_Date__c;
            acc.SearchId__c = objSanctionStatus.SearchId__c;
            acc.Decline_Reason__c = objSanctionStatus.Decline_Reason__c;
            acc.Review_Note__c = objSanctionStatus.Review_Note__c;
            acc.Review_Requested__c = objSanctionStatus.Review_Requested__c;
            acc.Review_Requested_By__c = objSanctionStatus.Review_Requested_By__c;
            acc.Reviewed_By__c = objSanctionStatus.Reviewed_By__c;
            acc.Reviewed_On__c = objSanctionStatus.Reviewed_On__c;
            listAccounttoUpdate.add(acc);
        }

        if(!listAccounttoUpdate.isEmpty()){
            update listAccounttoUpdate;
        }
    }

    public static void setSanctionStatusonAccountonUpdate(List<Sanction_Status__c> newDataList, Map<Id, Sanction_Status__c> oldDataMap){

        List<Account> listAccounttoUpdate = new List<Account>();
        for(Sanction_Status__c objSanctionStatus : newDataList){
            if(objSanctionStatus.Sanction_Status__c != oldDataMap.get(objSanctionStatus.Id).Sanction_Status__c 
            || objSanctionStatus.Account__c != oldDataMap.get(objSanctionStatus.Id).Account__c){
                Account acc = new Account();
                acc.Id = objSanctionStatus.Account__c;
                acc.CEL_Sanction_Status__c = objSanctionStatus.Sanction_Status__c;
                acc.Sanction_Date__c = objSanctionStatus.Sanction_Date__c;
                acc.SearchId__c = objSanctionStatus.SearchId__c;
                acc.Decline_Reason__c = objSanctionStatus.Decline_Reason__c;
                acc.Review_Note__c = objSanctionStatus.Review_Note__c;
                acc.Review_Requested__c = objSanctionStatus.Review_Requested__c;
                acc.Review_Requested_By__c = objSanctionStatus.Review_Requested_By__c;
                acc.Reviewed_By__c = objSanctionStatus.Reviewed_By__c;
                acc.Reviewed_On__c = objSanctionStatus.Reviewed_On__c;    
                listAccounttoUpdate.add(acc);
            }
        }

        if(!listAccounttoUpdate.isEmpty()){
            update listAccounttoUpdate;
        }
    }
    
    /********************CD 170   *****************/
    public static void setFieldOnInsert(List<Sanction_Status__c> newDataList){
        
        List<String> AccountIDs = new List<String>();
        
        for(Sanction_Status__c san : newDataList){
            if(san.Account__c != null){
                AccountIDs.add(san.Account__c);
            }
        }
        Map<String,String> newAccountMap = new Map<String,String>();
        for(Account acc : [select id,Name from Account where Id IN:AccountIDs]){
            newAccountMap.put(acc.Id,acc.Name);
        }
        
        for(Sanction_Status__c objSanctionStatus : newDataList){
           objSanctionStatus.Account_Name__c   = !newAccountMap.isEmpty() && newAccountMap.containskey(objSanctionStatus.Account__c) ? newAccountMap.get(objSanctionStatus.Account__c) : '';
        }
        
    }
}