main/default/objects/Rating_Modifier_Factor__c/Rating_Modifier_Factor__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier Factor</label>
    <nameField>
        <displayFormat>RMF-{0000}</displayFormat>
        <label>Rating Modifier Factor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rating Modifier Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifier_Factor__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Rating Modifier Factors</relationshipLabel>
    <relationshipName>Rating_Modifier_Factors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifier_Factor__c/fields/Rating_Modifier__c.field-meta.xml
<CustomField>
    <fullName>Rating_Modifier__c</fullName>
    <label>Rating Modifier</label>
    <referenceTo>Rating_Modifiers__c</referenceTo>
    <relationshipLabel>Rating Modifier Factors</relationshipLabel>
    <relationshipName>Rating_Modifier_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Rating_Modifiers__c/Rating_Modifiers__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier</label>
    <nameField>
        <label>Rating Modifiers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifiers__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Aqueous</fullName>
                <isActive>false</isActive>
                <label>Aqueous</label>
            </value>
            <value>
                <fullName>Cel1</fullName>
                <isActive>false</isActive>
                <label>Cel1</label>
            </value>
            <value>
                <fullName>D&amp;O Standalone</fullName>
                <isActive>false</isActive>
                <label>D&amp;O Standalone</label>
            </value>
            <value>
                <fullName>New Test</fullName>
                <isActive>false</isActive>
                <label>New Test</label>
            </value>
            <value>
                <fullName>Test</fullName>
                <isActive>false</isActive>
                <label>Test</label>
            </value>
            <value>
                <fullName>Test Product 00</fullName>
                <isActive>false</isActive>
                <label>Test Product 00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/RatingModifierFactorQueryUtil.cls
/**************************************************************************************************
 * Class Name: RatingModifierFactorQueryUtil
 * Author: Vinay
 * Date: Dec 22, 2021
 * Description: Class to keep rating modifier factors queries
 * Test Class : RatingModifierFactorQueryUtilTest
 **************************************************************************************************/
public with sharing class RatingModifierFactorQueryUtil {
    /*************************************************
    * Method Name: fetchFatorsByProductNamesAndQuotes
    * Author: 
    * Date: 
    * Params: list of product names and quote ids
    * Return: 
    * Exceptions:
    * Description: list of rating modifier factors
    * Revision: 
     *************************************************/
    public static list<Rating_Modifier_Factor__c> fetchNewCLIs (List<String> prodNames, Set<Id> quoteIds){
        return  [SELECT id from Rating_Modifier_Factor__c where Rating_Modifier__r.Product__c in: prodNames and Quote__c in: quoteIds]; 
    }
}