main/default/objects/TempNoteContent__c/TempNoteContent__c.object-meta.xml
<CustomObject>
    <label>TempNoteContent</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NoteContents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/TempNoteContent__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/TempNoteContent__c/fields/SubmissionId__c.field-meta.xml
<CustomField>
    <fullName>SubmissionId__c</fullName>
    <label>SubmissionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/classes/SubmissionNotesImportBatch_Test.cls
/**************************************************************************************************
 * Class Name: SubmissionNotesImportBatch_Test
 * Author: Gaurish G
 * Date: 11-Oct-2021
 * Description: Test class of "SubmissionNotesImportBatch" class
 **************************************************************************************************/
@isTest
public class SubmissionNotesImportBatch_Test {
    static testMethod void test1(){
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        insert acc;
        
        Product2 product = TestUtil.createProduct('D&O Standalone');
        insert product;
        
        Opportunity opportunity = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        insert opportunity;
        
        Opportunity opportunity1 = TestUtil.createOpportunity('Opp Test1',acc.Id, product.Id);
        insert opportunity1;
        
        TempNoteContent__c tnc = new TempNoteContent__c(Error_Message__c='test',Content__c='test',Title__c='test');
        tnc.SubmissionId__c = opportunity.Id;
        insert tnc;
        
        Test.startTest();
        	SubmissionNotesImportBatch obj = new SubmissionNotesImportBatch();
        	Database.executeBatch(obj);
        Test.stopTest();
    }
}