main/default/objects/Master_Binder__c/Master_Binder__c.object-meta.xml
<CustomObject>
    <label>Master Binder</label>
    <nameField>
        <label>Master Binder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Binders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Master_Binder__c/fields/Layer__c.field-meta.xml
<CustomField>
    <fullName>Layer__c</fullName>
    <label>Layer</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/fields/Binding_License_Number__c.field-meta.xml
<CustomField>
    <fullName>Binding_License_Number__c</fullName>
    <label>Binding License Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Policy__c/fields/Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date__c</fullName>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-Payment</fullName>
            </value>
            <value>
                <fullName>Business Closed</fullName>
            </value>
            <value>
                <fullName>Insured Request</fullName>
            </value>
            <value>
                <fullName>Sanctions/OFAC</fullName>
            </value>
            <value>
                <fullName>Merger or Acquisition</fullName>
            </value>
            <value>
                <fullName>Completion of Operation</fullName>
            </value>
            <value>
                <fullName>Underwriting Reasons</fullName>
            </value>
            <value>
                <fullName>Finance Company Request</fullName>
            </value>
            <value>
                <fullName>Product Unsuitable / Misunderstood</fullName>
            </value>
            <value>
                <fullName>Product too expensive</fullName>
            </value>
            <value>
                <fullName>Alternate Product Purchased</fullName>
            </value>
            <value>
                <fullName>Cover overlapped with pre-existing cover</fullName>
            </value>
            <value>
                <fullName>Product cancelled within cooling off period</fullName>
            </value>
            <value>
                <fullName>Product cancelled by Underwriter</fullName>
            </value>
            <value>
                <fullName>Poor service / complaint</fullName>
            </value>
            <value>
                <fullName>Cover no longer required</fullName>
            </value>
            <value>
                <fullName>Other (administrative reason)</fullName>
            </value>
            <value>
                <fullName>Not Known</fullName>
            </value>
            <value>
                <fullName>Non Payment of premium</fullName>
            </value>
            <value>
                <fullName>Cancellation ab initio</fullName>
                <isActive>false</isActive>
                <label>Cancellation ab initio</label>
            </value>
            <value>
                <fullName>Cancellation mid term</fullName>
                <isActive>false</isActive>
                <label>Cancellation mid term</label>
            </value>
            <value>
                <fullName>Cancelled due to non-payment of premium</fullName>
                <isActive>false</isActive>
                <label>Cancelled due to non-payment of premium</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Layer__c.field-meta.xml
<CustomField>
    <fullName>Layer__c</fullName>
    <label>Layer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Master_Binder__c.field-meta.xml
<CustomField>
    <fullName>Master_Binder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Binder</label>
    <referenceTo>Master_Binder__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/fields/NIPR_Results__c.field-meta.xml
<CustomField>
    <fullName>NIPR_Results__c</fullName>
    <label>NIPR Results</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Pending_or_Prior_Proceedings_Date__c.field-meta.xml
<CustomField>
    <fullName>Pending_or_Prior_Proceedings_Date__c</fullName>
    <label>Pending or Prior Proceedings Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Bound Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>D_O</fullName>
                <label>D&amp;O</label>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Total_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_Premium__c</fullName>
    <label>Total Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/classes/PolicyQueryUtil.cls
/**************************************************************************************************
 * Class Name: PolicyQueryUtil
 * Author: 
 * Date: Jan 3, 2021
 * Description: Class to keep policy queries
 * Test Class : PolicyQueryUtilTest
 **************************************************************************************************/
public with sharing class PolicyQueryUtil {
    
    /*************************************************
    * Method Name: fetchPolicyById
    * Author: 
    * Date: 6th Jan 2022
    * Params: String policyId
    * Return: List<Policy__c>
    * Exceptions:
    * Revision: 
    * Description: Fetch policy by Id
     *************************************************/
    public static List<Policy__c> fetchPolicyById(String policyId){
        return [SELECT Id, Account__c, Cancellation_Reason__c, Effective_Date__c, Expiration_Date__c, Master_Binder__c, 
                Layer__c, Policy_Number__c, Total_Premium__c, Product_Name__c, Cancellation_Date__c, RecordType.Name,
                Policy_Status__c, Pending_or_Prior_Proceedings_Date__c, NIPR_Results__c, Binding_License_Number__c 
                From Policy__c Where Id = :policyId];
    }

}