main/default/objects/Broker_Account__c/Broker_Account__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Broker_Account__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Broker_Contact__r.AccountId ,  Broker_Contact__r.Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <label>Broker Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker_Contact</value>
        </filterItems>
        <infoMessage>You Must Select a Broker Contact</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Broker_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/IsPrimaryBroker__c.field-meta.xml
<CustomField>
    <fullName>IsPrimaryBroker__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary Broker?</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Broker Accounts</relationshipLabel>
    <relationshipName>Opportunity_Accounts1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Claim_Data__c/Claim_Data__c.object-meta.xml
<CustomObject>
    <label>Claim Data</label>
    <nameField>
        <displayFormat>CLD-{00000}</displayFormat>
        <label>Claim Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Claim_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims Data</relationshipLabel>
    <relationshipName>Claims_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Claim_Data__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Claims Summary</relationshipLabel>
    <relationshipName>Claims_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Claim_Data__c/recordTypes/Aqueous.recordType-meta.xml
<RecordType>
    <fullName>Aqueous</fullName>
    <active>true</active>
    <label>Aqueous</label>
</RecordType>

main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Renewals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <label>Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Coverage__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <externalId>true</externalId>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Coverage__c/fields/Main_Profession__c.field-meta.xml
<CustomField>
    <fullName>Main_Profession__c</fullName>
    <label>Main Profession</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Main_Profession</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Payment_Data__c/Payment_Data__c.object-meta.xml
<CustomObject>
    <label>Payment Summary</label>
    <nameField>
        <displayFormat>PD-{00000}</displayFormat>
        <label>Payment Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Payment_Data__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Payments Summary</relationshipLabel>
    <relationshipName>Payments_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Payment_Data__c/recordTypes/Aqueous.recordType-meta.xml
<RecordType>
    <fullName>Aqueous</fullName>
    <active>true</active>
    <label>Aqueous</label>
</RecordType>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Initial_Premium__c.field-meta.xml
<CustomField>
    <fullName>Initial_Premium__c</fullName>
    <label>Initial Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Policy__c/fields/Layer__c.field-meta.xml
<CustomField>
    <fullName>Layer__c</fullName>
    <label>Layer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Bound Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>D_O</fullName>
                <label>D&amp;O</label>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Total_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_Premium__c</fullName>
    <label>Total Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Policy__c/recordTypes/Aqueous.recordType-meta.xml
<RecordType>
    <fullName>Aqueous</fullName>
    <active>true</active>
    <label>Aqueous</label>
</RecordType>

main/default/objects/Quote_Option__c/Quote_Option__c.object-meta.xml
<CustomObject>
    <label>Quote Option</label>
    <nameField>
        <displayFormat>QO-{000000}</displayFormat>
        <label>Quote Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Quote_Option__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <externalId>true</externalId>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Rating_Modifiers__c/Rating_Modifiers__c.object-meta.xml
<CustomObject>
    <label>Rating Modifier</label>
    <nameField>
        <label>Rating Modifiers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Modifiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Rating_Modifiers__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Rating Modifiers</relationshipLabel>
    <relationshipName>Rating_Modifiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Renewal__c/Renewal__c.object-meta.xml
<CustomObject>
    <label>Renewal</label>
    <nameField>
        <displayFormat>REN-{00000}</displayFormat>
        <label>Renewal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Renewal__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker</label>
    <referenceTo>Broker_Account__c</referenceTo>
    <relationshipLabel>Renewals</relationshipLabel>
    <relationshipName>Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Renewal__c/fields/Main_Profession__c.field-meta.xml
<CustomField>
    <fullName>Main_Profession__c</fullName>
    <formula>TEXT(Latest_Bound_Quote__r.Opportunity.Main_Profession__c)</formula>
    <label>Main Profession</label>
    <type>Text</type>
</CustomField>

main/default/objects/Renewal__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Renewals</relationshipLabel>
    <relationshipName>Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Renewal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Suppressed</fullName>
            </value>
            <value>
                <fullName>Ready to Send</fullName>
            </value>
            <value>
                <fullName>1st Notice Sent</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Renewal__c/recordTypes/Aqueous.recordType-meta.xml
<RecordType>
    <fullName>Aqueous</fullName>
    <active>true</active>
    <label>Aqueous</label>
</RecordType>

main/default/objects/TriggerSettings__c/fields/BypassAccountTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassAccountTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassAccountTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassOpportunityTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassOpportunityTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassOpportunityTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassProductTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassProductTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassProductTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/AutoRenewalsEmailBatch_Test.cls
@isTest
public class AutoRenewalsEmailBatch_Test {
    public static testmethod void  test(){
        TriggerSettings__c setting = TestUtil.initialTriggerSetting();
        setting.BypassOpportunityTrigger__c = true;
        setting.BypassAccountTrigger__c = true;
        setting.BypassProductTrigger__c = true;
        setting.BypassQuoteTrigger__c  = true;
        update setting;
       
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Broker').getRecordTypeId();
		Account acc  =TestUtil.createAccount('Test account 1', recordTypeId, '01 Tran Duy Hung','Westminster',
												'California','90000', 'United States');
        insert acc;
        
         // Create contact
		Contact con = new Contact(
			Lastname = 'Test broker',
			RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId(),
            Role__c='Renewals',
            Email = 'abc@gmail.com',
            AccountId = acc.Id
		);
		insert con;
        
        Product2 product = TestUtil.createProduct('D&O');
        insert product;
        
        Opportunity opportunity = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opportunity.StageName = 'Qualified';
        opportunity.Main_Profession__c = 'Property Professionals';
        insert opportunity; 
      	
        List<Policy__c> policyList = new List<Policy__c>();
        Policy__c policy = new Policy__c();
        	policy.Account__c = acc.Id;
        	policy.Product_Name__c = 'Professional Indemnity';
        	policy.Expiration_Date__c = Date.today().addmonths(2);
        	policy.Total_Premium__c = 2000;
        	policy.Initial_Premium__c = null;
        	policy.Policy_Status__c = 'Bound';        	
        	policyList.add(policy);
        
        	Policy__c policy1 = new Policy__c();
        	policy1.Account__c = acc.Id;
        	policy1.Product_Name__c = 'Professional Indemnity';
        	policy1.Expiration_Date__c = Date.today().addmonths(2);
        	policy1.Total_Premium__c = 2000;
        	policy1.Initial_Premium__c = null;
        	policy1.Policy_Status__c = 'Bound';
        	policyList.add(policy1);
        insert policyList;
        
        Quote quote = TestUtil.createQuote('Quote Test',opportunity.Id);
        quote.Azure_ID__c = 'Test Az 1';
        quote.Policy__c = policy.Id;
        quote.Status = 'Bound';
        quote.Layer__c = 'Primary';
        insert quote;
        
         Quote quote1 = TestUtil.createQuote('Quote Test1',opportunity.Id);
        quote1.Azure_ID__c = 'Testaz2';
        quote1.Policy__c = policy1.Id;
        quote1.Status = 'Bound';
        quote1.Layer__c = 'Primary';
        insert quote1;
        
        // Create broker
		Broker_Account__c broketAccount = new Broker_Account__c(
			Broker_Contact__c = con.Id,
			Opportunity__c = opportunity.Id,
			IsPrimaryBroker__c = true,
			Relationship_Type__c = 'Broker'
		);
		insert broketAccount;
        
            //Create coverage
        Coverage__c cov = TestUtil.createCoverage('Coverage test', 'Professional Indemnity');
        cov.Coverage_Type__c = 'Endorsement';
        insert cov;
        
         // Coverages Line Item
         CoveragesLineItem__c coverLi = new CoveragesLineItem__c();
         coverLi.Coverage__c  = cov.Id; 
         coverLi.Quote__c = quote.Id;
         coverLi.Coverage_Premium__c  = 'Text Premium'; 
         coverLi.Min_amt__c  = 1000;
         coverLi.Max_amt__c  = 5000;
         coverLi.Deductible_Frequency__c  = 'Daily';
         coverLi.Options_Value_Percent__c  = 5;
         coverLi.Parent_Coverages_Line_Item__c = null; 
         coverLi.Form_Number__c = 'AQUW153';
         insert coverLi;
        
        Claim_Data__c cd = new Claim_Data__c();
        cd.Account__c = acc.id;
        cd.Policy__c  = policy.id;
        cd.Claim_status__c = 'Test Status';
        cd.Indemnity_Paid__c = 10000.7;
        cd.Fees_Paid__c = 2000.66;
        cd.Fees_Reserve__c = 3000.24;
        cd.Indemnity_Reserve__c = 4000.11;
        cd.TPA_Fees__c = 1223.11;
        insert cd;
        
        Quote_Option__c quoteOpt = new Quote_Option__c();
        quoteOpt.Azure_ID__c = 'Test 1';
        quoteOpt.Quote__c =  quote.Id;
        quoteOpt.Bound__c = true;
        insert quoteOpt;
        
       	Rating_Modifiers__c ratingModifier = TestUtil.createRatingModifier('Is the business regulated by the Royal Institution of Chartered Surveyors?', 'Professional Indemnity', opportunity.Id);
        ratingModifier.Rating_Modifier_Value__c ='YES';
        insert ratingModifier;
        
        Payment_Data__c paymentData = new  Payment_Data__c();
        paymentData.Policy__c = policy.Id ; 
        paymentData.Quote__c = quote.id;
        paymentData.Paid_Status__c = 'Not Paid';        
        paymentData.Last_Modified_Date__c = System.now();
        insert paymentData;
        
        String RecordTypeIdREN = Schema.SObjectType.Renewal__c.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Renewal__c rn = new Renewal__c(
        Broker__c = broketAccount.id,
        Policy__c = policy.Id,
        recordtypeId = RecordTypeIdREN,
        status__c= 'Ready to Send',
        Documents_Required__c = 'Accountants Proposal Form;Accountants Renewal Declaration Form');
        insert rn;
        
        // rn.status__c= 'Ready to Send';
        // update rn;
        
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (thisUser) {
        Group grp = new Group();
        grp.name = 'Admin Renewals';
        grp.Type = 'Regular'; 
        Insert grp;
        
        //Create Group Member
        GroupMember grpMem1 = new GroupMember();
        grpMem1.UserOrGroupId = UserInfo.getUserId();
        grpMem1.GroupId = grp.Id;
        Insert grpMem1;
        }

        Test.startTest();
        AutoRenewalsEmailBatch b = new AutoRenewalsEmailBatch(true, Date.today(), 'Professional Indemnity');
        database.executebatch(b,2);
        Test.stopTest();
    }
}