main/default/objects/Broker_Account__c/Broker_Account__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Broker_Account__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Broker_Contact__r.AccountId ,  Broker_Contact__r.Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <label>Broker Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker_Contact</value>
        </filterItems>
        <infoMessage>You Must Select a Broker Contact</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Broker_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/IsPrimaryBroker__c.field-meta.xml
<CustomField>
    <fullName>IsPrimaryBroker__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary Broker?</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Broker Accounts</relationshipLabel>
    <relationshipName>Opportunity_Accounts1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker</fullName>
                <default>true</default>
                <label>Broker</label>
            </value>
            <value>
                <fullName>Sub-Producer</fullName>
            </value>
            <value>
                <fullName>Additional Interest</fullName>
                <isActive>false</isActive>
                <label>Additional Interest</label>
            </value>
            <value>
                <fullName>Insured</fullName>
                <isActive>false</isActive>
                <label>Insured</label>
            </value>
            <value>
                <fullName>Reinsured</fullName>
                <isActive>false</isActive>
                <label>Reinsured</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Bound Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/RenewalPolicyControllerTest.cls
@isTest
public class RenewalPolicyControllerTest {
@testsetup static void testSetup(){
       TriggerSettings__c setting = TestUtil.initialTriggerSetting();
       setting.BypassQuoteTrigger__c = true;
       update setting;
        Account acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
		insert acc;
        
        Product2 product = TestUtil.createProduct('D&O Standalone');
		insert product; 
        Policy__c pol = new Policy__c();
    	pol.Policy_Number__c = '12345';
    	pol.Effective_Date__c = Date.today()+5;
    	pol.Expiration_Date__c = Date.today() + 30;
    	pol.Policy_Status__c = 'Bound';
    	insert pol;
    
    	Policy__c pol2 = new Policy__c();
    	pol2.Policy_Number__c = '123456';
    	pol2.Effective_Date__c = Date.today()+5;
    	pol2.Expiration_Date__c = Date.today() + 30;
    	pol2.Policy_Status__c = 'Bound';
    	insert pol2;
    
        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
    	opp.Name = 'Test Opportunity';
        opp.CloseDate = Date.today()+10;
        opp.StageName = 'New';
    	opp.Effective_Date__c = Date.today();
    	opp.Expiration_Date__c = Date.today()+10;
        opp.Received_Date__c=Date.today()-120;
         opp.Prior_Policy__c=pol.id;
         opp.Policy__c=pol2.Id;
         opp.Azure_ID__c= 'Test Id';
         opp.Probability= 0.5;
        insert opp;
        
        
        Opportunity opp2 = TestUtil.createOpportunity('Opp Test2',acc.Id, product.Id);
        opp2.CloseDate = Date.today();
        opp2.StageName = 'Closed Won';
    	opp2.Expiration_Date__c = Date.today()+60;
        insert opp2;
        
  
    
        Quote quote1 = TestUtil.createQuote('New quote 1', opp.Id);
        quote1.Status = 'In Progress';
        quote1.Coverage_Product_Options__c = 'D&O';
     	quote1.Refer_Type__c = 'Underwriting Referral';
    	quote1.Policy__c = pol.Id;
        insert quote1;  

		Quote quote2 = Testutil.createQuote('New Quote 2', opp.Id);
        quote2.Status = 'Bound Pending';
        quote2.Coverage_Product_Options__c = 'D&O';
        quote2.Refer_Type__c = 'Underwriting Referral';
    	quote2.Policy__c = pol2.Id;
        insert quote2;  
	
    	Contact con = new Contact(
			Lastname = 'Test broker',
			RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId()
		);
		insert con;
    
    		Broker_Account__c brokerAccount = new Broker_Account__c(
			Broker_Contact__c = con.Id,
			Opportunity__c = opp.Id,
			IsPrimaryBroker__c = true,
			Relationship_Type__c = 'Broker'
		);
		insert brokerAccount;

	}
    @isTest
    static void cloneOpportunityRenewalTest(){
        Test.startTest();
        Opportunity opp = [Select Id, Name, Expiration_Date__c, Type, Received_Date__c, CloseDate, Effective_Date__c, Prior_Policy__c, Policy__c, Azure_ID__c, Probability from Opportunity Limit 1]; 
        opp.Name = 'Bussiness Account Test';
        update opp;
        List<sObject> lstOfOpps = new List<sObject>{opp};
        
       RenewalPolicyController.ResponseResult result = RenewalPolicyController.cloneOpportunityRenewal(lstOfOpps);
        
        Test.stoptest();
        System.assert(result.isSuccess == true);
    }
    
    @isTest
    static void generateOpportunityTest(){
        Test.startTest();
        Opportunity opp = [Select Id, Name, Expiration_Date__c, Type, Received_Date__c, CloseDate, Effective_Date__c, Prior_Policy__c, Policy__c, Azure_ID__c, Probability from Opportunity Limit 1];
        Opportunity generatedOpp = RenewalPolicyController.generateOpportunity(opp);
         System.assertEquals( 'Qualified',generatedOpp.StageName);
        Test.stoptest();
    }
    @isTest
    static void generateQuoteMapTest(){
        Test.startTest();
        List<Quote> lstOfQuotes = [Select Id, OpportunityId from Quote];
        Map<String, Quote> quoteMap = RenewalPolicyController.generateQuoteMap(lstOfQuotes);
         System.assertEquals( true, quoteMap != null);
        Test.stopTest();
    }
    @isTest
    static void getQuoteBusinessQueryTest(){
        Test.startTest();
        List<Id> quoteIds = new List<Id>();
        for(Quote q :[Select Id from Quote]){
            quoteIds.add(q.Id);
        }
     List<Quote> quotes = RenewalPolicyController.getQuoteBusinessQuery(quoteIds);
         System.assert( quotes != null);
        Test.stopTest();
    }
     @isTest
    static void getBrokerAccountsTest(){
        Test.startTest();
        List<Id> quoteIds = new List<Id>();
        for(Quote q :[Select Id from Quote]){
            quoteIds.add(q.Id);
        }
       List<Broker_Account__c> brokerAccounts = RenewalPolicyController.getBrokerAccounts(quoteIds);
        System.assert( brokerAccounts != null);
        Test.stopTest();
    }
    @isTest
    static void renewalControllerTest(){
        Test.startTest();
        Policy__c pol = [Select Id from Policy__c Limit 1];
       RenewalPolicyController.ResponseResult result = RenewalPolicyController.renewalController(pol.Id);
        System.assertEquals('Renewal is not created.', result.msgError);
        Test.stopTest();
    }
     @isTest
    static void renewalControllerBlankPolicyTest(){
        Test.startTest();
        Policy__c pol = [Select Id from Policy__c Limit 1];
       RenewalPolicyController.ResponseResult result = RenewalPolicyController.renewalController('');
         System.assert(result.isSuccess == false);
        Test.stopTest();
    }
     @isTest
    static void renewalControllerQuoteBPTest(){
        Test.startTest();
        Policy__c pol = [Select Id from Policy__c where Policy_Number__c = '123456'];
       RenewalPolicyController.ResponseResult result = RenewalPolicyController.renewalController(pol.Id);
        System.assert(result.isSuccess == false);
        Test.stopTest();
    }
    
     @isTest
    static void generateNewBrokerAccountTest(){
        Test.startTest();
        List<Broker_Account__c> brokerList = [Select id, Opportunity__c from Broker_Account__c Limit 1];
        List<Opportunity> lstOfOpps = [Select Id from Opportunity];
        Map<id, Opportunity> oppMap = new Map<id, Opportunity>(lstOfOpps);
       List<Broker_Account__c> brokerAccounts = RenewalPolicyController.generateNewBrokerAccount(brokerList, oppMap);
       System.assert(brokerAccounts != null);
        Test.stopTest();
    }
}