main/default/objects/Broker_Account__c/Broker_Account__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Broker_Account__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Broker_Contact__r.AccountId ,  Broker_Contact__r.Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker</fullName>
                <default>true</default>
                <label>Broker</label>
            </value>
            <value>
                <fullName>Sub-Producer</fullName>
            </value>
            <value>
                <fullName>Additional Interest</fullName>
                <isActive>false</isActive>
                <label>Additional Interest</label>
            </value>
            <value>
                <fullName>Insured</fullName>
                <isActive>false</isActive>
                <label>Insured</label>
            </value>
            <value>
                <fullName>Reinsured</fullName>
                <isActive>false</isActive>
                <label>Reinsured</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/SectionSetting__c.object-meta.xml
<CustomObject>
    <description>Contains info to configure components that use sections</description>
    <label>Section Setting</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/SectionSetting__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Format__c.field-meta.xml
<CustomField>
    <fullName>Format__c</fullName>
    <label>Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Long Text</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Hyperlink</fullName>
            </value>
            <value>
                <fullName>MultiSelectPicklist</fullName>
            </value>
            <value>
                <fullName>Range</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Main_Section__c.field-meta.xml
<CustomField>
    <fullName>Main_Section__c</fullName>
    <label>Main Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>PCC</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
            <value>
                <fullName>Aqueous</fullName>
                <isActive>false</isActive>
                <label>Aqueous</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Field_API__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_API__c</fullName>
    <label>Source Field API</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_Label__c</fullName>
    <label>Source Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Broker_Account__c</fullName>
                <label>Broker Account</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Policy_c</fullName>
                <label>Policy</label>
            </value>
            <value>
                <fullName>Rating_Modifier_Factor__c</fullName>
            </value>
            <value>
                <fullName>CoveragesLineItem__c</fullName>
            </value>
            <value>
                <fullName>Coverage_Limits_Deductibles__c</fullName>
            </value>
            <value>
                <fullName>Quote_Option__c</fullName>
            </value>
            <value>
                <fullName>Renewal__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Sub_Section__c.field-meta.xml
<CustomField>
    <fullName>Sub_Section__c</fullName>
    <label>Sub Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/classes/SectionSettingVSLwcControllerTest.cls
@isTest
public class SectionSettingVSLwcControllerTest {
	@testSetup
    public static void setup() {
        List<SectionSetting__c> secLst = new List<SectionSetting__c>();
        
        SectionSetting__c secSetting = new SectionSetting__c();
        secSetting.Component__c = 'Submission Info';
        secSetting.Main_Section__c = 'Broker Account';
        secSetting.Source_Object__c = 'Broker_Account__c';
        secSetting.Order__c = 4;
        secSetting.Source_Field_Label__c = 'Relationship Type';
        //secSetting.Source_Field_API__c = 'Relationship_Type__c';
        secSetting.Format__c = 'Picklist';
        secSetting.Product__c = 'MPL';
        secSetting.Record_Type__c = 'Celerity';
        secLst.add(secSetting);
        
        
        SectionSetting__c secSetting1 = new SectionSetting__c();
        secSetting1.Component__c = 'Submission Info';
        secSetting1.Main_Section__c = 'Contact Info';
        secSetting1.Sub_Section__c = 'Insured Contact Info';
        secSetting1.Source_Object__c = 'Contact';
        secSetting1.Order__c = 1;
        secSetting1.Source_Field_Label__c = 'Salutation';
        //secSetting1.Source_Field_API__c = 'Salutation';
        secSetting1.Format__c = 'Text';
        secSetting1.Product__c = 'MPL';
        secSetting1.Record_Type__c = 'Celerity';
        secLst.add(secSetting1);
        
        SectionSetting__c secSetting2 = new SectionSetting__c();
        secSetting2.Component__c = 'Submission Test Info';
        secSetting2.Main_Section__c = 'Broker Account';
        secSetting2.Source_Object__c = 'Broker_Account__c';
        secSetting2.Order__c = 4;
        secSetting2.Source_Field_Label__c = 'Relationship Type';
        secSetting2.Source_Field_API__c = 'Relationship_Type__c';
        secSetting2.Format__c = 'Picklist';
        secSetting2.Product__c = 'MPL';
        secSetting2.Record_Type__c = 'Celerity';
        secLst.add(secSetting2);
        
        SectionSetting__c secSetting3 = new SectionSetting__c();
        secSetting3.Component__c = 'Test Info';
        secSetting3.Main_Section__c = 'Broker Account';
        secSetting3.Sub_Section__c = 'Insured Contact Info';
        secSetting3.Source_Object__c = 'Contact';
        secSetting3.Order__c = 2;
        secSetting3.Source_Field_Label__c = 'Salutation';
        //secSetting3.Source_Field_API__c = 'Salutation';
        secSetting3.Format__c = 'Text';
        secSetting3.Product__c = 'MPL';
        secSetting3.Record_Type__c = 'Celerity';
       	secLst.add(secSetting3);
        
        SectionSetting__c secSetting4 = new SectionSetting__c();
        secSetting4.Component__c = 'Testing Info';
        secSetting4.Main_Section__c = 'Broker Account';
        secSetting4.Sub_Section__c = 'Insured Contact Info';
        secSetting4.Source_Object__c = 'Contact';
        secSetting4.Order__c = 2;
        secSetting4.Source_Field_Label__c = 'Salutation';
        secSetting3.Source_Field_API__c = 'Salutation';
        secSetting4.Format__c = 'Text';
        secSetting4.Product__c = 'MPL';
        secSetting4.Record_Type__c = 'Celerity';
       	secLst.add(secSetting4);
        insert secLst;
    }
    
    @isTest
    public static void testGetSectionSettingStructure() {
        SectionSettingViewStructureLwcController.getSectionSettingStructure('Celerity','Submission Info');
        
    }
}