main/default/objects/Broker_Account__c/Broker_Account__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Broker_Account__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Broker_Contact__r.AccountId ,  Broker_Contact__r.Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <label>Broker Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker_Contact</value>
        </filterItems>
        <infoMessage>You Must Select a Broker Contact</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Broker_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/IsPrimaryBroker__c.field-meta.xml
<CustomField>
    <fullName>IsPrimaryBroker__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary Broker?</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Broker Accounts</relationshipLabel>
    <relationshipName>Opportunity_Accounts1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker</fullName>
                <default>true</default>
                <label>Broker</label>
            </value>
            <value>
                <fullName>Sub-Producer</fullName>
            </value>
            <value>
                <fullName>Additional Interest</fullName>
                <isActive>false</isActive>
                <label>Additional Interest</label>
            </value>
            <value>
                <fullName>Insured</fullName>
                <isActive>false</isActive>
                <label>Insured</label>
            </value>
            <value>
                <fullName>Reinsured</fullName>
                <isActive>false</isActive>
                <label>Reinsured</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/LookupControllerTest.cls
@isTest
public class LookupControllerTest {
	@testSetup
    public static void setup() {
        // create broker account 
        Id brokerRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account accBroker = TestUtil.createAccount('Account_Business_Test_01', brokerRtId, '5305, Monroe Street', 'Toledo', 'Ohio','43623', 'United States');
        insert accBroker;
        
        Id brokerRtId1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Broker').getRecordTypeId();
        Account accBroker1 = TestUtil.createAccount('Account_Broker_Test_02', brokerRtId1, '5305, Monroe Street', 'Toledo', 'Ohio','43623', 'United States');
        insert accBroker1;
        
        // create product
        Product2 product = TestUtil.createProduct('Test Product');
		insert product;
        
		// create opportunity        
        Opportunity opp = TestUtil.createOpportunity('Test Opportunity', accBroker.Id, product.Id);
        opp.StageName = 'Qualified';
        insert opp;
        
        Id recordTypeContactAgency = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Contact contactBroker = new Contact(
			LastName = 'Contact_Business_Test_01',
			RecordTypeId =recordTypeContactAgency ,
            Azure_Id__c = '1234',
			AccountId = accBroker.Id);
		insert contactBroker;
        
        Id recordTypeContactAgency1 = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId();        
        Contact contactBroker1 = new Contact(
			LastName = 'Contact_Broker_Test_02',
			RecordTypeId = recordTypeContactAgency1 ,
            Azure_Id__c = '4321',
			AccountId = accBroker1.Id);
		insert contactBroker1;
        
        Broker_Account__c newBrokerAccount = new Broker_Account__c(
													Broker_Contact__c = contactBroker1.Id,
													Relationship_Type__c = 'Broker',
													IsPrimaryBroker__c = true,
													Opportunity__c = opp.Id
													);
	    insert newBrokerAccount;
    }
    
    @isTest
    public static void testLookUp() {
        Account acc = [SELECT id,Name FROM Account WHERE Name=:'Account_Business_Test_01' LIMIT 1];
        Schema.SObjectType sObjectType = (acc.id).getSobjectType();
        String objectType = String.valueOf(sObjectType);
        String filter = 'Name=\''+'Account_Business_Test_01'+'\'';
        LookupController.lookUp('Test',objectType,filter);
        LookupController.lookUp('',objectType,'');
        LookupController.lookUp('Test',objectType,'');
       
        
        Opportunity opp = [SELECT id,Name FROM Opportunity WHERE StageName=:'Qualified' LIMIT 1];
        Schema.SObjectType sObjectTypeOpp = (opp.id).getSobjectType();
        String objectTypeOpp = String.valueOf(sObjectTypeOpp);
        String filterOpp = 'Name=\''+'Test Opportunity'+'\'';
        LookupController.lookUp('Test',objectTypeOpp,filterOpp);
        LookupController.lookUp('',objectTypeOpp,'');
        LookupController.lookUp('Test',objectTypeOpp,'');
        
        Contact con = [SELECT id,LastName FROM Contact Where LastName ='Contact_Business_Test_01' LIMIT 1];
        Schema.SObjectType sObjectTypeCon = (con.id).getSobjectType();
        String objectTypeCon = String.valueOf(sObjectTypeCon);
        String filterCon = 'LastName=\''+'Contact_Business_Test_01'+'\'';
        LookupController.lookUp('Test',objectTypeCon,filterCon);
        LookupController.lookUp('',objectTypeCon,'');
        LookupController.lookUp('Test',objectTypeCon,'');
        
      /*  Broker_Account__c BrokerAccount = [SELECT id,Name FROM Broker_Account__c Where Relationship_Type__c=:'Broker' LIMIT 1];
        Schema.SObjectType sObjectTypebrokerAcc = (BrokerAccount.id).getSobjectType();
        String objectTypeBrokkerAcc = String.valueOf(sObjectTypebrokerAcc);
        String filterBrokerAcc = 'Relationship_Type__c=\''+'Broker'+'\'';
        LookupController.lookUp('Test',objectTypeBrokkerAcc,filterBrokerAcc);
        LookupController.lookUp('',objectTypeBrokkerAcc,'');
        LookupController.lookUp('Test',objectTypeBrokkerAcc,'');*/
        
    }
    
    @isTest
    public static void testGetObjectById() {
        Account acc = [SELECT id,Name FROM Account WHERE Name=:'Account_Business_Test_01' LIMIT 1];
        Schema.SObjectType sObjectType = (acc.id).getSobjectType();
        String objectType = String.valueOf(sObjectType);
        sObject result = LookupController.getObjectById(String.valueOf(acc.Id),objectType);
        System.assertEquals('Account_Business_Test_01',((Account)result).Name);
    }
    @isTest
    public static void testGetLastModified() {
        LookupController.getModifiedRecords('User',UserInfo.getUserId());
    }
    
}