main/default/objects/Broker_Account__c/Broker_Account__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Broker_Account__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Broker_Contact__r.AccountId ,  Broker_Contact__r.Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Quote_Process__c/Quote_Process__c.object-meta.xml
<CustomObject>
    <label>Underwriter Workbench</label>
    <nameField>
        <label>Quote Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Underwriter Workbench</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Quote_Process__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quote_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Quote_Process__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+Submission__r.Agency__c, Submission__r.Agency__r.Name , &apos;_blank&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agency</label>
    <type>Text</type>
</CustomField>

main/default/objects/Quote_Process__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insured Info</fullName>
                <default>true</default>
                <label>Insured Info</label>
            </value>
            <value>
                <fullName>Submission Console</fullName>
            </value>
            <value>
                <fullName>Underwriting Console</fullName>
            </value>
            <value>
                <fullName>Submission Info</fullName>
            </value>
            <value>
                <fullName>Underwritting Analysis</fullName>
                <label>Underwriting Analysis</label>
            </value>
            <value>
                <fullName>Compare &amp; Rate Quotes</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Quote Console</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
                <isActive>false</isActive>
                <label>Closed Lost</label>
            </value>
            <value>
                <fullName>Closed Won</fullName>
                <isActive>false</isActive>
                <label>Closed Won</label>
            </value>
            <value>
                <fullName>Pre-Screening</fullName>
                <isActive>false</isActive>
                <label>Pre-Screening</label>
            </value>
            <value>
                <fullName>Quote Version Console</fullName>
                <isActive>false</isActive>
                <label>Quote Version Console</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Quote_Process__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submission</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Underwriter Workbench</relationshipLabel>
    <relationshipName>Quote_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/OpportunityInitFormCmpControllerTest.cls
/***********************************************************************
 * Class Name: OpportunityInitFormCmpControllerTest
 * Author: Khanh TRAN
 * Date: 28-Oct-2019
 * Description: Unit test for OpportunityInitFormCmpController 
 ***********************************************************************
 */

@isTest
private class OpportunityInitFormCmpControllerTest {
	public static Product2 product;
	public static Account acc;
	public static Opportunity opp;
    public static Quote_Process__c newQuoteProcess;
    public static Contact con;
	
	static {
        
		acc = TestUtil.createBusinessAccount('Bussiness Account Test', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
		insert acc;

		product = TestUtil.createProduct('D&O Standalone');
		insert product;

		opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
		insert opp;
        
        con = new Contact(
			Lastname = 'Test',
			RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId()
		);
		insert con;
        
        newQuoteProcess = new Quote_Process__c(Submission__c = opp.Id, Account__c = opp.AccountId, Status__c = 'Submission Info', Record_Type__c = 'Celerity');
		insert newQuoteProcess;
        
        opp.Agency__c = acc.Id;
        opp.Type = 'New Business';
        opp.StageName = 'New';
        update opp;           
	}
	
	@isTest static void getOpportunityRecordTypeTest() {
		List<RecordType> oppRecordTypeList = OpportunityInitFormCmpController.getOpportunityRecordType();
        OpportunityInitFormCmpController.getSubmissionName(acc.Id,product.Id);
		System.assertEquals('Aqueous', oppRecordTypeList[0].Name);
	}

	// getOpportunityInfo
	@isTest static void getOpportunityInfoTest(){
		new OpportunityInitFormCmpController.GenerateResult();
		new OpportunityInitFormCmpController.AccountWrapper();
		OpportunityInitFormCmpController.GenerateResult result = OpportunityInitFormCmpController.getOpportunityInfo(acc.Id, product.Id);
		System.assertEquals('Bussiness Account Test D&O Standalone', result.oppName);
	}

	@isTest static void getInfoTest(){
		Opportunity testOpp = OpportunityInitFormCmpController.getInfo(opp.Id);
		System.assert(testOpp != null);
	}
    
    //Added by sarthak 07-07-2020
    @isTest
    static void getFieldNameOpportunityTest(){
        Test.startTest();
        List<String> apiNames = OpportunityInitFormCmpController.getFieldNameOpportunity();       
        Test.stopTest();
        System.assert(apiNames != null);
    }
    //Added by sarthak 07-07-2020
   @isTest
    static void validateOpportunityDuplicateTest2(){
        Test.startTest();
        Contact con = [Select Id from Contact Limit 1];
        OpportunityInitFormCmpController.ValidateResult vResult = OpportunityInitFormCmpController.validateOpportunity(acc.Id, product.Id, con.Id, 'Primary');
        Test.stopTest();
        System.assert(con != null);
    }
    
    @isTest
    static void validateOpportunityTest(){
        Broker_Account__c newBroAccount = TestUtil.createBrokerAccount(con.Id, opp.Id);
        insert newBroAccount;
        
        Test.startTest();
        Contact con = [Select Id from Contact Limit 1];
        OpportunityInitFormCmpController.ValidateResult vResult = OpportunityInitFormCmpController.validateOpportunity(acc.Id, product.Id, con.Id, 'Primary');
        Test.stopTest();
        System.assert(newBroAccount != null);
    }
    
    @isTest static void getDefaultRecordTypeTest() {
        Test.startTest();
		String defaultRecordType = OpportunityInitFormCmpController.getDefaultRecordType(newQuoteProcess.Id);
        Test.stopTest();
		System.assert(defaultRecordType.contains('Celerity'));
	}
    
    @isTest static void getDefaultProductTest() {
        Test.startTest();
		String defaultProduct = OpportunityInitFormCmpController.getDefaultProduct(newQuoteProcess.Id);
        Test.stopTest();
		
        System.assertEquals('', defaultProduct);
	}
}