main/default/objects/Broker_Account__c/Broker_Account__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Broker_Account__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Broker_Contact__r.AccountId ,  Broker_Contact__r.Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <label>Broker Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker_Contact</value>
        </filterItems>
        <infoMessage>You Must Select a Broker Contact</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Broker_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/IsPrimaryBroker__c.field-meta.xml
<CustomField>
    <fullName>IsPrimaryBroker__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary Broker?</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Broker Accounts</relationshipLabel>
    <relationshipName>Opportunity_Accounts1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker</fullName>
                <default>true</default>
                <label>Broker</label>
            </value>
            <value>
                <fullName>Sub-Producer</fullName>
            </value>
            <value>
                <fullName>Additional Interest</fullName>
                <isActive>false</isActive>
                <label>Additional Interest</label>
            </value>
            <value>
                <fullName>Insured</fullName>
                <isActive>false</isActive>
                <label>Insured</label>
            </value>
            <value>
                <fullName>Reinsured</fullName>
                <isActive>false</isActive>
                <label>Reinsured</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/classes/UpdateLicenseInfoOnPolicy_Test.cls
@isTest
public class UpdateLicenseInfoOnPolicy_Test {
    
    public static testmethod void testbrokerpolicy(){
        
        test.startTest();
        
        // Account Business
		Account accBusiness = TestUtil.createBusinessAccount('Bussiness Account Test', 'Broker_Account', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        
		insert accBusiness;

	/*	// Create Contact Broker
        Id recordTypeContactAgency = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId();
		Contact contactBroker = TestUtil.createContact(accBusiness.Id, 'Broker', 'New broker contact');
		contactBroker.RecordTypeId = recordTypeContactAgency;
		insert contactBroker;
        */
        Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Broker_Contact').getRecordTypeId();
        system.debug('broker id' + recordTypeId);
		Contact newContact = new Contact(
			LastName ='New broker contact',
			RecordTypeId = recordTypeId,
			AccountId = accBusiness.Id);
        system.debug('hello'+newContact);
        insert newContact;

		Product2 product = TestUtil.createProduct('MPL Standalone');
		insert product;

        Opportunity oppt = TestUtil.createOpportunity('Opp Test',accBusiness.Id, product.Id);
		insert oppt;
		TriggerHandler.bypass('BrokerAccountTriggerBaseHandler');
		
        // Add Broker to Opportunity
			Broker_Account__c broAcc = new Broker_Account__c();
			broAcc.Relationship_Type__c = 'Broker';
			broAcc.Broker_Contact__c = newContact.Id;
			broAcc.Opportunity__c = oppt.Id;
			broAcc.IsPrimaryBroker__c = true;
		insert broAcc;
        TriggerHandler.bypass('BrokerAccountTriggerBaseHandler');
        system.debug('BrokerAccount' + broAcc);
        
        Quote quote = TestUtil.createQuote('New Quote Test',oppt.Id);
		quote.Coverage_Product_Options__c ='MPL';
		insert quote;	
        
         
        Policy__c policy = new Policy__c();
        policy.Account__c = accBusiness.Id; 
        policy.Expiration_Date__c = Date.today().addDays(100);
        insert policy;
        
        UpdateLicenseInfoOnPolicy m =  new UpdateLicenseInfoOnPolicy();
        UpdateLicenseInfoOnPolicy.getBrokerDetail(quote.id);
        UpdateLicenseInfoOnPolicy.getBrokerDetail(policy.Id);
        UpdateLicenseInfoOnPolicy.updatePolicyBLInfo(policy.Id,'{"blOwner":"Agency","id":"a082500000IxAI5AAN","blOwnerName":"Test User","blNo":"1407112","liceseState":"TX","NPNStatus":"Pass","blOwnerAddress":"Test User, 15687 Thistle Court, New York, New York, 40000"}');
        
        test.stopTest();
    }
    
}