main/default/objects/Broker_Account__c/Broker_Account__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Broker_Account__c/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <label>Broker Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker_Contact</value>
        </filterItems>
        <infoMessage>You Must Select a Broker Contact</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Broker_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <label>Document Template</label>
    <nameField>
        <displayFormat>DOC-{0000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Document_Template__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <label>Document Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Renewal__c/Renewal__c.object-meta.xml
<CustomObject>
    <label>Renewal</label>
    <nameField>
        <displayFormat>REN-{00000}</displayFormat>
        <label>Renewal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Renewal__c/fields/Assigned_Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Underwriter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Underwriter</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>AQ Auto Renewals checkbox needs to be true on the user.</errorMessage>
        <filterItems>
            <field>User.Is_AQ_Auto_Renewals_Underwriter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Renewals1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Renewal__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker</label>
    <referenceTo>Broker_Account__c</referenceTo>
    <relationshipLabel>Renewals</relationshipLabel>
    <relationshipName>Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Renewal__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Renewals</relationshipLabel>
    <relationshipName>Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/User/fields/Is_AQ_Auto_Renewals_Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Is_AQ_Auto_Renewals_Underwriter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is AQ Auto Renewals Underwriter</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/RenewalServiceHandler_AQ.cls
public class RenewalServiceHandler_AQ {


public static AutoRenewalsWrapper autoAssignRenewals(AutoRenewalsWrapper wrapperAutoRenewals, List<Renewal__c> listOfRenewals){

   List<String> publicGroupUsers = new List<String>();
   List<Renewal__c> renewalListUpdate = new List<Renewal__c>(); 

    for(User user : [select Id from user where Is_AQ_Auto_Renewals_Underwriter__c = true]){
      publicGroupUsers.add(user.Id);
   }

    
    
   for( Renewal__c renewalRecord  : [select id,Policy__c,Policy__r.Account__c,Assigned_Underwriter__c from Renewal__c where Id IN: listOfRenewals]){

      if( renewalRecord.Policy__c != null && renewalRecord.Policy__r.Account__c != null){

    
    
           /****************** If map is empty then assign first user from group ************/
           if(wrapperAutoRenewals == null || (wrapperAutoRenewals != null && wrapperAutoRenewals.mapOfAccountVsUser.isEmpty())){
              if(wrapperAutoRenewals == null){
                        wrapperAutoRenewals = new RenewalServiceHandler_AQ.AutoRenewalsWrapper();
                        wrapperAutoRenewals.index = 0;
                        wrapperAutoRenewals.mapOfAccountVsUser = new Map<String,String>();
                  }
                renewalRecord.Assigned_Underwriter__c = publicGroupUsers[wrapperAutoRenewals.index];

                wrapperAutoRenewals.mapOfAccountVsUser.put(renewalRecord.Policy__r.Account__c,renewalRecord.Assigned_Underwriter__c);
                
               }
               else if(!wrapperAutoRenewals.mapOfAccountVsUser.isEmpty()){

                  /******************** If user map contains Account whom we already have assigned the user */
                   if(wrapperAutoRenewals.mapOfAccountVsUser.containsKey(renewalRecord.Policy__r.Account__c)){

                    renewalRecord.Assigned_Underwriter__c = wrapperAutoRenewals.mapOfAccountVsUser.get(renewalRecord.Policy__r.Account__c);

                   }
                   else{

                     /*************************** Emptying the map so that map gets empty if account id gets changed to maintain the heap size*/
                     wrapperAutoRenewals.mapOfAccountVsUser = new Map<String,String>();
                  
                     renewalRecord.Assigned_Underwriter__c = publicGroupUsers[wrapperAutoRenewals.index];

                     wrapperAutoRenewals.mapOfAccountVsUser.put(renewalRecord.Policy__r.Account__c,renewalRecord.Assigned_Underwriter__c);
                    

                  }

               }

                   
               /********* Indexing Logic ***********/
               if(wrapperAutoRenewals.index <= publicGroupUsers.size()-2){
                  wrapperAutoRenewals.index++;
               }
               else{
                  wrapperAutoRenewals.index = 0;
               }

            }

            renewalListUpdate.add(renewalRecord);
          }

          if(renewalListUpdate.size()>0){
            system.debug('Assigned Underwriter Before Update'+renewalListUpdate[0].Assigned_Underwriter__c);
            GlobalStaticVar.byPassRenewalTrigger = true;
            update renewalListUpdate;
            system.debug('listOfRenewals update'+renewalListUpdate[0].Id);
             system.debug('Assigned Underwriter After Update'+renewalListUpdate[0].Assigned_Underwriter__c);
        }
          return wrapperAutoRenewals;
   }

   public static Map<String,List<Renewal__c>> emailNotificationHandler(Map<String,List<Renewal__c>> mapofBrokerAndRenewals,List<Renewal__c> listOfRenewals){


      for(Renewal__c renewalRecord : listOfRenewals){
       
         if(renewalRecord.Broker__c != null &&  renewalRecord.Broker__r.Broker_Contact__c != null){

            if(mapofBrokerAndRenewals==null ||  mapofBrokerAndRenewals.isEmpty() ){

               mapofBrokerAndRenewals = new Map<String,List<Renewal__c>>();

               mapofBrokerAndRenewals.put(renewalRecord.Broker__r.Broker_Contact__r.AccountId,new List<Renewal__c>{renewalRecord});

            }
            else if(mapofBrokerAndRenewals.containsKey(renewalRecord.Broker__r.Broker_Contact__r.AccountId)){

               mapofBrokerAndRenewals.get(renewalRecord.Broker__r.Broker_Contact__r.AccountId).add(renewalRecord);
            }
            else if(!mapofBrokerAndRenewals.containsKey(renewalRecord.Broker__r.Broker_Contact__r.AccountId)){
               
               mapofBrokerAndRenewals.put(renewalRecord.Broker__r.Broker_Contact__r.AccountId,new List<Renewal__c>{renewalRecord});
            }

         }
      }

      return mapofBrokerAndRenewals;



   }

   public static Map<String,List<ContentVersion>> fetchDocumentRelatedFiles(Set<String> documentRequired){
    
    List<ContentVersion> documents  = new List<ContentVersion>{};
    List<String> contentDocumentIds = new List<String>();
    List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>{};
    Map<String,String> documentNameMap = new Map<String,String>();
    Map<String,String> contentLinkDocMap = new Map<String,String>();
    Map<String,List<ContentVersion>> ContentVersionMap = new Map<String,List<ContentVersion>>();

    Set<Id> documentsIds = new Set<Id>();
   
    List<Document_Template__c> documentTemplates   = [select id,Document_Name__c from Document_Template__c where Document_Name__c IN:documentRequired];

    for(Document_Template__c docTemp  : documentTemplates){
      documentsIds.add(docTemp.Id);
      documentNameMap.put(docTemp.Id,docTemp.Document_Name__c.trim());
    }
    
    for(ContentDocumentLink contdocLink  : [SELECT ContentDocumentId, LinkedEntityId  FROM ContentDocumentLink where LinkedEntityId IN:documentsIds]){
      contentDocumentIds.add(contdocLink.ContentDocumentId);
      contentLinkDocMap.put(contdocLink.ContentDocumentId,contdocLink.LinkedEntityId);
    }
    documents.addAll([
      SELECT Id, Title, FileType, VersionData, isLatest, ContentDocumentId,FileExtension
      FROM ContentVersion
      WHERE isLatest = true AND ContentDocumentId IN :contentDocumentIds
    ]);

    for (ContentVersion document: documents) {

       String documentId  = contentLinkDocMap.get(document.ContentDocumentId);
       String documentName = documentNameMap.get(documentId);

       if(!ContentVersionMap.containskey(documentName)){
         ContentVersionMap.put(documentName,new List<ContentVersion>{});
       }
       ContentVersionMap.get(documentName).add(document);
      /*  Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
        attachment.setBody(document.VersionData);
        attachment.setFileName(document.Title);
       attachments.add(attachment);*/
    }

    return ContentVersionMap; 

   }


   public class AutoRenewalsWrapper{
      public Map<String,String> mapOfAccountVsUser;
      public Integer index;
   }

}