main/default/objects/Broker_Account__c/Broker_Account__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Broker_Account__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Broker_Contact__r.AccountId ,  Broker_Contact__r.Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <label>Broker Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker_Contact</value>
        </filterItems>
        <infoMessage>You Must Select a Broker Contact</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Broker_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Bypass_New_Broker_Validation__c.field-meta.xml
<CustomField>
    <fullName>Bypass_New_Broker_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass New Broker Validation</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/IsPrimaryBroker__c.field-meta.xml
<CustomField>
    <fullName>IsPrimaryBroker__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary Broker?</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Broker Accounts</relationshipLabel>
    <relationshipName>Opportunity_Accounts1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker</fullName>
                <default>true</default>
                <label>Broker</label>
            </value>
            <value>
                <fullName>Sub-Producer</fullName>
            </value>
            <value>
                <fullName>Additional Interest</fullName>
                <isActive>false</isActive>
                <label>Additional Interest</label>
            </value>
            <value>
                <fullName>Insured</fullName>
                <isActive>false</isActive>
                <label>Insured</label>
            </value>
            <value>
                <fullName>Reinsured</fullName>
                <isActive>false</isActive>
                <label>Reinsured</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Renewals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Initial_Premium__c.field-meta.xml
<CustomField>
    <fullName>Initial_Premium__c</fullName>
    <label>Initial Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Policy__c/fields/Layer__c.field-meta.xml
<CustomField>
    <fullName>Layer__c</fullName>
    <label>Layer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Bound Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Fiduciary</fullName>
            </value>
            <value>
                <fullName>EPL</fullName>
            </value>
            <value>
                <fullName>D_O</fullName>
                <label>D&amp;O</label>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>MPL Standalone</fullName>
            </value>
            <value>
                <fullName>Cyber Standalone</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Total_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_Premium__c</fullName>
    <label>Total Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Policy__c/recordTypes/Aqueous.recordType-meta.xml
<RecordType>
    <fullName>Aqueous</fullName>
    <active>true</active>
    <label>Aqueous</label>
</RecordType>

main/default/objects/Policy__c/recordTypes/Celerity.recordType-meta.xml
<RecordType>
    <fullName>Celerity</fullName>
    <active>true</active>
    <label>Celerity</label>
</RecordType>

main/default/objects/Renewal__c/Renewal__c.object-meta.xml
<CustomObject>
    <label>Renewal</label>
    <nameField>
        <displayFormat>REN-{00000}</displayFormat>
        <label>Renewal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Renewal__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker</label>
    <referenceTo>Broker_Account__c</referenceTo>
    <relationshipLabel>Renewals</relationshipLabel>
    <relationshipName>Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Renewal__c/fields/No_Recipients__c.field-meta.xml
<CustomField>
    <fullName>No_Recipients__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Recipients</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Renewal__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Renewals</relationshipLabel>
    <relationshipName>Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Renewal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Suppressed</fullName>
            </value>
            <value>
                <fullName>Ready to Send</fullName>
            </value>
            <value>
                <fullName>1st Notice Sent</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Renewal__c/recordTypes/Aqueous.recordType-meta.xml
<RecordType>
    <fullName>Aqueous</fullName>
    <active>true</active>
    <label>Aqueous</label>
</RecordType>

main/default/objects/TriggerSettings__c/fields/BypassAccountTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassAccountTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassAccountTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassContactTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassContactTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassContactTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassOpportunityTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassOpportunityTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassOpportunityTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassProductTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassProductTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassProductTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/ContactTriggerHandlerTest.cls
/**************************************************************************************************
 * Class Name: ContactTriggerHandlerTest
 * Author: Hoang Bui
 * Date: 21-Oct-2019
 * Description: ContactTriggerHandlerTest Test
 **************************************************************************************************/
@isTest
private class ContactTriggerHandlerTest {
   @testSetup static void setup(){
    	TriggerSettings__c setting = TestUtil.initialTriggerSetting();
		setting.BypassContactTrigger__c = false;
        setting.BypassOpportunityTrigger__c = true;
        setting.BypassAccountTrigger__c = true;
        setting.BypassProductTrigger__c = true;
        setting.BypassQuoteTrigger__c  = true;
        update setting;
       
        
       /*
        
       System.debug('Renewal'+ rn);
       
        con.LastName = 'Test2 Broker';
        update con;
       
        Contact con3 = new Contact(
            Lastname = 'Test broker3',
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId()
        );
        insert con3;
        con3.Role__c = 'Renewals';
        update con3;
        con3.Role__c = '';
       	update con3;*/

    }

    @isTest
	static void testCreateAndUpdateAccountContact() {
        Id recordTypeBrokerAgency = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Broker').getRecordTypeId();
        Id recordTypeContactAgency = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId();
        List<String> contactIds = new List<String>();
		Account accBroker = TestUtil.createBusinessAccount('Broker Account Test', 'Broker_Account', '625, South Mill Road', 'Anycity', 'New York', '67074', 'United States');
		accBroker.RecordTypeId = recordTypeBrokerAgency;
		
        insert accBroker;
        
        //Create Product
		Product2 prd = new Product2(
			Name = 'Private Company Combo',
			RecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('Celerity').getRecordTypeId(),
			Innovisk_Entity_ID__c = 'Celerity',
			Package_Indicator__c = true,
			IsActive = true,
			Expiration_Date__c = Date.today().addDays(200),
			Effective_Date__c = Date.today().addDays(-1)
		);
		insert prd;

        
        // Create opportunity
		Opportunity opp = new Opportunity();
		opp.Name = 'Test opp';
		opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Celerity').getRecordTypeId();
		opp.Coverage_Product_Options__c = 'D&O';
		opp.AccountId = accBroker.Id;
		opp.Pricebook2Id = Test.getStandardPricebookId();
		opp.Product__c = prd.Id;
		opp.Received_Date__c = Date.today();
		opp.CloseDate = Date.today().addDays(30);
		opp.Effective_Date__c = Date.today();
		opp.Type = 'New Business';
		opp.LeadSource = 'Email';
		opp.StageName = 'New';
		insert opp;

        // Create Contact Broker
        Contact contactBroker = TestUtil.createContact(accBroker.Id, 'Broker_Contact', 'New broker contact');
		contactBroker.RecordTypeId = recordTypeContactAgency;
		contactBroker.Home_License_no__c ='123456';
        contactBroker.Email = 'Test@test.com';
		Test.startTest();
		insert contactBroker;
               
        
         // Create broker
		Broker_Account__c brokerAccount = new Broker_Account__c(
			Broker_Contact__c = contactBroker.Id,
			Opportunity__c = opp.Id,
			IsPrimaryBroker__c = true,
			Relationship_Type__c = 'Broker'
		);
		insert brokerAccount;

		contactBroker.LastName = 'New update Name';
		contactBroker.Home_License_no__c ='0123456';
        contactBroker.Email = 'Test2@test.com';
		update contactBroker;
		Test.stopTest();
        
       

		List<Contact> contacts = [Select Id From Contact];
		system.assertEquals(false, contacts.isEmpty());
	}

	@isTest
	static void testCreateUpdateBusinessContact() {
        Id recordTypeBrokerAgency = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Id recordTypeContactAgency = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        List<String> contactIds = new List<String>();
		Account accBroker = TestUtil.createBusinessAccount('Broker Account Test', 'Broker_Account', '625, South Mill Road', 'Anycity', 'New York', '67074', 'United States');
		accBroker.RecordTypeId = recordTypeBrokerAgency;
        insert accBroker;

        // Create Contact Broker
        Contact contactBroker = TestUtil.createContact(accBroker.Id, 'Broker_Contact', 'New broker contact');
		contactBroker.RecordTypeId = recordTypeContactAgency;
		contactBroker.Home_License_no__c ='123456';
        contactBroker.Email = 'Test@test.com';

		Test.startTest();
		insert contactBroker;

		contactBroker.Email = 'test@test2.com';
		update contactBroker;
		Test.stopTest();
	}	

	@isTest
	static void testCreateUpdateOtherContact() {
        Id recordTypeBrokerAgency = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Id recordTypeContactAgency = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Attorney').getRecordTypeId();
        List<String> contactIds = new List<String>();
		Account accBroker = TestUtil.createBusinessAccount('Broker Account Test', 'Broker_Account', '625, South Mill Road', 'Anycity', 'New York', '67074', 'United States');
		accBroker.RecordTypeId = recordTypeBrokerAgency;
        insert accBroker;

        // Create Contact Broker
        Contact contactBroker = TestUtil.createContact(accBroker.Id, 'Broker_Contact', 'New broker contact');
		contactBroker.RecordTypeId = recordTypeContactAgency;
		contactBroker.Home_License_no__c ='123456';
        contactBroker.Email = 'Test@test.com';

		Test.startTest();
		insert contactBroker;

		contactBroker.Email = 'test@test2.com';
		update contactBroker;
		Test.stopTest();
	}
    
   @istest 
    public static void updateNoRecipientOnAutoRenewalsTest()
    {
   		list<Contact> conList = new list<Contact>();
        List<Policy__c> policyList = new List<Policy__c>();
        List<Quote> quoteList = new List<Quote>();
       
        Id recordTypeIdBrokerAcc = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Broker').getRecordTypeId();
        Account brokeracc  =TestUtil.createAccount('Test account 1', recordTypeIdBrokerAcc, '01 Tran Duy Hung','Westminster',
                                             'California','90000', 'United States');
         insert brokeracc;
        
        Id recordTypeIdBusiness = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account businessacc  =TestUtil.createAccount('Test account business', recordTypeIdBusiness, '01 Tran Duy Hung','Westminster',
                                             'California','90000', 'United States');
         insert businessacc;
        
        // Create contact 
        Contact con = new Contact();
        con.Lastname = 'Test broker';
        con.Role__c = 'Renewals';
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId();
        con.AccountId = brokeracc.id;
        conList.add(con);
        
        Contact con1 = new Contact();
        con1.Lastname = 'Test broker1';
        con1.Role__c = 'Renewals';
        con1.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId();
        con1.AccountId = brokeracc.id;
        conList.add(con1);
        
         Contact norenewalContact = new Contact();
        norenewalContact.Lastname = 'Test broker2';
        norenewalContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId();
        norenewalContact.AccountId = brokeracc.id;
        conList.add(norenewalContact);
        insert conList;
        
        Id aqueousRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Product2 productaq = TestUtil.createProduct('Professional Indemnity');
       productaq.RecordTypeId = aqueousRecordTypeId; 
      productaq.Innovisk_Entity_ID__c = 'Aqueous';
       
        insert productaq; 
        
        Opportunity oppaq = TestUtil.createOpportunity('Opp Test',brokeracc.Id, productaq.Id);
        oppaq.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        oppaq.AccountId = brokeracc.Id;
        oppaq.StageName = 'Qualified'; 
        oppaq.Innovisk_Entity_ID__c = 'Aqueous';                            
        oppaq.Product__c = productaq.Id;
        oppaq.Submission_Status__c = 'Quoted';
        oppaq.Transaction_Status__c = 'Active';
        oppaq.Coverage_Product_Options__c = 'Professional Indemnity';
        oppaq.Tax_Country__c = 'United Kingdom';
        insert oppaq;
        
        // Create broker
        Broker_Account__c brokersAccount = new Broker_Account__c(
            Broker_Contact__c = con1.Id,
            Opportunity__c = oppaq.Id,
            IsPrimaryBroker__c = true,
            Relationship_Type__c = 'Broker',
          Bypass_New_Broker_Validation__c = true
        );
        insert brokersAccount;
         
        Policy__c policy = new Policy__c();
        policy.Account__c = brokeracc.Id;
        policy.Product_Name__c = 'Professional Indemnity';
        policy.Expiration_Date__c = Date.today().addmonths(3);
        policy.Total_Premium__c = 2000;
        policy.Initial_Premium__c = null;
        policy.Policy_Status__c = 'Bound';        	
        policyList.add(policy);
        
        Policy__c policy1 = new Policy__c();
        policy1.Account__c = brokeracc.Id;
        policy1.Product_Name__c = 'Professional Indemnity';
        policy1.Expiration_Date__c = Date.today().addmonths(3);
        policy1.Total_Premium__c = 2000;
        policy1.Initial_Premium__c = null;
        policy1.Policy_Status__c = 'Bound';
        policyList.add(policy1);
        insert policyList;
        
        
        Quote quote = TestUtil.createQuote('Quote Test',oppaq.Id);
        quote.Azure_ID__c = 'Test Az 1';
        quote.Policy__c = policy.Id;
        quote.Status = 'Bound';
        quote.Layer__c = 'Primary';
        quote.OpportunityId = oppaq.Id;
        quoteList.add(quote);
        
        Quote quote1 = TestUtil.createQuote('Quote Test1',oppaq.Id);
        quote1.Azure_ID__c = 'Testaz2';
        quote1.Policy__c = policy1.Id;
        quote1.Status = 'Bound';
        quote1.Layer__c = 'Primary';
        quote.OpportunityId = oppaq.Id;
        quoteList.add(quote1);
        insert quoteList;
   
        String RecordTypeIdREN = Schema.SObjectType.Renewal__c.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Renewal__c rn = new Renewal__c(
        Broker__c = brokersAccount.id,
        Policy__c = policy.Id,
        recordtypeId = RecordTypeIdREN,
        Status__c = 'Suppressed',
        No_Recipients__c = true ,
        Documents_Required__c = 'Miscellaneous Proposal Form');
    	insert rn;

       
       	//Contact c = [Select Id, Role__c from Contact where lastname = 'Test broker2' limit 1 ];
     	norenewalContact.Role__c = 'Renewals';
        update norenewalContact;
        norenewalContact.Role__c= '';
        update norenewalContact;
        norenewalContact.Role__c = 'Renewals';
        update norenewalContact;
        
        Test.startTest();
       	delete norenewalContact; 
       	test.stopTest();
      
    }
    
    
}