main/default/objects/Broker_Account__c/Broker_Account__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Broker_Account__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Broker_Contact__r.AccountId ,  Broker_Contact__r.Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <label>Broker Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker_Contact</value>
        </filterItems>
        <infoMessage>You Must Select a Broker Contact</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brokers</relationshipLabel>
    <relationshipName>Broker_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/IsPrimaryBroker__c.field-meta.xml
<CustomField>
    <fullName>IsPrimaryBroker__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary Broker?</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Broker Accounts</relationshipLabel>
    <relationshipName>Opportunity_Accounts1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker</fullName>
                <default>true</default>
                <label>Broker</label>
            </value>
            <value>
                <fullName>Sub-Producer</fullName>
            </value>
            <value>
                <fullName>Additional Interest</fullName>
                <isActive>false</isActive>
                <label>Additional Interest</label>
            </value>
            <value>
                <fullName>Insured</fullName>
                <isActive>false</isActive>
                <label>Insured</label>
            </value>
            <value>
                <fullName>Reinsured</fullName>
                <isActive>false</isActive>
                <label>Reinsured</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Document_Revision__c/Document_Revision__c.object-meta.xml
<CustomObject>
    <label>Document Revision</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Revisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Document_Revision__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Document Revisions</relationshipLabel>
    <relationshipName>Document_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Document_Revision__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Document Revisions</relationshipLabel>
    <relationshipName>Document_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Document_Revision__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <label>Policy</label>
</RecordType>

main/default/objects/Document_Revision__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

main/default/objects/Master_Binder__c/Master_Binder__c.object-meta.xml
<CustomObject>
    <label>Master Binder</label>
    <nameField>
        <label>Master Binder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Binders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Master_Binder__c/fields/Coverholder_Name__c.field-meta.xml
<CustomField>
    <fullName>Coverholder_Name__c</fullName>
    <label>Coverholder Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Master_Binder__c/fields/Coverholder_Pin__c.field-meta.xml
<CustomField>
    <fullName>Coverholder_Pin__c</fullName>
    <label>Coverholder Pin</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Master_Binder__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Master_Binder__c/fields/Inception_Date__c.field-meta.xml
<CustomField>
    <fullName>Inception_Date__c</fullName>
    <label>Inception Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Master_Binder__c/fields/Layer__c.field-meta.xml
<CustomField>
    <fullName>Layer__c</fullName>
    <label>Layer</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Master_Binder__c/fields/MGA_Commission__c.field-meta.xml
<CustomField>
    <fullName>MGA_Commission__c</fullName>
    <label>MGA Commission</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>Pol-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/fields/Azure_ID__c.field-meta.xml
<CustomField>
    <fullName>Azure_ID__c</fullName>
    <label>Azure ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Policy__c/fields/Layer__c.field-meta.xml
<CustomField>
    <fullName>Layer__c</fullName>
    <label>Layer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Master_Binder__c.field-meta.xml
<CustomField>
    <fullName>Master_Binder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Binder</label>
    <referenceTo>Master_Binder__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Bound Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Policy__c/fields/Renewal_Completed__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewal Completed?</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Policy__c/recordTypes/Aqueous.recordType-meta.xml
<RecordType>
    <fullName>Aqueous</fullName>
    <active>true</active>
    <label>Aqueous</label>
</RecordType>

main/default/objects/Transactions__c/Transactions__c.object-meta.xml
<CustomObject>
    <label>Transactions</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Transactions__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Transactions__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <label>Submission</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassAccountTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassAccountTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassAccountTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassCoverageLineItemTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassCoverageLineItemTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassCoverageLineItemTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassOpportunityTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassOpportunityTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassOpportunityTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/RenewalPolicyAQControllerTest.cls
/**************************************************************************************************
* Class Name: RenewalPolicyAQControllerTest
* Author: Ashik Zahir
* Created date: May 5th 2021
* Description: Controller class for RenewalPolicyAQController
**************************************************************************************************/
@isTest
public class RenewalPolicyAQControllerTest {

    @testSetup 
    static void createData(){
    	TriggerSettings__c setting = TestUtil.initialTriggerSetting();
        setting.BypassOpportunityTrigger__c = true;
        setting.BypassQuoteTrigger__c = true;
        setting.BypassCoverageLineItemTrigger__c = true;
        setting.BypassAccountTrigger__c = true;
        update setting;
        
        Account acc = TestUtil.createBusinessAccount('Bussiness Accoun Aq', 'Business', '123 Main Street', 'Anycity', 'New York', '11354', 'United States');
        acc.BillingStreet = acc.ShippingStreet;
        acc.BillingCity = acc.ShippingCity;
        acc.BillingState = acc.ShippingState;
        acc.BillingPostalCode = acc.ShippingPostalCode;
        acc.BillingCountry = acc.ShippingCountry;
        insert acc;
        
        Id aqueousRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        Product2 product = TestUtil.createProduct('Professional Indemnity');
        product.RecordTypeId = aqueousRecordTypeId; 
        product.Innovisk_Entity_ID__c = 'Aqueous';
        insert product;   
        
        String rdPolicyId = Schema.SObjectType.Document_Revision__c.getRecordTypeInfosByName().get('Policy').getRecordTypeId(); 
        Policy__c policy = new Policy__c();
        policy.Account__c = acc.Id; 
        policy.Expiration_Date__c = Date.today().addDays(10);
        policy.Policy_Number__c = '12345';
        policy.Effective_Date__c = Date.today()+5;
        policy.Policy_Status__c = 'Bound';
        policy.Renewal_Completed__c = false;
        policy.Policy_Status__c = 'Active'; 
        insert policy;
        
        Opportunity opp = TestUtil.createOpportunity('Opp Test',acc.Id, product.Id);
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aqueous').getRecordTypeId();
        opp.StageName = 'Qualified'; 
        opp.CloseDate = Date.today()+10;
        opp.Innovisk_Entity_ID__c = 'Aqueous';                            
        opp.Product__c = product.Id;
        opp.Effective_Date__c = Date.today();
    	opp.Expiration_Date__c = Date.today()+10;
        opp.Received_Date__c=Date.today()-120;
        opp.Submission_Status__c = 'Quoted';
        opp.Transaction_Status__c = 'Active';
        opp.Coverage_Product_Options__c = 'Professional Indemnity';
        opp.Azure_ID__c= 'Test Id';
        opp.Policy__c=policy.Id;
        opp.Probability= 0.5;
        
		insert opp;

        //Quote
        Quote quote = TestUtil.createQuote('New Quote Test',opp.Id);
        quote.Coverage_Product_Options__c ='Professional Indemnity'; 
        quote.Status = 'Bound';
        quote.Layer__c = 'Primary';
        quote.OpportunityId = opp.Id;
        quote.Policy__c = policy.Id;
        quote.Endorsement_Effective_Date__c = System.today() + 5;
       // quote.Endorsement_Type__c='New Business' - date.parse('08/08/2021');
        insert quote;
        
        // Create contact
        Contact con = new Contact(
            Email = 'test@j.com',
            Lastname = 'Test broker',
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId()
        );
        insert con;

        // Create broker
        Broker_Account__c broketAccount = new Broker_Account__c(
            Broker_Contact__c = con.Id,
            Opportunity__c = opp.Id,
            IsPrimaryBroker__c = true,
            Relationship_Type__c = 'Broker'
        );
        insert broketAccount;
        
        //Create Transaction
        Transactions__c transactions = new Transactions__c();
        transactions.Policy__c=policy.Id;
        transactions.Submission__c=opp.Id;
        insert transactions;
        
        List<Master_Binder__c> lofmasterbind = new List<Master_Binder__c>();
        Master_Binder__c masterbinder =new Master_Binder__c();
        masterbinder.Layer__c = 'Primary;Excess';
        masterbinder.Name = 'Master AZ';
        masterbinder.Expiry_Date__c = Date.today()+365;
        masterbinder.Inception_Date__c = Date.today();
        masterbinder.MGA_Commission__c = 15;
        masterbinder.Coverholder_Name__c = 'AZ masterBinder Holder';
        masterbinder.Coverholder_Pin__c = 'AZ masterBinder Pin';
        masterbinder.Country__c = 'United Kingdom';
        insert masterbinder;
        lofmasterbind.add(masterbinder);
        
        quote.Master_Binder__c =  masterBinder.Id;
        update quote;
        
        Master_Binder__c masterbinder2 =new Master_Binder__c();
        //masterbinder2.Layer__c = 'Primary;Excess';
        masterbinder2.Name = 'Master AZ 2';
        masterbinder2.Expiry_Date__c = Date.today()+365;
        masterbinder2.Inception_Date__c = Date.today();
        masterbinder2.MGA_Commission__c = 15;
        masterbinder2.Coverholder_Name__c = 'AZ masterBinder Holder';
        masterbinder2.Coverholder_Pin__c = 'AZ masterBinder Pin';
        
        lofmasterbind.add(masterbinder2);
    }
    
    @isTest
    static void renewalControllerTest(){
        Test.startTest();
        
        Policy__c pol = [Select Id from Policy__c Limit 1];
        Opportunity opp = [Select Id, Name, Expiration_Date__c, Type, Received_Date__c, CloseDate, Effective_Date__c, Prior_Policy__c, Policy__c, Azure_ID__c, Probability from Opportunity Limit 1];
        List<Quote> lstOfQuotes = [Select Id, OpportunityId from Quote];
        Master_Binder__c masterbinder = [Select Id,Name,Expiry_Date__c,Inception_Date__c,MGA_Commission__c,Layer__c,Coverholder_Name__c,Coverholder_Pin__c, Country__c from Master_Binder__c  where Name = 'Master AZ' Limit 1];
      
        RenewalPolicyAQController.ResultWrapper result = RenewalPolicyAQController.renewalController(pol.Id);
        RenewalPolicyAQController.getMasterBinders(pol.Id);
        RenewalPolicyAQController.createRenewalQuote(opp.Id, pol.Id, lstOfQuotes, masterbinder.Id, masterbinder.Id);
        RenewalPolicyAQController.deleteClonedOpp(opp.Id);
        
        Test.stopTest();
        System.assert( result != null);
    }
    
    @isTest
    static void testrenewalControllerExpirydate(){
        Test.startTest();
        Policy__c pol = [Select Id,Expiration_Date__c,Renewal_Completed__c,Policy_Status__c from Policy__c Limit 1];
        
        pol.Expiration_Date__c = Date.today().addDays(-10);
        update pol;
        RenewalPolicyAQController.ResultWrapper result1 = RenewalPolicyAQController.renewalController(pol.Id);

        Test.stopTest();
        System.assert( result1 != null);
    }
    
    @isTest
    static void testrenewalControllerrenewalComplete(){
        Test.startTest();
        Policy__c pol = [Select Id,Expiration_Date__c,Renewal_Completed__c,Policy_Status__c from Policy__c Limit 1];

        pol.Renewal_Completed__c = true;
        update pol;
        RenewalPolicyAQController.ResultWrapper result2 = RenewalPolicyAQController.renewalController(pol.Id);

        Test.stopTest();
        System.assert( result2 != null);
    }
    
    @isTest
    static void testrenewalControllerstatus(){
        Test.startTest();
        
        Policy__c pol = [Select Id,Expiration_Date__c,Renewal_Completed__c,Policy_Status__c from Policy__c Limit 1];

        pol.Policy_Status__c = 'Cancelled';
        update pol; 
        RenewalPolicyAQController.ResultWrapper result2 = RenewalPolicyAQController.renewalController(pol.Id);

        Test.stopTest();
        System.assert( result2 != null);
    }
    
    @isTest
    static void testrenewalControllersubmission(){
        Test.startTest();
        Opportunity opp = [Select Id, Name, Expiration_Date__c, Type, Received_Date__c, CloseDate, Effective_Date__c, Prior_Policy__c, Policy__c, Azure_ID__c, Probability from Opportunity Limit 1];
		opp.Transaction_Status__c = 'Inactive';
        update opp;
        
        Policy__c pol = [Select Id,Expiration_Date__c,Renewal_Completed__c,Policy_Status__c from Policy__c Limit 1];

        RenewalPolicyAQController.ResultWrapper result2 = RenewalPolicyAQController.renewalController(pol.Id);

        Test.stopTest();
        System.assert( result2 != null);
    }
    
    @isTest
    static void testrenewalControllerExpiryDate2(){
        Test.startTest();
        Policy__c pol = [Select Id,Expiration_Date__c,Renewal_Completed__c,Policy_Status__c from Policy__c Limit 1];
        
        pol.Expiration_Date__c = Date.today().addDays(100);
        update pol;

        RenewalPolicyAQController.ResultWrapper result2 = RenewalPolicyAQController.renewalController(pol.Id);

        Test.stopTest();
        System.assert( result2 != null);
    }
    @isTest
    static void renewalControllerTestException(){
        Test.startTest();
        //Policy__c pol = [Select Id from Policy__c Limit 1];
        Opportunity opp = [Select Id, Name, Expiration_Date__c, Type, Received_Date__c, CloseDate, Effective_Date__c, Prior_Policy__c, Policy__c, Azure_ID__c, Probability from Opportunity Limit 1];
        List<Quote> lstOfQuotes = [Select Id, OpportunityId from Quote];
        
        List<String> listQuoteId = new List<String>{lstOfQuotes[0].Id};
        RenewalPolicyAQController.ratingQuoteRenewal(listQuoteId);
        RenewalPolicyAQController.ResultWrapper result = RenewalPolicyAQController.renewalController(opp.Id);
        //RenewalPolicyAQController.createRenewalQuote('', '', lstOfQuotes,'', '');
        RenewalPolicyAQController.ResultWrapper result2 = RenewalPolicyAQController.getMasterBinders('');
        Test.stopTest();
        System.assert(result !=null );
    }
}