main/default/objects/Broker_Account__c/Broker_Account__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Broker_Account__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Broker_Contact__r.AccountId ,  Broker_Contact__r.Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Broker Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Broker_Account__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker</fullName>
                <default>true</default>
                <label>Broker</label>
            </value>
            <value>
                <fullName>Sub-Producer</fullName>
            </value>
            <value>
                <fullName>Additional Interest</fullName>
                <isActive>false</isActive>
                <label>Additional Interest</label>
            </value>
            <value>
                <fullName>Insured</fullName>
                <isActive>false</isActive>
                <label>Insured</label>
            </value>
            <value>
                <fullName>Reinsured</fullName>
                <isActive>false</isActive>
                <label>Reinsured</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Quote_Process__c/Quote_Process__c.object-meta.xml
<CustomObject>
    <label>Underwriter Workbench</label>
    <nameField>
        <label>Quote Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Underwriter Workbench</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Quote_Process__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quote_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Quote_Process__c/fields/Submission__c.field-meta.xml
<CustomField>
    <fullName>Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submission</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Underwriter Workbench</relationshipLabel>
    <relationshipName>Quote_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/SectionSetting__c/SectionSetting__c.object-meta.xml
<CustomObject>
    <description>Contains info to configure components that use sections</description>
    <label>Section Setting</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/SectionSetting__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Format__c.field-meta.xml
<CustomField>
    <fullName>Format__c</fullName>
    <label>Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Long Text</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Hyperlink</fullName>
            </value>
            <value>
                <fullName>MultiSelectPicklist</fullName>
            </value>
            <value>
                <fullName>Range</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Main_Section__c.field-meta.xml
<CustomField>
    <fullName>Main_Section__c</fullName>
    <label>Main Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>PCC</fullName>
            </value>
            <value>
                <fullName>Professional Indemnity</fullName>
            </value>
            <value>
                <fullName>Private Company Combo</fullName>
            </value>
            <value>
                <fullName>Aqueous</fullName>
                <isActive>false</isActive>
                <label>Aqueous</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Quote_Layer__c.field-meta.xml
<CustomField>
    <fullName>Quote_Layer__c</fullName>
    <label>Quote Layer</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Field_API__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_API__c</fullName>
    <label>Source Field API</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_Label__c</fullName>
    <label>Source Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SectionSetting__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Broker_Account__c</fullName>
                <label>Broker Account</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Policy_c</fullName>
                <label>Policy</label>
            </value>
            <value>
                <fullName>Rating_Modifier_Factor__c</fullName>
            </value>
            <value>
                <fullName>CoveragesLineItem__c</fullName>
            </value>
            <value>
                <fullName>Coverage_Limits_Deductibles__c</fullName>
            </value>
            <value>
                <fullName>Quote_Option__c</fullName>
            </value>
            <value>
                <fullName>Renewal__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/SectionSetting__c/fields/Sub_Section__c.field-meta.xml
<CustomField>
    <fullName>Sub_Section__c</fullName>
    <label>Sub Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/TriggerSettings__c/fields/BypassQuoteTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassQuoteTrigger</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/QuoteComparisonLWCTest.cls
@isTest
public class QuoteComparisonLWCTest {
	@testSetup
    public static void setup() {
        TriggerSettings__c setting = new TriggerSettings__c();
        setting.BypassQuoteTrigger__c = true;
        insert setting;
        
        Id brokerRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account accBroker = TestUtil.createAccount('Account_Business_Test_01', brokerRtId, '5305, Monroe Street', 'Toledo', 'Ohio','43623', 'United States');
        insert accBroker;              	
        
        // create product
        Product2 product = TestUtil.createProduct('MPL');
		insert product;
        
		// create opportunity        
        Opportunity opp = TestUtil.createOpportunity('Test Opportunity', accBroker.Id, product.Id);
        opp.StageName = 'Qualified';
        insert opp;
        
        // create Quote
        Quote q = TestUtil.createQuote('Test Quote', opp.Id);
        q.Rating_Status__c = 'Refer';
        q.Status = 'Rated';
        insert q;
        
        Quote_Process__c qp = new Quote_Process__c();
        qp.Account__c = accBroker.Id;
        qp.Submission__c = opp.Id;
        insert qp;
        
        List<SectionSetting__c> secSetLst = new List<SectionSetting__c>();
        SectionSetting__c secSetting0 = new SectionSetting__c();
        secSetting0.Component__c = 'Rate Quotes';
        secSetting0.Main_Section__c = 'Quote Data';
        secSetting0.Source_Object__c = '';
        secSetting0.Order__c = 4;
        secSetting0.Source_Field_Label__c = '';
        //secSetting.Source_Field_API__c = 'Relationship_Type__c';
        secSetting0.Format__c = '';
        secSetting0.Product__c = 'MPL';
        secSetting0.Active__c = true;
        secSetting0.Record_Type__c = 'Celerity';
        secSetting0.Quote_Layer__c = 'Excess';
        secSetLst.add(secSetting0);

        SectionSetting__c secSetting = new SectionSetting__c();
        secSetting.Component__c = 'Rate Quotes';
        secSetting.Main_Section__c = 'Quote Data';
        secSetting.Source_Object__c = 'Broker_Account__c';
        secSetting.Order__c = 4;
        secSetting.Source_Field_Label__c = 'Relationship Type';
        //secSetting.Source_Field_API__c = 'Relationship_Type__c';
        secSetting.Format__c = 'Picklist';
        secSetting.Product__c = 'MPL';
        secSetting.Active__c = true;
        secSetting.Record_Type__c = 'Celerity';
        secSetting.Quote_Layer__c = 'Excess';
        secSetLst.add(secSetting);
        
        SectionSetting__c secSetting1 = new SectionSetting__c();
        secSetting1.Component__c = 'Rate Quotes';
        secSetting1.Main_Section__c = 'Quote Data';
        secSetting1.Source_Object__c = 'Quote';
        secSetting1.Order__c = 4;
        secSetting1.Source_Field_Label__c = 'Override Premium';
        secSetting1.Source_Field_API__c = 'Override_Premium__c';
        secSetting1.Format__c = 'Number';
        secSetting1.Product__c = 'MPL';
        secSetting1.Active__c = true;
        secSetting1.Record_Type__c = 'Celerity';
        secSetting1.Quote_Layer__c = 'Excess';
        secSetLst.add(secSetting1);
        
        SectionSetting__c secSetting2 = new SectionSetting__c();
        secSetting2.Component__c = 'Rate Quotes';
        secSetting2.Main_Section__c = 'Quote Data';
        secSetting2.Sub_Section__c = 'Insured Contact Info';
        secSetting2.Source_Object__c = 'Quote';
        secSetting2.Order__c = 4;
        secSetting2.Source_Field_Label__c = 'Override Premium';
        //secSetting2.Source_Field_API__c = 'Override_Premium__c';
        secSetting2.Format__c = 'Number';
        secSetting2.Product__c = 'MPL';
        secSetting2.Active__c = true;
        secSetting2.Record_Type__c = 'Celerity';
        secSetting2.Quote_Layer__c = 'Excess';
        secSetLst.add(secSetting2);
        
        SectionSetting__c secSetting3 = new SectionSetting__c();
        secSetting3.Component__c = 'Rate Quotes';
        secSetting3.Main_Section__c = 'Quote Data';
        secSetting3.Sub_Section__c = 'Insured Contact Info';
        secSetting3.Source_Object__c = 'Quote';
        secSetting3.Order__c = 2;
        secSetting3.Source_Field_Label__c = 'Quote Type';
        secSetting3.Source_Field_API__c = 'Quote_Type__c';
        secSetting3.Format__c = 'Picklist';
        secSetting3.Product__c = 'MPL';
        secSetting3.Active__c = true;
        secSetting3.Record_Type__c = 'Celerity';
        secSetting3.Quote_Layer__c = 'Excess';
        secSetLst.add(secSetting3);
        
        insert secSetLst;
    }
    
    @isTest
    public static void testInitValues() {
        Opportunity sub = [SELECT id FROM Opportunity LIMIT 1];
        QuoteComparisonLWC.initValues(sub.Id, false);
    }
    
    @isTest
    public static void testGetFieldType() {
        String resultStr = QuoteComparisonLWC.getFieldType('Name','Account');
        System.assertEquals('String',resultStr);
        String resultPcklst = QuoteComparisonLWC.getFieldType('Country_Code__c','Account');
        System.assertEquals('Picklist',resultPcklst);
        String resultNull = QuoteComparisonLWC.getFieldType('NumberOfEmployees','Account');
        System.assertEquals(null,resultNull);
    }
    
    @isTest
    public static void testUpdateQuote() {
        QuoteComparisonLWC.updateQuote('{}', 'Testing');
        QuoteComparisonLWC.updateQuote('', 'Testing');
    }
}